--------------------------------------------------------------------------------
-- MelloUI - Class Icons
--
-- The high resolution painted class medallions (Media/Icons/Class, from
-- docs/class-icons.webp) and faction medallions (Media/Icons/Faction, from
-- docs/faction-icons.webp), generated by Tools/extract_icons.py into
-- Media/ClassIcons.lua (MelloUI_ClassIcons). This module:
--   * exposes MelloUI:ClassIconPath(classFile) for any module that draws a
--     class icon,
--   * covers PLAYER portraits everywhere the game draws one (the player
--     frame, target, focus, party) with the player's class medallion; NPC
--     portraits are never touched.
-- (0.19.4, the options audit: the PvP Flag Icon switch is gone -- its hook
-- was on a function this client never calls; a cover over the flag the
-- client does draw may come back as a feature of its own.)
--
-- The portraits are COVERED, never written (0.17.0: the game redraws some
-- every frame, and a write back made the engine redo its own work every
-- frame; "Portraits", below). No frame geometry changes, so nothing here
-- needs an InCombatLockdown guard. Everything is a post-hook
-- (hooksecurefunc); MelloUI never calls a Blizzard function that rebuilds
-- game data.
--------------------------------------------------------------------------------

local _, ns = ...
local MelloUI = ns.MelloUI
local Perf = MelloUI.Perf:Scope("ClassIcons")
local hooksecurefunc = Perf.hooksecurefunc

local M = MelloUI:RegisterModule("ClassIcons", {
	title = "Class Icons",
	desc = "High resolution painted class medallions in place of the default class icons, and on player portraits.",
	icon = "Interface\\Icons\\INV_Misc_Rune_01",
	flavour = "Painted medallions for every class, on the character sheet and on every portrait.",
	role = "look",
	tweak = { label = "Class Icons", desc = "The painted class medallions in place of the game's class icons and on player portraits.", order = 8 },
	enabledByDefault = true,
	defaults = {
		portraits = true,
	},
	options = {
		{ type = "toggle", key = "portraits", name = "Player Portraits",
		  desc = "Replace player portraits (yourself, target, focus, party) with the player's class medallion. NPC portraits are never touched." },
	},
})

-- The classes this client's character creation screen actually offers
-- (Interface/AddOns/Blizzard_CharacterCreate/Camelot/Blizzard_CharacterCreate.lua,
-- local classLayoutIndices, lines 1105-1119), for /icondump and for anyone
-- reading this file. Media/ClassIcons.lua only ships art for the ones the
-- user has confirmed or the orchestrator was confident about; see
-- Tools/class_icons.json for the mapping and confidence per icon.
local CLASSES_IN_CLIENT = {
	"WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "SHAMAN", "MAGE",
	"WARLOCK", "MONK", "DRUID", "DEMONHUNTER", "DEATHKNIGHT", "EVOKER",
}

--------------------------------------------------------------------------------
-- Helpers other modules call
--------------------------------------------------------------------------------

-- Values this client keeps secret from addons (e.g. UnitClass on some units)
-- cannot be read or compared; skip rather than error. SafeValue(v) is v, or
-- nil when v is secret: MelloUI.Safe (Core.lua), one set for the addon. The
-- old copy compared v with nil before asking issecretvalue, which a secret
-- refuses (audit, 2026-09-24).
local SafeValue = MelloUI.Safe.Value

-- Returns the texture path (no extension) for a class file name (as
-- select(2, UnitClass(unit)) returns it, e.g. "WARRIOR"), or nil when that
-- class has no shipped icon. variant "plain" is the medallion without its
-- diamonds (Tools/make_plain_medallions.py), for the character window's
-- portrait inside the kit ring.
function MelloUI:ClassIconPath(classFile, variant)
	classFile = SafeValue(classFile)
	local icons = MelloUI_ClassIcons
	local path = classFile and icons and icons.classes and icons.classes[classFile] or nil
	if path and variant then
		path = path .. "_" .. variant
	end
	return path
end

--------------------------------------------------------------------------------
-- Portraits
--
-- A COVER, never a write on the game's portrait (0.17.0; the user's FPS in
-- combat, docs/plans/fps-portrait-fix.md). The target of target redraws its
-- portrait on EVERY frame (its OnUpdate runs UnitFrame_Update ->
-- UnitFramePortrait_Update: a class atlas or SetPortraitTexture); the old
-- way put the medallion on that same texture, so each frame the game put
-- its art back and this put the medallion back: two texture swaps a frame,
-- each a file load the next one cancelled (AsyncFile.log: 3381 cancels of
-- the class icon sheet), 160 fps down to 66 in a fight. Now:
--   * one texture of ours per portrait, made at its first need, in the
--     portrait's own layer and sublevel (under the frame's ring at the next
--     sublevel), on its rect (SetAllPoints: the kit's fit follows);
--   * while it shows, the game's portrait is masked out (a mask of ours far
--     off its rect, added when the cover comes and taken off when it goes,
--     never per frame): two regions of one sublevel are drawn in no fixed
--     order -- the player's own portrait came out over the cover (user,
--     2026-10-01: "it only changed the portraits of my target, but not
--     mine") -- and with the game's masked out, the order cannot matter;
--   * its state kept per portrait (the class and the variant shown): the
--     hooks only compare, and the texture is set when the answer changes;
--   * the game's own writes on its portrait copied onto the cover, only when
--     they change it: the alpha (range fading), the vertex colour (dead,
--     tapped, disconnected), the desaturation, the show and hide;
--   * Player Portraits off or the module off: the covers hidden, the game's
--     portrait as the game left it (nothing to put back).
-- The character window's portrait and the class-icon portraits of other
-- panels (SetPortraitToClassIcon / SetPortraitToSpecIcon) take the same
-- cover.
--------------------------------------------------------------------------------

local WHITE = "Interface\\Buttons\\WHITE8x8"

-- The character window's own portrait sits inside the kit ring: it gets the
-- plain medallion (no diamonds).
local function VariantFor(texture)
	if CharacterFrame and CharacterFrame.GetPortrait and texture == CharacterFrame:GetPortrait() then
		return "plain"
	end
	-- a unit frame portrait inside the kit ring (UnitFramePanel marks it)
	if texture and texture.melloKitRing then
		return "plain"
	end
	return nil
end

-- [portrait] = { tex, hide, masked, class, variant, alpha, r, g, b, a, desat }:
-- the cover and what it shows (a side table: nothing written on the game's)
local covers = setmetatable({}, { __mode = "k" })

local function Num(v)
	return MelloUI.Safe.Number(v)
end

-- the game's look of its portrait copied onto the cover (each only when it
-- changed: these come with every update of the frame)
local function CopyAlpha(c, portrait)
	local ok, a = pcall(portrait.GetAlpha, portrait)
	a = ok and Num(a) or 1
	if c.alpha ~= a then
		c.alpha = a
		c.tex:SetAlpha(a)
	end
end

local function CopyColour(c, portrait)
	local ok, r, g, b, a = pcall(portrait.GetVertexColor, portrait)
	r, g, b, a = ok and Num(r) or 1, ok and Num(g) or 1, ok and Num(b) or 1, ok and Num(a) or 1
	if c.r ~= r or c.g ~= g or c.b ~= b or c.a ~= a then
		c.r, c.g, c.b, c.a = r, g, b, a
		c.tex:SetVertexColor(r, g, b, a)
	end
end

local function CopyDesaturated(c, portrait)
	local ok, d = pcall(portrait.IsDesaturated, portrait)
	d = ok and d == true or false
	if c.desat ~= d then
		c.desat = d
		c.tex:SetDesaturated(d)
	end
end

local function CopyShown(c, portrait)
	local ok, shown = pcall(portrait.IsShown, portrait)
	shown = (ok and shown == true and c.class ~= nil) and true or false
	if c.shown ~= shown then
		c.shown = shown
		c.tex:SetShown(shown)
	end
	-- the game's portrait masked out while the cover shows (on a change only)
	if c.hide and c.masked ~= shown then
		c.masked = shown
		if shown then
			pcall(portrait.AddMaskTexture, portrait, c.hide)
		else
			pcall(portrait.RemoveMaskTexture, portrait, c.hide)
		end
	end
end

-- the game's writes on a covered portrait (one set of handlers for all)
local function OnPortraitAlpha(portrait)
	local c = covers[portrait]
	if c and c.class then
		CopyAlpha(c, portrait)
	end
end
local function OnPortraitColour(portrait)
	local c = covers[portrait]
	if c and c.class then
		CopyColour(c, portrait)
	end
end
local function OnPortraitDesaturated(portrait)
	local c = covers[portrait]
	if c and c.class then
		CopyDesaturated(c, portrait)
	end
end
local function OnPortraitShown(portrait)
	local c = covers[portrait]
	if c then
		CopyShown(c, portrait)
	end
end

local function NewCover(portrait)
	local parent = portrait.GetParent and portrait:GetParent()
	if not (parent and parent.CreateTexture) then
		return nil
	end
	local okL, layer, sub = pcall(portrait.GetDrawLayer, portrait)
	if not okL or type(layer) ~= "string" then
		layer, sub = "BACKGROUND", 0
	end
	sub = Num(sub) or 0
	-- (in its layer and sublevel: under the ring the frame keeps at the next
	-- sublevel; the game's portrait masked out while it shows)
	local tex = parent:CreateTexture(nil, layer, nil, sub)
	tex:SetAllPoints(portrait)
	tex:Hide()
	-- the mask that hides the game's portrait: one white pixel far off its
	-- rect, everything else clamped to nothing (a mask must be the
	-- portrait's frame's own region)
	local hide = nil
	if parent.CreateMaskTexture and portrait.AddMaskTexture then
		hide = parent:CreateMaskTexture()
		hide:SetTexture(WHITE, "CLAMPTOBLACKADDITIVE", "CLAMPTOBLACKADDITIVE")
		hide:SetSize(1, 1)
		hide:SetPoint("BOTTOMRIGHT", portrait, "TOPLEFT", -64, 64)
	end
	local c = { tex = tex, hide = hide, masked = false, shown = false }
	covers[portrait] = c
	hooksecurefunc(portrait, "SetAlpha", OnPortraitAlpha)
	hooksecurefunc(portrait, "SetVertexColor", OnPortraitColour)
	if type(portrait.SetDesaturated) == "function" then
		hooksecurefunc(portrait, "SetDesaturated", OnPortraitDesaturated)
	end
	hooksecurefunc(portrait, "Show", OnPortraitShown)
	hooksecurefunc(portrait, "Hide", OnPortraitShown)
	hooksecurefunc(portrait, "SetShown", OnPortraitShown)
	return c
end

-- The medallion of classFile on the portrait's cover (made at its first
-- need), set only when the class or the variant changed. Returns true if it
-- shows one.
local function ApplyClassPortrait(texture, classFile)
	if not texture then
		return false
	end
	local variant = VariantFor(texture)
	local path = MelloUI:ClassIconPath(classFile, variant)
	local c = covers[texture]
	if not path then
		if c and c.class then
			c.class = nil
			CopyShown(c, texture)
		end
		return false
	end
	c = c or NewCover(texture)
	if not c then
		return false
	end
	if c.class ~= classFile or c.variant ~= variant then
		c.class, c.variant = classFile, variant
		c.tex:SetTexture(path)
		c.tex:SetTexCoord(0, 1, 0, 1)
		CopyAlpha(c, texture)
		CopyColour(c, texture)
		CopyDesaturated(c, texture)
	end
	CopyShown(c, texture)
	return true
end

-- the cover off a portrait (an NPC now, the toggle off): hidden, its class
-- forgotten; the game's portrait as the game left it
local function Uncover(texture)
	local c = covers[texture]
	if c and c.class then
		c.class, c.variant = nil, nil
		CopyShown(c, texture)
	end
end

-- unit's portrait, if unit is a player with a mapped class icon and the
-- Player Portraits toggle is on. NPC units are left with the game's own
-- portrait (model render or its default question-mark art).
local function TryReplacePlayerPortrait(texture, unit)
	if not (M.isEnabled and M.db and M.db.portraits) then
		Uncover(texture)
		return false
	end
	-- UnitIsPlayer first: it is false for an NPC and for no unit at all, so
	-- an NPC's portrait costs one question
	if not (texture and unit and UnitIsPlayer(unit) and UnitExists(unit)) then
		if texture then
			Uncover(texture)
		end
		return false
	end
	local _, classFile = UnitClass(unit)
	return ApplyClassPortrait(texture, SafeValue(classFile))
end

-- The medallion again in its current variant on every portrait that shows
-- one: the kit modules call it when a ring goes on or off.
function M:RefreshPortraits(textures)
	for _, texture in ipairs(textures or {}) do
		local c = texture and covers[texture]
		if c and c.class then
			pcall(ApplyClassPortrait, texture, c.class)
		end
	end
end

-- (the tests': the cover of a portrait, nil when none)
function M.CoverOf(texture)
	return covers[texture]
end

local hooksInstalled = false

-- [portrait] = the frame time the SetPortraitTexture hook last looked at it.
-- UnitFramePortrait_Update ends in SetPortraitTexture (its render branch),
-- and its own hook below runs right after: for the same portrait in the
-- same frame that second look would do the same again (the target of
-- target does both on every frame, 41 a second in /melloperf 2026-09-24),
-- so it is left at once. The class atlas branch never calls
-- SetPortraitTexture, so its portrait is never stamped and is still seen.
local looked = setmetatable({}, { __mode = "k" })

local function InstallHooks()
	if hooksInstalled then
		return
	end
	hooksInstalled = true

	-- Every portrait the game draws eventually calls this (CharacterPanel's
	-- own "player" portrait, PortraitFrameMixin:SetPortraitToUnit, and the
	-- unit frame portrait path below). One hook covers all of them. It runs
	-- many times a second (the target of target's portrait, every frame):
	-- with the toggle off and no cover, no texture or no unit token, it is
	-- left at once; an NPC's portrait is left at UnitIsPlayer.
	if type(SetPortraitTexture) == "function" then
		hooksecurefunc("SetPortraitTexture", function(texture, unit)
			if not (texture and type(unit) == "string") then
				return
			end
			if not (M.isEnabled and M.db and M.db.portraits) then
				if covers[texture] then
					Uncover(texture)
				end
				return
			end
			looked[texture] = GetTime()
			pcall(TryReplacePlayerPortrait, texture, unit)
		end)
	end

	-- PlayerFrame, TargetFrame, FocusFrame and the party member frames all
	-- share this update path (Blizzard_UnitFrame/Mainline/UnitFrame.lua):
	-- for a player it sets the game's class atlas instead of calling
	-- SetPortraitTexture (UnitFrame_ShouldReplacePortrait, the
	-- ReplaceOtherPlayerPortraits CVar), so it needs its own hook too. The
	-- stamp is used up here: seen once, then looked at again next time.
	if type(UnitFramePortrait_Update) == "function" then
		hooksecurefunc("UnitFramePortrait_Update", function(self)
			local portrait = self and self.portrait
			if not portrait then
				return
			end
			local at = looked[portrait]
			if at then
				looked[portrait] = nil
				if at == GetTime() then
					return   -- its SetPortraitTexture was just seen, for this unit
				end
			end
			pcall(TryReplacePlayerPortrait, portrait, self.unit)
		end)
	end

	-- PlayerSpellsFrame and similar panels ask for a plain class icon
	-- portrait directly (already a class, not a unit, so no player check).
	-- Mixin() copies this field onto each frame when it is created, so this
	-- hook only reaches frames created after MelloUI loads; not verified
	-- against the live client.
	if PortraitFrameMixin and type(PortraitFrameMixin.SetPortraitToClassIcon) == "function" then
		hooksecurefunc(PortraitFrameMixin, "SetPortraitToClassIcon", function(self, classFilename)
			if not (M.isEnabled and M.db and M.db.portraits and self and self.GetPortrait) then
				return
			end
			classFilename = SafeValue(classFilename)
			if classFilename then
				pcall(ApplyClassPortrait, self:GetPortrait(), string.upper(classFilename))
			end
		end)
	end

	-- The character window's own portrait: on the paper doll the game sets it
	-- to the SPEC icon (PortraitFrameMixin:SetPortraitToSpecIcon, a square
	-- asset) without going through SetPortraitTexture. CharacterFrame exists
	-- before addons load, so the mixin hook above never reaches it; hook the
	-- instance. It is always the player, so the class medallion applies.
	if CharacterFrame and type(CharacterFrame.SetPortraitToSpecIcon) == "function" then
		hooksecurefunc(CharacterFrame, "SetPortraitToSpecIcon", function(self)
			if not (M.isEnabled and M.db and M.db.portraits and self.GetPortrait) then
				return
			end
			local _, classFile = UnitClass("player")
			if classFile then
				pcall(ApplyClassPortrait, self:GetPortrait(), SafeValue(classFile))
			end
		end)
	end
end

-- The unit frames' portraits as they are now (the player, target, focus and
-- party frames, each with the portrait and unit the game gave it): covered at
-- once when Player Portraits or the module comes on again, not at the game's
-- next portrait update (0.19.4, the options audit). The target of target's
-- comes back by itself: the game sets its portrait every frame.
local function CoverFramePortrait(frame)
	local portrait = frame and frame.portrait
	if portrait then
		pcall(TryReplacePlayerPortrait, portrait, frame.unit)
	end
end

local function CoverUnitPortraits()
	CoverFramePortrait(PlayerFrame)
	CoverFramePortrait(TargetFrame)
	CoverFramePortrait(FocusFrame)
	if PartyFrame then
		for i = 1, 4 do
			CoverFramePortrait(PartyFrame["MemberFrame" .. i])
		end
	end
end

--------------------------------------------------------------------------------
-- Module lifecycle
--------------------------------------------------------------------------------

function M:OnInit(db)
	self.db = db
end

function M:OnEnable(db)
	self.db = db
	-- (on again after an OnDisable: the covers back at once; the first
	-- enable, at login, leaves them to the game's own first updates)
	if hooksInstalled and db and db.portraits then
		CoverUnitPortraits()
	end
	InstallHooks()
end

function M:OnDisable()
	-- Hooks cannot be removed (hooksecurefunc); every callback checks
	-- M.isEnabled and the toggles, so they are no-ops from here on. The
	-- covers are hidden: the game's portraits were never written, so there
	-- is nothing to put back.
	for texture in pairs(covers) do
		Uncover(texture)
	end
end

function M:OnSettingChanged(key, value, db)
	self.db = db
	if key == "portraits" and not value then
		for texture in pairs(covers) do
			Uncover(texture)
		end
	elseif key == "portraits" then
		CoverUnitPortraits()
	end
end

--------------------------------------------------------------------------------
-- /icondump: the class list, what is mapped, and the current target's portrait
--------------------------------------------------------------------------------

SLASH_MELLOICONDUMP1 = "/icondump"
SlashCmdList.MELLOICONDUMP = function()
	MelloUI:Print("Classes in this client: %s", table.concat(CLASSES_IN_CLIENT, ", "))

	local icons = MelloUI_ClassIcons
	local mappedClasses = {}
	if icons and icons.classes then
		for classFile in pairs(icons.classes) do
			mappedClasses[#mappedClasses + 1] = classFile
		end
		table.sort(mappedClasses)
	end
	MelloUI:Print("Class icons mapped (%d/%d): %s", #mappedClasses, #CLASSES_IN_CLIENT,
		#mappedClasses > 0 and table.concat(mappedClasses, ", ") or "none")

	local mappedFactions = {}
	if icons and icons.factions then
		for faction in pairs(icons.factions) do
			mappedFactions[#mappedFactions + 1] = faction
		end
		table.sort(mappedFactions)
	end
	MelloUI:Print("Faction icons mapped: %s", #mappedFactions > 0 and table.concat(mappedFactions, ", ") or "none")

	-- (0.17.0) the covers on your own and your target's portraits
	local function CoverLine(label, portrait)
		local c = portrait and covers[portrait]
		if not portrait then
			MelloUI:Print("%s: no portrait found", label)
		elseif not c then
			MelloUI:Print("%s portrait: no cover made", label)
		else
			local okL, layer, sub = pcall(portrait.GetDrawLayer, portrait)
			local okC, cl, cs = pcall(c.tex.GetDrawLayer, c.tex)
			MelloUI:Print("%s portrait: cover %s, class %s, the game's portrait %s (portrait %s %s, cover %s %s)", label,
				c.tex:IsShown() and "shown" or "hidden", tostring(c.class), c.masked and "masked out" or "visible",
				okL and tostring(layer) or "?", okL and tostring(sub) or "?", okC and tostring(cl) or "?", okC and tostring(cs) or "?")
		end
	end
	local pf = PlayerFrame and PlayerFrame.PlayerFrameContainer
	CoverLine("your", pf and pf.PlayerPortrait)
	CoverLine("the target's", TargetFrame and TargetFrame.portrait)

	if not UnitExists("target") then
		MelloUI:Print("target: none")
		return
	end
	if not UnitIsPlayer("target") then
		MelloUI:Print("target: not a player, keeps the game's own portrait")
		return
	end
	local _, classFile = UnitClass("target")
	classFile = SafeValue(classFile)
	if not classFile then
		MelloUI:Print("target: class is a secret value on this client, cannot pick an icon")
		return
	end
	if MelloUI:ClassIconPath(classFile) then
		MelloUI:Print("target: portrait replaced with the %s medallion", classFile)
	else
		MelloUI:Print("target: class %s has no mapped icon, portrait unchanged", classFile)
	end
end
