--------------------------------------------------------------------------------
-- MelloUI - Class Icons
--
-- The high resolution painted class medallions (Media/Icons/Class, from
-- docs/class-icons.webp) and faction medallions (Media/Icons/Faction, from
-- docs/faction-icons.webp), generated by Tools/extract_icons.py into
-- Media/ClassIcons.lua (MelloUI_ClassIcons). This module:
--   * exposes MelloUI:ClassIconPath(classFile) / MelloUI:FactionIconPath(faction)
--     for any module that draws a class or faction icon,
--   * replaces PLAYER portraits everywhere the game draws one (the player
--     frame, target, focus, party) with the player's class medallion; NPC
--     portraits are never touched,
--   * optionally swaps the player frame's PvP flag icon for the faction
--     medallion.
--
-- Only texture swaps on existing widgets: no frame geometry changes, so
-- nothing here needs an InCombatLockdown guard. Everything is a post-hook
-- (hooksecurefunc); MelloUI never calls a Blizzard function that rebuilds
-- game data.
--------------------------------------------------------------------------------

local _, ns = ...
local MelloUI = ns.MelloUI
local Perf = MelloUI.Perf:Scope("ClassIcons")
local hooksecurefunc = Perf.hooksecurefunc

local M = MelloUI:RegisterModule("ClassIcons", {
	title = "Class Icons",
	desc = "High resolution painted class medallions in place of the default class icons, and on player portraits.",
	enabledByDefault = true,
	defaults = {
		portraits = true,
		pvpFlag = true,
	},
	options = {
		{ type = "toggle", key = "portraits", name = "Player Portraits",
		  desc = "Replace player portraits (yourself, target, focus, party) with the player's class medallion. NPC portraits are never touched." },
		{ type = "toggle", key = "pvpFlag", name = "PvP Flag Icon",
		  desc = "Use the faction medallion for the player frame's PvP flag icon." },
	},
})

-- The classes this client's character creation screen actually offers
-- (Interface/AddOns/Blizzard_CharacterCreate/Camelot/Blizzard_CharacterCreate.lua,
-- local classLayoutIndices, lines 1105-1119), for /icondump and for anyone
-- reading this file. Media/ClassIcons.lua only ships art for the ones the
-- user has confirmed or the orchestrator was confident about; see
-- Tools/class_icons.json for the mapping and confidence per icon.
local CLASSES_IN_CLIENT = {
	"WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "SHAMAN", "MAGE",
	"WARLOCK", "MONK", "DRUID", "DEMONHUNTER", "DEATHKNIGHT", "EVOKER",
}

--------------------------------------------------------------------------------
-- Helpers other modules call
--------------------------------------------------------------------------------

-- Values this client keeps secret from addons (e.g. UnitClass on some units)
-- cannot be read or compared; skip rather than error.
local function SafeValue(v)
	if v == nil or (issecretvalue and issecretvalue(v)) then
		return nil
	end
	return v
end

-- Returns the texture path (no extension) for a class file name (as
-- select(2, UnitClass(unit)) returns it, e.g. "WARRIOR"), or nil when that
-- class has no shipped icon. variant "plain" is the medallion without its
-- diamonds (Tools/make_plain_medallions.py), for the character window's
-- portrait inside the kit ring.
function MelloUI:ClassIconPath(classFile, variant)
	classFile = SafeValue(classFile)
	local icons = MelloUI_ClassIcons
	local path = classFile and icons and icons.classes and icons.classes[classFile] or nil
	if path and variant then
		path = path .. "_" .. variant
	end
	return path
end

-- Returns the texture path (no extension) for "Alliance" or "Horde", or nil.
function MelloUI:FactionIconPath(faction)
	faction = SafeValue(faction)
	local icons = MelloUI_ClassIcons
	return faction and icons and icons.factions and icons.factions[faction] or nil
end

--------------------------------------------------------------------------------
-- Portraits
--------------------------------------------------------------------------------

-- The character window's own portrait sits inside the kit ring: it gets the
-- plain medallion (no diamonds).
local function VariantFor(texture)
	if CharacterFrame and CharacterFrame.GetPortrait and texture == CharacterFrame:GetPortrait() then
		return "plain"
	end
	-- a unit frame portrait inside the kit ring (UnitFramePanel marks it)
	if texture and texture.melloKitRing then
		return "plain"
	end
	return nil
end

local replaced = setmetatable({}, { __mode = "k" })   -- portraits carrying a medallion

-- Puts classFile's medallion on a portrait texture object. Returns true if it did.
local function ApplyClassPortrait(texture, classFile)
	local path = MelloUI:ClassIconPath(classFile, VariantFor(texture))
	if not (texture and path) then
		return false
	end
	texture:SetTexture(path)
	texture:SetTexCoord(0, 1, 0, 1)
	texture.melloClassIcon = classFile
	replaced[texture] = true
	return true
end

-- unit's portrait, if unit is a player with a mapped class icon and the
-- Player Portraits toggle is on. NPC units are left with the game's own
-- portrait (model render or its default question-mark art).
local function TryReplacePlayerPortrait(texture, unit)
	if not (M.isEnabled and M.db and M.db.portraits) then
		return false
	end
	-- UnitIsPlayer first: it is false for an NPC and for no unit at all, so
	-- an NPC's portrait costs one question
	if not (texture and unit and UnitIsPlayer(unit) and UnitExists(unit)) then
		return false
	end
	local _, classFile = UnitClass(unit)
	return ApplyClassPortrait(texture, SafeValue(classFile))
end

-- Re-applies the medallion (in its current variant) to every portrait that
-- carries one: the kit modules call it when a ring goes on or off.
function M:RefreshPortraits(textures)
	for _, texture in ipairs(textures or {}) do
		if texture and texture.melloClassIcon then
			pcall(ApplyClassPortrait, texture, texture.melloClassIcon)
		end
	end
end

local hooksInstalled = false

-- [portrait] = the frame time the SetPortraitTexture hook last looked at it.
-- UnitFramePortrait_Update ends in SetPortraitTexture (its render branch),
-- and its own hook below runs right after: for the same portrait in the
-- same frame that second look would do the same again (the target of
-- target does both on every frame, 41 a second in /melloperf 2026-09-24:
-- twice the unit questions for an NPC, the medallion set twice for a
-- player), so it is left at once. The class atlas branch never calls
-- SetPortraitTexture, so its portrait is never stamped and is still seen.
local looked = setmetatable({}, { __mode = "k" })

local function InstallHooks()
	if hooksInstalled then
		return
	end
	hooksInstalled = true

	-- Every portrait the game draws eventually calls this (CharacterPanel's
	-- own "player" portrait, PortraitFrameMixin:SetPortraitToUnit, and the
	-- unit frame portrait path below). One hook covers all of them. It runs
	-- many times a second (the target of target's frame redraws its portrait
	-- with each update, 24/s in a /melloperf recording, 2026-09-24): with the
	-- toggle off, no texture or no unit token, it is left at once, before any
	-- call into the game; an NPC's portrait is left at UnitIsPlayer.
	if type(SetPortraitTexture) == "function" then
		hooksecurefunc("SetPortraitTexture", function(texture, unit)
			if not (texture and type(unit) == "string" and M.isEnabled and M.db and M.db.portraits) then
				return
			end
			looked[texture] = GetTime()
			pcall(TryReplacePlayerPortrait, texture, unit)
		end)
	end

	-- PlayerFrame, TargetFrame, FocusFrame and the party member frames all
	-- share this update path (Blizzard_UnitFrame/Mainline/UnitFrame.lua):
	-- it sometimes sets a plain class atlas instead of calling
	-- SetPortraitTexture (UnitFrame_ShouldReplacePortrait branch, e.g. a
	-- vehicle or mind-controlled unit), so it needs its own hook too. The
	-- stamp is used up here: seen once, then looked at again next time.
	if type(UnitFramePortrait_Update) == "function" then
		hooksecurefunc("UnitFramePortrait_Update", function(self)
			local portrait = self and self.portrait
			if not portrait then
				return
			end
			local at = looked[portrait]
			if at then
				looked[portrait] = nil
				if at == GetTime() then
					return   -- its SetPortraitTexture was just seen, for this unit
				end
			end
			pcall(TryReplacePlayerPortrait, portrait, self.unit)
		end)
	end

	-- PlayerSpellsFrame and similar panels ask for a plain class icon
	-- portrait directly (already a class, not a unit, so no player check).
	-- Mixin() copies this field onto each frame when it is created, so this
	-- hook only reaches frames created after MelloUI loads; not verified
	-- against the live client.
	if PortraitFrameMixin and type(PortraitFrameMixin.SetPortraitToClassIcon) == "function" then
		hooksecurefunc(PortraitFrameMixin, "SetPortraitToClassIcon", function(self, classFilename)
			if not (M.isEnabled and M.db and M.db.portraits and self and self.GetPortrait) then
				return
			end
			classFilename = SafeValue(classFilename)
			if classFilename then
				pcall(ApplyClassPortrait, self:GetPortrait(), string.upper(classFilename))
			end
		end)
	end

	-- The character window's own portrait: on the paper doll the game sets it
	-- to the SPEC icon (PortraitFrameMixin:SetPortraitToSpecIcon, a square
	-- asset) without going through SetPortraitTexture. CharacterFrame exists
	-- before addons load, so the mixin hook above never reaches it; hook the
	-- instance. It is always the player, so the class medallion applies.
	if CharacterFrame and type(CharacterFrame.SetPortraitToSpecIcon) == "function" then
		hooksecurefunc(CharacterFrame, "SetPortraitToSpecIcon", function(self)
			if not (M.isEnabled and M.db and M.db.portraits and self.GetPortrait) then
				return
			end
			local _, classFile = UnitClass("player")
			if classFile then
				pcall(ApplyClassPortrait, self:GetPortrait(), classFile)
			end
		end)
	end

	-- The player frame's PvP flag icon: the faction medallion instead of the
	-- small Alliance/Horde atlas, when the player is flagged.
	if type(PlayerFrame_ShowPvPIcon) == "function" then
		hooksecurefunc("PlayerFrame_ShowPvPIcon", function(factionGroup)
			if not (M.isEnabled and M.db and M.db.pvpFlag) then
				return
			end
			local path = MelloUI:FactionIconPath(SafeValue(factionGroup))
			if not path then
				return -- "FFA" or an unmapped faction: keep the game's icon
			end
			local getContainer = PlayerFrame_GetPlayerFrameContentContextual
			local container = type(getContainer) == "function" and getContainer()
			local icon = container and container.PVPIcon
			if icon then
				if icon.melloPvPAtlas == nil then
					-- the game's flag, for the restore
					icon.melloPvPAtlas = (icon.GetAtlas and icon:GetAtlas()) or false
				end
				icon:SetTexture(path)
				icon:SetTexCoord(0, 1, 0, 1)
				M.pvpIcon = icon
			end
		end)
	end
end

--------------------------------------------------------------------------------
-- Module lifecycle
--------------------------------------------------------------------------------

function M:OnInit(db)
	self.db = db
end

function M:OnEnable(db)
	self.db = db
	InstallHooks()
end

function M:OnDisable()
	-- Hooks cannot be removed (hooksecurefunc); every callback checks
	-- M.isEnabled and the toggles, so they are no-ops from here on. The
	-- portraits already carrying a medallion go back to the game's render
	-- where the unit is known (the unit frames); the rest refresh when
	-- their window next asks for its portrait.
	for texture in pairs(replaced) do
		texture.melloClassIcon = nil
		local parent = texture.GetParent and texture:GetParent()
		local unit = parent and parent.unit
		if type(unit) == "string" and type(SetPortraitTexture) == "function" then
			pcall(SetPortraitTexture, texture, unit)
		end
	end
	wipe(replaced)
	local icon = M.pvpIcon
	if icon and icon.melloPvPAtlas then
		pcall(icon.SetAtlas, icon, icon.melloPvPAtlas)
	end
end

function M:OnSettingChanged(key, value, db)
	self.db = db
end

--------------------------------------------------------------------------------
-- /icondump: the class list, what is mapped, and the current target's portrait
--------------------------------------------------------------------------------

SLASH_MELLOICONDUMP1 = "/icondump"
SlashCmdList.MELLOICONDUMP = function()
	MelloUI:Print("Classes in this client: %s", table.concat(CLASSES_IN_CLIENT, ", "))

	local icons = MelloUI_ClassIcons
	local mappedClasses = {}
	if icons and icons.classes then
		for classFile in pairs(icons.classes) do
			mappedClasses[#mappedClasses + 1] = classFile
		end
		table.sort(mappedClasses)
	end
	MelloUI:Print("Class icons mapped (%d/%d): %s", #mappedClasses, #CLASSES_IN_CLIENT,
		#mappedClasses > 0 and table.concat(mappedClasses, ", ") or "none")

	local mappedFactions = {}
	if icons and icons.factions then
		for faction in pairs(icons.factions) do
			mappedFactions[#mappedFactions + 1] = faction
		end
		table.sort(mappedFactions)
	end
	MelloUI:Print("Faction icons mapped: %s", #mappedFactions > 0 and table.concat(mappedFactions, ", ") or "none")

	if not UnitExists("target") then
		MelloUI:Print("target: none")
		return
	end
	if not UnitIsPlayer("target") then
		MelloUI:Print("target: not a player, keeps the game's own portrait")
		return
	end
	local _, classFile = UnitClass("target")
	classFile = SafeValue(classFile)
	if not classFile then
		MelloUI:Print("target: class is a secret value on this client, cannot pick an icon")
		return
	end
	if MelloUI:ClassIconPath(classFile) then
		MelloUI:Print("target: portrait replaced with the %s medallion", classFile)
	else
		MelloUI:Print("target: class %s has no mapped icon, portrait unchanged", classFile)
	end
end
