--------------------------------------------------------------------------------
-- MelloUI - Quest List
--
-- A panel attached to the right of the world map listing the quests that can
-- be picked up in a zone: how many of them you have done, and for each quest
-- its level, the quest giver and where to find it. Quests are grouped under
-- collapsible headers in the style of the quest log: one per quest chain,
-- then the single quests. Titles are coloured by difficulty like the quest
-- log, completed quests are greyed with a tick, and clicking a quest drops a
-- map pin on the giver.
--
-- Data: Media\QuestListData.lua, generated by Tools\build_quest_list.py from
-- Wowhead's Forever database, the vanilla server database and the map tables.
-- Quest givers that no database places (new Forever NPCs) get their position
-- from the Voice Over collector the first time you talk to them.
--------------------------------------------------------------------------------

local ADDON_NAME, ns = ...
local MelloUI = ns.MelloUI

local M = MelloUI:RegisterModule("QuestList", {
	title = "Quest List",
	desc = "Panel next to the world map listing the quests of a zone, how many you have completed, and where each one is picked up.",
	enabledByDefault = true,
	defaults = {
		filter = "zone",
		hideCompleted = false,
		otherFaction = false,
		otherClass = false,
		levelAbove = 0,
		width = 380,
		mapPins = true,
		pinCompleted = false,
		zoneBadges = true,
		entrancePins = true,
		transportPins = true,
		dungeonSummary = true,
	},
	options = {
		{ type = "header", name = "List" },
		{ type = "dropdown", key = "filter", name = "Show Quests For", values = {
			{ value = "all", label = "All" },
			{ value = "continent", label = "Current continent" },
			{ value = "zone", label = "Current zone" },
			{ value = "class", label = "Class quests" },
			{ value = "dungeons", label = "Dungeons" },
			{ value = "raids", label = "Raids" },
			{ value = "attunements", label = "Attunements" },
			{ value = "events", label = "Events" },
		  },
		  desc = "Which quests the panel lists. The buttons on the panel switch this as well." },
		{ type = "toggle", key = "hideCompleted", name = "Hide Completed",
		  desc = "Leave out quests you have already completed instead of greying them." },
		{ type = "toggle", key = "otherFaction", name = "Show Other Faction's Quests",
		  desc = "Also list quests only the other faction can take." },
		{ type = "toggle", key = "otherClass", name = "Show Other Classes' Quests",
		  desc = "Also list quests restricted to classes other than yours." },
		{ type = "slider", key = "levelAbove", name = "Hide Quests More Than N Levels Above Me", min = 0, max = 30, step = 1,
		  format = function(v) return v == 0 and "no limit" or ("+" .. v) end,
		  desc = "Leave out quests whose level is more than this many levels above your character. 0 shows everything." },
		{ type = "slider", key = "width", name = "Panel Width", min = 260, max = 520, step = 10,
		  desc = "Width of the panel next to the map." },
		{ type = "header", name = "Map" },
		{ type = "toggle", key = "mapPins", name = "Quest Givers On Zone Maps",
		  desc = "Mark every known quest giver on the zone map with a ! or ? coloured by what you can do there. Hover for the quests, click to track the giver." },
		{ type = "toggle", key = "pinCompleted", name = "Include Givers You Are Done With",
		  desc = "Also mark givers whose quests you have all completed, with a grey tick." },
		{ type = "toggle", key = "zoneBadges", name = "Zone Progress On Continent Maps",
		  desc = "Show a done/total badge on each zone of the continent map. Hover for the level range, click to open the zone." },
		{ type = "toggle", key = "entrancePins", name = "Dungeon And Raid Entrances",
		  desc = "Mark instance entrances on the zone maps. Hover for the level range and your quest progress, click to list its quests. Entrances of new instances are learned the first time you walk in." },
		{ type = "toggle", key = "transportPins", name = "Boats And Zeppelins",
		  desc = "Mark the docks and zeppelin towers on the zone maps with the destination. Click to open the destination's map." },
		{ type = "header", name = "Dungeons" },
		{ type = "toggle", key = "dungeonSummary", name = "Quest Check When Entering An Instance",
		  desc = "When you enter a dungeon or raid, list in chat the quests for it you could have picked up but have not." },
	},
})

--------------------------------------------------------------------------------
-- Data
--------------------------------------------------------------------------------

local function IsSecret(v)
	return issecretvalue and issecretvalue(v)
end

local function Plain(v)
	if v == nil or IsSecret(v) then
		return nil
	end
	return v
end

-- Row fields in MelloUI_QuestListData.quests
local F_ID, F_TITLE, F_LEVEL, F_REQ, F_SIDE, F_CLASS, F_ZONE, F_GIVERZONE, F_GIVER, F_X, F_Y, F_KIND, F_EVENT, F_CHAIN, F_DUNGEON, F_ATTUNE, F_PREV, F_CONT, F_WX, F_WY =
	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
-- giver NPC id; turn-in: name, NPC id, zone (build-time guess), continent, world x, world y
local F_NPC, F_ENDER, F_ENDERNPC, F_ENDERZONE, F_ENDERCONT, F_ENDERWX, F_ENDERWY = 21, 22, 23, 24, 25, 26, 27

local byZone = nil        -- [areaID] = { rows }   (pick-up zone, falling back to quest zone)
local allRows = nil       -- every zone row, sorted by level once
local searchText = nil    -- [row] = lower-cased "title giver zone" for the search box
local rowByID = nil       -- [questID] = row
local byDungeon = nil     -- [dungeonID] = { rows }
local chainStep = nil     -- [row] = position in its chain (1 = first)
local chainTotal = nil    -- [chainID] = number of steps
local nextInChain = nil   -- [questID] = the row that follows it
local eventRows = nil     -- holiday / world event quests, kept out of the zone lists
local zoneByName = nil    -- [lower name] = areaID
local classBit = nil      -- player's class bit in the data's mask
local playerSide = nil    -- 1 Alliance, 2 Horde
local collapsed = {}      -- [group key] = true while a header is collapsed (per session)
local trackedQuestID = nil -- quest whose giver the map pin currently points at
local RefreshPins = nil   -- redraws the map pins; defined in the map pins section

-- Pins recorded by hand (entrances, docks) live with the Route module's
-- learned paths, which the baker keeps across sessions, not in the settings
-- (those are mirrored into account macros and must stay small).
local function LearnedStore(kind)
	local R = MelloUI.Route
	local store = R and R.Pins and R:Pins()
	if store then
		-- Older versions kept them in the settings: move them over once.
		local old = M.db and (kind == "entrances" and M.db.learnedEntrances or kind == "transports" and M.db.learnedTransports)
		if type(old) == "table" then
			for name, v in pairs(old) do
				if store[kind][name] == nil then
					store[kind][name] = v
				end
			end
			if kind == "entrances" then M.db.learnedEntrances = nil else M.db.learnedTransports = nil end
		end
		return store[kind]
	end
	local key = kind == "entrances" and "learnedEntrances" or "learnedTransports"
	M.db[key] = M.db[key] or {}
	return M.db[key]
end
local resolved = nil      -- [row] = { mapID, x, y, cx, cy, contMapID }: the client's placement of a giver's world position
local zoneOverride = nil  -- [row] = areaID when the client puts the giver in another zone than the build did
local rowsByMap = nil     -- [uiMapID] = rows the client placed on that map
local resolvedEnd = nil   -- [row] = placement of the turn-in NPC when it is not the giver
local endRowsByMap = nil  -- [uiMapID] = rows whose turn-in the client placed on that map

local function Data()
	return MelloUI_QuestListData
end

local function ZoneOf(row)
	local override = zoneOverride and zoneOverride[row]
	if override then
		return override
	end
	return row[F_GIVERZONE] ~= 0 and row[F_GIVERZONE] or row[F_ZONE]
end

--------------------------------------------------------------------------------
-- World positions
--
-- Vanilla data gives world coordinates. The client turns them into a
-- continent-map position; the continent map's hit test says which zone (and
-- city) is there, and the zone's rectangle on the continent gives the position
-- on the zone map. Build-time zone guesses are wrong at zone edges and on maps
-- Forever changed (Stormwind with its harbour), so this is done here.
--------------------------------------------------------------------------------

local function VectorXY(pos)
	if type(pos) ~= "table" then
		return nil, nil
	end
	local x, y = Plain(pos.x), Plain(pos.y)
	if (x == nil or y == nil) and type(pos.GetXY) == "function" then
		local ok, gx, gy = pcall(pos.GetXY, pos)
		if ok then
			x, y = Plain(gx), Plain(gy)
		end
	end
	return x, y
end

-- Is `mapID` the map `uiMapID` or one of its parents (city inside a zone)?
local function IsOnOrUnder(uiMapID, mapID)
	local id = uiMapID
	for _ = 1, 4 do
		if id == mapID then
			return true
		end
		local ok, info = pcall(C_Map.GetMapInfo, id)
		id = ok and type(info) == "table" and Plain(info.parentMapID) or nil
		if not id or id == 0 then
			return false
		end
	end
	return false
end

local rectCache = {}

-- Rectangle of a map on its continent map, cached.
local function RectOn(mapID, contMapID)
	local key = mapID .. ":" .. contMapID
	local r = rectCache[key]
	if r == nil then
		local ok, minX, maxX, minY, maxY = pcall(C_Map.GetMapRectOnMap, mapID, contMapID)
		minX, maxX, minY, maxY = Plain(minX), Plain(maxX), Plain(minY), Plain(maxY)
		r = (ok and minX and maxX and minY and maxY and maxX > minX and maxY > minY) and { minX, maxX, minY, maxY } or false
		rectCache[key] = r
	end
	return r or nil
end

local function InRect(r, cx, cy)
	local x, y = (cx - r[1]) / (r[2] - r[1]), (cy - r[3]) / (r[4] - r[3])
	if x >= 0 and x <= 1 and y >= 0 and y <= 1 then
		return x, y
	end
	return nil
end

-- A world point as { mapID, x, y, cx, cy, contMapID }: the deepest map that
-- holds it (city before zone) and its position there, or nil.
local function ResolveWorld(cont, wx, wy)
	if not (C_Map.GetMapPosFromWorldPos and CreateVector2D and C_Map.GetMapInfoAtPosition and C_Map.GetMapRectOnMap) then
		return nil
	end
	local ok, contMapID, pos = pcall(C_Map.GetMapPosFromWorldPos, cont, CreateVector2D(wx, wy))
	contMapID = ok and Plain(contMapID) or nil
	local cx, cy = VectorXY(pos)
	if not (contMapID and cx and cy) then
		return nil
	end
	local okZ, zinfo = pcall(C_Map.GetMapInfoAtPosition, contMapID, cx, cy)
	local zone = okZ and type(zinfo) == "table" and Plain(zinfo.mapID) or nil
	if not zone or zone == contMapID then
		return nil
	end
	local r = RectOn(zone, contMapID)
	local x, y
	if r then
		x, y = InRect(r, cx, cy)
	end
	if not x then
		return nil
	end
	-- One level deeper: a city inside the zone.
	local okC, cinfo = pcall(C_Map.GetMapInfoAtPosition, zone, x, y)
	local child = okC and type(cinfo) == "table" and Plain(cinfo.mapID) or nil
	if child and child ~= zone then
		local r2 = RectOn(child, contMapID)
		local x2, y2
		if r2 then
			x2, y2 = InRect(r2, cx, cy)
		end
		if x2 then
			zone, x, y = child, x2, y2
		end
	end
	return { mapID = zone, x = x, y = y, cx = cx, cy = cy, contMapID = contMapID }
end

-- Position of a resolved point on the map shown (its own map, a parent, or a
-- child), or nil when the point is elsewhere.
local function ProjectOnMap(res, mapID)
	if res.mapID == mapID then
		return res.x, res.y
	end
	if not (IsOnOrUnder(res.mapID, mapID) or IsOnOrUnder(mapID, res.mapID)) then
		return nil
	end
	local r = RectOn(mapID, res.contMapID)
	if not r then
		return nil
	end
	return InRect(r, res.cx, res.cy)
end

-- Where a quest giver is: uiMapID, x, y (0..1) from the client's placement,
-- else the build-time zone and map percentage.
local function GiverPoint(row)
	local res = resolved and resolved[row]
	if res then
		return res.mapID, res.x, res.y
	end
	if row[F_X] ~= 0 or row[F_Y] ~= 0 then
		return nil, row[F_X] / 100, row[F_Y] / 100
	end
	return nil
end

-- Is the quest handed back to the NPC that gave it?
local function SameEnder(row)
	local ender, giver = row[F_ENDER] or "", row[F_GIVER] or ""
	if ender == "" then
		return true
	end
	local enpc, gnpc = row[F_ENDERNPC] or 0, row[F_NPC] or 0
	if enpc ~= 0 and gnpc ~= 0 then
		return enpc == gnpc
	end
	return ender == giver
end

-- Where a quest is handed in: uiMapID, x, y from the client's placement, or nil.
local function EndPoint(row)
	local res = resolvedEnd and resolvedEnd[row]
	if res then
		return res.mapID, res.x, res.y
	end
	return nil
end

-- Zone name of the turn-in, from its placement or the build-time guess.
local function EnderZoneName(row)
	local res = resolvedEnd and resolvedEnd[row]
	if res then
		local ok, info = pcall(C_Map.GetMapInfo, res.mapID)
		local name = ok and type(info) == "table" and Plain(info.name) or nil
		if name then
			return name
		end
	end
	return (row[F_ENDERZONE] or 0) ~= 0 and Data().zones[row[F_ENDERZONE]] or nil
end

local function ByLevel(a, b)
	if a[F_LEVEL] ~= b[F_LEVEL] then return a[F_LEVEL] < b[F_LEVEL] end
	return a[F_TITLE] < b[F_TITLE]
end

local function BuildIndex()
	byZone, zoneByName, eventRows, allRows, searchText = {}, {}, {}, {}, {}
	local data = Data()
	if type(data) ~= "table" then
		return
	end
	local zones = data.zones or {}
	for areaID, name in pairs(zones) do
		zoneByName[name:lower()] = areaID
	end
	-- The client's placements (filled in over a few frames after enable by
	-- ResolveInChunks; the index is rebuilt when they are complete). The zone
	-- a giver lands in wins over the build-time guess.
	zoneOverride, rowsByMap, endRowsByMap = {}, {}, {}
	resolved = resolved or {}
	resolvedEnd = resolvedEnd or {}
	local mapArea = {}
	for _, row in ipairs(data.quests or {}) do
		local res = resolved[row]
		if res then
			rowsByMap[res.mapID] = rowsByMap[res.mapID] or {}
			table.insert(rowsByMap[res.mapID], row)
			local areaID = mapArea[res.mapID]
			if areaID == nil then
				local okI, info = pcall(C_Map.GetMapInfo, res.mapID)
				local name = okI and type(info) == "table" and Plain(info.name) or nil
				areaID = name and zoneByName[name:lower()] or false
				mapArea[res.mapID] = areaID
			end
			if areaID and areaID ~= ZoneOf(row) then
				zoneOverride[row] = areaID
			end
		end
		local ender = resolvedEnd[row]
		if ender then
			endRowsByMap[ender.mapID] = endRowsByMap[ender.mapID] or {}
			table.insert(endRowsByMap[ender.mapID], row)
		end
	end
	for _, row in ipairs(data.quests or {}) do
		local zone = ZoneOf(row)
		searchText[row] = (row[F_TITLE] .. " " .. row[F_GIVER] .. " " .. (zones[zone] or "")):lower()
		if (row[F_EVENT] or 0) ~= 0 then
			table.insert(eventRows, row)
		elseif zone ~= 0 then
			byZone[zone] = byZone[zone] or {}
			table.insert(byZone[zone], row)
			allRows[#allRows + 1] = row
		end
	end
	table.sort(eventRows, ByLevel)
	table.sort(allRows, ByLevel)
	for _, rows in pairs(byZone) do
		table.sort(rows, ByLevel)
	end
	-- Chain steps: follow the "previous quest" links back to the chain start.
	rowByID, chainStep, chainTotal, nextInChain, byDungeon = {}, {}, {}, {}, {}
	for _, row in ipairs(data.quests or {}) do
		rowByID[row[F_ID]] = row
		if row[F_DUNGEON] ~= 0 then
			byDungeon[row[F_DUNGEON]] = byDungeon[row[F_DUNGEON]] or {}
			table.insert(byDungeon[row[F_DUNGEON]], row)
		end
	end
	local function StepOf(row, depth)
		local step = chainStep[row]
		if step then
			return step
		end
		local prevRow = (row[F_PREV] or 0) ~= 0 and rowByID[row[F_PREV]] or nil
		if prevRow and prevRow[F_CHAIN] == row[F_CHAIN] and depth < 60 then
			step = StepOf(prevRow, depth + 1) + 1
		else
			step = 1
		end
		chainStep[row] = step
		return step
	end
	for _, row in ipairs(data.quests or {}) do
		if row[F_CHAIN] ~= 0 then
			local step = StepOf(row, 0)
			if step > (chainTotal[row[F_CHAIN]] or 0) then
				chainTotal[row[F_CHAIN]] = step
			end
			local prev = row[F_PREV] or 0
			if prev ~= 0 and rowByID[prev] and not nextInChain[prev] then
				nextInChain[prev] = row
			end
		end
	end
	local _, classFile = UnitClass("player")
	for mask, name in pairs(data.classes or {}) do
		if name == classFile then
			classBit = mask
		end
	end
	playerSide = UnitFactionGroup("player") == "Horde" and 2 or 1
end

-- Ask the client where every vanilla giver and turn-in is, a few hundred rows
-- per frame so login does not stall, then rebuild the index once.
local resolving = false
local resolveDone = false

local function ResolveInChunks(onDone)
	if resolving or resolveDone then
		return
	end
	local data = Data()
	local rows = type(data) == "table" and data.quests or nil
	if not rows or not (C_Map.GetMapPosFromWorldPos and CreateVector2D and C_Map.GetMapInfoAtPosition and C_Map.GetMapRectOnMap) then
		resolveDone = true
		return
	end
	resolving = true
	resolved = resolved or {}
	resolvedEnd = resolvedEnd or {}
	local i, n = 1, #rows
	local function Step()
		local stop = math.min(i + 299, n)
		while i <= stop do
			local row = rows[i]
			if (row[F_CONT] or -1) >= 0 and resolved[row] == nil then
				resolved[row] = ResolveWorld(row[F_CONT], row[F_WX], row[F_WY]) or false
			end
			if (row[F_ENDERCONT] or -1) >= 0 and resolvedEnd[row] == nil
				and not (row[F_ENDERCONT] == row[F_CONT] and row[F_ENDERWX] == row[F_WX] and row[F_ENDERWY] == row[F_WY]) then
				resolvedEnd[row] = ResolveWorld(row[F_ENDERCONT], row[F_ENDERWX], row[F_ENDERWY]) or false
			end
			i = i + 1
		end
		if i <= n then
			C_Timer.After(0, Step)
		else
			resolving = false
			resolveDone = true
			onDone()
		end
	end
	Step()
end

-- step, total steps, next row (or nil) for a quest in a chain.
local function ChainInfo(row)
	if row[F_CHAIN] == 0 or not chainStep then
		return nil
	end
	return chainStep[row] or 1, chainTotal[row[F_CHAIN]] or 1, nextInChain[row[F_ID]]
end

local function Eligible(row)
	local db = M.db
	if not db.otherFaction and row[F_SIDE] ~= 0 and row[F_SIDE] ~= 3 and row[F_SIDE] ~= playerSide then
		return false
	end
	if not db.otherClass and row[F_CLASS] ~= 0 and classBit and bit.band(row[F_CLASS], classBit) == 0 then
		return false
	end
	local above = tonumber(db.levelAbove) or 0
	if above > 0 then
		local level = Plain(UnitLevel("player")) or 60
		if row[F_LEVEL] > level + above then
			return false
		end
	end
	return true
end

local function IsCompleted(questID)
	if C_QuestLog and C_QuestLog.IsQuestFlaggedCompleted then
		local ok, done = pcall(C_QuestLog.IsQuestFlaggedCompleted, questID)
		if ok and not IsSecret(done) then
			return done == true
		end
	end
	return false
end

local function IsOnQuest(questID)
	if C_QuestLog and C_QuestLog.IsOnQuest then
		local ok, on = pcall(C_QuestLog.IsOnQuest, questID)
		if ok and not IsSecret(on) then
			return on == true
		end
	end
	return false
end

-- A quest in the log whose objectives are all done.
local readyChecks = nil
local function IsReadyForTurnIn(questID)
	if not readyChecks then
		readyChecks = {}
		for _, name in ipairs({ "ReadyForTurnIn", "IsComplete" }) do
			if C_QuestLog and type(C_QuestLog[name]) == "function" then
				readyChecks[#readyChecks + 1] = C_QuestLog[name]
			end
		end
	end
	for _, fn in ipairs(readyChecks) do
		local ok, ready = pcall(fn, questID)
		if ok and not IsSecret(ready) and ready ~= nil then
			return ready == true
		end
	end
	return false
end

-- Quest log colouring: grey trivial, green easy, yellow fair, orange hard, red very hard.
local function DifficultyColor(level)
	if level <= 0 then
		return 0.75, 0.61, 0
	end
	if GetQuestDifficultyColor then
		local ok, color = pcall(GetQuestDifficultyColor, level)
		if ok and type(color) == "table" and color.r then
			return color.r, color.g, color.b
		end
	end
	local mine = Plain(UnitLevel("player")) or 60
	local diff = level - mine
	if diff >= 5 then return 1, 0.1, 0.1 end
	if diff >= 3 then return 1, 0.5, 0.25 end
	if diff >= -2 then return 1, 0.82, 0 end
	local trivial = 5
	if mine >= 40 then trivial = 12 elseif mine >= 30 then trivial = 9 elseif mine >= 20 then trivial = 7 elseif mine >= 10 then trivial = 6 end
	if diff > -trivial then return 0.25, 0.75, 0.25 end
	return 0.5, 0.5, 0.5
end

--------------------------------------------------------------------------------
-- Map helpers
--------------------------------------------------------------------------------

local mapIDByName = nil

local function MapIDForZoneName(name)
	if not mapIDByName then
		mapIDByName = {}
		local ok, root = pcall(C_Map.GetFallbackWorldMapID)
		root = ok and Plain(root) or 947
		local okC, children = pcall(C_Map.GetMapChildrenInfo, root, nil, true)
		if okC and type(children) == "table" then
			for _, info in ipairs(children) do
				local n = Plain(info.name)
				if n and not mapIDByName[n:lower()] then
					mapIDByName[n:lower()] = info.mapID
				end
			end
		end
	end
	return mapIDByName[name:lower()]
end

local function ZoneNameForMap(mapID)
	if not mapID then
		return nil
	end
	local ok, info = pcall(C_Map.GetMapInfo, mapID)
	if ok and info then
		return Plain(info.name)
	end
	return nil
end

local function CurrentMapID()
	local ok, id = pcall(WorldMapFrame.GetMapID, WorldMapFrame)
	local mapID = ok and Plain(id) or nil
	if not mapID then
		local okP, pid = pcall(C_Map.GetBestMapForUnit, "player")
		mapID = okP and Plain(pid) or nil
	end
	return mapID
end

local function CurrentAreaID()
	local mapID = CurrentMapID()
	local name = ZoneNameForMap(mapID)
	if not name then
		return nil, nil
	end
	local areaID = zoneByName[name:lower()]
	if not areaID then
		-- A continent or the world is shown: use the zone the player is in.
		local okP, pid = pcall(C_Map.GetBestMapForUnit, "player")
		local pname = ZoneNameForMap(okP and Plain(pid) or nil)
		if pname then
			areaID, name = zoneByName[pname:lower()], pname
		end
	end
	return areaID, name
end

-- Continent (0 Eastern Kingdoms, 1 Kalimdor) of the map shown, walking up the map tree.
local function CurrentContinent()
	local mapID = CurrentMapID()
	for _ = 1, 6 do
		if not mapID then break end
		local ok, info = pcall(C_Map.GetMapInfo, mapID)
		if not ok or not info then break end
		local name = Plain(info.name)
		if name then
			for c, cname in pairs(Data().continentNames or {}) do
				if cname:lower() == name:lower() then
					return c, cname
				end
			end
		end
		mapID = Plain(info.parentMapID)
		if not mapID or mapID == 0 then break end
	end
	local areaID = CurrentAreaID()
	if areaID then
		local c = Data().zoneContinent and Data().zoneContinent[areaID]
		if c and c >= 0 then
			return c, Data().continentNames[c]
		end
	end
	return nil, nil
end

local function SetWaypoint(row, atEnder)
	local mapID, x, y
	if atEnder then
		mapID, x, y = EndPoint(row)
	end
	if not x then
		mapID, x, y = GiverPoint(row)
	end
	if not x then
		return false
	end
	if not mapID then
		local zoneName = Data().zones[ZoneOf(row)]
		mapID = zoneName and MapIDForZoneName(zoneName)
	end
	if not mapID or not C_Map.SetUserWaypoint or not UiMapPoint then
		return false
	end
	local okCan, can = pcall(C_Map.CanSetUserWaypointOnMap, mapID)
	if okCan and can == false then
		return false
	end
	-- Through the Route module when it is on: pin, route, label and notice in one.
	local R = MelloUI.Route
	if R and R.isEnabled and R.SetDestinationTo then
		local who = atEnder and (row[F_ENDER] or "") ~= "" and row[F_ENDER] or row[F_GIVER]
		local icon = atEnder and "|A:QuestTurnin:16:16|a " or "|A:QuestNormal:16:16|a "
		local label = icon .. row[F_TITLE] .. (who ~= "" and (" - " .. who) or "")
		local what = atEnder and "turn-in" or "quest giver"
		local text = string.format("%sTracking %s %s for %s, {dist} away", icon, what, who ~= "" and who or "", row[F_TITLE])
		if R:SetDestinationTo({ mapID = mapID, x = x, y = y }, label, true, text) then
			trackedQuestID = row[F_ID]
			return true
		end
	end
	local point = UiMapPoint.CreateFromCoordinates(mapID, x, y)
	local ok = pcall(C_Map.SetUserWaypoint, point)
	if ok and C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then
		pcall(C_SuperTrack.SetSuperTrackedUserWaypoint, true)
	end
	if ok then
		trackedQuestID = row[F_ID]
	end
	return ok
end

-- Route to a point on a map (entrance, dock, flight master): the Route
-- module when it is on, else a plain user waypoint.
local function RouteToPoint(mapID, x, y, label, notice)
	if not (mapID and x and y) then
		return false
	end
	local R = MelloUI.Route
	if R and R.isEnabled and R.SetDestinationTo then
		return R:SetDestinationTo({ mapID = mapID, x = x, y = y }, label, true, notice) and true or false
	end
	if not (C_Map.SetUserWaypoint and UiMapPoint) then
		return false
	end
	local okCan, can = pcall(C_Map.CanSetUserWaypointOnMap, mapID)
	if okCan and can == false then
		return false
	end
	local ok = pcall(C_Map.SetUserWaypoint, UiMapPoint.CreateFromCoordinates(mapID, x, y))
	if ok and C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then
		pcall(C_SuperTrack.SetSuperTrackedUserWaypoint, true)
	end
	return ok
end

local function ClearWaypoint()
	if C_Map.ClearUserWaypoint then
		pcall(C_Map.ClearUserWaypoint)
	end
	trackedQuestID = nil
end

-- The pin can be removed from the map itself; forget the quest then.
local function SyncTracked()
	if trackedQuestID and C_Map.HasUserWaypoint then
		local ok, has = pcall(C_Map.HasUserWaypoint)
		if ok and has == false then
			trackedQuestID = nil
		end
	end
end

--------------------------------------------------------------------------------
-- Panel
--------------------------------------------------------------------------------

local Panel = {}
local ROW_HEIGHT = 34
local HEADER_HEIGHT = 24
local FILTERS = {
	{ key = "all", label = "All" }, { key = "continent", label = "Continent" }, { key = "zone", label = "Zone" }, { key = "class", label = "Class" },
	{ key = "dungeons", label = "Dungeons" }, { key = "raids", label = "Raids" }, { key = "attunements", label = "Attunements" }, { key = "events", label = "Events" },
}
local BUTTONS_PER_ROW = 4
local GOLD = { 0.75, 0.61, 0 }
local GOLD_DIM = { 0.55, 0.45, 0.18 }

local function HeaderClick(self)
	if self.entry and self.entry.header then
		collapsed[self.entry.key] = not collapsed[self.entry.key] or nil
		PlaySound(collapsed[self.entry.key] and SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_OFF or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON)
		Panel:Update()
	end
end

local function RowClick(self)
	if not (self.entry and self.entry.row) then
		return
	end
	if trackedQuestID == self.entry.row[F_ID] then
		ClearWaypoint()
		PlaySound(SOUNDKIT.UI_MAP_WAYPOINT_REMOVE or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_OFF)
	elseif SetWaypoint(self.entry.row, self.entry.ready) then
		PlaySound(SOUNDKIT.UI_MAP_WAYPOINT_CLICK_TO_PLACE or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON)
	end
	Panel:Update()
	if RefreshPins then
		RefreshPins()
	end
end

local function RowEnter(self)
	local e = self.entry
	if not e or not e.row then return end
	local row = e.row
	GameTooltip:SetOwner(self, "ANCHOR_LEFT")
	local r, g, b = DifficultyColor(row[F_LEVEL])
	GameTooltip:SetText(row[F_TITLE], r, g, b)
	GameTooltip:AddLine(string.format("Level %d, requires level %d", row[F_LEVEL], row[F_REQ]), 0.8, 0.8, 0.8)
	if row[F_DUNGEON] ~= 0 and Data().dungeons[row[F_DUNGEON]] then
		GameTooltip:AddLine("Dungeon quest: " .. Data().dungeons[row[F_DUNGEON]], 0.75, 0.61, 0)
	end
	if row[F_CHAIN] ~= 0 and Data().chains[row[F_CHAIN]] then
		local step, total, nextRow = ChainInfo(row)
		GameTooltip:AddLine(string.format("Step %d of %d in the chain: %s", step, total, Data().chains[row[F_CHAIN]]), 0.75, 0.61, 0)
		if nextRow then
			GameTooltip:AddLine("Next: " .. nextRow[F_TITLE], 0.6, 0.6, 0.6)
		end
	end
	if row[F_GIVER] ~= "" then
		local giverZone = Data().zones[ZoneOf(row)]
		GameTooltip:AddLine("From " .. row[F_GIVER] .. (giverZone and (" in " .. giverZone) or ""), 0.8, 0.8, 0.8)
	end
	if (row[F_ENDER] or "") ~= "" then
		if SameEnder(row) then
			GameTooltip:AddLine("Turn in to the same NPC", 0.6, 0.6, 0.6)
		else
			local endZone = EnderZoneName(row)
			GameTooltip:AddLine("Turn in to " .. row[F_ENDER] .. (endZone and (" in " .. endZone) or ""), 0.8, 0.8, 0.8)
		end
	end
	if e.completed then
		GameTooltip:AddLine("Completed", 0.5, 0.5, 0.5)
	elseif e.onQuest and e.ready then
		GameTooltip:AddLine("In your quest log, ready to turn in", 1, 0.82, 0)
	elseif e.onQuest then
		GameTooltip:AddLine("In your quest log, objectives not done", 0.7, 0.7, 0.7)
	elseif e.available then
		GameTooltip:AddLine("Available to pick up", 1, 0.82, 0)
	else
		GameTooltip:AddLine(string.format("Needs level %d", row[F_REQ]), 0.7, 0.7, 0.7)
	end
	if trackedQuestID == row[F_ID] then
		GameTooltip:AddLine("Map pin set on this quest giver. Click to remove it.", 0.6, 0.8, 1)
	elseif e.ready and EndPoint(row) then
		GameTooltip:AddLine("Click to place a map pin on the turn-in NPC.", 0.6, 0.8, 1)
	elseif select(2, GiverPoint(row)) then
		GameTooltip:AddLine("Click to place a map pin on the quest giver.", 0.6, 0.8, 1)
	else
		GameTooltip:AddLine("Location not known yet.", 0.6, 0.6, 0.6)
	end
	GameTooltip:Show()
end

local function Leave()
	GameTooltip:Hide()
end

-- One button pool serves headers and rows, so every widget is created once
-- and each init sets up the button completely for the kind it shows.
local function EnsureWidgets(button)
	if button.title then
		return
	end
	button.label = button:CreateFontString(nil, "OVERLAY", "GameFontNormal")
	if Game15Font_Shadow then
		button.label:SetFontObject(Game15Font_Shadow)
	end
	button.label:SetPoint("LEFT", 9, 0)
	button.label:SetPoint("RIGHT", -70, 0)
	button.label:SetJustifyH("LEFT")
	button.label:SetWordWrap(false)
	button.count = button:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
	button.count:SetPoint("RIGHT", -30, 0)
	button.count:SetJustifyH("RIGHT")
	button.plus = button:CreateTexture(nil, "OVERLAY")
	button.plus:SetPoint("RIGHT", -6, 0)
	button.check = button:CreateTexture(nil, "ARTWORK")
	button.check:SetSize(14, 14)
	button.check:SetPoint("LEFT", 14, 0)
	button.title = button:CreateFontString(nil, "OVERLAY", "GameFontNormal")
	button.title:SetPoint("TOPLEFT", 34, -3)
	button.title:SetPoint("RIGHT", -8, 0)
	button.title:SetJustifyH("LEFT")
	button.title:SetWordWrap(false)
	button.where = button:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
	button.where:SetPoint("BOTTOMLEFT", 34, 4)
	button.where:SetPoint("RIGHT", -8, 0)
	button.where:SetJustifyH("LEFT")
	button.where:SetWordWrap(false)
	button.pin = button:CreateTexture(nil, "OVERLAY")
	button.pin:SetSize(20, 20)
	button.pin:SetPoint("RIGHT", -6, 0)
	-- The map's own pin art, not the small chat icon version.
	local pinned = false
	for _, atlas in ipairs({ "Waypoint-MapPin-Minimap-Tracked", "Waypoint-MapPin-Tracked", "Waypoint-MapPin-Untracked" }) do
		if pcall(button.pin.SetAtlas, button.pin, atlas) and button.pin:GetAtlas() then
			pinned = true
			break
		end
	end
	if not pinned then
		button.pin:SetTexture([[Interface\MINIMAP\TRACKING\None]])
	end
	button.pin:Hide()
end

local function InitHeader(button, entry)
	EnsureWidgets(button)
	button.entry = entry
	button:SetHeight(HEADER_HEIGHT)
	button.check:Hide()
	button.title:Hide()
	button.where:Hide()
	button.label:Show()
	button.count:Show()
	button.plus:Show()
	button.pin:Hide()
	button:SetNormalAtlas("common-button-list-collapseExpand")
	button:SetHighlightAtlas("common-button-list-collapseExpand", "ADD")
	button:GetHighlightTexture():SetAlpha(0.4)
	button.plus:SetAtlas(collapsed[entry.key] and "common-button-list-plus" or "common-button-list-minus", true)
	button:SetScript("OnClick", HeaderClick)
	button:SetScript("OnEnter", nil)
	button:SetScript("OnLeave", nil)
	button.label:SetText(entry.name)
	button.label:SetTextColor(0.9, 0.9, 0.9)
	button.count:SetText(string.format("%d/%d", entry.done, entry.total))
	if entry.done == entry.total and entry.total > 0 then
		button.count:SetTextColor(0.5, 0.5, 0.5)
	else
		button.count:SetTextColor(1, 1, 1)
	end
end

local function InitRow(button, entry)
	EnsureWidgets(button)
	button.entry = entry
	button:SetHeight(ROW_HEIGHT)
	button.label:Hide()
	button.count:Hide()
	button.plus:Hide()
	button.title:Show()
	button.where:Show()
	local tracked = trackedQuestID ~= nil and entry.row[F_ID] == trackedQuestID
	button.pin:SetShown(tracked)
	button.title:SetPoint("RIGHT", tracked and -28 or -8, 0)
	button.where:SetPoint("RIGHT", tracked and -28 or -8, 0)
	button:ClearNormalTexture()
	button:SetHighlightTexture([[Interface\QuestFrame\UI-QuestTitleHighlight]], "ADD")
	button:GetHighlightTexture():SetAlpha(0.6)
	button:SetScript("OnClick", RowClick)
	button:SetScript("OnEnter", RowEnter)
	button:SetScript("OnLeave", Leave)
	local row = entry.row
	local r, g, b = DifficultyColor(row[F_LEVEL])
	local levelText = row[F_LEVEL] > 0 and string.format(" (%d)", row[F_LEVEL]) or ""
	local stepText = entry.step and string.format("%d. ", entry.step) or ""
	button.title:SetText(stepText .. row[F_TITLE] .. levelText)
	-- Icon: tick = done before; yellow ? = in log and finished; grey ? = in log,
	-- not finished; yellow ! = can be picked up; grey ! = not yet (level).
	button.check:Show()
	if entry.completed then
		button.check:SetAtlas("questlog-icon-checkmark-yellow")
		button.check:SetDesaturated(true)
		button.check:SetAlpha(0.7)
		button.title:SetTextColor(0.5, 0.5, 0.5)
	elseif entry.onQuest then
		button.check:SetAtlas("QuestTurnin")
		button.check:SetDesaturated(not entry.ready)
		button.check:SetAlpha(entry.ready and 1 or 0.6)
		button.title:SetTextColor(r, g, b)
	else
		button.check:SetAtlas("QuestNormal")
		button.check:SetDesaturated(not entry.available)
		button.check:SetAlpha(entry.available and 1 or 0.6)
		button.title:SetTextColor(r, g, b)
	end
	local where
	if entry.ready and (row[F_ENDER] or "") ~= "" then
		where = "Turn in: " .. row[F_ENDER]
		local _, ex, ey = EndPoint(row)
		if not ex and SameEnder(row) then
			_, ex, ey = GiverPoint(row)
		end
		if ex then
			where = where .. string.format("   %.1f, %.1f", ex * 100, ey * 100)
		end
		if entry.showZone then
			local endZone = EnderZoneName(row) or Data().zones[ZoneOf(row)]
			if endZone then
				where = endZone .. "  -  " .. where
			end
		end
	elseif row[F_GIVER] ~= "" then
		where = row[F_GIVER]
		local _, gx, gy = GiverPoint(row)
		if gx then
			where = where .. string.format("   %.1f, %.1f", gx * 100, gy * 100)
		end
		if entry.showZone then
			local giverZone = Data().zones[ZoneOf(row)]
			if giverZone then
				where = giverZone .. "  -  " .. where
			end
		end
	else
		where = entry.showZone and (Data().zones[row[F_ZONE]] or "") or "quest giver unknown"
	end
	button.where:SetText(where)
	if entry.completed then
		button.where:SetTextColor(0.4, 0.4, 0.4)
	else
		button.where:SetTextColor(GOLD_DIM[1], GOLD_DIM[2], GOLD_DIM[3])
	end
end

function Panel:Create()
	if self.frame then
		return
	end
	local frame = CreateFrame("Frame", "MelloUIQuestListPanel", WorldMapFrame, "PortraitFrameTemplate")
	self.frame = frame
	frame:SetPoint("TOPLEFT", WorldMapFrame, "TOPRIGHT", 2, 0)
	frame:SetPoint("BOTTOMLEFT", WorldMapFrame, "BOTTOMRIGHT", 2, 0)
	frame:SetWidth(tonumber(M.db.width) or 340)
	frame:SetFrameStrata(WorldMapFrame:GetFrameStrata())
	frame:SetFrameLevel(WorldMapFrame:GetFrameLevel() + 5)
	frame:EnableMouse(true)
	if frame.SetTitle then
		frame:SetTitle("Quests")
	end
	if frame.CloseButton then
		frame.CloseButton:Hide()
	end
	-- Drop the portrait ring: the border art without the circle is a separate
	-- layout that Blizzard's own helper switches to.
	if not (ButtonFrameTemplate_HidePortrait and pcall(ButtonFrameTemplate_HidePortrait, frame)) then
		if frame.PortraitContainer then
			frame.PortraitContainer:Hide()
		end
		if NineSliceUtil and frame.NineSlice then
			pcall(NineSliceUtil.ApplyLayoutByName, frame.NineSlice, "PortraitFrameTemplateNoPortrait")
		end
	end

	-- The quest log's dark book background inside the border.
	frame.bg = frame:CreateTexture(nil, "BACKGROUND", nil, 1)
	frame.bg:SetPoint("TOPLEFT", 8, -26)
	frame.bg:SetPoint("BOTTOMRIGHT", -8, 8)
	if not pcall(frame.bg.SetAtlas, frame.bg, "QuestLog-main-background") then
		frame.bg:SetColorTexture(0.08, 0.06, 0.05, 1)
	end

	frame.zone = frame:CreateFontString(nil, "OVERLAY", "GameFontHighlightMedium")
	frame.zone:SetPoint("TOPLEFT", 18, -36)
	frame.zone:SetPoint("RIGHT", -18, 0)
	frame.zone:SetJustifyH("LEFT")
	frame.zone:SetWordWrap(false)
	frame.count = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
	frame.count:SetPoint("TOPLEFT", frame.zone, "BOTTOMLEFT", 0, -3)
	frame.count:SetJustifyH("LEFT")

	frame.divider = frame:CreateTexture(nil, "ARTWORK")
	frame.divider:SetPoint("TOPLEFT", frame.count, "BOTTOMLEFT", -6, -6)
	frame.divider:SetPoint("RIGHT", -12, 0)
	frame.divider:SetHeight(8)
	if not pcall(frame.divider.SetAtlas, frame.divider, "QuestLog-frame-devider") then
		frame.divider:SetColorTexture(0.4, 0.32, 0.12, 0.6)
		frame.divider:SetHeight(1)
	end

	-- Search box in the quest log's style. Typing searches every zone.
	local search = CreateFrame("EditBox", nil, frame, "SearchBoxTemplate")
	search:SetPoint("TOPLEFT", frame.divider, "BOTTOMLEFT", 10, -6)
	search:SetPoint("RIGHT", -16, 0)
	search:SetHeight(22)
	search:SetAutoFocus(false)
	if search.Instructions then
		search.Instructions:SetText("Search quests")
	end
	search:HookScript("OnTextChanged", function(self, userInput)
		if userInput then
			Panel:Schedule()
		end
	end)
	search:SetScript("OnEscapePressed", function(self)
		self:SetText("")
		self:ClearFocus()
		Panel:Update()
	end)
	frame.search = search

	-- Filter buttons.
	frame.filters = {}
	for i, f in ipairs(FILTERS) do
		local b = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")
		b:SetSize(84, 22)
		local column, row = (i - 1) % BUTTONS_PER_ROW, math.floor((i - 1) / BUTTONS_PER_ROW)
		if column > 0 then
			b:SetPoint("LEFT", frame.filters[i - 1], "RIGHT", 3, 0)
		elseif row > 0 then
			b:SetPoint("TOPLEFT", frame.filters[i - BUTTONS_PER_ROW], "BOTTOMLEFT", 0, -3)
		else
			b:SetPoint("TOPLEFT", frame.search, "BOTTOMLEFT", -4, -5)
		end
		b:SetText(f.label)
		b.key = f.key
		b:SetScript("OnClick", function(self)
			M.db.filter = self.key
			MelloUI:NotifySettingChanged(M.name, "filter", self.key)
			Panel:Update()
		end)
		frame.filters[i] = b
	end
	frame.hide = CreateFrame("CheckButton", nil, frame, "UICheckButtonTemplate")
	frame.hide:SetSize(22, 22)
	-- Below the last row of buttons.
	local lastRowFirst = frame.filters[#frame.filters - ((#frame.filters - 1) % BUTTONS_PER_ROW)]
	frame.hide:SetPoint("TOPLEFT", lastRowFirst, "BOTTOMLEFT", -4, -3)
	frame.hide.text = frame.hide:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
	frame.hide.text:SetPoint("LEFT", frame.hide, "RIGHT", 2, 0)
	frame.hide.text:SetText("Hide completed")
	frame.hide:SetScript("OnClick", function(self)
		M.db.hideCompleted = self:GetChecked() and true or false
		MelloUI:NotifySettingChanged(M.name, "hideCompleted", M.db.hideCompleted)
		Panel:Update()
	end)

	-- Virtualised list with headers and rows.
	frame.scrollBox = CreateFrame("Frame", nil, frame, "WowScrollBoxList")
	frame.scrollBox:SetPoint("TOPLEFT", frame.hide, "BOTTOMLEFT", 6, -4)
	frame.scrollBox:SetPoint("BOTTOMRIGHT", -30, 14)
	frame.scrollBar = CreateFrame("EventFrame", nil, frame, "MinimalScrollBar")
	frame.scrollBar:SetPoint("TOPLEFT", frame.scrollBox, "TOPRIGHT", 6, 0)
	frame.scrollBar:SetPoint("BOTTOMLEFT", frame.scrollBox, "BOTTOMRIGHT", 6, 0)
	local view = CreateScrollBoxListLinearView()
	view:SetElementExtentCalculator(function(_, entry)
		return entry.header and HEADER_HEIGHT or ROW_HEIGHT
	end)
	view:SetElementFactory(function(factory, entry)
		if entry.header then
			factory("Button", InitHeader)
		else
			factory("Button", InitRow)
		end
	end)
	ScrollUtil.InitScrollBoxListWithScrollBar(frame.scrollBox, frame.scrollBar, view)
	frame.empty = frame:CreateFontString(nil, "OVERLAY", "GameFontDisable")
	frame.empty:SetPoint("CENTER", frame.scrollBox, "CENTER")
	frame.empty:SetWidth(240)
	frame.empty:Hide()

	frame:SetScript("OnShow", function() Panel:Update() end)
end

function Panel:Apply()
	if not self.frame then
		return
	end
	self.frame:SetWidth(tonumber(M.db.width) or 340)
	self.frame:SetShown(M.isEnabled)
	self:Update()
end

-- Turn a flat list of rows into header + row entries.
-- groupOf(row) -> key, name; groups are ordered by the level of their first quest.
local function BuildEntries(rows, groupOf, showZone)
	local db = M.db
	local groups, order = {}, {}
	local done, total = 0, 0
	local level = Plain(UnitLevel("player")) or 60
	for _, row in ipairs(rows) do
		if Eligible(row) then
			local completed = IsCompleted(row[F_ID])
			total = total + 1
			if completed then
				done = done + 1
			end
			local key, name, sortLevel = groupOf(row)
			local group = groups[key]
			if not group then
				group = { key = key, name = name, rows = {}, done = 0, total = 0, level = sortLevel or row[F_LEVEL], single = key == "single" }
				groups[key] = group
				order[#order + 1] = group
			end
			group.total = group.total + 1
			if completed then
				group.done = group.done + 1
			end
			if not (completed and db.hideCompleted) then
				local onQuest = not completed and IsOnQuest(row[F_ID])
				group.rows[#group.rows + 1] = {
					row = row, completed = completed, onQuest = onQuest, showZone = showZone,
					ready = onQuest and IsReadyForTurnIn(row[F_ID]) or false,
					available = not onQuest and row[F_REQ] <= level,
					step = (key:sub(1, 5) == "chain") and chainStep and chainStep[row] or nil,
				}
			end
		end
	end
	table.sort(order, function(a, b)
		if a.level ~= b.level then return a.level < b.level end
		return a.name < b.name
	end)
	-- Chain groups read top to bottom in chain order.
	for _, group in ipairs(order) do
		if group.key:sub(1, 5) == "chain" then
			table.sort(group.rows, function(a, b)
				if (a.step or 0) ~= (b.step or 0) then return (a.step or 0) < (b.step or 0) end
				return ByLevel(a.row, b.row)
			end)
		end
	end
	local entries = {}
	for _, group in ipairs(order) do
		if #group.rows > 0 or not db.hideCompleted then
			entries[#entries + 1] = { header = true, key = group.key, name = group.name, done = group.done, total = group.total }
			if not collapsed[group.key] then
				for _, e in ipairs(group.rows) do
					entries[#entries + 1] = e
				end
			end
		end
	end
	return entries, done, total
end

local updatePending = false

-- QUEST_LOG_UPDATE arrives in bursts (a dozen times on a turn-in) and every
-- keystroke in the search box counts too: fold them into one rebuild.
function Panel:Schedule()
	if updatePending then
		return
	end
	updatePending = true
	C_Timer.After(0.15, function()
		updatePending = false
		Panel:Update()
		if RefreshPins then
			RefreshPins()
		end
	end)
end

function Panel:Update()
	local frame = self.frame
	if not frame or not frame:IsShown() or not byZone then
		return
	end
	local db, data = M.db, Data()
	SyncTracked()
	for _, b in ipairs(frame.filters) do
		b:SetAlpha(b.key == db.filter and 1 or 0.6)
	end
	frame.hide:SetChecked(db.hideCompleted and true or false)

	local rows, title, groupOf, showZone
	local term = frame.search and frame.search:GetText() or ""
	term = term:lower():gsub("^%s+", ""):gsub("%s+$", "")

	local function ByZoneGroup(row)
		local zone = ZoneOf(row)
		return "zone" .. zone, data.zones[zone] or "Unknown zone"
	end
	local function DungeonLevel(id)
		-- Instances Wowhead has no level for (Forever's new ones) sort by
		-- their lowest quest instead.
		local lv = data.dungeonLevel and data.dungeonLevel[id]
		return (lv and lv[1] > 0) and lv[1] or nil
	end
	local function DungeonName(id)
		local name = data.dungeons[id] or "Dungeon"
		local lv = data.dungeonLevel and data.dungeonLevel[id]
		if lv and lv[1] > 0 then
			name = string.format("%s |cff888888(%d-%d)|r", name, lv[1], lv[2] > 0 and lv[2] or lv[1])
		end
		return name
	end
	local function ByChainGroup(row)
		if row[F_DUNGEON] ~= 0 and data.dungeons[row[F_DUNGEON]] then
			return "dungeon" .. row[F_DUNGEON], DungeonName(row[F_DUNGEON]), DungeonLevel(row[F_DUNGEON])
		end
		if row[F_CHAIN] ~= 0 and data.chains[row[F_CHAIN]] then
			return "chain" .. row[F_CHAIN], data.chains[row[F_CHAIN]]
		end
		return "single", "Single quests"
	end
	-- allRows is already sorted by level; filtering keeps that order.
	local function AllRows(include)
		if not include then
			return allRows
		end
		local list = {}
		for _, row in ipairs(allRows) do
			if include(row) then list[#list + 1] = row end
		end
		return list
	end

	if term ~= "" then
		local function Matches(row)
			local text = searchText[row]
			return text ~= nil and text:find(term, 1, true) ~= nil
		end
		rows, title, showZone = AllRows(Matches), "Search: " .. term, false
		for _, row in ipairs(eventRows) do
			if Matches(row) then rows[#rows + 1] = row end
		end
		table.sort(rows, ByLevel)
		groupOf = function(row)
			if row[F_EVENT] ~= 0 then
				return "event" .. row[F_EVENT], data.events[row[F_EVENT]] or "Event"
			end
			return ByZoneGroup(row)
		end
	elseif db.filter == "all" then
		rows, title, showZone, groupOf = AllRows(), "All quests", false, ByZoneGroup
	elseif db.filter == "continent" then
		local c, cname = CurrentContinent()
		title = cname or "Unknown continent"
		rows, showZone, groupOf = AllRows(function(row) return c ~= nil and (data.zoneContinent[ZoneOf(row)] == c) end), false, ByZoneGroup
	elseif db.filter == "class" then
		title, showZone = "Class quests", true
		rows = AllRows(function(row) return row[F_CLASS] ~= 0 end)
		groupOf = function(row)
			if row[F_CHAIN] ~= 0 and data.chains[row[F_CHAIN]] then
				return "chain" .. row[F_CHAIN], data.chains[row[F_CHAIN]]
			end
			return ByZoneGroup(row)
		end
	elseif db.filter == "dungeons" or db.filter == "raids" then
		local wantRaid = db.filter == "raids"
		title, showZone = wantRaid and "Raids" or "Dungeons", true
		rows = AllRows(function(row)
			return row[F_DUNGEON] ~= 0 and ((data.raids[row[F_DUNGEON]] == true) == wantRaid)
		end)
		groupOf = function(row)
			return "dungeon" .. row[F_DUNGEON], DungeonName(row[F_DUNGEON]), DungeonLevel(row[F_DUNGEON])
		end
	elseif db.filter == "attunements" then
		title, showZone = "Attunements", true
		rows = AllRows(function(row) return row[F_ATTUNE] == 1 end)
		groupOf = function(row)
			if row[F_CHAIN] ~= 0 and data.chains[row[F_CHAIN]] then
				return "chain" .. row[F_CHAIN], data.chains[row[F_CHAIN]]
			end
			return "single", row[F_TITLE]
		end
	elseif db.filter == "events" then
		rows, title, showZone = eventRows, "Holidays and world events", false
		groupOf = function(row)
			return "event" .. row[F_EVENT], data.events[row[F_EVENT]] or "Event"
		end
	else
		local areaID, name = CurrentAreaID()
		title = name or "Unknown zone"
		rows, showZone, groupOf = areaID and byZone[areaID] or {}, false, ByChainGroup
	end

	local entries, done, total = BuildEntries(rows, groupOf, showZone)
	frame.zone:SetText(title)
	frame.count:SetText(string.format("%d of %d completed", done, total))
	frame.scrollBox:SetDataProvider(CreateDataProvider(entries), ScrollBoxConstants.RetainScrollPosition)
	if #entries == 0 then
		frame.empty:SetText(term ~= "" and "Nothing found." or (total == 0 and "No quests known for this zone." or "All completed."))
		frame.empty:Show()
	else
		frame.empty:Hide()
	end
end


--------------------------------------------------------------------------------
-- Map pins
--
-- Zone maps: one pin per quest giver location, showing what you can do there
-- (yellow ! pick up, yellow ? turn in, grey ? in progress, grey ! too low,
-- grey tick all done). Continent maps: a done/total badge on every zone.
-- Built on the map's own data provider system, so the pins pan and zoom with
-- the canvas like Blizzard's.
--------------------------------------------------------------------------------

local PIN_TEMPLATE = "MelloUIQuestPinTemplate"
local MAP_ZONE = (Enum and Enum.UIMapType and Enum.UIMapType.Zone) or 3
local MAP_CONTINENT = (Enum and Enum.UIMapType and Enum.UIMapType.Continent) or 2

-- Priority of what a giver offers, highest wins the icon.
local STATE_RANK = { ready = 5, available = 4, progress = 3, locked = 2, done = 1 }
local STATE_TEXT = {
	ready = { "Ready to turn in", 1, 0.82, 0 },
	available = { "Available", 1, 0.82, 0 },
	progress = { "In progress", 0.7, 0.7, 0.7 },
	locked = { "Level too low", 0.6, 0.6, 0.6 },
	done = { "Completed", 0.5, 0.5, 0.5 },
}

local TRANSPORT_ATLAS = {
	[0] = { "taxinode_continent_neutral_timed", "TaxiNode_Neutral" },
	[1] = { "taxinode_continent_alliance_timed", "TaxiNode_Alliance" },
	[2] = { "taxinode_continent_horde_timed", "TaxiNode_Horde" },
}

-- Not every atlas of the retail engine is in this client's art; try in turn.
local function SetFirstAtlas(tex, list)
	for _, atlas in ipairs(list) do
		if pcall(tex.SetAtlas, tex, atlas) and tex:GetAtlas() then
			return true
		end
	end
	tex:SetTexture("Interface/Minimap/Tracking/None")
	return false
end

local function DungeonIDByName(name)
	if not name then
		return 0
	end
	for id, dname in pairs(Data().dungeons or {}) do
		if dname:lower() == name:lower() then
			return id
		end
	end
	return 0
end

-- Done / total of a dungeon's quests for this character.
local function DungeonProgress(dungeonID)
	local done, total = 0, 0
	for _, row in ipairs(byDungeon and byDungeon[dungeonID] or {}) do
		if Eligible(row) then
			total = total + 1
			if IsCompleted(row[F_ID]) then
				done = done + 1
			end
		end
	end
	return done, total
end

local function QuestState(row, level)
	if IsCompleted(row[F_ID]) then
		return "done"
	end
	if IsOnQuest(row[F_ID]) then
		return IsReadyForTurnIn(row[F_ID]) and "ready" or "progress"
	end
	return row[F_REQ] <= level and "available" or "locked"
end

MelloUI_QuestPinMixin = MelloUI_QuestPinMixin or {}
local PinMixin = MelloUI_QuestPinMixin
local PinMethods = {}

function PinMethods:OnLoad()
	-- Constant on-screen size whatever the zoom, layered with the map's POIs.
	self:SetScalingLimits(1, 1.0, 1.0)
	self:UseFrameLevelType("PIN_FRAME_LEVEL_AREA_POI")
end

function PinMethods:OnAcquired(kind, data)
	self.kind, self.data = kind, data
	self.Label:ClearAllPoints()
	if kind == "giver" then
		self.Bg:Hide()
		self.Icon:Show()
		self:SetSize(22, 22)
		local state = data.state
		if state == "done" then
			self.Icon:SetAtlas("questlog-icon-checkmark-yellow")
			self.Icon:SetDesaturated(true)
			self.Icon:SetAlpha(0.7)
		elseif state == "ready" or state == "progress" then
			self.Icon:SetAtlas("QuestTurnin")
			self.Icon:SetDesaturated(state ~= "ready")
			self.Icon:SetAlpha(state == "ready" and 1 or 0.75)
		else
			self.Icon:SetAtlas("QuestNormal")
			self.Icon:SetDesaturated(state ~= "available")
			self.Icon:SetAlpha(state == "available" and 1 or 0.75)
		end
		self.Label:SetPoint("TOP", self, "BOTTOM", 0, 2)
		self.Label:SetText(data.tracked and data.giver or "")
		self.Label:SetTextColor(0.6, 0.8, 1)
		self.Label:SetShown(data.tracked)
	elseif kind == "entrance" or kind == "transport" then
		self.Bg:Hide()
		self.Label:Hide()
		self.Icon:Show()
		self.Icon:SetDesaturated(false)
		self.Icon:SetAlpha(1)
		if kind == "entrance" then
			self:SetSize(30, 30)
			SetFirstAtlas(self.Icon, data.raid and { "Raid", "DungeonSkull" } or { "Dungeon", "DungeonSkull" })
		else
			self:SetSize(26, 26)
			SetFirstAtlas(self.Icon, TRANSPORT_ATLAS[data.faction] or TRANSPORT_ATLAS[0])
		end
	else
		self.Icon:Hide()
		self.Bg:Show()
		self.Bg:SetColorTexture(0, 0, 0, 0.7)
		self.Label:SetPoint("CENTER")
		self.Label:SetText(string.format("%d/%d", data.done, data.total))
		if data.done >= data.total then
			self.Label:SetTextColor(0.55, 0.55, 0.55)
		else
			self.Label:SetTextColor(1, 0.82, 0)
		end
		self.Label:Show()
		self:SetSize((self.Label:GetStringWidth() or 30) + 10, 15)
	end
	self:SetPosition(data.x, data.y)
end

function PinMethods:OnReleased()
	if self.widgetContainer then
		self.widgetContainer:UnregisterForWidgetSet()
	end
	if self.RemoveAllTags then
		self:RemoveAllTags()
	end
	if GameTooltip:GetOwner() == self then
		GameTooltip:Hide()
	end
end

function PinMethods:OnMouseEnter()
	local data = self.data
	if not data then
		return
	end
	GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
	if self.kind == "giver" then
		GameTooltip:SetText(data.giver ~= "" and data.giver or "Quest giver", 1, 0.82, 0)
		for _, q in ipairs(data.quests) do
			local row = q.row
			local r, g, b = DifficultyColor(row[F_LEVEL])
			local text = STATE_TEXT[q.state]
			GameTooltip:AddDoubleLine(string.format("%s (%d)", row[F_TITLE], row[F_LEVEL]), text[1], r, g, b, text[2], text[3], text[4])
			local step, total, nextRow = ChainInfo(row)
			if step then
				local chain = Data().chains[row[F_CHAIN]] or "chain"
				local line = string.format("   Step %d of %d in %s", step, total, chain)
				if nextRow and q.state ~= "done" then
					line = line .. ", next: " .. nextRow[F_TITLE]
				end
				GameTooltip:AddLine(line, 0.6, 0.6, 0.6, true)
			end
		end
		if data.tracked then
			GameTooltip:AddLine("Tracked. Click to remove the waypoint.", 0.6, 0.8, 1)
		else
			GameTooltip:AddLine("Click to set a waypoint on this giver.", 0.6, 0.8, 1)
		end
	elseif self.kind == "entrance" then
		GameTooltip:SetText(data.name, 1, 0.82, 0)
		local lv = data.dungeonID ~= 0 and Data().dungeonLevel and Data().dungeonLevel[data.dungeonID]
		local what = data.raid and "Raid" or "Dungeon"
		if lv and lv[1] > 0 then
			GameTooltip:AddLine(string.format("%s, level %d to %d", what, lv[1], lv[2] > 0 and lv[2] or lv[1]), 0.8, 0.8, 0.8)
		else
			GameTooltip:AddLine(what, 0.8, 0.8, 0.8)
		end
		if data.dungeonID ~= 0 then
			local done, total = DungeonProgress(data.dungeonID)
			if total > 0 then
				GameTooltip:AddLine(string.format("%d of %d quests completed", done, total), done >= total and 0.5 or 1, done >= total and 0.5 or 0.82, done >= total and 0.5 or 0)
				GameTooltip:AddLine("Click to list its quests. Shift-click to route there.", 0.6, 0.8, 1)
			else
				GameTooltip:AddLine("No quests known for it yet.", 0.6, 0.6, 0.6)
				GameTooltip:AddLine("Shift-click to route there.", 0.6, 0.8, 1)
			end
		end
		if data.source == "learned" then
			GameTooltip:AddLine("Position learned when you walked in.", 0.6, 0.6, 0.6)
		elseif data.source == "client" then
			GameTooltip:AddLine("Position from the client's own entrance list.", 0.6, 0.6, 0.6)
		end
	elseif self.kind == "transport" then
		GameTooltip:SetText(data.label, 1, 0.82, 0)
		GameTooltip:AddLine((data.kind == 2 and "Zeppelin tower" or "Dock") .. " at " .. data.dock, 0.8, 0.8, 0.8)
		if data.faction == 1 then
			GameTooltip:AddLine("Alliance", 0.3, 0.6, 1)
		elseif data.faction == 2 then
			GameTooltip:AddLine("Horde", 1, 0.3, 0.3)
		else
			GameTooltip:AddLine("Neutral, both factions", 0.8, 0.8, 0.8)
		end
		if data.destMapID or data.destCont then
			GameTooltip:AddLine("Click to route to it. Shift-click to open the destination's map.", 0.6, 0.8, 1)
		end
		if data.learned then
			GameTooltip:AddLine("Recorded with /qlmap dock. Remove with /qlmap remove.", 0.6, 0.6, 0.6)
		end
	else
		GameTooltip:SetText(data.name, 1, 0.82, 0)
		GameTooltip:AddLine(string.format("%d of %d quests completed", data.done, data.total), 0.9, 0.9, 0.9)
		if data.lo > 0 then
			GameTooltip:AddLine(string.format("Quest levels %d to %d", data.lo, data.hi), 0.8, 0.8, 0.8)
		end
		if data.available > 0 then
			GameTooltip:AddLine(string.format("%d you could pick up now", data.available), 1, 0.82, 0)
		end
		if data.inLog > 0 then
			GameTooltip:AddLine(string.format("%d in your quest log", data.inLog), 0.7, 0.7, 0.7)
		end
		GameTooltip:AddLine("Click to open the zone map.", 0.6, 0.8, 1)
	end
	GameTooltip:Show()
end

function PinMethods:OnMouseLeave()
	GameTooltip:Hide()
end

function PinMethods:OnMouseClickAction(button)
	local data = self.data
	if not data or button ~= "LeftButton" then
		return
	end
	if self.kind == "giver" then
		if data.tracked then
			ClearWaypoint()
			PlaySound(SOUNDKIT.UI_MAP_WAYPOINT_REMOVE or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_OFF)
		elseif SetWaypoint(data.quests[1].row, data.quests[1].state == "ready") then
			PlaySound(SOUNDKIT.UI_MAP_WAYPOINT_CLICK_TO_PLACE or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON)
		end
		Panel:Update()
		RefreshPins()
	elseif self.kind == "entrance" then
		if IsShiftKeyDown() then
			-- Shift-click routes to the door; a plain click lists its quests.
			local map = self:GetMap()
			local mapID = map and Plain(map:GetMapID())
			local icon = data.raid and "|A:Raid:16:16|a " or "|A:Dungeon:16:16|a "
			local what = data.raid and "raid" or "dungeon"
			if RouteToPoint(mapID, data.x, data.y, icon .. data.name,
				string.format("%sTracking the %s entrance of %s, {dist} away", icon, what, data.name)) then
				PlaySound(SOUNDKIT.UI_MAP_WAYPOINT_CLICK_TO_PLACE or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON)
			end
		elseif data.dungeonID ~= 0 and byDungeon and byDungeon[data.dungeonID] then
			-- Show the instance's quests: switch the panel and fold the others.
			M.db.filter = data.raid and "raids" or "dungeons"
			MelloUI:NotifySettingChanged(M.name, "filter", M.db.filter)
			for id in pairs(Data().dungeons or {}) do
				collapsed["dungeon" .. id] = (id ~= data.dungeonID) or nil
			end
			Panel:Update()
		end
	elseif self.kind == "transport" and not IsShiftKeyDown() then
		local map = self:GetMap()
		local mapID = map and Plain(map:GetMapID())
		local what = data.kind == 2 and "zeppelin" or "boat"
		local icon = "|A:TaxiNode_Neutral:16:16|a "
		if RouteToPoint(mapID, data.x, data.y, icon .. data.label,
			string.format("%sTracking the %s to %s, {dist} away", icon, what, data.label)) then
			PlaySound(SOUNDKIT.UI_MAP_WAYPOINT_CLICK_TO_PLACE or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON)
		end
	elseif self.kind == "transport" then
		local map = self:GetMap()
		local target = data.destMapID
		if not target and data.destCont and C_Map.GetMapPosFromWorldPos and CreateVector2D then
			local ok, contMapID, pos = pcall(C_Map.GetMapPosFromWorldPos, data.destCont, CreateVector2D(data.destX, data.destY))
			contMapID = ok and Plain(contMapID) or nil
			local cx, cy = VectorXY(pos)
			target = contMapID
			if contMapID and cx and cy and C_Map.GetMapInfoAtPosition then
				local okZ, zinfo = pcall(C_Map.GetMapInfoAtPosition, contMapID, cx, cy)
				local zoneMapID = okZ and type(zinfo) == "table" and Plain(zinfo.mapID) or nil
				if zoneMapID then
					target = zoneMapID
				end
			end
		end
		if map and map.SetMapID and target then
			map:SetMapID(target)
		end
	elseif data.mapID then
		local map = self:GetMap()
		if map and map.SetMapID then
			map:SetMapID(data.mapID)
		end
	end
end

local function PreparePinMixin()
	if PinMixin.SetPosition and PinMixin.OnMouseClickAction then
		return true
	end
	if not MapCanvasPinMixin then
		return false
	end
	Mixin(PinMixin, MapCanvasPinMixin, PinMethods)
	return true
end
PreparePinMixin()

local Provider = nil

local function AddGiverPins(map, mapID, mapName)
	local level = Plain(UnitLevel("player")) or 60
	local groups, order = {}, {}
	local function Consider(row, x, y, who, state)
		local key = string.format("%s|%.3f|%.3f", who, x, y)
		local group = groups[key]
		if not group then
			group = { giver = who, x = x, y = y, quests = {}, state = "done", tracked = false }
			groups[key] = group
			order[#order + 1] = group
		end
		group.quests[#group.quests + 1] = { row = row, state = state }
		if STATE_RANK[state] > STATE_RANK[group.state] then
			group.state = state
		end
		if trackedQuestID == row[F_ID] then
			group.tracked = true
		end
	end
	local seen = {}
	-- A quest ready to hand in is pinned at its turn-in, everything else at its giver.
	local function Place(row, endOnly)
		if seen[row] or not Eligible(row) then
			return
		end
		local state = QuestState(row, level)
		local x, y, who
		if state == "ready" and resolvedEnd[row] then
			x, y = ProjectOnMap(resolvedEnd[row], mapID)
			who = row[F_ENDER]
		elseif not endOnly and resolved[row] then
			x, y = ProjectOnMap(resolved[row], mapID)
			who = row[F_GIVER]
		end
		if x then
			seen[row] = true
			Consider(row, x, y, who, state)
		end
	end
	-- Rows the client placed on this map or on a city inside it.
	local maps = { mapID }
	local okC, children = pcall(C_Map.GetMapChildrenInfo, mapID)
	if okC and type(children) == "table" then
		for _, child in ipairs(children) do
			if Plain(child.mapID) then
				maps[#maps + 1] = child.mapID
			end
		end
	end
	for _, id in ipairs(maps) do
		for _, row in ipairs(rowsByMap and rowsByMap[id] or {}) do
			Place(row, false)
		end
		for _, row in ipairs(endRowsByMap and endRowsByMap[id] or {}) do
			Place(row, true)
		end
	end
	-- Givers with a map percentage only (collected in game on this zone).
	local areaID = zoneByName[mapName:lower()]
	for _, row in ipairs(areaID and byZone[areaID] or {}) do
		if not seen[row] and not (resolved and resolved[row]) and (row[F_X] ~= 0 or row[F_Y] ~= 0) and Eligible(row) then
			seen[row] = true
			Consider(row, row[F_X] / 100, row[F_Y] / 100, row[F_GIVER], QuestState(row, level))
		end
	end
	for _, group in ipairs(order) do
		if group.state ~= "done" or M.db.pinCompleted or group.tracked then
			table.sort(group.quests, function(a, b) return ByLevel(a.row, b.row) end)
			map:AcquirePin(PIN_TEMPLATE, "giver", group)
		end
	end
end

local function AddZoneBadges(map, continentMapID)
	local ok, children = pcall(C_Map.GetMapChildrenInfo, continentMapID, MAP_ZONE, false)
	if not ok or type(children) ~= "table" then
		return
	end
	local level = Plain(UnitLevel("player")) or 60
	for _, child in ipairs(children) do
		local name = Plain(child.name)
		local areaID = name and zoneByName[name:lower()]
		local rows = areaID and byZone[areaID]
		if rows then
			local done, total, available, inLog, lo, hi = 0, 0, 0, 0, 0, 0
			for _, row in ipairs(rows) do
				if Eligible(row) then
					total = total + 1
					local state = QuestState(row, level)
					if state == "done" then
						done = done + 1
					elseif state == "available" then
						available = available + 1
					elseif state == "ready" or state == "progress" then
						inLog = inLog + 1
					end
					local lv = row[F_LEVEL]
					if lv > 0 then
						if lo == 0 or lv < lo then lo = lv end
						if lv > hi then hi = lv end
					end
				end
			end
			local okR, minX, maxX, minY, maxY = pcall(C_Map.GetMapRectOnMap, child.mapID, continentMapID)
			if total > 0 and okR and Plain(minX) and Plain(maxX) and Plain(minY) and Plain(maxY) then
				map:AcquirePin(PIN_TEMPLATE, "badge", {
					mapID = child.mapID, name = name, done = done, total = total, available = available, inLog = inLog,
					lo = lo, hi = hi, x = (minX + maxX) / 2, y = (minY + maxY) / 2,
				})
			end
		end
	end
end


--------------------------------------------------------------------------------
-- Instance entrances and transports
--------------------------------------------------------------------------------

-- Where a world point lies on the map shown. The client's own map assignment
-- is used when it has the API; else the build-time zone guess.
local lastPointTrace = {}

local function WorldPointOnMap(mapID, mapName, cont, wx, wy, zoneArea, px, py)
	local res = ResolveWorld(cont, wx, wy)
	if res then
		local x, y = ProjectOnMap(res, mapID)
		if x then
			return x, y
		end
		return nil
	end
	if C_Map.GetMapPosFromWorldPos then
		lastPointTrace[#lastPointTrace + 1] = string.format("point (%d, %.0f, %.0f): the client could not place it", cont, wx, wy)
	end
	if zoneArea ~= 0 and zoneByName[mapName:lower()] == zoneArea then
		return px / 100, py / 100
	end
	return nil
end

-- Dungeon entrances the client itself knows for a map (retail-style API).
local function ClientEntrances(mapID)
	local out = {}
	if not (C_EncounterJournal and C_EncounterJournal.GetDungeonEntrancesForMap) then
		return out
	end
	local ok, list = pcall(C_EncounterJournal.GetDungeonEntrancesForMap, mapID)
	if not ok or type(list) ~= "table" then
		return out
	end
	for _, info in ipairs(list) do
		local name = Plain(info.name)
		local x, y = VectorXY(info.position)
		if name and x and y then
			local atlas = Plain(info.atlasName) or ""
			out[#out + 1] = { name = name, x = x, y = y, raid = atlas:lower():find("raid") ~= nil }
		end
	end
	return out
end

-- Points of interest the map itself shows, with name, position and icon.
local function ClientPOIs(mapID)
	local out = {}
	if not (C_AreaPoiInfo and C_AreaPoiInfo.GetAreaPOIForMap and C_AreaPoiInfo.GetAreaPOIInfo) then
		return out
	end
	local ok, ids = pcall(C_AreaPoiInfo.GetAreaPOIForMap, mapID)
	if not ok or type(ids) ~= "table" then
		return out
	end
	for _, poiID in ipairs(ids) do
		local okI, info = pcall(C_AreaPoiInfo.GetAreaPOIInfo, mapID, poiID)
		if okI and type(info) == "table" then
			local name = Plain(info.name)
			local x, y = VectorXY(info.position)
			if name and x and y then
				out[#out + 1] = { name = name, x = x, y = y, atlas = Plain(info.atlasName) or "", description = Plain(info.description) or "" }
			end
		end
	end
	return out
end

-- A point of interest that is an instance door: named like one of our
-- dungeons, or drawn with the dungeon / raid icon.
local function IsEntrancePOI(poi)
	if DungeonIDByName(poi.name) ~= 0 then
		return true
	end
	local atlas = poi.atlas:lower()
	return atlas:find("dungeon") ~= nil or atlas:find("raid") ~= nil
end

local function AddEntrancePins(map, mapID, mapName)
	local data = Data()
	local names = {}
	for _, e in ipairs(data.entrances or {}) do
		names[e[2]:lower()] = true
		local x, y = WorldPointOnMap(mapID, mapName, e[3], e[4], e[5], e[6], e[7], e[8])
		if x then
			map:AcquirePin(PIN_TEMPLATE, "entrance", { dungeonID = e[1], name = e[2], raid = e[9] == 2, x = x, y = y, source = "data" })
		end
	end
	-- Entrances learned by walking in (Forever's new instances).
	for name, l in pairs(LearnedStore("entrances")) do
		if l.mapID == mapID and not names[name:lower()] then
			names[name:lower()] = true
			map:AcquirePin(PIN_TEMPLATE, "entrance", { dungeonID = DungeonIDByName(name), name = name, raid = l.raid == true, x = l.x, y = l.y, source = "learned" })
		end
	end
	-- The client's own entrance list for the map, when this build has one.
	for _, e in ipairs(ClientEntrances(mapID)) do
		if not names[e.name:lower()] then
			names[e.name:lower()] = true
			map:AcquirePin(PIN_TEMPLATE, "entrance", { dungeonID = DungeonIDByName(e.name), name = e.name, raid = e.raid, x = e.x, y = e.y, source = "client" })
		end
	end
	-- Points of interest that are instance doors.
	for _, poi in ipairs(ClientPOIs(mapID)) do
		if IsEntrancePOI(poi) and not names[poi.name:lower()] then
			names[poi.name:lower()] = true
			local id = DungeonIDByName(poi.name)
			map:AcquirePin(PIN_TEMPLATE, "entrance", { dungeonID = id, name = poi.name, raid = (id ~= 0 and Data().raids[id] == true) or poi.atlas:lower():find("raid") ~= nil, x = poi.x, y = poi.y, source = "client" })
		end
	end
end

local function AddTransportPins(map, mapID, mapName)
	for _, t in ipairs(Data().transports or {}) do
		local x, y = WorldPointOnMap(mapID, mapName, t[5], t[6], t[7], t[8], t[9], t[10])
		if x then
			map:AcquirePin(PIN_TEMPLATE, "transport", {
				kind = t[1], faction = t[2], label = t[3], dock = t[4], x = x, y = y,
				destCont = t[11], destX = t[12], destY = t[13],
			})
		end
	end
	-- Docks recorded with /qlmap dock (routes the vanilla data cannot know).
	for label, l in pairs(LearnedStore("transports")) do
		if l.mapID == mapID then
			map:AcquirePin(PIN_TEMPLATE, "transport", {
				kind = l.kind or 1, faction = l.faction or 0, label = label, dock = l.dock or mapName, x = l.x, y = l.y,
				destMapID = l.destMapID, learned = true,
			})
		end
	end
end

-- Player's map and position, for recording pins by hand.
local function PlayerMapPoint()
	local okM, mapID = pcall(C_Map.GetBestMapForUnit, "player")
	mapID = okM and Plain(mapID) or nil
	if not mapID then
		return nil
	end
	local okP, pos = pcall(C_Map.GetPlayerMapPosition, mapID, "player")
	local x, y
	if okP then
		x, y = VectorXY(pos)
	end
	if not (x and y) then
		return nil
	end
	local subzone = Plain(GetSubZoneText and GetSubZoneText()) or ""
	return mapID, x, y, subzone ~= "" and subzone or (ZoneNameForMap(mapID) or "here")
end

-- The last outdoor position seen before a loading screen: when the next map
-- is a dungeon or raid the data has no entrance for, that is where it is.
local lastOutside = nil

local function RememberOutside()
	local okI, inInstance = pcall(IsInInstance)
	if not okI or inInstance then
		return
	end
	local okM, mapID = pcall(C_Map.GetBestMapForUnit, "player")
	mapID = okM and Plain(mapID) or nil
	if not mapID then
		return
	end
	local okP, pos = pcall(C_Map.GetPlayerMapPosition, mapID, "player")
	local x, y
	if okP then
		x, y = VectorXY(pos)   -- pos.x is a secret value on this client; VectorXY falls back to GetXY
	end
	if x and y and x > 0 and y > 0 then
		lastOutside = { mapID = mapID, x = x, y = y, at = GetTime() }
	end
end

-- Zone events alone are too sparse (a fight in one subzone can last minutes),
-- so the outdoor position is also refreshed on a slow ticker.
local outsideTicker = nil
local function StartOutsideTicker()
	if outsideTicker or not C_Timer.NewTicker then
		return
	end
	outsideTicker = C_Timer.NewTicker(3, RememberOutside)
end

local learnFailed = nil   -- instance name already reported this session
local pendingExit = nil   -- { name, raid }: instance to learn from where the player exits it

-- Returns true when done (learned, already known, or not applicable); false
-- when the instance is not readable yet and a retry is worth it.
local function LearnEntrance()
	local okI, inInstance, kind = pcall(IsInInstance)
	if not okI or not inInstance or (kind ~= "party" and kind ~= "raid") then
		return true
	end
	local okN, name = pcall(GetInstanceInfo)
	name = okN and Plain(name) or nil
	if not name or name == "" then
		return false
	end
	for _, e in ipairs(Data().entrances or {}) do
		if e[2]:lower() == name:lower() then
			return true
		end
	end
	local learned = LearnedStore("entrances")
	if learned[name] then
		return true
	end
	if not lastOutside or GetTime() - lastOutside.at > 180 then
		-- No position from before the loading screen (reloaded inside, for
		-- instance). Leaving the instance puts the player at its door, so the
		-- entrance is learned on the way out instead.
		pendingExit = { name = name, raid = kind == "raid" }
		if learnFailed ~= name then
			learnFailed = name
			MelloUI:Print("Quest List: the entrance of %s will be put on the map when you walk out of it.", name)
		end
		return true
	end
	learned[name] = { mapID = lastOutside.mapID, x = lastOutside.x, y = lastOutside.y, raid = kind == "raid" }
	MelloUI:Print("Quest List: learned where the entrance of %s is; it is on the zone map now.", name)
	RefreshPins()
	return true
end

-- After leaving an instance whose entrance is unknown, the first readable
-- outdoor position is the door. Polls for a few seconds because the position
-- is not readable right after the loading screen.
local function LearnEntranceOnExit(attempt)
	local pending = pendingExit
	if not pending then
		return
	end
	local okI, inInstance = pcall(IsInInstance)
	if not okI or inInstance then
		return
	end
	local mapID, x, y = PlayerMapPoint()
	if not mapID then
		if (attempt or 1) < 10 then
			C_Timer.After(1, function() LearnEntranceOnExit((attempt or 1) + 1) end)
		end
		return
	end
	pendingExit = nil
	local learned = LearnedStore("entrances")
	if learned[pending.name] then
		return
	end
	learned[pending.name] = { mapID = mapID, x = x, y = y, raid = pending.raid }
	MelloUI:Print("Quest List: learned where the entrance of %s is; it is on the zone map now.", pending.name)
	RefreshPins()
end

local lastPinErrors, lastPinInfo = {}, nil

-- Blizzard's flight point pins: a click also routes to the flight master.
-- Each pin is hooked once, a frame after the map refreshed (its provider has
-- made the pins for the map by then).
local function FlightPinClicked(pin, button)
	if button ~= "LeftButton" or IsShiftKeyDown() or not M.isEnabled then
		return
	end
	local map = pin.GetMap and pin:GetMap()
	local mapID = map and Plain(map:GetMapID())
	local okP, x, y = pcall(pin.GetPosition, pin)
	x, y = okP and Plain(x) or nil, okP and Plain(y) or nil
	local info = pin.poiInfo
	local name = info and Plain(info.name) or "Flight master"
	if mapID and x and y then
		local icon = "|T" .. "Interface/Minimap/Tracking/FlightMaster" .. ":16:16|t "
		RouteToPoint(mapID, x, y, icon .. name, string.format("%sTracking the flight master at %s, {dist} away", icon, name))
	end
end

local function HookFlightPins(map)
	if map and map.EnumeratePinsByTemplate then
		-- EnumeratePinsByTemplate hands back a generic-for triple (next, set, nil)
		local ok, f, state, init = pcall(map.EnumeratePinsByTemplate, map, "FlightPointPinTemplate")
		if ok and type(f) == "function" then
			for pin in f, state, init do
				if not pin.melloFlightHooked and pin.OnMouseClickAction then
					pin.melloFlightHooked = true
					hooksecurefunc(pin, "OnMouseClickAction", FlightPinClicked)
				end
			end
		end
	end
end

local function CreateProvider()
	if Provider or not (MapCanvasDataProviderMixin and WorldMapFrame and WorldMapFrame.AddDataProvider) then
		return
	end
	if not PreparePinMixin() then
		return
	end
	Provider = CreateFromMixins(MapCanvasDataProviderMixin)
	function Provider:RemoveAllData()
		self:GetMap():RemoveAllPinsByTemplate(PIN_TEMPLATE)
	end
	function Provider:RefreshAllData()
		self:RemoveAllData()
		if not (M.isEnabled and byZone) then
			return
		end
		local map = self:GetMap()
		C_Timer.After(0, function() HookFlightPins(map) end)
		local mapID = Plain(map:GetMapID())
		local okI, info = pcall(C_Map.GetMapInfo, mapID)
		if not mapID or not okI or type(info) ~= "table" then
			return
		end
		local mapType, name = Plain(info.mapType), Plain(info.name)
		wipe(lastPointTrace)
		lastPinErrors = {}
		lastPinInfo = { mapID = mapID, name = name, mapType = mapType }
		local function Try(label, fn, ...)
			local ok, err = pcall(fn, ...)
			if not ok then
				lastPinErrors[#lastPinErrors + 1] = label .. ": " .. tostring(err)
			end
		end
		if mapType == MAP_ZONE and name then
			if M.db.mapPins then
				Try("quest givers", AddGiverPins, map, mapID, name)
			end
			if M.db.entrancePins then
				Try("entrances", AddEntrancePins, map, mapID, name)
			end
			if M.db.transportPins then
				Try("transports", AddTransportPins, map, mapID, name)
			end
		elseif mapType == MAP_CONTINENT and M.db.zoneBadges then
			Try("zone badges", AddZoneBadges, map, mapID)
		end
	end
	WorldMapFrame:AddDataProvider(Provider)
end

RefreshPins = function()
	if Provider and WorldMapFrame and WorldMapFrame:IsShown() then
		Provider:RefreshAllData()
	end
end

--------------------------------------------------------------------------------
-- Dungeon check on entering an instance
--------------------------------------------------------------------------------

local lastInstance = nil

local function DungeonSummary()
	if not (M.isEnabled and M.db.dungeonSummary and byZone) then
		return
	end
	local okI, inInstance, kind = pcall(IsInInstance)
	if not okI or not inInstance or (kind ~= "party" and kind ~= "raid") then
		lastInstance = nil
		return
	end
	local okN, name = pcall(GetInstanceInfo)
	name = okN and Plain(name) or nil
	if not name or name == lastInstance then
		return
	end
	lastInstance = name
	local data = Data()
	local dungeonID
	for id, dname in pairs(data.dungeons or {}) do
		if dname:lower() == name:lower() then
			dungeonID = id
		end
	end
	if not dungeonID then
		return
	end
	local missing, inLog, done, total = {}, 0, 0, 0
	for _, row in ipairs(data.quests or {}) do
		if row[F_DUNGEON] == dungeonID and Eligible(row) then
			total = total + 1
			if IsCompleted(row[F_ID]) then
				done = done + 1
			elseif IsOnQuest(row[F_ID]) then
				inLog = inLog + 1
			else
				missing[#missing + 1] = row
			end
		end
	end
	if total == 0 then
		return
	end
	MelloUI:Print("%s: %d of %d quests done, %d in your log, %d not picked up.", name, done, total, inLog, #missing)
	for _, row in ipairs(data.quests or {}) do
		if row[F_DUNGEON] == dungeonID and Eligible(row) and IsOnQuest(row[F_ID]) and IsReadyForTurnIn(row[F_ID]) and (row[F_ENDER] or "") ~= "" then
			local endZone = EnderZoneName(row) or Data().zones[ZoneOf(row)]
			print(string.format("   |cffffd200%s|r is ready: turn in to %s%s", row[F_TITLE], row[F_ENDER], endZone and (" in " .. endZone) or ""))
		end
	end
	table.sort(missing, ByLevel)
	for i, row in ipairs(missing) do
		if i > 12 then
			print(string.format("   ... and %d more; see the Dungeons tab of the quest list.", #missing - 12))
			break
		end
		local r, g, b = DifficultyColor(row[F_LEVEL])
		local zone = data.zones[row[F_GIVERZONE]] or data.zones[row[F_ZONE]]
		local from = row[F_GIVER] ~= "" and row[F_GIVER] or "giver unknown"
		print(string.format("   |cff%02x%02x%02x%s|r (%d)  -  %s%s", r * 255, g * 255, b * 255, row[F_TITLE], row[F_LEVEL],
			from, zone and (", " .. zone) or ""))
	end
end

--------------------------------------------------------------------------------
-- Module lifecycle
--------------------------------------------------------------------------------

local eventFrame = CreateFrame("Frame")
eventFrame:SetScript("OnEvent", function(_, event, ...)
	if event == "PLAYER_ENTERING_WORLD" then
		-- Instance info and quest flags settle a moment after the load.
		C_Timer.After(2, function()
			if not LearnEntrance() then
				C_Timer.After(6, LearnEntrance)
			end
			DungeonSummary()
		end)
		if pendingExit then
			C_Timer.After(1, LearnEntranceOnExit)
		end
	elseif event == "UNIT_SPELLCAST_SUCCEEDED" then
		-- Hearthstone or Astral Recall out of the instance: the arrival point
		-- is not the door.
		local _, _, spellID = ...
		spellID = Plain(spellID)
		if spellID == 8690 or spellID == 556 then
			pendingExit = nil
		end
	elseif event == "PLAYER_LEAVING_WORLD" or event == "ZONE_CHANGED" or event == "ZONE_CHANGED_INDOORS" or event == "ZONE_CHANGED_NEW_AREA" then
		RememberOutside()
	end
	if WorldMapFrame and WorldMapFrame:IsShown() then
		Panel:Schedule()
	end
end)

local hooked = false

function M:OnInit(db)
	self.db = db
end

function M:OnEnable(db)
	self.db = db
	if type(MelloUI_QuestListData) ~= "table" then
		MelloUI:Print("Quest List: Media\\QuestListData.lua is missing; run Tools\\build_quest_list.py.")
		return
	end
	if not WorldMapFrame then
		return
	end
	if not byZone then
		BuildIndex()
	end
	Panel:Create()
	Panel:Apply()
	CreateProvider()
	RefreshPins()
	ResolveInChunks(function()
		BuildIndex()
		if Panel.frame and Panel.frame:IsShown() then
			Panel:Update()
		end
		RefreshPins()
	end)
	if not hooked then
		hooked = true
		if WorldMapFrame.OnMapChanged then
			hooksecurefunc(WorldMapFrame, "OnMapChanged", function() Panel:Update() end)
		end
		eventFrame:RegisterEvent("QUEST_LOG_UPDATE")
		eventFrame:RegisterEvent("ZONE_CHANGED_NEW_AREA")
		eventFrame:RegisterEvent("PLAYER_LEVEL_UP")
		eventFrame:RegisterEvent("PLAYER_ENTERING_WORLD")
		eventFrame:RegisterEvent("PLAYER_LEAVING_WORLD")
		eventFrame:RegisterEvent("ZONE_CHANGED")
		eventFrame:RegisterEvent("ZONE_CHANGED_INDOORS")
		if eventFrame.RegisterUnitEvent then
			eventFrame:RegisterUnitEvent("UNIT_SPELLCAST_SUCCEEDED", "player")
		else
			eventFrame:RegisterEvent("UNIT_SPELLCAST_SUCCEEDED")
		end
	end
	StartOutsideTicker()
end

function M:OnDisable()
	if Panel.frame then
		Panel.frame:Hide()
	end
	if Provider and WorldMapFrame then
		Provider:RemoveAllData()
	end
end

function M:OnSettingChanged(key, value, db)
	self.db = db
	Panel:Apply()
	RefreshPins()
end

-- /qlmap: why pins are (not) on the map shown.
SLASH_MELLOQUESTMAP1 = "/qlmap"
SlashCmdList.MELLOQUESTMAP = function(msg)
	local data = Data()
	msg = (msg or ""):gsub("^%s+", ""):gsub("%s+$", "")
	local cmd, rest = msg:match("^(%S+)%s*(.-)$")
	cmd = cmd and cmd:lower()
	if cmd == "dock" or cmd == "zeppelin" then
		-- /qlmap dock Boat to Auberdine [| Alliance|Horde]   (stand on the dock)
		if rest == "" then
			MelloUI:Print("Stand on the dock and type:  /qlmap dock Boat to Auberdine   (add  | horde  or  | alliance  for a faction-only route; default neutral).")
			return
		end
		local label, side = rest:match("^(.-)%s*|%s*(%a+)$")
		label = label or rest
		local faction = 0
		if side and side:lower() == "alliance" then faction = 1 elseif side and side:lower() == "horde" then faction = 2 end
		local mapID, x, y, dock = PlayerMapPoint()
		if not mapID then
			MelloUI:Print("Cannot read your position here.")
			return
		end
		LearnedStore("transports")[label] = { mapID = mapID, x = x, y = y, dock = dock, kind = cmd == "zeppelin" and 2 or 1, faction = faction }
		MelloUI:Print("Recorded '%s' at %s (%.1f, %.1f). Sail there and type  /qlmap arrive %s  to link the destination map.", label, dock, x * 100, y * 100, label)
		RefreshPins()
	elseif cmd == "arrive" then
		local l = rest ~= "" and LearnedStore("transports")[rest]
		if not l then
			MelloUI:Print("No recorded dock called '%s'.", rest)
			return
		end
		local mapID = PlayerMapPoint()
		if mapID then
			l.destMapID = mapID
			MelloUI:Print("'%s' now opens %s when clicked.", rest, ZoneNameForMap(mapID) or tostring(mapID))
		end
	elseif cmd == "entrance" then
		-- /qlmap entrance Hall of Thanes [| raid]   (stand at the entrance)
		if rest == "" then
			MelloUI:Print("Stand at the entrance and type:  /qlmap entrance Hall of Thanes   (add  | raid  for a raid).")
			return
		end
		local name, kind = rest:match("^(.-)%s*|%s*(%a+)$")
		name = name or rest
		local mapID, x, y = PlayerMapPoint()
		if not mapID then
			MelloUI:Print("Cannot read your position here.")
			return
		end
		LearnedStore("entrances")[name] = { mapID = mapID, x = x, y = y, raid = kind ~= nil and kind:lower() == "raid" }
		MelloUI:Print("Recorded the entrance of %s at %.1f, %.1f.", name, x * 100, y * 100)
		RefreshPins()
	elseif cmd == "remove" then
		local removed = false
		if LearnedStore("transports")[rest] then
			LearnedStore("transports")[rest] = nil
			removed = true
		end
		if LearnedStore("entrances")[rest] then
			LearnedStore("entrances")[rest] = nil
			removed = true
		end
		MelloUI:Print(removed and ("Removed '" .. rest .. "'.") or ("Nothing recorded as '" .. rest .. "'."))
		RefreshPins()
	elseif cmd == "list" then
		MelloUI:Print("Recorded pins:")
		for name, l in pairs(LearnedStore("entrances")) do
			print(string.format("   entrance  %s  (%s %.1f, %.1f)", name, ZoneNameForMap(l.mapID) or "?", l.x * 100, l.y * 100))
		end
		for label, l in pairs(LearnedStore("transports")) do
			print(string.format("   dock  %s  (%s %.1f, %.1f)%s", label, ZoneNameForMap(l.mapID) or "?", l.x * 100, l.y * 100,
				l.destMapID and ("  ->  " .. (ZoneNameForMap(l.destMapID) or "?")) or ""))
		end
		return
	elseif cmd and cmd ~= "" then
		MelloUI:Print("/qlmap  (diagnostics)  |  /qlmap dock <label> [| alliance|horde]  |  /qlmap zeppelin <label>  |  /qlmap arrive <label>  |  /qlmap entrance <name> [| raid]  |  /qlmap remove <name>  |  /qlmap list")
		return
	end
	if cmd then
		return
	end
	MelloUI:Print("Quest List map pins")
	print("   provider: " .. tostring(Provider ~= nil) .. "   pin mixin ready: " .. tostring(PinMixin.SetPosition ~= nil)
		.. "   GetMapPosFromWorldPos: " .. tostring(C_Map.GetMapPosFromWorldPos ~= nil) .. "   CreateVector2D: " .. tostring(CreateVector2D ~= nil))
	print(string.format("   data: %d entrances, %d transports, %d learned", #(data.entrances or {}), #(data.transports or {}),
		(function() local n = 0 for _ in pairs(LearnedStore("entrances")) do n = n + 1 end return n end)()))
	print(string.format("   options: pins %s, entrances %s, transports %s, badges %s",
		tostring(M.db.mapPins), tostring(M.db.entrancePins), tostring(M.db.transportPins), tostring(M.db.zoneBadges)))
	if lastPinInfo then
		print(string.format("   last refresh: map %s (%s), type %s", tostring(lastPinInfo.mapID), tostring(lastPinInfo.name), tostring(lastPinInfo.mapType)))
		local client = ClientEntrances(lastPinInfo.mapID)
		print(string.format("   client entrance list for this map: %s, %d entries", tostring(C_EncounterJournal and C_EncounterJournal.GetDungeonEntrancesForMap ~= nil), #client))
		for i, e in ipairs(client) do
			if i > 8 then break end
			print(string.format("      %s at %.1f, %.1f", e.name, e.x * 100, e.y * 100))
		end
		local pois = ClientPOIs(lastPinInfo.mapID)
		print(string.format("   points of interest the map shows: %d", #pois))
		for i, poi in ipairs(pois) do
			if i > 12 then
				print("      ... " .. (#pois - 12) .. " more")
				break
			end
			print(string.format("      %s%s at %.1f, %.1f  [%s]", poi.name, IsEntrancePOI(poi) and " (instance)" or "", poi.x * 100, poi.y * 100, poi.atlas))
		end
	else
		print("   no refresh yet (open the map).")
	end
	local pools = WorldMapFrame and WorldMapFrame.pinPools and WorldMapFrame.pinPools[PIN_TEMPLATE]
	if pools then
		local n, kinds = 0, {}
		for pin in pools:EnumerateActive() do
			n = n + 1
			kinds[pin.kind or "?"] = (kinds[pin.kind or "?"] or 0) + 1
		end
		local parts = {}
		for k, v in pairs(kinds) do parts[#parts + 1] = k .. " " .. v end
		print("   pins on the map: " .. n .. (n > 0 and (" (" .. table.concat(parts, ", ") .. ")") or ""))
	end
	for _, err in ipairs(lastPinErrors) do
		print("   |cffff4040error|r " .. err)
	end
	for i, line in ipairs(lastPointTrace) do
		if i > 8 then
			print("   ... " .. (#lastPointTrace - 8) .. " more")
			break
		end
		print("   " .. line)
	end
	-- Probe the API with the first entrance.
	local e = data.entrances and data.entrances[1]
	if e and C_Map.GetMapPosFromWorldPos and CreateVector2D then
		local ok, uiMapID, pos = pcall(C_Map.GetMapPosFromWorldPos, e[3], CreateVector2D(e[4], e[5]))
		local x, y = VectorXY(pos)
		print(string.format("   probe %s at (%d, %.0f, %.0f): ok %s, map %s, pos %s (%s, %s)", e[2], e[3], e[4], e[5],
			tostring(ok), tostring(uiMapID), type(pos), tostring(x), tostring(y)))
	end
end

MelloUI:Profile("QuestList", "quest log events", eventFrame)
MelloUI:Profile("QuestList", "panel rebuild", Panel.Update)
MelloUI:Profile("QuestList", "map pins", RefreshPins)
