--------------------------------------------------------------------------------
-- MelloUI - Quest List
--
-- A panel attached to the right of the world map listing the quests that can
-- be picked up in a zone: how many of them you have done, and for each quest
-- its level, the quest giver and where to find it. Quests are grouped under
-- collapsible headers in the style of the quest log: one per quest chain,
-- then the single quests. Titles are coloured by difficulty like the quest
-- log, completed quests are greyed with a tick, and clicking a quest drops a
-- map pin on the giver.
--
-- The module is in three files: this one (data, placement, dungeon summary,
-- lifecycle, /qlmap), QuestListPanel.lua (the panel) and QuestListMap.lua
-- (map pins, entrances, transports and how entrances are learned).
--
-- Data: Media\QuestListData.lua, generated by Tools\build_quest_list.py from
-- Wowhead's Forever database, the vanilla server database and the map tables.
-- Quest givers that no database places (new Forever NPCs) get their position
-- from the Voice Over collector the first time you talk to them.
--------------------------------------------------------------------------------

local _, ns = ...
local MelloUI = ns.MelloUI

local M = MelloUI:RegisterModule("QuestList", {
	title = "Quest List",
	desc = "Panel next to the world map listing the quests of a zone, how many you have completed, and where each one is picked up.",
	enabledByDefault = true,
	defaults = {
		filter = "zone",
		hideCompleted = false,
		otherFaction = false,
		otherClass = false,
		levelAbove = 0,
		width = 380,
		mapPins = true,
		pinCompleted = false,
		zoneBadges = true,
		entrancePins = true,
		transportPins = true,
		dungeonSummary = true,
	},
	options = {
		{ type = "header", name = "List" },
		{ type = "dropdown", key = "filter", name = "Show Quests For", values = {
			{ value = "all", label = "All" },
			{ value = "continent", label = "Current continent" },
			{ value = "zone", label = "Current zone" },
			{ value = "class", label = "Class quests" },
			{ value = "dungeons", label = "Dungeons" },
			{ value = "raids", label = "Raids" },
			{ value = "attunements", label = "Attunements" },
			{ value = "events", label = "Events" },
		  },
		  desc = "Which quests the panel lists. The buttons on the panel switch this as well." },
		{ type = "toggle", key = "hideCompleted", name = "Hide Completed",
		  desc = "Leave out quests you have already completed instead of greying them." },
		{ type = "toggle", key = "otherFaction", name = "Show Other Faction's Quests",
		  desc = "Also list quests only the other faction can take." },
		{ type = "toggle", key = "otherClass", name = "Show Other Classes' Quests",
		  desc = "Also list quests restricted to classes other than yours." },
		{ type = "slider", key = "levelAbove", name = "Hide Quests More Than N Levels Above Me", min = 0, max = 30, step = 1,
		  format = function(v) return v == 0 and "no limit" or ("+" .. v) end,
		  desc = "Leave out quests whose level is more than this many levels above your character. 0 shows everything." },
		{ type = "slider", key = "width", name = "Panel Width", min = 260, max = 520, step = 10,
		  desc = "Width of the panel next to the map." },
		{ type = "header", name = "Map" },
		{ type = "toggle", key = "mapPins", name = "Quest Givers On Zone Maps",
		  desc = "Mark every known quest giver on the zone map with a ! or ? coloured by what you can do there. Hover for the quests, click to track the giver." },
		{ type = "toggle", key = "pinCompleted", name = "Include Givers You Are Done With",
		  desc = "Also mark givers whose quests you have all completed, with a grey tick." },
		{ type = "toggle", key = "zoneBadges", name = "Zone Progress On Continent Maps",
		  desc = "Show a done/total badge on each zone of the continent map. Hover for the level range, click to open the zone." },
		{ type = "toggle", key = "entrancePins", name = "Dungeon And Raid Entrances",
		  desc = "Mark instance entrances on the zone maps. Hover for the level range and your quest progress, click to list its quests. Entrances of new instances are learned the first time you walk in." },
		{ type = "toggle", key = "transportPins", name = "Boats And Zeppelins",
		  desc = "Mark the docks and zeppelin towers on the zone maps with the destination. Click to open the destination's map." },
		{ type = "header", name = "Dungeons" },
		{ type = "toggle", key = "dungeonSummary", name = "Quest Check When Entering An Instance",
		  desc = "When you enter a dungeon or raid, list in chat the quests for it you could have picked up but have not." },
	},
})

-- Shared with QuestListPanel.lua and QuestListMap.lua: state and helpers the
-- three files use together. Everything else stays local to its file.
local QL = { M = M }
ns.QuestList = QL

--------------------------------------------------------------------------------
-- Data
--------------------------------------------------------------------------------

local function IsSecret(v)
	return issecretvalue and issecretvalue(v)
end

function QL.Plain(v)
	if IsSecret(v) or v == nil then
		return nil
	end
	return v
end

-- Row fields in MelloUI_QuestListData.quests
QL.F_ID, QL.F_TITLE, QL.F_LEVEL, QL.F_REQ, QL.F_SIDE, QL.F_CLASS, QL.F_ZONE, QL.F_GIVERZONE, QL.F_GIVER, QL.F_X, QL.F_Y, QL.F_KIND, QL.F_EVENT, QL.F_CHAIN, QL.F_DUNGEON, QL.F_ATTUNE, QL.F_PREV, QL.F_CONT, QL.F_WX, QL.F_WY =
	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
-- giver NPC id; turn-in: name, NPC id, zone (build-time guess), continent, world x, world y
QL.F_NPC, QL.F_ENDER, QL.F_ENDERNPC, QL.F_ENDERZONE, QL.F_ENDERCONT, QL.F_ENDERWX, QL.F_ENDERWY = 21, 22, 23, 24, 25, 26, 27

QL.byZone = nil        -- [areaID] = { rows }   (pick-up zone, falling back to quest zone)
QL.allRows = nil       -- every zone row, sorted by level once
QL.searchText = nil    -- [row] = lower-cased "title giver zone" for the search box
local rowByID = nil       -- [questID] = row
QL.byDungeon = nil     -- [dungeonID] = { rows }
QL.chainStep = nil     -- [row] = position in its chain (1 = first)
local chainTotal = nil    -- [chainID] = number of steps
local nextInChain = nil   -- [questID] = the row that follows it
QL.eventRows = nil     -- holiday / world event quests, kept out of the zone lists
QL.zoneByName = nil    -- [lower name] = areaID
local classBit = nil      -- player's class bit in the data's mask
local playerSide = nil    -- 1 Alliance, 2 Horde
QL.collapsed = {}      -- [group key] = true while a header is collapsed (per session)
QL.trackedQuestID = nil -- quest whose giver the map pin currently points at
QL.RefreshPins = nil   -- redraws the map pins; defined in the map pins section

-- Pins recorded by hand (entrances, docks) live with the Route module's
-- learned paths, which the baker keeps across sessions, not in the settings
-- (those are mirrored into account macros and must stay small).
function QL.LearnedStore(kind)
	local R = MelloUI.Route
	local store = R and R.Pins and R:Pins()
	if store then
		-- Older versions kept them in the settings: move them over once.
		local old = M.db and (kind == "entrances" and M.db.learnedEntrances or kind == "transports" and M.db.learnedTransports)
		if type(old) == "table" then
			for name, v in pairs(old) do
				if store[kind][name] == nil then
					store[kind][name] = v
				end
			end
			if kind == "entrances" then M.db.learnedEntrances = nil else M.db.learnedTransports = nil end
		end
		return store[kind]
	end
	local key = kind == "entrances" and "learnedEntrances" or "learnedTransports"
	M.db[key] = M.db[key] or {}
	return M.db[key]
end
QL.resolved = nil      -- [row] = { mapID, x, y, cx, cy, contMapID }: the client's placement of a giver's world position
local zoneOverride = nil  -- [row] = areaID when the client puts the giver in another zone than the build did
QL.rowsByMap = nil     -- [uiMapID] = rows the client placed on that map
QL.resolvedEnd = nil   -- [row] = placement of the turn-in NPC when it is not the giver
QL.endRowsByMap = nil  -- [uiMapID] = rows whose turn-in the client placed on that map

function QL.Data()
	return MelloUI_QuestListData
end

function QL.ZoneOf(row)
	local override = zoneOverride and zoneOverride[row]
	if override then
		return override
	end
	return row[QL.F_GIVERZONE] ~= 0 and row[QL.F_GIVERZONE] or row[QL.F_ZONE]
end

--------------------------------------------------------------------------------
-- World positions
--
-- Vanilla data gives world coordinates. The client turns them into a
-- continent-map position; the continent map's hit test says which zone (and
-- city) is there, and the zone's rectangle on the continent gives the position
-- on the zone map. Build-time zone guesses are wrong at zone edges and on maps
-- Forever changed (Stormwind with its harbour), so this is done here.
--------------------------------------------------------------------------------

function QL.VectorXY(pos)
	if type(pos) ~= "table" then
		return nil, nil
	end
	local x, y = QL.Plain(pos.x), QL.Plain(pos.y)
	if (x == nil or y == nil) and type(pos.GetXY) == "function" then
		local ok, gx, gy = pcall(pos.GetXY, pos)
		if ok then
			x, y = QL.Plain(gx), QL.Plain(gy)
		end
	end
	return x, y
end

-- Is `mapID` the map `uiMapID` or one of its parents (city inside a zone)?
local function IsOnOrUnder(uiMapID, mapID)
	local id = uiMapID
	for _ = 1, 4 do
		if id == mapID then
			return true
		end
		local ok, info = pcall(C_Map.GetMapInfo, id)
		id = ok and type(info) == "table" and QL.Plain(info.parentMapID) or nil
		if not id or id == 0 then
			return false
		end
	end
	return false
end

local rectCache = {}

-- Rectangle of a map on its continent map, cached.
local function RectOn(mapID, contMapID)
	local key = mapID .. ":" .. contMapID
	local r = rectCache[key]
	if r == nil then
		local ok, minX, maxX, minY, maxY = pcall(C_Map.GetMapRectOnMap, mapID, contMapID)
		minX, maxX, minY, maxY = QL.Plain(minX), QL.Plain(maxX), QL.Plain(minY), QL.Plain(maxY)
		r = (ok and minX and maxX and minY and maxY and maxX > minX and maxY > minY) and { minX, maxX, minY, maxY } or false
		rectCache[key] = r
	end
	return r or nil
end

local function InRect(r, cx, cy)
	local x, y = (cx - r[1]) / (r[2] - r[1]), (cy - r[3]) / (r[4] - r[3])
	if x >= 0 and x <= 1 and y >= 0 and y <= 1 then
		return x, y
	end
	return nil
end

-- A world point as { mapID, x, y, cx, cy, contMapID }: the deepest map that
-- holds it (city before zone) and its position there, or nil.
function QL.ResolveWorld(cont, wx, wy)
	if not (C_Map.GetMapPosFromWorldPos and CreateVector2D and C_Map.GetMapInfoAtPosition and C_Map.GetMapRectOnMap) then
		return nil
	end
	local ok, contMapID, pos = pcall(C_Map.GetMapPosFromWorldPos, cont, CreateVector2D(wx, wy))
	contMapID = ok and QL.Plain(contMapID) or nil
	local cx, cy = QL.VectorXY(pos)
	if not (contMapID and cx and cy) then
		return nil
	end
	local okZ, zinfo = pcall(C_Map.GetMapInfoAtPosition, contMapID, cx, cy)
	local zone = okZ and type(zinfo) == "table" and QL.Plain(zinfo.mapID) or nil
	if not zone or zone == contMapID then
		return nil
	end
	local r = RectOn(zone, contMapID)
	local x, y
	if r then
		x, y = InRect(r, cx, cy)
	end
	if not x then
		return nil
	end
	-- One level deeper: a city inside the zone.
	local okC, cinfo = pcall(C_Map.GetMapInfoAtPosition, zone, x, y)
	local child = okC and type(cinfo) == "table" and QL.Plain(cinfo.mapID) or nil
	if child and child ~= zone then
		local r2 = RectOn(child, contMapID)
		local x2, y2
		if r2 then
			x2, y2 = InRect(r2, cx, cy)
		end
		if x2 then
			zone, x, y = child, x2, y2
		end
	end
	return { mapID = zone, x = x, y = y, cx = cx, cy = cy, contMapID = contMapID }
end

-- Position of a resolved point on the map shown (its own map, a parent, or a
-- child), or nil when the point is elsewhere.
function QL.ProjectOnMap(res, mapID)
	if res.mapID == mapID then
		return res.x, res.y
	end
	if not (IsOnOrUnder(res.mapID, mapID) or IsOnOrUnder(mapID, res.mapID)) then
		return nil
	end
	local r = RectOn(mapID, res.contMapID)
	if not r then
		return nil
	end
	return InRect(r, res.cx, res.cy)
end

-- Where a quest giver is: uiMapID, x, y (0..1) from the client's placement,
-- else the build-time zone and map percentage.
function QL.GiverPoint(row)
	local res = QL.resolved and QL.resolved[row]
	if res then
		return res.mapID, res.x, res.y
	end
	if row[QL.F_X] ~= 0 or row[QL.F_Y] ~= 0 then
		return nil, row[QL.F_X] / 100, row[QL.F_Y] / 100
	end
	return nil
end

-- Is the quest handed back to the NPC that gave it?
function QL.SameEnder(row)
	local ender, giver = row[QL.F_ENDER] or "", row[QL.F_GIVER] or ""
	if ender == "" then
		return true
	end
	local enpc, gnpc = row[QL.F_ENDERNPC] or 0, row[QL.F_NPC] or 0
	if enpc ~= 0 and gnpc ~= 0 then
		return enpc == gnpc
	end
	return ender == giver
end

-- Where a quest is handed in: uiMapID, x, y from the client's placement, or nil.
function QL.EndPoint(row)
	local res = QL.resolvedEnd and QL.resolvedEnd[row]
	if res then
		return res.mapID, res.x, res.y
	end
	return nil
end

-- Zone name of the turn-in, from its placement or the build-time guess.
function QL.EnderZoneName(row)
	local res = QL.resolvedEnd and QL.resolvedEnd[row]
	if res then
		local ok, info = pcall(C_Map.GetMapInfo, res.mapID)
		local name = ok and type(info) == "table" and QL.Plain(info.name) or nil
		if name then
			return name
		end
	end
	return (row[QL.F_ENDERZONE] or 0) ~= 0 and QL.Data().zones[row[QL.F_ENDERZONE]] or nil
end

function QL.ByLevel(a, b)
	if a[QL.F_LEVEL] ~= b[QL.F_LEVEL] then return a[QL.F_LEVEL] < b[QL.F_LEVEL] end
	return a[QL.F_TITLE] < b[QL.F_TITLE]
end

local function BuildIndex()
	QL.byZone, QL.zoneByName, QL.eventRows, QL.allRows, QL.searchText = {}, {}, {}, {}, {}
	local data = QL.Data()
	if type(data) ~= "table" then
		return
	end
	local zones = data.zones or {}
	for areaID, name in pairs(zones) do
		QL.zoneByName[name:lower()] = areaID
	end
	-- The client's placements (filled in over a few frames after enable by
	-- ResolveInChunks; the index is rebuilt when they are complete). The zone
	-- a giver lands in wins over the build-time guess.
	zoneOverride, QL.rowsByMap, QL.endRowsByMap = {}, {}, {}
	QL.resolved = QL.resolved or {}
	QL.resolvedEnd = QL.resolvedEnd or {}
	local mapArea = {}
	for _, row in ipairs(data.quests or {}) do
		local res = QL.resolved[row]
		if res then
			QL.rowsByMap[res.mapID] = QL.rowsByMap[res.mapID] or {}
			table.insert(QL.rowsByMap[res.mapID], row)
			local areaID = mapArea[res.mapID]
			if areaID == nil then
				local okI, info = pcall(C_Map.GetMapInfo, res.mapID)
				local name = okI and type(info) == "table" and QL.Plain(info.name) or nil
				areaID = name and QL.zoneByName[name:lower()] or false
				mapArea[res.mapID] = areaID
			end
			if areaID and areaID ~= QL.ZoneOf(row) then
				zoneOverride[row] = areaID
			end
		end
		local ender = QL.resolvedEnd[row]
		if ender then
			QL.endRowsByMap[ender.mapID] = QL.endRowsByMap[ender.mapID] or {}
			table.insert(QL.endRowsByMap[ender.mapID], row)
		end
	end
	for _, row in ipairs(data.quests or {}) do
		local zone = QL.ZoneOf(row)
		QL.searchText[row] = (row[QL.F_TITLE] .. " " .. row[QL.F_GIVER] .. " " .. (zones[zone] or "")):lower()
		if (row[QL.F_EVENT] or 0) ~= 0 then
			table.insert(QL.eventRows, row)
		elseif zone ~= 0 then
			QL.byZone[zone] = QL.byZone[zone] or {}
			table.insert(QL.byZone[zone], row)
			QL.allRows[#QL.allRows + 1] = row
		end
	end
	table.sort(QL.eventRows, QL.ByLevel)
	table.sort(QL.allRows, QL.ByLevel)
	for _, rows in pairs(QL.byZone) do
		table.sort(rows, QL.ByLevel)
	end
	-- Chain steps: follow the "previous quest" links back to the chain start.
	rowByID, QL.chainStep, chainTotal, nextInChain, QL.byDungeon = {}, {}, {}, {}, {}
	for _, row in ipairs(data.quests or {}) do
		rowByID[row[QL.F_ID]] = row
		if row[QL.F_DUNGEON] ~= 0 then
			QL.byDungeon[row[QL.F_DUNGEON]] = QL.byDungeon[row[QL.F_DUNGEON]] or {}
			table.insert(QL.byDungeon[row[QL.F_DUNGEON]], row)
		end
	end
	local function StepOf(row, depth)
		local step = QL.chainStep[row]
		if step then
			return step
		end
		local prevRow = (row[QL.F_PREV] or 0) ~= 0 and rowByID[row[QL.F_PREV]] or nil
		if prevRow and prevRow[QL.F_CHAIN] == row[QL.F_CHAIN] and depth < 60 then
			step = StepOf(prevRow, depth + 1) + 1
		else
			step = 1
		end
		QL.chainStep[row] = step
		return step
	end
	for _, row in ipairs(data.quests or {}) do
		if row[QL.F_CHAIN] ~= 0 then
			local step = StepOf(row, 0)
			if step > (chainTotal[row[QL.F_CHAIN]] or 0) then
				chainTotal[row[QL.F_CHAIN]] = step
			end
			local prev = row[QL.F_PREV] or 0
			if prev ~= 0 and rowByID[prev] and not nextInChain[prev] then
				nextInChain[prev] = row
			end
		end
	end
	local _, classFile = UnitClass("player")
	for mask, name in pairs(data.classes or {}) do
		if name == classFile then
			classBit = mask
		end
	end
	playerSide = UnitFactionGroup("player") == "Horde" and 2 or 1
end

-- Ask the client where every vanilla giver and turn-in is, a few hundred rows
-- per frame so login does not stall, then rebuild the index once.
local resolving = false
local resolveDone = false

local function ResolveInChunks(onDone)
	if resolving or resolveDone then
		return
	end
	local data = QL.Data()
	local rows = type(data) == "table" and data.quests or nil
	if not rows or not (C_Map.GetMapPosFromWorldPos and CreateVector2D and C_Map.GetMapInfoAtPosition and C_Map.GetMapRectOnMap) then
		resolveDone = true
		return
	end
	resolving = true
	QL.resolved = QL.resolved or {}
	QL.resolvedEnd = QL.resolvedEnd or {}
	local i, n = 1, #rows
	local function Step()
		local stop = math.min(i + 299, n)
		while i <= stop do
			local row = rows[i]
			if (row[QL.F_CONT] or -1) >= 0 and QL.resolved[row] == nil then
				QL.resolved[row] = QL.ResolveWorld(row[QL.F_CONT], row[QL.F_WX], row[QL.F_WY]) or false
			end
			if (row[QL.F_ENDERCONT] or -1) >= 0 and QL.resolvedEnd[row] == nil
				and not (row[QL.F_ENDERCONT] == row[QL.F_CONT] and row[QL.F_ENDERWX] == row[QL.F_WX] and row[QL.F_ENDERWY] == row[QL.F_WY]) then
				QL.resolvedEnd[row] = QL.ResolveWorld(row[QL.F_ENDERCONT], row[QL.F_ENDERWX], row[QL.F_ENDERWY]) or false
			end
			i = i + 1
		end
		if i <= n then
			C_Timer.After(0, Step)
		else
			resolving = false
			resolveDone = true
			onDone()
		end
	end
	Step()
end

-- step, total steps, next row (or nil) for a quest in a chain.
function QL.ChainInfo(row)
	if row[QL.F_CHAIN] == 0 or not QL.chainStep then
		return nil
	end
	return QL.chainStep[row] or 1, chainTotal[row[QL.F_CHAIN]] or 1, nextInChain[row[QL.F_ID]]
end

function QL.Eligible(row)
	local db = M.db
	if not db.otherFaction and row[QL.F_SIDE] ~= 0 and row[QL.F_SIDE] ~= 3 and row[QL.F_SIDE] ~= playerSide then
		return false
	end
	if not db.otherClass and row[QL.F_CLASS] ~= 0 and classBit and bit.band(row[QL.F_CLASS], classBit) == 0 then
		return false
	end
	local above = tonumber(db.levelAbove) or 0
	if above > 0 then
		local level = QL.Plain(UnitLevel("player")) or 60
		if row[QL.F_LEVEL] > level + above then
			return false
		end
	end
	return true
end

function QL.IsCompleted(questID)
	if C_QuestLog and C_QuestLog.IsQuestFlaggedCompleted then
		local ok, done = pcall(C_QuestLog.IsQuestFlaggedCompleted, questID)
		if ok and not IsSecret(done) then
			return done == true
		end
	end
	return false
end

function QL.IsOnQuest(questID)
	if C_QuestLog and C_QuestLog.IsOnQuest then
		local ok, on = pcall(C_QuestLog.IsOnQuest, questID)
		if ok and not IsSecret(on) then
			return on == true
		end
	end
	return false
end

-- A quest in the log whose objectives are all done.
local readyChecks = nil
function QL.IsReadyForTurnIn(questID)
	if not readyChecks then
		readyChecks = {}
		for _, name in ipairs({ "ReadyForTurnIn", "IsComplete" }) do
			if C_QuestLog and type(C_QuestLog[name]) == "function" then
				readyChecks[#readyChecks + 1] = C_QuestLog[name]
			end
		end
	end
	for _, fn in ipairs(readyChecks) do
		local ok, ready = pcall(fn, questID)
		if ok and not IsSecret(ready) and ready ~= nil then
			return ready == true
		end
	end
	return false
end

-- Quest log colouring: grey trivial, green easy, yellow fair, orange hard, red very hard.
function QL.DifficultyColor(level)
	if level <= 0 then
		return 0.75, 0.61, 0
	end
	if GetQuestDifficultyColor then
		local ok, color = pcall(GetQuestDifficultyColor, level)
		if ok and type(color) == "table" and color.r then
			return color.r, color.g, color.b
		end
	end
	local mine = QL.Plain(UnitLevel("player")) or 60
	local diff = level - mine
	if diff >= 5 then return 1, 0.1, 0.1 end
	if diff >= 3 then return 1, 0.5, 0.25 end
	if diff >= -2 then return 1, 0.82, 0 end
	local trivial = 5
	if mine >= 40 then trivial = 12 elseif mine >= 30 then trivial = 9 elseif mine >= 20 then trivial = 7 elseif mine >= 10 then trivial = 6 end
	if diff > -trivial then return 0.25, 0.75, 0.25 end
	return 0.5, 0.5, 0.5
end

--------------------------------------------------------------------------------
-- Map helpers
--------------------------------------------------------------------------------

local mapIDByName = nil

local function MapIDForZoneName(name)
	if not mapIDByName then
		mapIDByName = {}
		local ok, root = pcall(C_Map.GetFallbackWorldMapID)
		root = ok and QL.Plain(root) or 947
		local okC, children = pcall(C_Map.GetMapChildrenInfo, root, nil, true)
		if okC and type(children) == "table" then
			for _, info in ipairs(children) do
				local n = QL.Plain(info.name)
				local id = QL.Plain(info.mapID)
				if n and id and not mapIDByName[n:lower()] then
					mapIDByName[n:lower()] = id
				end
			end
		end
	end
	return mapIDByName[name:lower()]
end

function QL.ZoneNameForMap(mapID)
	if not mapID then
		return nil
	end
	local ok, info = pcall(C_Map.GetMapInfo, mapID)
	if ok and info then
		return QL.Plain(info.name)
	end
	return nil
end

local function CurrentMapID()
	local ok, id = pcall(WorldMapFrame.GetMapID, WorldMapFrame)
	local mapID = ok and QL.Plain(id) or nil
	if not mapID then
		local okP, pid = pcall(C_Map.GetBestMapForUnit, "player")
		mapID = okP and QL.Plain(pid) or nil
	end
	return mapID
end

function QL.CurrentAreaID()
	local mapID = CurrentMapID()
	local name = QL.ZoneNameForMap(mapID)
	if not name then
		return nil, nil
	end
	local areaID = QL.zoneByName[name:lower()]
	if not areaID then
		-- A continent or the world is shown: use the zone the player is in.
		local okP, pid = pcall(C_Map.GetBestMapForUnit, "player")
		local pname = QL.ZoneNameForMap(okP and QL.Plain(pid) or nil)
		if pname then
			areaID, name = QL.zoneByName[pname:lower()], pname
		end
	end
	return areaID, name
end

-- Continent (0 Eastern Kingdoms, 1 Kalimdor) of the map shown, walking up the map tree.
function QL.CurrentContinent()
	local mapID = CurrentMapID()
	for _ = 1, 6 do
		if not mapID then break end
		local ok, info = pcall(C_Map.GetMapInfo, mapID)
		if not ok or not info then break end
		local name = QL.Plain(info.name)
		if name then
			for c, cname in pairs(QL.Data().continentNames or {}) do
				if cname:lower() == name:lower() then
					return c, cname
				end
			end
		end
		mapID = QL.Plain(info.parentMapID)
		if not mapID or mapID == 0 then break end
	end
	local areaID = QL.CurrentAreaID()
	if areaID then
		local c = QL.Data().zoneContinent and QL.Data().zoneContinent[areaID]
		if c and c >= 0 then
			return c, QL.Data().continentNames[c]
		end
	end
	return nil, nil
end

function QL.SetWaypoint(row, atEnder)
	local mapID, x, y
	if atEnder then
		mapID, x, y = QL.EndPoint(row)
	end
	if not x then
		mapID, x, y = QL.GiverPoint(row)
	end
	if not x then
		return false
	end
	if not mapID then
		local zoneName = QL.Data().zones[QL.ZoneOf(row)]
		mapID = zoneName and MapIDForZoneName(zoneName)
	end
	if not mapID or not C_Map.SetUserWaypoint or not UiMapPoint then
		return false
	end
	local okCan, can = pcall(C_Map.CanSetUserWaypointOnMap, mapID)
	if okCan and can == false then
		return false
	end
	-- Through the Route module when it is on: pin, route, label and notice in one.
	local R = MelloUI.Route
	if R and R.isEnabled and R.SetDestinationTo then
		local who = atEnder and (row[QL.F_ENDER] or "") ~= "" and row[QL.F_ENDER] or row[QL.F_GIVER]
		local icon = atEnder and "|A:QuestTurnin:16:16|a " or "|A:QuestNormal:16:16|a "
		local label = icon .. row[QL.F_TITLE] .. (who ~= "" and (" - " .. who) or "")
		local what = atEnder and "turn-in" or "quest giver"
		local text = string.format("%sTracking %s %s for %s, {dist} away", icon, what, who ~= "" and who or "", row[QL.F_TITLE])
		if R:SetDestinationTo({ mapID = mapID, x = x, y = y }, label, true, text) then
			QL.trackedQuestID = row[QL.F_ID]
			return true
		end
	end
	local point = UiMapPoint.CreateFromCoordinates(mapID, x, y)
	local ok = pcall(C_Map.SetUserWaypoint, point)
	if ok and C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then
		pcall(C_SuperTrack.SetSuperTrackedUserWaypoint, true)
	end
	if ok then
		QL.trackedQuestID = row[QL.F_ID]
	end
	return ok
end

-- Route to a point on a map (entrance, dock, flight master): the Route
-- module when it is on, else a plain user waypoint.
function QL.RouteToPoint(mapID, x, y, label, notice)
	if not (mapID and x and y) then
		return false
	end
	local R = MelloUI.Route
	if R and R.isEnabled and R.SetDestinationTo then
		return R:SetDestinationTo({ mapID = mapID, x = x, y = y }, label, true, notice) and true or false
	end
	if not (C_Map.SetUserWaypoint and UiMapPoint) then
		return false
	end
	local okCan, can = pcall(C_Map.CanSetUserWaypointOnMap, mapID)
	if okCan and can == false then
		return false
	end
	local ok = pcall(C_Map.SetUserWaypoint, UiMapPoint.CreateFromCoordinates(mapID, x, y))
	if ok and C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then
		pcall(C_SuperTrack.SetSuperTrackedUserWaypoint, true)
	end
	return ok
end

function QL.ClearWaypoint()
	if C_Map.ClearUserWaypoint then
		pcall(C_Map.ClearUserWaypoint)
	end
	QL.trackedQuestID = nil
end

-- The pin can be removed from the map itself; forget the quest then.
function QL.SyncTracked()
	if QL.trackedQuestID and C_Map.HasUserWaypoint then
		local ok, has = pcall(C_Map.HasUserWaypoint)
		if ok and has == false then
			QL.trackedQuestID = nil
		end
	end
end

--------------------------------------------------------------------------------
-- Dungeon check on entering an instance
--------------------------------------------------------------------------------

local lastInstance = nil

local function DungeonSummary()
	if not (M.isEnabled and M.db.dungeonSummary and QL.byZone) then
		return
	end
	local okI, inInstance, kind = pcall(IsInInstance)
	if not okI or not inInstance or (kind ~= "party" and kind ~= "raid") then
		lastInstance = nil
		return
	end
	local okN, name = pcall(GetInstanceInfo)
	name = okN and QL.Plain(name) or nil
	if not name or name == lastInstance then
		return
	end
	lastInstance = name
	local data = QL.Data()
	local dungeonID
	for id, dname in pairs(data.dungeons or {}) do
		if dname:lower() == name:lower() then
			dungeonID = id
		end
	end
	if not dungeonID then
		return
	end
	local missing, inLog, done, total = {}, 0, 0, 0
	for _, row in ipairs(data.quests or {}) do
		if row[QL.F_DUNGEON] == dungeonID and QL.Eligible(row) then
			total = total + 1
			if QL.IsCompleted(row[QL.F_ID]) then
				done = done + 1
			elseif QL.IsOnQuest(row[QL.F_ID]) then
				inLog = inLog + 1
			else
				missing[#missing + 1] = row
			end
		end
	end
	if total == 0 then
		return
	end
	MelloUI:Print("%s: %d of %d quests done, %d in your log, %d not picked up.", name, done, total, inLog, #missing)
	for _, row in ipairs(data.quests or {}) do
		if row[QL.F_DUNGEON] == dungeonID and QL.Eligible(row) and QL.IsOnQuest(row[QL.F_ID]) and QL.IsReadyForTurnIn(row[QL.F_ID]) and (row[QL.F_ENDER] or "") ~= "" then
			local endZone = QL.EnderZoneName(row) or QL.Data().zones[QL.ZoneOf(row)]
			print(string.format("   |cffffd200%s|r is ready: turn in to %s%s", row[QL.F_TITLE], row[QL.F_ENDER], endZone and (" in " .. endZone) or ""))
		end
	end
	table.sort(missing, QL.ByLevel)
	for i, row in ipairs(missing) do
		if i > 12 then
			print(string.format("   ... and %d more; see the Dungeons tab of the quest list.", #missing - 12))
			break
		end
		local r, g, b = QL.DifficultyColor(row[QL.F_LEVEL])
		local zone = data.zones[row[QL.F_GIVERZONE]] or data.zones[row[QL.F_ZONE]]
		local from = row[QL.F_GIVER] ~= "" and row[QL.F_GIVER] or "giver unknown"
		print(string.format("   |cff%02x%02x%02x%s|r (%d)  -  %s%s", r * 255, g * 255, b * 255, row[QL.F_TITLE], row[QL.F_LEVEL],
			from, zone and (", " .. zone) or ""))
	end
end

--------------------------------------------------------------------------------
-- Module lifecycle
--------------------------------------------------------------------------------

local eventFrame = CreateFrame("Frame")
eventFrame:SetScript("OnEvent", function(_, event, ...)
	if event == "PLAYER_ENTERING_WORLD" then
		-- Instance info and quest flags settle a moment after the load.
		C_Timer.After(2, function()
			if not QL.LearnEntrance() then
				C_Timer.After(6, QL.LearnEntrance)
			end
			DungeonSummary()
		end)
		if QL.pendingExit then
			C_Timer.After(1, QL.LearnEntranceOnExit)
		end
	elseif event == "UNIT_SPELLCAST_SUCCEEDED" then
		-- Hearthstone or Astral Recall out of the instance: the arrival point
		-- is not the door.
		local _, _, spellID = ...
		spellID = QL.Plain(spellID)
		if spellID == 8690 or spellID == 556 then
			QL.pendingExit = nil
		end
	elseif event == "PLAYER_LEAVING_WORLD" or event == "ZONE_CHANGED" or event == "ZONE_CHANGED_INDOORS" or event == "ZONE_CHANGED_NEW_AREA" then
		QL.RememberOutside()
	end
	if WorldMapFrame and WorldMapFrame:IsShown() then
		QL.Panel:Schedule()
	end
end)

local hooked = false

function M:OnInit(db)
	self.db = db
end

function M:OnEnable(db)
	self.db = db
	if type(MelloUI_QuestListData) ~= "table" then
		MelloUI:Print("Quest List: Media\\QuestListData.lua is missing; run Tools\\build_quest_list.py.")
		return
	end
	if not WorldMapFrame then
		return
	end
	if not QL.byZone then
		BuildIndex()
	end
	QL.Panel:Create()
	QL.Panel:Apply()
	QL.CreateProvider()
	QL.RefreshPins()
	ResolveInChunks(function()
		BuildIndex()
		if QL.Panel.frame and QL.Panel.frame:IsShown() then
			QL.Panel:Update()
		end
		QL.RefreshPins()
	end)
	if not hooked then
		hooked = true
		if WorldMapFrame.OnMapChanged then
			hooksecurefunc(WorldMapFrame, "OnMapChanged", function() QL.Panel:Update() end)
		end
	end
	-- the events go with the module's state (they ran on after a disable;
	-- audit 2026-09-22)
	eventFrame:RegisterEvent("QUEST_LOG_UPDATE")
	eventFrame:RegisterEvent("ZONE_CHANGED_NEW_AREA")
	eventFrame:RegisterEvent("PLAYER_LEVEL_UP")
	eventFrame:RegisterEvent("PLAYER_ENTERING_WORLD")
	eventFrame:RegisterEvent("PLAYER_LEAVING_WORLD")
	eventFrame:RegisterEvent("ZONE_CHANGED")
	eventFrame:RegisterEvent("ZONE_CHANGED_INDOORS")
	if eventFrame.RegisterUnitEvent then
		eventFrame:RegisterUnitEvent("UNIT_SPELLCAST_SUCCEEDED", "player")
	else
		eventFrame:RegisterEvent("UNIT_SPELLCAST_SUCCEEDED")
	end
	QL.StartOutsideTicker()
end

function M:OnDisable()
	eventFrame:UnregisterAllEvents()
	QL.StopOutsideTicker()
	if QL.Panel.frame then
		QL.Panel.frame:Hide()
	end
	if QL.Provider and WorldMapFrame then
		QL.Provider:RemoveAllData()
	end
end

function M:OnSettingChanged(key, value, db)
	self.db = db
	QL.Panel:Apply()
	QL.RefreshPins()
end

-- /qlmap: why pins are (not) on the map shown.
SLASH_MELLOQUESTMAP1 = "/qlmap"
SlashCmdList.MELLOQUESTMAP = function(msg)
	local data = QL.Data()
	if type(data) ~= "table" then
		MelloUI:Print("Quest List: Media\\QuestListData.lua is missing; run Tools\\build_quest_list.py.")
		return
	end
	msg = (msg or ""):gsub("^%s+", ""):gsub("%s+$", "")
	local cmd, rest = msg:match("^(%S+)%s*(.-)$")
	cmd = cmd and cmd:lower()
	if cmd == "dock" or cmd == "zeppelin" then
		-- /qlmap dock Boat to Auberdine [| Alliance|Horde]   (stand on the dock)
		if rest == "" then
			MelloUI:Print("Stand on the dock and type:  /qlmap dock Boat to Auberdine   (add  | horde  or  | alliance  for a faction-only route; default neutral).")
			return
		end
		local label, side = rest:match("^(.-)%s*|%s*(%a+)$")
		label = label or rest
		local faction = 0
		if side and side:lower() == "alliance" then faction = 1 elseif side and side:lower() == "horde" then faction = 2 end
		local mapID, x, y, dock = QL.PlayerMapPoint()
		if not mapID then
			MelloUI:Print("Cannot read your position here.")
			return
		end
		QL.LearnedStore("transports")[label] = { mapID = mapID, x = x, y = y, dock = dock, kind = cmd == "zeppelin" and 2 or 1, faction = faction }
		MelloUI:Print("Recorded '%s' at %s (%.1f, %.1f). Sail there and type  /qlmap arrive %s  to link the destination map.", label, dock, x * 100, y * 100, label)
		QL.RefreshPins()
	elseif cmd == "arrive" then
		local l = rest ~= "" and QL.LearnedStore("transports")[rest]
		if not l then
			MelloUI:Print("No recorded dock called '%s'.", rest)
			return
		end
		local mapID = QL.PlayerMapPoint()
		if mapID then
			l.destMapID = mapID
			MelloUI:Print("'%s' now opens %s when clicked.", rest, QL.ZoneNameForMap(mapID) or tostring(mapID))
		end
	elseif cmd == "entrance" then
		-- /qlmap entrance Hall of Thanes [| raid]   (stand at the entrance)
		if rest == "" then
			MelloUI:Print("Stand at the entrance and type:  /qlmap entrance Hall of Thanes   (add  | raid  for a raid).")
			return
		end
		local name, kind = rest:match("^(.-)%s*|%s*(%a+)$")
		name = name or rest
		local mapID, x, y = QL.PlayerMapPoint()
		if not mapID then
			MelloUI:Print("Cannot read your position here.")
			return
		end
		QL.LearnedStore("entrances")[name] = { mapID = mapID, x = x, y = y, raid = kind ~= nil and kind:lower() == "raid" }
		MelloUI:Print("Recorded the entrance of %s at %.1f, %.1f.", name, x * 100, y * 100)
		QL.RefreshPins()
	elseif cmd == "remove" then
		local removed = false
		if QL.LearnedStore("transports")[rest] then
			QL.LearnedStore("transports")[rest] = nil
			removed = true
		end
		if QL.LearnedStore("entrances")[rest] then
			QL.LearnedStore("entrances")[rest] = nil
			removed = true
		end
		MelloUI:Print(removed and ("Removed '" .. rest .. "'.") or ("Nothing recorded as '" .. rest .. "'."))
		QL.RefreshPins()
	elseif cmd == "list" then
		MelloUI:Print("Recorded pins:")
		for name, l in pairs(QL.LearnedStore("entrances")) do
			print(string.format("   entrance  %s  (%s %.1f, %.1f)", name, QL.ZoneNameForMap(l.mapID) or "?", l.x * 100, l.y * 100))
		end
		for label, l in pairs(QL.LearnedStore("transports")) do
			print(string.format("   dock  %s  (%s %.1f, %.1f)%s", label, QL.ZoneNameForMap(l.mapID) or "?", l.x * 100, l.y * 100,
				l.destMapID and ("  ->  " .. (QL.ZoneNameForMap(l.destMapID) or "?")) or ""))
		end
		return
	elseif cmd and cmd ~= "" then
		MelloUI:Print("/qlmap  (diagnostics)  |  /qlmap dock <label> [| alliance|horde]  |  /qlmap zeppelin <label>  |  /qlmap arrive <label>  |  /qlmap entrance <name> [| raid]  |  /qlmap remove <name>  |  /qlmap list")
		return
	end
	if cmd then
		return
	end
	MelloUI:Print("Quest List map pins")
	print("   provider: " .. tostring(QL.Provider ~= nil) .. "   pin mixin ready: " .. tostring(QL.PinMixin.SetPosition ~= nil)
		.. "   GetMapPosFromWorldPos: " .. tostring(C_Map.GetMapPosFromWorldPos ~= nil) .. "   CreateVector2D: " .. tostring(CreateVector2D ~= nil))
	print(string.format("   data: %d entrances, %d transports, %d learned", #(data.entrances or {}), #(data.transports or {}),
		(function() local n = 0 for _ in pairs(QL.LearnedStore("entrances")) do n = n + 1 end return n end)()))
	print(string.format("   options: pins %s, entrances %s, transports %s, badges %s",
		tostring(M.db.mapPins), tostring(M.db.entrancePins), tostring(M.db.transportPins), tostring(M.db.zoneBadges)))
	if QL.lastPinInfo then
		print(string.format("   last refresh: map %s (%s), type %s", tostring(QL.lastPinInfo.mapID), tostring(QL.lastPinInfo.name), tostring(QL.lastPinInfo.mapType)))
		local client = QL.ClientEntrances(QL.lastPinInfo.mapID)
		print(string.format("   client entrance list for this map: %s, %d entries", tostring(C_EncounterJournal and C_EncounterJournal.GetDungeonEntrancesForMap ~= nil), #client))
		for i, e in ipairs(client) do
			if i > 8 then break end
			print(string.format("      %s at %.1f, %.1f", e.name, e.x * 100, e.y * 100))
		end
		local pois = QL.ClientPOIs(QL.lastPinInfo.mapID)
		print(string.format("   points of interest the map shows: %d", #pois))
		for i, poi in ipairs(pois) do
			if i > 12 then
				print("      ... " .. (#pois - 12) .. " more")
				break
			end
			print(string.format("      %s%s at %.1f, %.1f  [%s]", poi.name, QL.IsEntrancePOI(poi) and " (instance)" or "", poi.x * 100, poi.y * 100, poi.atlas))
		end
	else
		print("   no refresh yet (open the map).")
	end
	local pools = WorldMapFrame and WorldMapFrame.pinPools and WorldMapFrame.pinPools[QL.PIN_TEMPLATE]
	if pools then
		local n, kinds = 0, {}
		for pin in pools:EnumerateActive() do
			n = n + 1
			kinds[pin.kind or "?"] = (kinds[pin.kind or "?"] or 0) + 1
		end
		local parts = {}
		for k, v in pairs(kinds) do parts[#parts + 1] = k .. " " .. v end
		print("   pins on the map: " .. n .. (n > 0 and (" (" .. table.concat(parts, ", ") .. ")") or ""))
	end
	for _, err in ipairs(QL.lastPinErrors) do
		print("   |cffff4040error|r " .. err)
	end
	for i, line in ipairs(QL.lastPointTrace) do
		if i > 8 then
			print("   ... " .. (#QL.lastPointTrace - 8) .. " more")
			break
		end
		print("   " .. line)
	end
	-- Probe the API with the first entrance.
	local e = data.entrances and data.entrances[1]
	if e and C_Map.GetMapPosFromWorldPos and CreateVector2D then
		local ok, uiMapID, pos = pcall(C_Map.GetMapPosFromWorldPos, e[3], CreateVector2D(e[4], e[5]))
		local x, y = QL.VectorXY(pos)
		print(string.format("   probe %s at (%d, %.0f, %.0f): ok %s, map %s, pos %s (%s, %s)", e[2], e[3], e[4], e[5],
			tostring(ok), tostring(uiMapID), type(pos), tostring(x), tostring(y)))
	end
end

MelloUI:Profile("QuestList", "quest log events", eventFrame)
