--------------------------------------------------------------------------------
-- MelloUI - Voice Over
--
-- Reads NPC dialog aloud with the client's built in text-to-speech: gossip
-- greetings, quest offers, progress and turn-in text. Speech keeps playing
-- after the window is closed, so you can accept a quest and walk off while the
-- NPC is still talking.
--
-- Voices come from the operating system (the same ones the chat text-to-speech
-- accessibility feature uses). The NPC's race and gender are looked up in
-- Media\NPCVoiceData.lua (generated by Tools\extract_npc_voices.py) and
-- Media\NPCVoiceOverrides.lua (hand written). Each race has a pitch and speed
-- profile so goblins chatter and ogres rumble, and any race group can be given
-- its own voice. NPCs missing from the data fall back to the gender voices.
--
-- If a VoiceOver data pack (AI_VoiceOverData_Vanilla) is installed, its
-- recorded lines are played instead of text-to-speech whenever one exists.
--
-- Commands: /vo stop, /vo pause, /vo skip, /vo read, /vo test, /vo voices, /vo npc,
-- /vo packs (what loaded, the last lookups), /vo lines, /vo reset
--------------------------------------------------------------------------------

local ADDON_NAME, ns = ...
local MelloUI = ns.MelloUI

local AUTO_VOICE = -1

-- Filled from C_VoiceChat.GetTtsVoices(); the config dropdowns read this table
-- lazily, so refilling it in place is enough to refresh the list.
local VOICE_VALUES = { { value = AUTO_VOICE, label = "Automatic (by gender)" } }

--------------------------------------------------------------------------------
-- Race profiles
--
-- pitch and rate are offsets in the speech engine's -10..10 units. They are
-- scaled by the Profile Strength setting, and rate is added to the base speed.
--------------------------------------------------------------------------------

local RACE_PROFILES = {
	human      = { pitch = 0,   rate = 0,  label = "Human" },
	dwarf      = { pitch = -2,  rate = -1, label = "Dwarf" },
	gnome      = { pitch = 4,   rate = 2,  label = "Gnome" },
	nightelf   = { pitch = 1,   rate = -1, label = "Night Elf" },
	highelf    = { pitch = 1,   rate = -1, label = "High Elf" },
	orc        = { pitch = -4,  rate = -1, label = "Orc" },
	troll      = { pitch = -2,  rate = 0,  label = "Troll" },
	tauren     = { pitch = -6,  rate = -3, label = "Tauren" },
	undead     = { pitch = -3,  rate = -2, label = "Undead" },
	goblin     = { pitch = 5,   rate = 3,  label = "Goblin" },
	ogre       = { pitch = -8,  rate = -4, label = "Ogre" },
	giant      = { pitch = -10, rate = -5, label = "Giant" },
	kobold     = { pitch = 6,   rate = 3,  label = "Kobold" },
	murloc     = { pitch = 7,   rate = 4,  label = "Murloc" },
	gnoll      = { pitch = 2,   rate = 2,  label = "Gnoll" },
	trogg      = { pitch = -3,  rate = 1,  label = "Trogg" },
	furbolg    = { pitch = -5,  rate = -2, label = "Furbolg" },
	naga       = { pitch = -1,  rate = -2, label = "Naga" },
	satyr      = { pitch = 1,   rate = 1,  label = "Satyr" },
	harpy      = { pitch = 4,   rate = 1,  label = "Harpy" },
	centaur    = { pitch = -3,  rate = 0,  label = "Centaur" },
	quilboar   = { pitch = -2,  rate = 1,  label = "Quilboar" },
	dragon     = { pitch = -7,  rate = -4, label = "Dragon" },
	demon      = { pitch = -6,  rate = -3, label = "Demon" },
	imp        = { pitch = 8,   rate = 5,  label = "Imp" },
	succubus   = { pitch = 2,   rate = -1, label = "Succubus" },
	elemental  = { pitch = -5,  rate = -3, label = "Elemental" },
	spirit     = { pitch = 2,   rate = -2, label = "Spirit" },
	treant     = { pitch = -6,  rate = -5, label = "Treant" },
	keeper     = { pitch = -4,  rate = -3, label = "Keeper" },
	dryad      = { pitch = 3,   rate = 0,  label = "Dryad" },
	insect     = { pitch = 3,   rate = 2,  label = "Insect" },
	mechanical = { pitch = 0,   rate = 2,  label = "Mechanical" },
	beast      = { pitch = -2,  rate = 0,  label = "Beast" },
	other      = { pitch = -2,  rate = 0,  label = "Creature" },
}
local DEFAULT_PROFILE = { pitch = 0, rate = 0, label = "Unknown" }

-- Race groups that can be given their own voice in the settings.
local RACE_GROUPS = {
	{ key = "human",   name = "Humans",            races = { human = true } },
	{ key = "elf",     name = "Elves",             races = { nightelf = true, highelf = true } },
	{ key = "dwarf",   name = "Dwarves",           races = { dwarf = true } },
	{ key = "gnome",   name = "Gnomes",            races = { gnome = true } },
	{ key = "orc",     name = "Orcs",              races = { orc = true } },
	{ key = "troll",   name = "Trolls",            races = { troll = true } },
	{ key = "tauren",  name = "Tauren",            races = { tauren = true } },
	{ key = "undead",  name = "Undead",            races = { undead = true } },
	{ key = "goblin",  name = "Goblins",           races = { goblin = true } },
	{ key = "ogre",    name = "Ogres & Giants",    races = { ogre = true, giant = true } },
	{ key = "monster", name = "Monsters & Beasts", races = nil },  -- everything else
}

local function GroupForRace(race)
	for _, group in ipairs(RACE_GROUPS) do
		if group.races and group.races[race] then
			return group
		end
	end
	return RACE_GROUPS[#RACE_GROUPS]
end

--------------------------------------------------------------------------------
-- Module registration
--------------------------------------------------------------------------------

local defaults = {
	gossip = true,
	questDetail = true,
	questObjectives = false,
	questProgress = true,
	questComplete = true,
	maleVoice = AUTO_VOICE,
	femaleVoice = AUTO_VOICE,
	rate = 0,
	volume = 100,
	raceProfiles = true,
	profileStrength = 1,
	stopOnClose = false,
	questLog = true,
	questLogObjectives = true,
	stopOnMove = false,
	queueLines = true,
	soundPacks = true,
	preferRecordings = false,
	soundChannel = "Master",
	collectLines = true,
	overlay = true,
	overlayPortrait = true,
	overlaySubtitles = false,
	overlayLock = false,
	overlayScale = 1,
}
local options = {
	{ type = "header", name = "Read Aloud" },
	{ type = "toggle", key = "gossip", name = "NPC Greetings",
	  desc = "The text an NPC greets you with when you talk to them." },
	{ type = "toggle", key = "questDetail", name = "Quest Offers",
	  desc = "The quest description when a quest is offered." },
	{ type = "toggle", key = "questObjectives", parent = "questDetail", name = "Include Objectives",
	  desc = "Also read the objectives after the quest description." },
	{ type = "toggle", key = "questProgress", name = "Quest Progress",
	  desc = "What the NPC says when you return with an unfinished quest." },
	{ type = "toggle", key = "questComplete", name = "Quest Turn-In",
	  desc = "What the NPC says when you hand in a completed quest." },
	{ type = "header", name = "Voices" },
	{ type = "dropdown", key = "maleVoice", name = "Male NPCs", values = VOICE_VALUES,
	  desc = "Voice used for male and genderless NPCs. Install more voices in Windows speech settings." },
	{ type = "dropdown", key = "femaleVoice", name = "Female NPCs", values = VOICE_VALUES,
	  desc = "Voice used for female NPCs." },
	{ type = "slider", key = "rate", name = "Speed", min = -10, max = 10, step = 1,
	  format = function(v) return v > 0 and ("+" .. v) or tostring(v) end,
	  desc = "Base speaking speed. 0 is the voice's normal pace." },
	{ type = "slider", key = "volume", name = "Volume", min = 0, max = 100, step = 5,
	  format = function(v) return string.format("%d%%", v) end,
	  desc = "Speech volume." },
	{ type = "header", name = "Race Character" },
	{ type = "toggle", key = "raceProfiles", name = "Race Pitch & Speed",
	  desc = "Shape the voice by the NPC's race: goblins and gnomes high and quick, ogres and tauren low and slow, and so on. NPCs not in the data are read with the plain voice." },
	{ type = "slider", key = "profileStrength", parent = "raceProfiles", name = "Profile Strength", min = 0, max = 2, step = 0.1, percent = true,
	  desc = "How strongly the race profile bends pitch and speed. 100% is the built in profile." },
	{ type = "header", name = "Voice Per Race (optional)" },
}
for _, group in ipairs(RACE_GROUPS) do
	defaults["voice_" .. group.key] = AUTO_VOICE
	options[#options + 1] = { type = "dropdown", key = "voice_" .. group.key, name = group.name, values = VOICE_VALUES,
		desc = "Voice for " .. group.name:lower() .. " of either gender. Automatic uses the male / female voices above." }
end
options[#options + 1] = { type = "header", name = "Sound Packs" }
options[#options + 1] = { type = "toggle", key = "soundPacks", name = "Use VoiceOver Sound Packs",
	desc = "Play the recorded lines from an installed VoiceOver data pack (AI_VoiceOverData_Vanilla) when one exists for the quest or greeting, and use text-to-speech for everything else. Enable the pack in the addon list; it loads when needed." }
options[#options + 1] = { type = "toggle", key = "preferRecordings", parent = "soundPacks", name = "Prefer Recordings",
	desc = "When an NPC's greeting text was changed but the pack has exactly one recorded greeting for that NPC, play the recording anyway instead of reading the new text aloud. The words will not match what is on screen." }
options[#options + 1] = { type = "dropdown", key = "soundChannel", name = "Sound Channel", values = {
		{ value = "Master", label = "Master" },
		{ value = "Dialog", label = "Dialog" },
		{ value = "SFX", label = "Sound Effects" },
		{ value = "Ambience", label = "Ambience" },
	},
	desc = "Channel the recorded lines play on; its volume slider in the game's sound settings controls them." }
options[#options + 1] = { type = "toggle", key = "collectLines", name = "Record Dialog Lines",
	desc = "Keep every greeting and quest line you see, with the NPC and whether a recording existed, so Tools\\export_voice_lines.py can list the lines Forever added or changed for a new sound pack. Written to the saved variables on /reload." }
options[#options + 1] = { type = "header", name = "Playback" }
options[#options + 1] = { type = "toggle", key = "queueLines", name = "Queue Lines",
	desc = "Read lines one after another: a greeting finishes before the quest offer that follows it. Off makes every new dialog interrupt the previous one." }
options[#options + 1] = { type = "toggle", key = "stopOnClose", name = "Stop When Window Closes",
	desc = "Cut the speech off when you close the dialog. Off by default so the NPC keeps talking while you walk away." }
options[#options + 1] = { type = "toggle", key = "questLogObjectives", name = "Read The Objectives Too",
	desc = "After the description, read the objectives with their progress. Off reads only the description." }
options[#options + 1] = { type = "toggle", key = "questLog", name = "Read Button In The Quest Log",
	desc = "A Read button on the quest log's details view: the quest's description in the giver's voice (the recorded offer line when a pack has it), then the objectives with their progress. Also /vo read." }
options[#options + 1] = { type = "toggle", key = "stopOnMove", name = "Stop When Target Changes",
	desc = "Cut the speech off when you change target." }
options[#options + 1] = { type = "header", name = "Overlay" }
options[#options + 1] = { type = "toggle", key = "overlay", name = "Show Overlay",
	desc = "Show a frame with the speaking NPC, the line being read and the lines waiting. Drag it to move; /vo reset puts it back." }
options[#options + 1] = { type = "toggle", key = "overlayPortrait", parent = "overlay", name = "3D Portrait",
	desc = "Show the NPC's animated portrait. Off collapses the overlay to a thin bar with a pause button." }
options[#options + 1] = { type = "toggle", key = "overlaySubtitles", parent = "overlay", name = "Subtitles",
	desc = "Also show the text being read under the NPC name." }
options[#options + 1] = { type = "toggle", key = "overlayLock", parent = "overlay", name = "Lock Position",
	desc = "Prevent the overlay from being dragged." }
options[#options + 1] = { type = "slider", key = "overlayScale", parent = "overlay", name = "Overlay Scale", min = 0.6, max = 1.5, step = 0.05, percent = true,
	desc = "Size of the overlay." }

local M = MelloUI:RegisterModule("VoiceOver", {
	title = "Voice Over",
	desc = "Read NPC dialog and quest text aloud with the built in text-to-speech voices, shaped by the NPC's race and gender.",
	enabledByDefault = true,
	defaults = defaults,
	options = options,
})

--------------------------------------------------------------------------------
-- Helpers
--------------------------------------------------------------------------------

local function IsSecret(v)
	return issecretvalue and issecretvalue(v)
end

local function IsPlainNumber(v)
	return type(v) == "number" and not IsSecret(v)
end

local function HasTTS()
	return C_VoiceChat and C_VoiceChat.SpeakText and C_VoiceChat.GetTtsVoices
end

local function Clamp(v, lo, hi)
	if v < lo then return lo end
	if v > hi then return hi end
	return v
end

local FEMALE_HINTS = { "zira", "hazel", "susan", "heera", "catherine", "linda", "eva", "female", "aria", "jenny", "sonia", "natasha", "libby", "sara", "hedda", "helena", "julie", "irina", "hortense", "elsa", "maria", "hoda", "ayumi", "haruka", "huihui", "yaoyao", "tracy", "michelle", "emma", "ana", "clara", "sofia", "olivia", "amber", "ashley", "cora", "elizabeth", "jane", "monica", "nancy", "zoe" }

local function LooksFemale(name)
	name = (name or ""):lower()
	for _, hint in ipairs(FEMALE_HINTS) do
		if name:find(hint, 1, true) then
			return true
		end
	end
	return false
end

local voices = {}          -- list of { voiceID, name }
local voiceByID = {}       -- [voiceID] = name

local function RefreshVoices()
	wipe(voices)
	wipe(voiceByID)
	for i = #VOICE_VALUES, 2, -1 do
		VOICE_VALUES[i] = nil
	end
	if not HasTTS() then
		return
	end
	local ok, list = pcall(C_VoiceChat.GetTtsVoices)
	if not ok or type(list) ~= "table" then
		return
	end
	for _, voice in ipairs(list) do
		if IsPlainNumber(voice.voiceID) and type(voice.name) == "string" then
			voices[#voices + 1] = { voiceID = voice.voiceID, name = voice.name }
			voiceByID[voice.voiceID] = voice.name
			VOICE_VALUES[#VOICE_VALUES + 1] = { value = voice.voiceID, label = voice.name }
		end
	end
end

local function AutoVoice(female)
	if #voices == 0 then
		return nil
	end
	for _, voice in ipairs(voices) do
		if LooksFemale(voice.name) == female then
			return voice.voiceID
		end
	end
	return voices[1].voiceID
end

local function ChosenVoice(key)
	local chosen = M.db[key]
	if chosen ~= nil and chosen ~= AUTO_VOICE and voiceByID[chosen] then
		return chosen
	end
	return nil
end

local function PickVoice(race, female)
	if race then
		local group = GroupForRace(race)
		local voice = ChosenVoice("voice_" .. group.key)
		if voice then
			return voice
		end
	end
	return ChosenVoice(female and "femaleVoice" or "maleVoice") or AutoVoice(female)
end

--------------------------------------------------------------------------------
-- NPC lookup
--------------------------------------------------------------------------------

local npcLookup = nil   -- [npcID] = { race = string, gender = "m" | "f" | "n" }

local function BuildLookup()
	npcLookup = {}
	if type(MelloUI_NPCVoiceData) == "table" then
		for key, ids in pairs(MelloUI_NPCVoiceData) do
			local race, gender = tostring(key):match("^(%a+)_(%a)$")
			if race and type(ids) == "string" then
				local info = { race = race, gender = gender }
				for id in ids:gmatch("%d+") do
					npcLookup[tonumber(id)] = info
				end
			end
		end
	end
	if type(MelloUI_NPCVoiceOverrides) == "table" then
		for key, entry in pairs(MelloUI_NPCVoiceOverrides) do
			local id = tonumber(key)
			if id and type(entry) == "table" then
				local race = entry.race or entry[1]
				local gender = entry.gender or entry[2]
				if type(race) == "string" then
					npcLookup[id] = { race = race:lower(), gender = type(gender) == "string" and gender:sub(1, 1):lower() or "n", override = true }
				end
			end
		end
	end
end

local function NPCIDFromUnit(unit)
	local ok, guid = pcall(UnitGUID, unit)
	if not ok or type(guid) ~= "string" or IsSecret(guid) then
		return nil
	end
	local id = guid:match("^Creature%-%d+%-%d+%-%d+%-%d+%-(%d+)")
	return id and tonumber(id) or nil
end

local function UnitFemale(unit)
	local ok, sex = pcall(UnitSex, unit)
	if ok and IsPlainNumber(sex) then
		return sex == 3, true
	end
	return false, false
end

local function UnitPlainName(unit)
	local ok, name = pcall(UnitName, unit)
	if ok and type(name) == "string" and not IsSecret(name) then
		return name
	end
	return nil
end

-- Describe the NPC currently being talked to (or targeted, for /vo commands).
local function DescribeNPC(preferTarget)
	if not npcLookup then
		BuildLookup()
	end
	local units = preferTarget and { "target", "npc", "questnpc" } or { "npc", "questnpc", "target" }
	for _, unit in ipairs(units) do
		local ok, exists = pcall(UnitExists, unit)
		if ok and exists then
			local id = NPCIDFromUnit(unit)
			if id then
				local info = npcLookup[id]
				local female, known = UnitFemale(unit)
				local gender
				if info and info.gender ~= "n" then
					female = info.gender == "f"
					gender = info.gender
				elseif known then
					gender = female and "f" or "m"
				else
					gender = info and info.gender or "n"
				end
				return {
					unit = unit,
					id = id,
					name = UnitPlainName(unit),
					race = info and info.race or nil,
					gender = gender,
					female = female,
					source = info and (info.override and "override" or "data") or "unknown",
				}
			end
		end
	end
	return nil
end

--------------------------------------------------------------------------------
-- Text
--------------------------------------------------------------------------------

-- Strip UI escape sequences so the voice does not read colour codes.
local function CleanText(text)
	if type(text) ~= "string" or IsSecret(text) then
		return text
	end
	text = text:gsub("|c%x%x%x%x%x%x%x%x", "")
	text = text:gsub("|r", "")
	text = text:gsub("|T.-|t", "")
	text = text:gsub("|A.-|a", "")
	text = text:gsub("|H.-|h(.-)|h", "%1")
	text = text:gsub("|n", " ")
	text = text:gsub("%s+", " ")
	text = text:gsub("^%s+", ""):gsub("%s+$", "")
	return text
end

local function EscapeXML(text)
	return (text:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"))
end

-- Pitch / rate for an NPC according to its race profile and the settings.
local function VoiceShape(race)
	local base = tonumber(M.db.rate) or 0
	if not M.db.raceProfiles or not race then
		return 0, Clamp(base, -10, 10), DEFAULT_PROFILE
	end
	local profile = RACE_PROFILES[race] or DEFAULT_PROFILE
	local strength = tonumber(M.db.profileStrength) or 1
	local pitch = Clamp(math.floor(profile.pitch * strength + 0.5), -10, 10)
	local rate = Clamp(base + math.floor(profile.rate * strength + 0.5), -10, 10)
	return pitch, rate, profile
end

--------------------------------------------------------------------------------
-- Sound packs
--
-- The VoiceOver addon's data packs (AI_VoiceOverData_Vanilla and friends) are
-- load-on-demand addons holding one MP3 per quest line and greeting plus Lua
-- lookup tables. They are loaded here without the VoiceOver player and read
-- directly: quest lines by quest ID, greetings by NPC and text.
--------------------------------------------------------------------------------

local packs = {}            -- { name = addon, data = table, priority = number }
local packsLoaded = false
local packErrors = {}
local lookupTrace = {}      -- last few lookup results, for /vo packs
local MAX_TRACE = 8

local function Trace(fmt, ...)
	table.insert(lookupTrace, 1, string.format(fmt, ...))
	lookupTrace[MAX_TRACE + 1] = nil
end
local activeHandle = nil    -- sound handle of the file being played

local function AddOnAPI(name)
	return (C_AddOns and C_AddOns[name]) or _G[name]
end

local function PlainNumber(v)
	return IsPlainNumber(v) and v or nil
end

local function LoadSoundPacks()
	if packsLoaded then
		return
	end
	packsLoaded = true
	local GetNumAddOns, GetAddOnInfo, GetAddOnMetadata = AddOnAPI("GetNumAddOns"), AddOnAPI("GetAddOnInfo"), AddOnAPI("GetAddOnMetadata")
	local IsAddOnLoaded, LoadAddOn = AddOnAPI("IsAddOnLoaded"), AddOnAPI("LoadAddOn")
	if not (GetNumAddOns and GetAddOnInfo and GetAddOnMetadata and IsAddOnLoaded and LoadAddOn) then
		return
	end
	for i = 1, GetNumAddOns() do
		local name = GetAddOnInfo(i)
		local ok, version = pcall(GetAddOnMetadata, name, "X-VoiceOver-DataModule-Version")
		if ok and version then
			-- The pack files expect the VoiceOver player's globals to exist.
			if type(_G.VoiceOver) ~= "table" then
				_G.VoiceOver = {}
			end
			if type(_G.VoiceOver.DataModules) ~= "table" then
				_G.VoiceOver.DataModules = { Register = function() end }
			end
			if type(_G[name]) ~= "table" then
				_G[name] = {}
			end
			local loaded, reason = IsAddOnLoaded(name), nil
			if not loaded then
				-- The packs carry an old interface number; allow out of date
				-- addons just for this load and put the settings back after.
				local prevCheck = GetCVar("checkAddonVersion")
				local prevLast = GetCVar("lastAddonVersion")
				pcall(SetCVar, "checkAddonVersion", 0)
				local _, _, _, interface = GetBuildInfo()
				if prevLast ~= nil and interface then
					pcall(SetCVar, "lastAddonVersion", interface)
				end
				local callOk, a, b = pcall(LoadAddOn, name)
				if prevCheck ~= nil then pcall(SetCVar, "checkAddonVersion", prevCheck) end
				if prevLast ~= nil then pcall(SetCVar, "lastAddonVersion", prevLast) end
				if callOk then
					loaded, reason = a, b
				else
					loaded, reason = false, tostring(a)
				end
			end
			local data = _G[name]
			if loaded and type(data) == "table" and type(data.SoundLengthLookupByFileName) == "table" then
				local _, priority = pcall(GetAddOnMetadata, name, "X-VoiceOver-DataModule-Priority")
				packs[#packs + 1] = { name = name, data = data, priority = tonumber(priority) or 0 }
			else
				packErrors[name] = tostring(reason or (loaded and "no lookup tables" or "not loaded"))
			end
		end
	end
	table.sort(packs, function(a, b) return a.priority > b.priority end)
	if #packs > 0 and (IsAddOnLoaded("AI_VoiceOver_Continued") or IsAddOnLoaded("AI_VoiceOver")) then
		MelloUI:Notice("Voice Over: the VoiceOver player addon is also enabled, so lines may play twice. Disable one of them.")
	end
end

-- The pack texts keep the placeholders ($n name, $c class, $r race) that the
-- live text has already filled in. Put the placeholders back, drop case and
-- punctuation, so both sides compare on words alone.
local playerTokens = nil

local function PlayerTokens()
	if playerTokens then
		return playerTokens
	end
	playerTokens = {}
	local function Add(value, placeholder)
		if type(value) == "string" and not IsSecret(value) and value ~= "" then
			playerTokens[#playerTokens + 1] = { value:lower(), placeholder }
		end
	end
	local ok, name = pcall(UnitName, "player")
	if ok then Add(name, "$n") end
	local ok2, class = pcall(UnitClass, "player")
	if ok2 then Add(class, "$c") end
	local ok3, race = pcall(UnitRace, "player")
	if ok3 then Add(race, "$r") end
	return playerTokens
end

local function Normalise(text)
	text = text:lower()
	for _, pair in ipairs(PlayerTokens()) do
		local value, placeholder = pair[1], pair[2]
		text = text:gsub(value:gsub("%p", "%%%0"), placeholder)
	end
	-- $N / $C / $R are the capitalised forms of the same placeholders; $B is
	-- a line break in the pack texts, plain whitespace in the live text.
	text = text:gsub("%$g[^;]*;[^;]*;", " ")
	text = text:gsub("%$b", " ")
	text = text:gsub("[^%w%$%s]", " ")
	return text
end

-- Word overlap between two texts, 0..1 (the matcher the VoiceOver addon uses).
local function Similarity(a, b)
	local tokensA, tokensB = {}, {}
	for token in Normalise(a):gmatch("%S+") do tokensA[token] = true end
	for token in Normalise(b):gmatch("%S+") do tokensB[token] = true end
	local intersection, union = 0, 0
	for token in pairs(tokensA) do
		union = union + 1
		if tokensB[token] then intersection = intersection + 1 end
	end
	for token in pairs(tokensB) do
		if not tokensA[token] then union = union + 1 end
	end
	if union == 0 then return 0 end
	return intersection / union
end

local function BestMatch(query, entries, minimum)
	local exact = entries[query]
	if exact ~= nil then
		return exact, 1
	end
	local bestValue, bestScore = nil, minimum or 0
	for text, value in pairs(entries) do
		local score = Similarity(query, text)
		if score > bestScore then
			bestValue, bestScore = value, score
		end
	end
	return bestValue, bestScore
end

local function PackFile(pack, kind, fileName)
	local lengths = pack.data.SoundLengthLookupByFileName
	local folder = kind == "gossip" and "gossip" or "quests"
	-- Lines whose words depend on the player's gender ($G) exist only as
	-- m- / f- files (213 quest lines of the vanilla pack have no plain file):
	-- the player's own gender first, the plain file, then either gendered
	-- file rather than silence when UnitSex answers nothing on this client.
	local sex = PlainNumber(select(2, pcall(UnitSex, "player")))
	local prefix = sex == 2 and "m-" or (sex == 3 and "f-" or nil)
	if prefix and lengths[prefix .. fileName] then
		fileName = prefix .. fileName
	elseif not lengths[fileName] then
		if lengths["m-" .. fileName] then
			fileName = "m-" .. fileName
		elseif lengths["f-" .. fileName] then
			fileName = "f-" .. fileName
		else
			return nil
		end
	end
	return string.format("Interface\\AddOns\\%s\\generated\\sounds\\%s\\%s.mp3", pack.name, folder, fileName), lengths[fileName], fileName
end

local function FirstWords(text, n)
	local words = {}
	for word in text:gmatch("%S+") do
		words[#words + 1] = word
		if #words >= n then break end
	end
	return table.concat(words, " ")
end

local function LastWords(text, n)
	local words = {}
	for word in text:gmatch("%S+") do
		words[#words + 1] = word
	end
	return table.concat(words, " ", math.max(1, #words - n + 1), #words)
end

local function Unquote(text)
	return (text:gsub('"', "'"))
end

-- Quest ID from the client, or from the packs' title / NPC / text tables
-- when the client reports none.
local function ResolveQuestID(kind, npc, title, text, tablesOnly)
	if GetQuestID and not tablesOnly then
		local ok, id = pcall(GetQuestID)
		id = ok and PlainNumber(id) or nil
		if id and id > 0 then
			return id
		end
	end
	if type(title) ~= "string" or type(text) ~= "string" or IsSecret(text) then
		return nil
	end
	local cleanTitle = Unquote(title)
	local cleanName = Unquote(npc and npc.name or "")
	local cleanText = Unquote(FirstWords(text, 15)) .. " " .. Unquote(LastWords(text, 15))
	for _, pack in ipairs(packs) do
		local lookup = pack.data.QuestIDLookup and pack.data.QuestIDLookup[kind]
		local byTitle = lookup and lookup[cleanTitle]
		if type(byTitle) == "number" then
			return byTitle
		elseif type(byTitle) == "table" then
			local byNPC = byTitle[cleanName]
			if type(byNPC) == "number" then
				return byNPC
			elseif type(byNPC) == "table" then
				local id = BestMatch(cleanText, byNPC, 0.3)
				if id then return id end
			end
		end
	end
	return nil
end

-- Recorded file for a quest line: path, length in seconds.
local function PackQuestLine(kind, npc, title, text, questID)
	questID = questID or ResolveQuestID(kind, npc, title, text)
	if not questID then
		Trace("%s %q: no quest ID from the client or the pack tables", kind, tostring(title))
		return nil
	end
	for _, pack in ipairs(packs) do
		local path, length, name = PackFile(pack, kind, questID .. "-" .. kind)
		if path then
			Trace("%s %q: quest %d, recorded", kind, tostring(title), questID)
			return path, length, name
		end
	end
	-- Forever gave some vanilla quests new IDs (Chief Engineer Scooty 2842 ->
	-- 80133, the Zandalar enchant quests, ...) with the old words: look the
	-- title / NPC / text up in the pack tables and take the old recording
	-- when that names a different quest with a file. A Forever recording
	-- under the new ID (above) always wins.
	local old = ResolveQuestID(kind, npc, title, text, true)
	if old and old ~= questID then
		for _, pack in ipairs(packs) do
			local path, length, name = PackFile(pack, kind, old .. "-" .. kind)
			if path then
				Trace("%s %q: quest %d has no file; recorded as quest %d (same title)", kind, tostring(title), questID, old)
				return path, length, name
			end
		end
	end
	Trace("%s %q: quest %d has no %s recording in the pack", kind, tostring(title), questID, kind)
	return nil
end

-- Recorded file for a greeting: path, length in seconds.
local function PackGossipLine(npc, text)
	if type(text) ~= "string" or IsSecret(text) or not npc then
		return nil
	end
	local who = string.format("%s (%s)", tostring(npc.name), tostring(npc.id))
	local found = false
	for _, pack in ipairs(packs) do
		local entries
		if npc.id and pack.data.GossipLookupByNPCID then
			entries = pack.data.GossipLookupByNPCID[npc.id]
		end
		if not entries and npc.name and pack.data.GossipLookupByNPCName then
			entries = pack.data.GossipLookupByNPCName[Unquote(npc.name)]
		end
		if entries then
			found = true
			local hash, score = BestMatch(text, entries, 0.4)
			if hash then
				local path, length, name = PackFile(pack, "gossip", hash)
				if path then
					Trace("greeting from %s: matched %d%%, recorded", who, math.floor(score * 100 + 0.5))
					return path, length, nil, name
				end
				Trace("greeting from %s: matched %d%% but the file is missing", who, math.floor(score * 100 + 0.5))
			else
				local _, best = BestMatch(text, entries, 0)
				local onlyHash, count = nil, 0
				for _, h in pairs(entries) do
					onlyHash = h
					count = count + 1
				end
				if M.db.preferRecordings and count == 1 then
					local path, length, name = PackFile(pack, "gossip", onlyHash)
					if path then
						Trace("greeting from %s: text differs (%d%% match) but Prefer Recordings plays the NPC's only recording", who, math.floor((best or 0) * 100 + 0.5))
						return path, length, true, name
					end
				end
				Trace("greeting from %s: best match only %d%%, below the 40%% needed", who, math.floor((best or 0) * 100 + 0.5))
			end
		end
	end
	if not found then
		Trace("greeting from %s: NPC has no recorded greetings in the pack", who)
	end
	return nil
end

local function StopFile()
	if activeHandle then
		pcall(StopSound, activeHandle)
		activeHandle = nil
	end
end

--------------------------------------------------------------------------------
-- Line collector
--
-- Records the dialog lines seen in play into the MelloUIVoiceLines saved
-- variable so Tools\export_voice_lines.py can build the list of lines that
-- need recording for a Forever sound pack. On this beta the client writes
-- the file on /reload but never reads it back, so the export script merges
-- each session into its own store.
--------------------------------------------------------------------------------

local KINDS = {
	gossip   = { label = "Greeting",       bullet = "SoundQueueBulletGossip",   quest = false },
	accept   = { label = "Quest offer",    bullet = "SoundQueueBulletAccept",   quest = true },
	progress = { label = "Quest progress", bullet = "SoundQueueBulletProgress", quest = true },
	complete = { label = "Quest turn-in",  bullet = "SoundQueueBulletComplete", quest = true },
	objectives = { label = "Objectives",   bullet = "SoundQueueBulletProgress", quest = true, log = true },
}

local function PlainUnitValue(fn, unit)
	local ok, value = pcall(fn, unit)
	if ok and type(value) == "string" and not IsSecret(value) and value ~= "" then
		return value
	end
	return nil
end

local function Collected()
	if type(MelloUIVoiceLines) ~= "table" then
		MelloUIVoiceLines = {}
	end
	local store = MelloUIVoiceLines
	store.quests = store.quests or {}
	store.gossip = store.gossip or {}
	store.npcs = store.npcs or {}
	store.build = select(2, GetBuildInfo())
	store.player = store.player or {
		name = PlainUnitValue(UnitName, "player"),
		class = PlainUnitValue(UnitClass, "player"),
		race = PlainUnitValue(UnitRace, "player"),
	}
	return store
end

-- Put the placeholders back that the server filled in ($n name, $c class,
-- $r race), so the stored text is the same for every character and the
-- recording can say "adventurer" instead of one player's name.
local function Placeholdered(text, player)
	if type(text) ~= "string" or not player then
		return text
	end
	local function Swap(value, placeholder)
		if type(value) ~= "string" or value == "" then
			return
		end
		local pattern = "%f[%w]" .. value:gsub("%p", "%%%0") .. "%f[%W]"
		text = text:gsub(pattern, placeholder)
		local lower = value:lower()
		if lower ~= value then
			text = text:gsub("%f[%w]" .. lower:gsub("%p", "%%%0") .. "%f[%W]", placeholder)
		end
	end
	Swap(player.name, "$n")
	Swap(player.class, "$c")
	Swap(player.race, "$r")
	return text
end

local function CollectNPC(store, npc)
	if not npc or not npc.id then
		return
	end
	local rec = store.npcs[npc.id] or {}
	rec.name = npc.name or rec.name
	rec.gender = npc.gender or rec.gender
	rec.race = npc.race or rec.race
	rec.source = npc.source or rec.source
	if npc.unit then
		local ok, creatureType = pcall(UnitCreatureType, npc.unit)
		if ok and type(creatureType) == "string" and not IsSecret(creatureType) then
			rec.type = creatureType
		end
	end
	-- Where we are standing while talking is, near enough, where the NPC is:
	-- the quest list uses it as the pick-up location for NPCs no database knows.
	if not npc.remote and C_Map and C_Map.GetBestMapForUnit and C_Map.GetPlayerMapPosition then
		local okMap, mapID = pcall(C_Map.GetBestMapForUnit, "player")
		if okMap and IsPlainNumber(mapID) then
			local okPos, pos = pcall(C_Map.GetPlayerMapPosition, mapID, "player")
			if okPos and pos then
				local okXY, x, y = pcall(pos.GetXY, pos)
				if okXY and IsPlainNumber(x) and IsPlainNumber(y) then
					local okInfo, info = pcall(C_Map.GetMapInfo, mapID)
					rec.map = mapID
					rec.mapName = okInfo and info and not IsSecret(info.name) and info.name or rec.mapName
					rec.x = math.floor(x * 1000 + 0.5) / 10
					rec.y = math.floor(y * 1000 + 0.5) / 10
				end
			end
		end
	end
	store.npcs[npc.id] = rec
end

local unsavedLines = 0

local function CollectLine(entry, questID)
	if not M.db.collectLines or entry.secret or type(entry.text) ~= "string" then
		return
	end
	local store = Collected()
	local npc = entry.npc
	CollectNPC(store, npc)
	local info = KINDS[entry.kind] or KINDS.gossip
	local text = Placeholdered(entry.text, store.player)
	local rec = {
		text = text,
		npc = npc and npc.name or nil,
		npcID = npc and npc.id or nil,
		-- A recording with the right words played, from any pack. (The merged
		-- MelloUI_VoiceOverData pack carries the vanilla lines too, so the old
		-- "not our own pack" rule marked every recorded line as missing and
		-- nagged about new lines that had a recording.) "file" is the
		-- recording's name, so Tools/export_voice_lines.py can tell a line
		-- served by another quest's file (a renumbered quest) from a new one.
		recorded = entry.file ~= nil and not entry.mismatch,
		file = (entry.file ~= nil and not entry.mismatch) and entry.fileName or nil,
		seen = date("%Y-%m-%d"),
	}
	local isNew
	if info.quest then
		local key = questID and tostring(questID) or ("title:" .. tostring(entry.title))
		store.quests[key] = store.quests[key] or {}
		rec.title = entry.title
		isNew = store.quests[key][entry.kind] == nil
		store.quests[key][entry.kind] = rec
	else
		local id = npc and npc.id or 0
		store.gossip[id] = store.gossip[id] or {}
		isNew = store.gossip[id][text] == nil
		store.gossip[id][text] = rec
	end
	-- Lines only reach the disk on /reload; nudge now and then.
	if isNew and not rec.recorded then
		unsavedLines = unsavedLines + 1
		if unsavedLines % 5 == 0 then
			MelloUI:Notice("Voice Over: %d new lines without a recording collected. /reload writes them out for the generator.", unsavedLines)
		end
	end
end

--------------------------------------------------------------------------------
-- Speech queue
--
-- Lines are queued and read one after another, like the VoiceOver addon:
-- a greeting is not cut off by the quest that follows it. The queue advances
-- on the client's playback finished event, with an estimated duration as a
-- fallback in case the event never arrives.
--------------------------------------------------------------------------------

local queue = {}          -- waiting entries
local current = nil       -- entry being spoken
local paused = false
local entryCounter = 0
local finishTimer = nil
local failedWarned = false
local Overlay             -- forward declaration, defined below

local function TexturePath(name)
	return "Interface\\AddOns\\" .. ADDON_NAME .. "\\Media\\Textures\\VoiceOver\\" .. name
end

local function CancelFinishTimer()
	if finishTimer then
		finishTimer:Cancel()
		finishTimer = nil
	end
end

local function StopEngine()
	StopFile()
	if HasTTS() and C_VoiceChat.StopSpeakingText then
		pcall(C_VoiceChat.StopSpeakingText)
	end
end

-- Rough reading time so the queue still moves if no finished event comes.
local function EstimateSeconds(text, rate)
	local words = 12
	if type(text) == "string" and not IsSecret(text) then
		words = select(2, text:gsub("%S+", ""))
	end
	local perSecond = 2.3 * (1 + (rate or 0) * 0.06)
	return math.max(3, words / perSecond + 3)
end

-- Send one entry to the speech engine, or play its recorded file. Returns
-- true if it started.
local function SpeakEntry(entry)
	if entry.file then
		StopEngine()
		local ok, willPlay, handle = pcall(PlaySoundFile, entry.file, M.db.soundChannel or "Master")
		if ok and willPlay then
			activeHandle = handle
			return true
		end
		-- File missing or channel muted: fall back to speech.
		entry.file = nil
		entry.length = nil
	end
	local npc = entry.npc
	local race = npc and npc.race or nil
	local female = npc and npc.female or false
	local voiceID = PickVoice(race, female)
	if voiceID == nil then
		if not failedWarned then
			failedWarned = true
			MelloUI:Print("Voice Over: no text-to-speech voices installed. Add voices in Windows speech settings.")
		end
		return false
	end
	local pitch, rate = VoiceShape(race)
	local text = entry.text
	-- Pitch is only reachable through the speech engine's XML tags, which
	-- means the text has to be escaped; secret text cannot be, so it is read
	-- at the voice's natural pitch.
	if pitch ~= 0 and not entry.secret then
		text = string.format('<pitch absmiddle="%d"/>%s', pitch, EscapeXML(text))
	end
	StopEngine()
	local volume = tonumber(M.db.volume) or 100
	local ok = pcall(C_VoiceChat.SpeakText, voiceID, text, rate, volume, false)
	return ok
end

local PlayNext

local function OnFinished(entry)
	if entry ~= current then
		return
	end
	CancelFinishTimer()
	current = nil
	if not paused then
		PlayNext()
	end
	Overlay:Update()
end

local function StartEntry(entry)
	current = entry
	entry.startedAt = GetTime()
	CancelFinishTimer()
	if not SpeakEntry(entry) then
		current = nil
		return false
	end
	local seconds
	if entry.file and entry.length then
		seconds = entry.length + 0.5
	else
		local _, rate = VoiceShape(entry.npc and entry.npc.race or nil)
		seconds = EstimateSeconds(entry.text, rate)
	end
	entry.expected = seconds
	finishTimer = C_Timer.NewTimer(seconds, function()
		finishTimer = nil
		OnFinished(entry)
	end)
	return true
end

PlayNext = function()
	while not current and #queue > 0 do
		local entry = table.remove(queue, 1)
		if StartEntry(entry) then
			break
		end
	end
end

local function IsPlaying()
	return current ~= nil and not paused
end

local function Stop()
	CancelFinishTimer()
	wipe(queue)
	current = nil
	StopEngine()
	Overlay:Update()
end

local function Skip(entry)
	if entry == current then
		CancelFinishTimer()
		current = nil
		StopEngine()
		if not paused then
			PlayNext()
		end
	else
		for i, queued in ipairs(queue) do
			if queued == entry then
				table.remove(queue, i)
				break
			end
		end
	end
	Overlay:Update()
end

local function SetPaused(state)
	if paused == state then
		return
	end
	paused = state
	if paused then
		CancelFinishTimer()
		StopEngine()
	else
		if current then
			-- Text-to-speech cannot resume mid sentence; the line restarts.
			StartEntry(current)
		else
			PlayNext()
		end
	end
	Overlay:Update()
end

local function TogglePaused()
	SetPaused(not paused)
end

-- Queue a line. npc is a table from DescribeNPC (or nil), kind a KINDS key.
-- matchText, when given, is the text the pack lookups compare (the quest
-- description alone when the objectives are read after it).
local function Enqueue(text, npc, kind, title, questID, matchText)
	if not HasTTS() then
		return
	end
	text = CleanText(text)
	if text == nil then
		return
	end
	local secret = IsSecret(text)
	if not secret then
		if text == "" then
			return
		end
		-- The same window can fire its event twice (e.g. QUEST_DETAIL on
		-- refresh); do not queue identical text again.
		if current and current.text == text then
			return
		end
		for _, entry in ipairs(queue) do
			if entry.text == text then
				return
			end
		end
	end
	local info = KINDS[kind] or KINDS.gossip
	if M.db.queueLines then
		-- A greeting never waits behind a quest line (the player has already
		-- moved on to the quest).
		if not info.quest then
			if current and KINDS[current.kind].quest then
				return
			end
			for _, entry in ipairs(queue) do
				if KINDS[entry.kind].quest then
					return
				end
			end
		end
	else
		CancelFinishTimer()
		wipe(queue)
		current = nil
	end
	entryCounter = entryCounter + 1
	local entry = {
		id = entryCounter,
		text = text,
		secret = secret,
		npc = npc,
		kind = kind,
		title = title or info.label,
		name = npc and npc.name or nil,
	}
	if M.db.soundPacks and not info.log then
		-- The pack tables also resolve quest IDs the client does not give.
		LoadSoundPacks()
	end
	matchText = matchText or text
	if info.quest and not questID then
		questID = ResolveQuestID(kind, npc, title, matchText)
	end
	entry.questID = questID
	if M.db.soundPacks and not info.log and #packs > 0 then
		local path, length, mismatch, fileName
		if info.quest then
			path, length, fileName = PackQuestLine(kind, npc, title, matchText, questID)
		else
			path, length, mismatch, fileName = PackGossipLine(npc, text)
		end
		entry.file = path
		entry.length = length
		entry.mismatch = mismatch or nil
		entry.fileName = fileName
	end
	if not info.log then
		CollectLine(entry, questID)
	end
	queue[#queue + 1] = entry
	if not current and not paused then
		PlayNext()
	end
	Overlay:Update()
end

-- Speak a line straight away outside the queue (settings samples).
local function SpeakSample(text, npc)
	if not HasTTS() then
		return
	end
	CancelFinishTimer()
	current = nil
	SpeakEntry({ text = text, secret = false, npc = npc })
	Overlay:Update()
end

--------------------------------------------------------------------------------
-- Overlay
--
-- A movable frame with the speaking NPC's 3D portrait (playing its talk
-- animation), the NPC name, the line being read and the lines waiting.
-- Layout and textures follow the VoiceOver addon (MIT licence).
--------------------------------------------------------------------------------

-- The window is one picture (Media/Textures/VoiceOver/ScrollFrame.tga, made
-- from docs/voiceover-frame.webp): a dark square on the left holding the
-- model, a parchment scroll on the right holding the text. The areas were
-- measured on the 2000 x 668 art and scaled to FRAME_W.
local FRAME_W, FRAME_H = 600, 200
local ART_SCALE = FRAME_W / 2000
local TEX_BOTTOM = 342 / 512     -- the art fills the top 342 rows of the 1024 x 512 texture
local PORTRAIT_X, PORTRAIT_Y = 118 * ART_SCALE, 78 * ART_SCALE
local PORTRAIT_SIZE = (640 - 118) * ART_SCALE
local PARCHMENT_LEFT, PARCHMENT_RIGHT = 720 * ART_SCALE, 1860 * ART_SCALE
local ATLAS = 512
local ATLAS_BORDER = 416
local ATLAS_VIEWPORT = 348
local BORDER_SCALE = PORTRAIT_SIZE / ATLAS_VIEWPORT
local BORDER_OUTSET = 34 * BORDER_SCALE
local LINE_WIDTH = 56 * BORDER_SCALE
local MAX_LINES = 4
local TALK_ANIMATION = 60
local VALID_POINTS = {
	TOPLEFT = true, TOP = true, TOPRIGHT = true, LEFT = true, CENTER = true,
	RIGHT = true, BOTTOMLEFT = true, BOTTOM = true, BOTTOMRIGHT = true,
}

-- Talk animation length in seconds by model file ID (from the VoiceOver
-- addon). Models not listed loop every two seconds.
local TALK_DURATION = {
	[116921] = 4.0, [1100258] = 4.0, [117170] = 2.0, [1100087] = 2.0,
	[117437] = 3.0, [1022598] = 3.0, [117721] = 3.334, [1005887] = 3.334,
	[118135] = 2.0, [950080] = 2.0, [118355] = 2.0, [878772] = 2.0,
	[119063] = 4.0, [940356] = 4.0, [119159] = 4.0, [900914] = 4.0,
	[119369] = 1.8, [119376] = 1.8,
	[119563] = 2.667, [1000764] = 2.667, [119940] = 2.0, [1011653] = 2.0,
	[120263] = 3.0, [120294] = 3.0,
	[120590] = 2.1, [921844] = 2.1, [120791] = 2.0, [974343] = 2.0,
	[121087] = 2.0, [949470] = 2.0, [121287] = 2.0, [917116] = 2.0,
	[121608] = 2.0, [997378] = 2.467, [121768] = 2.667, [959310] = 2.667,
	[121942] = 2.667, [121961] = 2.934, [986648] = 2.934, [122055] = 2.934, [968705] = 2.934,
	[122414] = 2.5, [1018060] = 2.5, [122560] = 2.5, [1022938] = 2.5,
}

Overlay = { lines = {} }

local nameFont, lineFont, subtitleFont

local function EnsureFonts()
	if nameFont then
		return
	end
	local path = GameFontNormal:GetFont()
	nameFont = CreateFont("MelloUIVoiceOverNameFont")
	nameFont:SetFont(path, 19, "")
	nameFont:SetShadowColor(1, 0.95, 0.8, 0.35)
	nameFont:SetShadowOffset(1, -1)
	nameFont:SetJustifyH("LEFT")
	lineFont = CreateFont("MelloUIVoiceOverLineFont")
	lineFont:SetFont(path, 16, "")
	lineFont:SetShadowOffset(0, 0)
	lineFont:SetJustifyH("LEFT")
	subtitleFont = CreateFont("MelloUIVoiceOverSubtitleFont")
	subtitleFont:SetFont(path, 12, "")
	subtitleFont:SetShadowOffset(0, 0)
	subtitleFont:SetJustifyH("LEFT")
	subtitleFont:SetJustifyV("TOP")
end

local function SetAtlasTexture(texture, left, right, top, bottom)
	texture:SetTexture(TexturePath("PortraitFrameAtlas"))
	texture:SetTexCoord(left / ATLAS, right / ATLAS, top / ATLAS, bottom / ATLAS)
end

function Overlay:SavePosition()
	local frame = self.frame
	local point, _, relativePoint, x, y = frame:GetPoint(1)
	if point then
		M.db.overlayPoint = point
		M.db.overlayRelativePoint = relativePoint
		M.db.overlayX = math.floor(x + 0.5)
		M.db.overlayY = math.floor(y + 0.5)
	end
end

function Overlay:RestorePosition()
	local frame = self.frame
	frame:ClearAllPoints()
	-- Settings can come back from the macro backup with stray whitespace;
	-- only accept a clean anchor name.
	local function Anchor(value)
		if type(value) ~= "string" then
			return nil
		end
		value = value:gsub("%s+", ""):upper()
		if VALID_POINTS[value] then
			return value
		end
		return nil
	end
	local point = Anchor(M.db.overlayPoint)
	if point then
		frame:SetPoint(point, UIParent, Anchor(M.db.overlayRelativePoint) or point, tonumber(M.db.overlayX) or 0, tonumber(M.db.overlayY) or 0)
	else
		frame:SetPoint("BOTTOM", UIParent, "BOTTOM", 0, 200)
	end
end

function Overlay:ResetPosition()
	M.db.overlayPoint = nil
	M.db.overlayRelativePoint = nil
	M.db.overlayX = nil
	M.db.overlayY = nil
	if self.frame then
		self:RestorePosition()
	end
end

-- Let any widget of the overlay drag the whole frame.
local function AttachDrag(widget)
	widget:RegisterForDrag("LeftButton")
	widget:SetScript("OnDragStart", function()
		if not M.db.overlayLock then
			Overlay.frame:StartMoving()
		end
	end)
	widget:SetScript("OnDragStop", function()
		Overlay.frame:StopMovingOrSizing()
		Overlay:SavePosition()
	end)
end

-- Frame the head and shoulders. The custom camera used by the VoiceOver
-- addon shows the legs on this client, so the portrait zoom is used instead.
local function AimCamera(model)
	pcall(model.SetPortraitZoom, model, 0.85)
	pcall(model.SetPosition, model, 0, 0, 0)
	pcall(model.SetRotation, model, 0)
end

function Overlay:CreatePortrait()
	local frame = self.frame
	local portrait = CreateFrame("Frame", nil, frame)
	portrait:SetPoint("TOPLEFT", PORTRAIT_X, -PORTRAIT_Y)
	portrait:SetSize(PORTRAIT_SIZE, PORTRAIT_SIZE)
	frame.portrait = portrait

	local model = CreateFrame("DressUpModel", nil, portrait)
	model:SetAllPoints()
	portrait.model = model
	model.creatureID = nil
	model:SetScript("OnHide", function(self)
		pcall(self.ClearModel, self)
		self.creatureID = nil
		self.loaded = nil
		self.retries = nil
		self.retryIn = nil
		self.animation = nil
		self.animStart = nil
	end)
	model:SetScript("OnUpdate", function(self, elapsed)
		if not self.creatureID then
			return
		end
		if not self.loaded then
			-- The creature may not be cached yet: ask again every half second,
			-- a few times, then leave whatever loaded alone.
			local ok, fileID = pcall(self.GetModelFileID, self)
			if ok and fileID then
				self.loaded = true
				self.fileID = fileID
				AimCamera(self)
			else
				self.retryIn = (self.retryIn or 0.5) - elapsed
				if self.retryIn > 0 then
					return
				end
				self.retryIn = 0.5
				self.retries = (self.retries or 0) + 1
				if self.retries <= 8 then
					pcall(self.SetCreature, self, self.creatureID)
					AimCamera(self)
					return
				end
				self.loaded = true
			end
		end
		local playing = IsPlaying()
		local now = GetTime()
		local duration = TALK_DURATION[self.fileID or 0] or 2
		if playing then
			if self.animation ~= TALK_ANIMATION or now - (self.animStart or 0) >= duration then
				self.animation = TALK_ANIMATION
				self.animStart = now
				pcall(self.SetAnimation, self, TALK_ANIMATION)
			end
		elseif self.animation ~= 0 and now - (self.animStart or 0) >= duration then
			-- Let the current talk cycle finish, then go idle.
			self.animation = 0
			self.animStart = now
			pcall(self.SetAnimation, self, 0)
		end
	end)

	-- Book icon for NPCs whose model cannot be shown.
	portrait.book = portrait:CreateTexture(nil, "ARTWORK")
	portrait.book:SetAllPoints()
	portrait.book:SetTexture(TexturePath("Book"))
	portrait.book:SetTexCoord(8 / 256, 248 / 256, 8 / 256, 248 / 256)
	portrait.book:Hide()

	-- Pause button over the model; its background dims the model while paused.
	local pause = CreateFrame("Button", nil, portrait)
	pause:SetFrameLevel(model:GetFrameLevel() + 1)
	pause:SetAllPoints()
	pause.background = pause:CreateTexture(nil, "BACKGROUND")
	pause.background:SetAllPoints()
	pause.background:SetTexture(TexturePath("PortraitFrameBackground"))
	pause.background:SetAlpha(0.75)
	pause:SetNormalTexture(TexturePath("PortraitFrameAtlas"))
	pause:GetNormalTexture():ClearAllPoints()
	pause:GetNormalTexture():SetPoint("CENTER")
	pause:GetNormalTexture():SetSize(32, 32)
	pause:SetPushedTexture(TexturePath("PortraitFrameAtlas"))
	pause:GetPushedTexture():ClearAllPoints()
	pause:GetPushedTexture():SetPoint("CENTER")
	pause:GetPushedTexture():SetSize(28, 28)
	function pause:Update()
		local hovered = self:IsMouseOver()
		if paused then
			self.background:SetShown(true)
			SetAtlasTexture(self:GetNormalTexture(), 0, 93, 419, 512)
			SetAtlasTexture(self:GetPushedTexture(), 0, 93, 419, 512)
			self:GetNormalTexture():SetAlpha(hovered and 1 or 0.75)
		else
			self.background:Hide()
			SetAtlasTexture(self:GetNormalTexture(), 93, 186, 419, 512)
			SetAtlasTexture(self:GetPushedTexture(), 93, 186, 419, 512)
			self:GetNormalTexture():SetAlpha(hovered and 1 or 0)
		end
	end
	pause:SetScript("OnEnter", function(self)
		self:GetNormalTexture():SetAlpha(1)
		GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
		GameTooltip:SetText(paused and "Resume" or "Pause")
		GameTooltip:Show()
	end)
	pause:SetScript("OnLeave", function(self)
		self:GetNormalTexture():SetAlpha(paused and 0.75 or 0)
		GameTooltip:Hide()
	end)
	pause:SetScript("OnClick", function()
		PlaySound(SOUNDKIT.U_CHAT_SCROLL_BUTTON)
		TogglePaused()
	end)
	AttachDrag(pause)
	portrait.pause = pause

	-- The art draws the frame around the square; nothing above the model.
	local border = CreateFrame("Frame", nil, portrait)
	border:SetFrameLevel(pause:GetFrameLevel() + 1)
	border:SetAllPoints()
	portrait.border = border

	-- Thin line and mini pause button used when the portrait is hidden.
	frame.portraitLine = frame:CreateTexture(nil, "BORDER")
	frame.portraitLine:SetPoint("TOPLEFT", -LINE_WIDTH / 2 + 2, BORDER_OUTSET)
	frame.portraitLine:SetPoint("BOTTOMRIGHT", frame, "BOTTOMLEFT", LINE_WIDTH / 2 + 2, -BORDER_OUTSET)
	SetAtlasTexture(frame.portraitLine, 456, 512, 0, ATLAS_BORDER)

	local mini = CreateFrame("Button", nil, frame)
	mini:SetSize(26, 26)
	mini:SetNormalTexture(TexturePath("PortraitFrameAtlas"))
	mini:GetNormalTexture():ClearAllPoints()
	mini:GetNormalTexture():SetPoint("CENTER")
	mini:GetNormalTexture():SetSize(14, 14)
	mini:SetPushedTexture(TexturePath("PortraitFrameAtlas"))
	mini:GetPushedTexture():ClearAllPoints()
	mini:GetPushedTexture():SetPoint("CENTER")
	mini:GetPushedTexture():SetSize(12, 12)
	mini.background = mini:CreateTexture(nil, "BACKGROUND")
	mini.background:SetTexture(TexturePath("SettingsButton"))
	mini.background:SetPoint("CENTER")
	mini.background:SetSize(32, 32)
	function mini:Update()
		if paused then
			SetAtlasTexture(self:GetNormalTexture(), 0, 93, 419, 512)
			SetAtlasTexture(self:GetPushedTexture(), 0, 93, 419, 512)
		else
			SetAtlasTexture(self:GetNormalTexture(), 93, 186, 419, 512)
			SetAtlasTexture(self:GetPushedTexture(), 93, 186, 419, 512)
		end
		self:GetNormalTexture():SetAlpha(self:IsMouseOver() and 1 or 0.75)
	end
	mini:SetScript("OnEnter", function(self) self:GetNormalTexture():SetAlpha(1) end)
	mini:SetScript("OnLeave", function(self) self:GetNormalTexture():SetAlpha(0.75) end)
	mini:SetScript("OnClick", function()
		PlaySound(SOUNDKIT.U_CHAT_SCROLL_BUTTON)
		TogglePaused()
	end)
	AttachDrag(mini)
	frame.miniPause = mini
end

function Overlay:ConfigurePortrait(entry)
	local portrait = self.frame.portrait
	if not portrait:IsShown() then
		return
	end
	local model = portrait.model
	local npcID = entry and entry.npc and entry.npc.id or nil
	if not npcID then
		model:Hide()
		portrait.book:SetShown(entry ~= nil)
		return
	end
	portrait.book:Hide()
	model:Show()
	if model.creatureID ~= npcID then
		pcall(model.ClearModel, model)
		model.creatureID = npcID
		model.loaded = nil
		model.retries = nil
		model.retryIn = nil
		model.fileID = nil
		model.animation = nil
		model.animStart = nil
		pcall(model.SetCreature, model, npcID)
		AimCamera(model)
	end
end

function Overlay:CreateLine(index)
	local container = self.frame.container
	local button = CreateFrame("Button", nil, container)
	button:SetHeight(20)
	button.index = index
	button.text = button:CreateFontString(nil, "OVERLAY", "MelloUIVoiceOverLineFont")
	button.text:SetWordWrap(false)
	button.icon = button:CreateTexture(nil, "ARTWORK")
	button.icon:SetSize(16, 16)
	button.icon:SetPoint("CENTER", button, "LEFT", 8, 0)
	button:SetScript("OnClick", function(self)
		if self.entry then
			PlaySound(SOUNDKIT.U_CHAT_SCROLL_BUTTON)
			Skip(self.entry)
		end
	end)
	AttachDrag(button)
	button:SetScript("OnEnter", function(self)
		self.hovered = true
		self:Refresh()
		GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
		GameTooltip:SetText(self.entry == current and "Skip this line" or "Remove from queue")
		GameTooltip:Show()
	end)
	button:SetScript("OnLeave", function(self)
		self.hovered = false
		self:Refresh()
		GameTooltip:Hide()
	end)
	function button:Refresh()
		local entry = self.entry
		if not entry then
			self:Hide()
			return
		end
		self:Show()
		local info = KINDS[entry.kind] or KINDS.gossip
		local isCurrent = entry == current
		local anchor = self.index == 1 and container.name or container.lines[self.index - 1]
		self:ClearAllPoints()
		if isCurrent then
			self:SetAlpha(1)
			self:SetPoint("TOPLEFT", anchor, "BOTTOMLEFT", 0, -2)
		else
			local position = self.index - (current and 1 or 0)
			self:SetAlpha(math.max(0.1, math.min(1, 1 - (position - 1) / 3)))
			self:SetPoint("TOPLEFT", anchor, "BOTTOMLEFT", 0, position == 1 and -8 or -2)
		end
		self.text:ClearAllPoints()
		self.text:SetPoint("LEFT", 16 + 5, 0)
		self.text:SetText(entry.title)
		local width = container:GetWidth()
		self:SetWidth(math.min(width, 16 + 5 + self.text:GetStringWidth() + 1))
		self.text:SetPoint("RIGHT")
		if self.hovered then
			self:SetAlpha(1)
			self.text:SetTextColor(0.62, 0.10, 0.04)
			self.icon:SetTexture(TexturePath("SoundQueueBulletDelete"))
			self.icon:SetSize(14, 14)
		elseif isCurrent then
			if info.quest then
				self.text:SetTextColor(0.55, 0.36, 0.03)
			else
				self.text:SetTextColor(0.22, 0.13, 0.05)
			end
			self.icon:SetTexture(TexturePath(info.bullet))
			self.icon:SetSize(14, 14)
		else
			self.text:SetTextColor(0.45, 0.36, 0.26)
			self.icon:SetTexture(TexturePath("SoundQueueBulletQueue"))
			self.icon:SetSize(22, 22)
		end
	end
	container.lines[index] = button
	return button
end

function Overlay:Create()
	if self.frame then
		return
	end
	EnsureFonts()
	local frame = CreateFrame("Frame", "MelloUIVoiceOverFrame", UIParent)
	self.frame = frame
	frame:SetSize(FRAME_W, FRAME_H)
	frame:SetFrameStrata("MEDIUM")
	frame:SetMovable(true)
	frame:SetClampedToScreen(true)
	frame:EnableMouse(true)
	AttachDrag(frame)
	frame:SetScript("OnEnter", function(self)
		if M.db.overlayLock then
			return
		end
		GameTooltip:SetOwner(self, "ANCHOR_TOP")
		GameTooltip:SetText("Voice Over")
		GameTooltip:AddLine("Drag to move. The padlock in the corner locks the position.", 1, 1, 1, true)
		GameTooltip:Show()
	end)
	frame:SetScript("OnLeave", function() GameTooltip:Hide() end)
	frame:Hide()

	frame.background = frame:CreateTexture(nil, "BACKGROUND")
	frame.background:SetAllPoints()
	frame.background:SetTexture(TexturePath("ScrollFrame"))
	frame.background:SetTexCoord(0, 1, 0, TEX_BOTTOM)

	-- The parchment as a sheet with painted edges (user, 2026-09-23: painted
	-- edges in more places, the voice-over window among them). The picture's
	-- own parchment is covered by a dark backing, and the same parchment,
	-- cut from the picture, lies on it with dry-brush strokes on every side
	-- (Kit:PaintedEdge), so the strokes show against the dark inside the iron
	-- frame and its gold trim, which stay as painted.
	local Kit = MelloUI.Kit
	if Kit and Kit.PaintedEdge then
		-- the parchment in the 1024 x 512 texture, and so in the window
		local u1, u2, v1, v2 = 352 / 1024, 982 / 1024, 58 / 512, 292 / 512
		local sx, sy = FRAME_W / 1024, FRAME_H / (TEX_BOTTOM * 512)
		local left, right = 352 * sx, 982 * sx
		local top, bottom = 58 * sy, 292 * sy
		local backing = frame:CreateTexture(nil, "BACKGROUND", nil, 1)
		backing:SetColorTexture(0.09, 0.07, 0.05, 1)
		backing:SetPoint("TOPLEFT", frame, "TOPLEFT", left, -top)
		backing:SetSize(right - left, bottom - top)
		local sheet = frame:CreateTexture(nil, "BACKGROUND", nil, 2)
		sheet:SetTexture(TexturePath("ScrollFrame"))
		sheet:SetTexCoord(u1, u2, v1, v2)
		-- in the kit's one parchment tone, as every other parchment
		local tint = Kit.parchmentTint
		if tint then
			sheet:SetVertexColor(tint[1], tint[2], tint[3])
		end
		sheet:SetAllPoints(backing)
		local edge = Kit:PaintedEdge(sheet, sheet, false, true)
		if edge then
			edge:Fit(right - left, bottom - top)
		else
			backing:Hide()
			sheet:Hide()
		end
	end

	self:CreatePortrait()

	local container = CreateFrame("Frame", nil, frame)
	container:SetPoint("LEFT", frame, "LEFT", PARCHMENT_LEFT, -1)
	container.lines = {}
	frame.container = container

	container.name = container:CreateFontString(nil, "ARTWORK", "MelloUIVoiceOverNameFont")
	container.name:SetPoint("TOPLEFT")
	container.name:SetWordWrap(false)
	container.name:SetTextColor(0.30, 0.17, 0.05)

	-- Stop / skip button next to the name.
	local stop = CreateFrame("Button", nil, container)
	stop:SetSize(32, 32)
	stop:SetPoint("BOTTOMLEFT", container.name, "RIGHT", -6, 0)
	stop:SetScript("OnEnter", function(self)
		GameTooltip:SetOwner(self, "ANCHOR_NONE")
		GameTooltip:SetPoint("LEFT", self, "RIGHT")
		GameTooltip:SetText(#queue > 0 and "Skip to next line" or "Stop")
		GameTooltip:Show()
	end)
	stop:SetScript("OnLeave", function() GameTooltip:Hide() end)
	stop:SetScript("OnClick", function()
		PlaySound(SOUNDKIT.U_CHAT_SCROLL_BUTTON)
		if current then
			Skip(current)
		else
			Stop()
		end
	end)
	function stop:Refresh()
		local texture = TexturePath(#queue > 0 and "StopGossipMore" or "StopGossip")
		self:SetNormalTexture(texture)
		self:SetPushedTexture(texture)
		self:SetHighlightTexture(texture, "ADD")
		self:GetPushedTexture():SetAlpha(0.5)
		self:GetHighlightTexture():SetAlpha(0.5)
	end
	stop:Refresh()
	AttachDrag(stop)
	container.stop = stop

	-- Padlock in the corner: locks and unlocks the window's position.
	local lock = CreateFrame("Button", nil, frame)
	lock:SetSize(26, 26)
	-- inside the parchment, top right
	lock:SetPoint("TOPRIGHT", frame, "TOPRIGHT", -(FRAME_W - PARCHMENT_RIGHT) - 2, -34)
	lock:SetFrameLevel(frame:GetFrameLevel() + 5)
	function lock:Refresh()
		local locked = M.db.overlayLock
		local texture = locked and "Interface/Buttons/LockButton-Locked-Up" or "Interface/Buttons/LockButton-Unlocked-Up"
		self:SetNormalTexture(texture)
		self:SetPushedTexture(locked and "Interface/Buttons/LockButton-Locked-Down" or "Interface/Buttons/LockButton-Unlocked-Down")
		self:SetHighlightTexture(texture, "ADD")
		self:GetHighlightTexture():SetAlpha(0.4)
		self:SetAlpha(locked and 0.55 or 0.9)
	end
	lock:SetScript("OnClick", function(self)
		M.db.overlayLock = not M.db.overlayLock
		MelloUI:NotifySettingChanged(M.name, "overlayLock", M.db.overlayLock)
		PlaySound(M.db.overlayLock and SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON or SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_OFF)
		self:Refresh()
		GameTooltip:Hide()
	end)
	lock:SetScript("OnEnter", function(self)
		GameTooltip:SetOwner(self, "ANCHOR_NONE")
		GameTooltip:SetPoint("LEFT", self, "RIGHT", 4, 0)
		GameTooltip:SetText(M.db.overlayLock and "Position locked" or "Position unlocked")
		GameTooltip:AddLine(M.db.overlayLock and "Click to unlock and drag the window." or "Drag the window to move it. Click to lock it in place.", 1, 1, 1, true)
		GameTooltip:Show()
	end)
	lock:SetScript("OnLeave", function() GameTooltip:Hide() end)
	lock:Refresh()
	frame.lock = lock

	container.subtitle = container:CreateFontString(nil, "ARTWORK", "MelloUIVoiceOverSubtitleFont")
	container.subtitle:SetWordWrap(true)
	container.subtitle:SetMaxLines(3)
	container.subtitle:SetTextColor(0.24, 0.14, 0.05)
	container.subtitle:Hide()
	-- each new page fades in (a quarter of a second, easing out) instead of
	-- jumping in: the reading eye follows it
	local fade = container.subtitle:CreateAnimationGroup()
	local alpha = fade:CreateAnimation("Alpha")
	alpha:SetFromAlpha(0)
	alpha:SetToAlpha(1)
	alpha:SetDuration(0.25)
	alpha:SetSmoothing("OUT")
	fade:SetToFinalAlpha(true)
	container.subtitle.fade = fade
	local pageAcc = 0
	container:SetScript("OnUpdate", function(_, elapsed)
		pageAcc = pageAcc + elapsed
		if pageAcc < 0.1 then
			return
		end
		pageAcc = 0
		if current and current.pages and #current.pages > 1 and container.subtitle:IsShown() and Overlay.SubtitlePage then
			if Overlay.SubtitlePage(current) ~= current.page then
				Overlay:Update()
			end
		end
	end)

	self:Apply()
end

-- Apply the overlay settings (portrait, lock, scale, position).
function Overlay:Apply()
	local frame = self.frame
	if not frame then
		return
	end
	if frame.lock then
		frame.lock:Refresh()
	end
	-- without the model the art's own emblem shows in the square
	frame.portrait:SetShown(M.db.overlayPortrait and true or false)
	frame.portraitLine:Hide()
	frame.miniPause:Hide()
	frame:SetScale(tonumber(M.db.overlayScale) or 1)
	self:RestorePosition()
	self:Update()
end

-- Split a line into pages that fit the subtitle's lines, sentence by
-- sentence (a single too-long sentence is split on words).
local function BuildPages(fs, text)
	if not fs.IsTruncated then
		return { text }
	end
	local function Fits(candidate)
		fs:SetText(candidate)
		return not fs:IsTruncated()
	end
	local function Pack(pieces)
		local pages, page = {}, ""
		for _, piece in ipairs(pieces) do
			local candidate = page == "" and piece or (page .. " " .. piece)
			if page ~= "" and not Fits(candidate) then
				pages[#pages + 1] = page
				page = piece
			else
				page = candidate
			end
		end
		if page ~= "" then
			pages[#pages + 1] = page
		end
		return pages
	end
	local sentences = {}
	for raw in text:gmatch("%s*([^%.!%?]+[%.!%?]*)") do
		local sentence = raw:gsub("^%s+", ""):gsub("%s+$", "")
		if sentence ~= "" then
			sentences[#sentences + 1] = sentence
		end
	end
	local pages = {}
	for _, page in ipairs(Pack(sentences)) do
		if Fits(page) then
			pages[#pages + 1] = page
		else
			local words = {}
			for word in page:gmatch("%S+") do
				words[#words + 1] = word
			end
			for _, part in ipairs(Pack(words)) do
				pages[#pages + 1] = part
			end
		end
	end
	return #pages > 0 and pages or { text }
end

-- How long a page takes to SAY, in letters: its own letters plus the pauses
-- the voice makes at its punctuation -- about half a second at a full stop,
-- a quarter at a comma, which at a speaking pace of some 14 letters a second
-- are 7 and 3 letters (user, 2026-09-23: "go ahead with the subtitle
-- pacing"). A page ending a sentence carries that sentence's pause, so the
-- next page comes up when the voice starts it again, not during the pause.
local STOP_PAUSE, COMMA_PAUSE = 7, 3

local function SpokenWeight(text)
	local _, stops = text:gsub("[%.!%?]+", "")
	local _, commas = text:gsub("[,;:]", "")
	return #text + stops * STOP_PAUSE + commas * COMMA_PAUSE
end

-- Which page the playback is on: the share of the clip played so far against
-- the pages' spoken weights. The clip's own length where it is known (a
-- recorded line), else the estimate the text-to-speech line was timed by.
local function SubtitlePage(entry)
	local pages = entry.pages
	if not pages or #pages <= 1 then
		return 1
	end
	if not entry.pageWeights then
		local weights, total = {}, 0
		for i, page in ipairs(pages) do
			weights[i] = SpokenWeight(page)
			total = total + weights[i]
		end
		entry.pageWeights, entry.pageTotal = weights, total
	end
	local length = entry.length or entry.expected
	local progress = 0
	if length and length > 0 and entry.startedAt and not paused then
		progress = (GetTime() - entry.startedAt) / length
	end
	local at, index = 0, 1
	for i, weight in ipairs(entry.pageWeights) do
		if progress >= at / entry.pageTotal then
			index = i
		end
		at = at + weight
	end
	return math.min(index, #pages)
end
Overlay.SubtitlePage = SubtitlePage

function Overlay:Update()
	local frame = self.frame
	if not frame then
		return
	end
	local visible = M.db.overlay and M.isEnabled and (current ~= nil or #queue > 0)
	frame:SetShown(visible)
	if not visible then
		return
	end
	frame.portrait.pause:Update()
	frame.miniPause:Update()
	self:ConfigurePortrait(current or queue[1])

	local container = frame.container
	container:SetHeight(frame:GetHeight())
	local head = current or queue[1]
	container.name:SetText(head and (head.name or "Unknown") or "")
	container.stop:Refresh()

	-- Lines: the current one first, then the queue.
	local shown = 0
	local function Place(entry)
		if shown >= MAX_LINES then
			return
		end
		shown = shown + 1
		local line = container.lines[shown] or self:CreateLine(shown)
		line.entry = entry
	end
	if current then
		Place(current)
	end
	for _, entry in ipairs(queue) do
		Place(entry)
	end
	for i = shown + 1, #container.lines do
		container.lines[i].entry = nil
	end

	local width = PARCHMENT_RIGHT - PARCHMENT_LEFT - 32   -- the padlock sits at the right edge
	container:SetWidth(width)
	container.name:SetWidth(0)
	container.name:SetWidth(math.min(width - 26, container.name:GetStringWidth() + 1))
	for _, line in ipairs(container.lines) do
		line:Refresh()
	end

	-- Optional subtitle with the text being read, under the lines.
	local last = container.lines[shown] or container.name
	if M.db.overlaySubtitles and current and not current.secret then
		container.subtitle:ClearAllPoints()
		container.subtitle:SetPoint("TOPLEFT", last, "BOTTOMLEFT", 0, -6)
		container.subtitle:SetWidth(width)
		if not current.pages or current.pagesWidth ~= width then
			current.pages = BuildPages(container.subtitle, current.text)
			current.pagesWidth = width
			current.pageWeights = nil
		end
		current.page = SubtitlePage(current)
		container.subtitle:SetText(current.pages[current.page] or current.text)
		container.subtitle:Show()
		-- a new line or a new page fades in; the same page redrawn stays put
		if container.subtitle.shownEntry ~= current or container.subtitle.shownPage ~= current.page then
			container.subtitle.shownEntry, container.subtitle.shownPage = current, current.page
			container.subtitle.fade:Stop()
			container.subtitle.fade:Play()
		end
		last = container.subtitle
	else
		container.subtitle:Hide()
	end

	-- Centre the content vertically.
	local top = container.name:GetTop()
	local bottom = last:GetBottom()
	if top and bottom then
		container:SetHeight(math.max(20, top - bottom))
	end
end

--------------------------------------------------------------------------------
-- Dialog events
--------------------------------------------------------------------------------

local function PlainString(value)
	if type(value) == "string" and not IsSecret(value) then
		return value
	end
	return nil
end

local function QuestTitle()
	if GetTitleText then
		local ok, title = pcall(GetTitleText)
		if ok then
			return PlainString(title)
		end
	end
	return nil
end

local function GossipText()
	if C_GossipInfo and C_GossipInfo.GetText then
		local ok, text = pcall(C_GossipInfo.GetText)
		if ok then
			return text
		end
	end
	if GetGossipText then
		return GetGossipText()
	end
end

--------------------------------------------------------------------------------
-- Quest panels: read once the client has filled them in
--
-- QUEST_DETAIL / QUEST_PROGRESS / QUEST_COMPLETE fire synchronously, and on
-- the current Classic-line clients GetQuestID() can still answer 0, or the
-- previous quest's globals can still be in place, at that moment: the line
-- lost its recording or the wrong quest was read. The read is put off to
-- the next frame and retried a few times until the ID, title and text are
-- there, keyed so the same panel is not read twice when the event repeats.
--------------------------------------------------------------------------------

local QUEST_PANELS = { accept = "QuestFrameDetailPanel", progress = "QuestFrameProgressPanel", complete = "QuestFrameRewardPanel" }
local QUEST_TEXT = {
	accept = function() return GetQuestText and GetQuestText() or nil end,
	progress = function() return GetProgressText and GetProgressText() or nil end,
	complete = function() return GetRewardText and GetRewardText() or nil end,
}
local READ_TRIES, READ_STEP = 5, 0.1
local lastRead = { key = nil, at = 0 }
local readSerial = 0

local function ClientQuestID()
	if not GetQuestID then
		return nil
	end
	local ok, id = pcall(GetQuestID)
	id = ok and PlainNumber(id) or nil
	return id and id > 0 and id or nil
end

local function QuestPanelShown(kind)
	local panel = _G[QUEST_PANELS[kind]]
	-- No such frame on this client: trust the event.
	return not panel or panel:IsShown()
end

local function ReadQuestPanel(kind, serial, attempt)
	if serial ~= readSerial or not M.isEnabled or not QuestPanelShown(kind) then
		return
	end
	local questID = ClientQuestID()
	local title = QuestTitle()
	local text = QUEST_TEXT[kind]()
	local plain = PlainString(text)
	local ready = questID ~= nil and title ~= nil and (IsSecret(text) or (plain ~= nil and plain ~= ""))
	if not ready and attempt < READ_TRIES then
		C_Timer.After(READ_STEP, function() ReadQuestPanel(kind, serial, attempt + 1) end)
		return
	end
	local key = kind .. ":" .. tostring(questID or 0) .. ":" .. tostring(title)
	if key == lastRead.key and GetTime() - lastRead.at < 5 then
		return
	end
	lastRead.key, lastRead.at = key, GetTime()
	Trace("%s %q: client quest ID %s after %d read(s)", kind, tostring(title), tostring(questID or "none"), attempt)
	local spoken = text
	if kind == "accept" and M.db.questObjectives and GetObjectiveText and plain then
		local objectives = GetObjectiveText()
		if type(objectives) == "string" and not IsSecret(objectives) and objectives ~= "" then
			spoken = plain .. " " .. objectives
		end
	end
	Enqueue(spoken, DescribeNPC(), kind, title, questID, text)
end

local function ScheduleQuestRead(kind)
	readSerial = readSerial + 1
	local serial = readSerial
	C_Timer.After(0, function() ReadQuestPanel(kind, serial, 1) end)
end

local handlers = {
	GOSSIP_SHOW = function()
		if M.db.gossip then
			Enqueue(GossipText(), DescribeNPC(), "gossip")
		end
	end,
	QUEST_GREETING = function()
		if M.db.gossip and GetGreetingText then
			Enqueue(GetGreetingText(), DescribeNPC(), "gossip")
		end
	end,
	QUEST_DETAIL = function()
		if M.db.questDetail then
			ScheduleQuestRead("accept")
		end
	end,
	QUEST_PROGRESS = function()
		if M.db.questProgress and GetProgressText then
			ScheduleQuestRead("progress")
		end
	end,
	QUEST_COMPLETE = function()
		if M.db.questComplete and GetRewardText then
			ScheduleQuestRead("complete")
		end
	end,
	GOSSIP_CLOSED = function()
		if M.db.stopOnClose then
			Stop()
		end
	end,
	QUEST_FINISHED = function()
		if M.db.stopOnClose then
			Stop()
		end
	end,
	PLAYER_TARGET_CHANGED = function()
		if M.db.stopOnMove and current then
			Stop()
		end
	end,
	VOICE_CHAT_TTS_VOICES_UPDATE = function()
		RefreshVoices()
	end,
	VOICE_CHAT_TTS_PLAYBACK_FINISHED = function()
		if current and not current.file and not paused then
			OnFinished(current)
		end
	end,
	VOICE_CHAT_TTS_PLAYBACK_FAILED = function()
		if not failedWarned then
			failedWarned = true
			MelloUI:Print("Voice Over: text-to-speech playback failed. Check that a voice is installed and selected.")
		end
		if current and not current.file then
			OnFinished(current)
		end
	end,
}

local eventFrame = CreateFrame("Frame")
eventFrame:SetScript("OnEvent", function(_, event, ...)
	local handler = handlers[event]
	if handler then
		handler(...)
	end
end)

--------------------------------------------------------------------------------
-- Quest log read-aloud
--
-- A button on the quest log's details view reads the selected quest: the
-- description in the giver's voice (the recorded offer line when a pack has
-- it), then the objectives with their current counts.
--------------------------------------------------------------------------------

local questGiver = nil   -- [questID] = { name, npcID } from the Quest List data

local function GiverForQuest(questID)
	if not questGiver then
		questGiver = {}
		local data = MelloUI_QuestListData
		if type(data) == "table" and type(data.quests) == "table" then
			for _, row in ipairs(data.quests) do
				if row[9] ~= "" then
					questGiver[row[1]] = { name = row[9], npcID = row[21] or 0 }
				end
			end
		end
	end
	local g = questGiver[questID]
	if not npcLookup then
		BuildLookup()
	end
	local npcID = g and g.npcID ~= 0 and g.npcID or nil
	local name = g and g.name or nil
	if not npcID and M.db.soundPacks then
		-- Not in the quest list data (or an item starts it): the pack's own
		-- quest -> NPC table knows the vanilla givers.
		LoadSoundPacks()
		for _, pack in ipairs(packs) do
			local byQuest = pack.data.NPCIDLookupByQuestID
			local id = byQuest and byQuest[questID]
			if type(id) == "number" then
				npcID = id
				local names = pack.data.NPCNameLookupByNPCID
				name = name or (names and names[id]) or nil
				break
			end
		end
	end
	local info = npcID and npcLookup[npcID] or nil
	local gender = info and info.gender or "n"
	return {
		id = npcID,
		name = name,
		race = info and info.race or nil,
		gender = gender,
		female = gender == "f",
		source = info and (info.override and "override" or "data") or "unknown",
		remote = true,
	}
end

local function SpeakableObjectives(questID, objectivesText, description)
	local parts = {}
	if type(objectivesText) == "string" and not IsSecret(objectivesText) and objectivesText ~= "" then
		-- The objectives paragraph repeats the description on some quests
		-- (the recording already said it); only read it when it adds something.
		local same = false
		if type(description) == "string" and not IsSecret(description) then
			local a, b = Normalise(objectivesText), Normalise(description)
			same = a == b or (a ~= "" and b:find(a, 1, true) ~= nil) or Similarity(objectivesText, description) > 0.6
		end
		if not same then
			parts[#parts + 1] = objectivesText
		end
	end
	if C_QuestLog and C_QuestLog.GetQuestObjectives then
		local ok, list = pcall(C_QuestLog.GetQuestObjectives, questID)
		if ok and type(list) == "table" then
			for _, objective in ipairs(list) do
				local text = objective and objective.text
				if type(text) == "string" and not IsSecret(text) and text ~= "" then
					-- "Goretusk Liver: 0/8" -> "Goretusk Liver, 0 of 8"
					text = text:gsub("%s*:%s*", ", "):gsub("(%d+)%s*/%s*(%d+)", "%1 of %2")
					if objective.finished then
						text = text .. ", done"
					end
					parts[#parts + 1] = text .. "."
				end
			end
		end
	end
	if #parts == 0 then
		return nil
	end
	return "Objectives. " .. table.concat(parts, " ")
end


local function ReadQuest(questID)
	if not questID or not HasTTS() then
		return false
	end
	local logIndex
	if C_QuestLog and C_QuestLog.GetLogIndexForQuestID then
		local ok, idx = pcall(C_QuestLog.GetLogIndexForQuestID, questID)
		logIndex = ok and PlainNumber(idx) or nil
	end
	if not logIndex or not GetQuestLogQuestText then
		return false
	end
	local ok, description, objectivesText = pcall(GetQuestLogQuestText, logIndex)
	if not ok then
		return false
	end
	local title
	if C_QuestLog and C_QuestLog.GetTitleForQuestID then
		local okT, t = pcall(C_QuestLog.GetTitleForQuestID, questID)
		title = okT and type(t) == "string" and not IsSecret(t) and t or nil
	end
	Stop()
	local npc = GiverForQuest(questID)
	local spoken = false
	if type(description) == "string" and not IsSecret(description) and description ~= "" then
		Enqueue(description, npc, "accept", title, questID)
		spoken = true
	end
	local objectives = M.db.questLogObjectives and SpeakableObjectives(questID, objectivesText, description) or nil
	if objectives then
		Enqueue(objectives, npc, "objectives", "Objectives" .. (title and (": " .. title) or ""), questID)
		spoken = true
	end
	return spoken
end

local readButton = nil

local function IsReadingLog()
	if current and current.questID and (current.kind == "accept" or current.kind == "objectives") and current.npc and current.npc.remote then
		return true
	end
	for _, entry in ipairs(queue) do
		if entry.npc and entry.npc.remote then
			return true
		end
	end
	return false
end

local function CreateReadButton()
	if readButton or not (QuestMapFrame and QuestMapFrame.DetailsFrame and QuestMapFrame.DetailsFrame.BackFrame) then
		return
	end
	local frame = QuestMapFrame.DetailsFrame.BackFrame
	readButton = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")
	readButton:SetSize(72, 22)
	readButton:SetPoint("RIGHT", frame, "RIGHT", -11, 4)
	readButton:SetText("Read")
	readButton:SetScript("OnClick", function()
		if IsReadingLog() then
			Stop()
			PlaySound(SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_OFF)
		else
			local questID = QuestMapFrame.DetailsFrame.questID
			if not ReadQuest(questID) then
				MelloUI:Print("Voice Over: nothing to read for this quest.")
			else
				PlaySound(SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON)
			end
		end
	end)
	readButton:SetScript("OnEnter", function(self)
		GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
		GameTooltip:SetText("Read aloud", 1, 1, 1)
		GameTooltip:AddLine("Reads the quest's description in the quest giver's voice, then the objectives with their progress.", nil, nil, nil, true)
		GameTooltip:Show()
	end)
	readButton:SetScript("OnLeave", function() GameTooltip:Hide() end)
	local acc = 0
	readButton:SetScript("OnUpdate", function(self, elapsed)
		acc = acc + elapsed
		if acc < 0.25 then
			return
		end
		acc = 0
		local reading = IsReadingLog()
		if reading ~= self.reading then
			self.reading = reading
			self:SetText(reading and "Stop" or "Read")
		end
	end)
end

local function ApplyReadButton()
	if M.isEnabled and M.db.questLog and HasTTS() then
		CreateReadButton()
	end
	if readButton then
		readButton:SetShown(M.isEnabled and M.db.questLog and true or false)
	end
end

--------------------------------------------------------------------------------
-- Slash command
--------------------------------------------------------------------------------

local TEST_LINES = {
	"Greetings, traveller. The road ahead is long, but I trust you will manage.",
	"You there! Yes, you. I have work for someone who can swing a blade.",
	"Ah, another adventurer. Stay a while and listen.",
}

local function GenderWord(gender)
	if gender == "f" then return "female" end
	if gender == "m" then return "male" end
	return "none"
end

SLASH_MELLOVOICEOVER1 = "/voiceover"
SLASH_MELLOVOICEOVER2 = "/vo"
SlashCmdList.MELLOVOICEOVER = function(msg)
	msg = (msg or ""):lower():gsub("^%s+", ""):gsub("%s+$", "")
	if msg == "stop" or msg == "" then
		Stop()
	elseif msg == "pause" then
		TogglePaused()
		MelloUI:Print(paused and "Voice Over paused." or "Voice Over resumed.")
	elseif msg == "skip" then
		if current then
			Skip(current)
		end
	elseif msg == "read" then
		local questID = C_QuestLog and C_QuestLog.GetSelectedQuest and PlainNumber(select(2, pcall(C_QuestLog.GetSelectedQuest)))
		if not questID or questID == 0 then
			MelloUI:Print("Select a quest in the quest log first.")
		elseif not ReadQuest(questID) then
			MelloUI:Print("Nothing to read for that quest.")
		end
	elseif msg == "reset" then
		Overlay:ResetPosition()
		MelloUI:Print("Overlay position reset.")
	elseif msg == "lines" then
		local store = Collected()
		local quests, questLines, newQuestLines, gossip, newGossip = 0, 0, 0, 0, 0
		for _, kinds in pairs(store.quests) do
			quests = quests + 1
			for _, rec in pairs(kinds) do
				questLines = questLines + 1
				if not rec.recorded then newQuestLines = newQuestLines + 1 end
			end
		end
		for _, texts in pairs(store.gossip) do
			for _, rec in pairs(texts) do
				gossip = gossip + 1
				if not rec.recorded then newGossip = newGossip + 1 end
			end
		end
		MelloUI:Print("Collected this session: %d quest lines from %d quests (%d without a recording), %d greetings (%d without).",
			questLines, quests, newQuestLines, gossip, newGossip)
		local shown = 0
		for _, texts in pairs(store.gossip) do
			for text, rec in pairs(texts) do
				if shown < 3 then
					shown = shown + 1
					print(string.format("   %s: %s%s", tostring(rec.npc), text:sub(1, 60), rec.recorded and " (recorded)" or ""))
				end
			end
		end
		for _, kinds in pairs(store.quests) do
			for kind, rec in pairs(kinds) do
				if shown < 6 then
					shown = shown + 1
					print(string.format("   %s, %s of %q%s", tostring(rec.npc), kind, tostring(rec.title), rec.recorded and " (recorded)" or ""))
				end
			end
		end
		print("   /reload writes them to the saved variables; then run Tools\\export_voice_lines.py before restarting the client.")
	elseif msg == "packs" then
		LoadSoundPacks()
		if #packs == 0 and not next(packErrors) then
			MelloUI:Print("No VoiceOver sound packs installed (looked for addons with X-VoiceOver-DataModule-Version).")
		end
		for _, pack in ipairs(packs) do
			local files = 0
			for _ in pairs(pack.data.SoundLengthLookupByFileName) do files = files + 1 end
			MelloUI:Print("Pack %s: %d recorded lines (priority %d).", pack.name, files, pack.priority)
		end
		for name, err in pairs(packErrors) do
			MelloUI:Print("Pack %s could not be loaded: %s", name, err)
		end
		if current then
			print("   current line: " .. (current.file and ("recorded (" .. current.file .. ")") or "text-to-speech"))
		end
		for _, line in ipairs(lookupTrace) do
			print("   " .. line)
		end
	elseif msg == "portrait" then
		local frame = Overlay.frame
		local model = frame and frame.portrait and frame.portrait.model
		if not model then
			MelloUI:Print("Overlay not created yet.")
			return
		end
		local function Try(name, ...)
			local fn = model[name]
			if not fn then
				return name .. "=missing"
			end
			local ok, a, b = pcall(fn, model, ...)
			return string.format("%s=%s", name, ok and tostring(a) .. (b ~= nil and ("," .. tostring(b)) or "") or ("error: " .. tostring(a)))
		end
		MelloUI:Print("Portrait: creature %s, loaded %s, retries %s, shown %s, size %dx%d",
			tostring(model.creatureID), tostring(model.loaded), tostring(model.retries), tostring(model:IsShown()),
			model:GetWidth(), model:GetHeight())
		print("   " .. Try("GetModelFileID") .. "  " .. Try("GetModel") .. "  " .. Try("HasCustomCamera") .. "  " .. Try("GetModelScale"))
		print("   " .. Try("GetCameraPosition") .. "  " .. Try("GetPosition") .. "  " .. Try("GetModelAlpha"))
	elseif msg == "test" then
		if not M.isEnabled then
			MelloUI:Print("Voice Over is disabled. Enable it under /mello.")
			return
		end
		local npc = DescribeNPC(true)
		if npc then
			local profile = RACE_PROFILES[npc.race or ""] or DEFAULT_PROFILE
			MelloUI:Print("Reading as %s (%s, %s).", npc.name or ("NPC " .. npc.id), profile.label, GenderWord(npc.gender))
		else
			MelloUI:Print("No NPC targeted; reading with the male voice.")
		end
		Enqueue(TEST_LINES[math.random(#TEST_LINES)], npc, "gossip", "Test line")
	elseif msg == "voices" then
		RefreshVoices()
		if #voices == 0 then
			MelloUI:Print("No text-to-speech voices found.")
			return
		end
		MelloUI:Print("Installed voices (male pick: %s, female pick: %s):",
			tostring(voiceByID[PickVoice(nil, false) or -1] or "none"), tostring(voiceByID[PickVoice(nil, true) or -1] or "none"))
		for _, voice in ipairs(voices) do
			print(string.format("   %d  -  %s", voice.voiceID, voice.name))
		end
	elseif msg == "npc" then
		local npc = DescribeNPC(true)
		if not npc then
			MelloUI:Print("Target or talk to an NPC first.")
			return
		end
		local pitch, rate, profile = VoiceShape(npc.race)
		local voiceID = PickVoice(npc.race, npc.female)
		MelloUI:Print("%s  (NPC ID %d)", npc.name or "?", npc.id)
		print(string.format("   race: %s (%s)   gender: %s   source: %s",
			npc.race or "unknown", profile.label, GenderWord(npc.gender), npc.source))
		print(string.format("   voice: %s   pitch: %+d   speed: %+d", tostring(voiceByID[voiceID or -1] or "none"), pitch, rate))
		if npc.source == "unknown" then
			print(string.format('   Not in the data. Add to Media\\NPCVoiceOverrides.lua:  [%d] = { race = "human", gender = "%s" },',
				npc.id, npc.female and "f" or "m"))
		end
	else
		MelloUI:Print("/vo stop | pause | skip | read | test | voices | npc | packs | lines | reset | portrait")
	end
end

--------------------------------------------------------------------------------
-- Module lifecycle
--------------------------------------------------------------------------------

local EVENTS = {
	"GOSSIP_SHOW", "GOSSIP_CLOSED",
	"QUEST_GREETING", "QUEST_DETAIL", "QUEST_PROGRESS", "QUEST_COMPLETE", "QUEST_FINISHED",
	"PLAYER_TARGET_CHANGED",
	"VOICE_CHAT_TTS_VOICES_UPDATE", "VOICE_CHAT_TTS_PLAYBACK_FINISHED", "VOICE_CHAT_TTS_PLAYBACK_FAILED",
}

function M:OnInit(db)
	self.db = db
	RefreshVoices()
end

function M:OnEnable(db)
	self.db = db
	RefreshVoices()
	npcLookup = nil
	if not HasTTS() then
		MelloUI:Print("Voice Over: this client has no text-to-speech API; the module will do nothing.")
		return
	end
	Overlay:Create()
	Overlay:Apply()
	ApplyReadButton()
	for _, event in ipairs(EVENTS) do
		pcall(eventFrame.RegisterEvent, eventFrame, event)
	end
	if db.collectLines then
		-- Create the store now so the saved file shows an empty table (the
		-- collector is running) rather than nothing at all.
		Collected()
	end
	if db.soundPacks then
		-- The packs' lookup tables are a few megabytes of Lua; load them a
		-- moment after login rather than inside the first dialog.
		C_Timer.After(3, function()
			if M.isEnabled and M.db.soundPacks then
				LoadSoundPacks()
			end
		end)
	end
end

function M:OnDisable()
	for _, event in ipairs(EVENTS) do
		pcall(eventFrame.UnregisterEvent, eventFrame, event)
	end
	Stop()
	if Overlay.frame then
		Overlay.frame:Hide()
	end
	if readButton then
		readButton:Hide()
	end
end

function M:OnSettingChanged(key, value, db)
	self.db = db
	if key == "maleVoice" or key == "femaleVoice" then
		-- Let the user hear the choice straight away.
		local female = key == "femaleVoice"
		SpeakSample(female and "This is the voice used for female characters." or "This is the voice used for male characters.", { female = female })
	elseif key:match("^voice_") then
		local groupKey = key:sub(7)
		for _, group in ipairs(RACE_GROUPS) do
			if group.key == groupKey then
				local race = group.races and next(group.races) or "other"
				SpeakSample("This is the voice used for " .. group.name:lower() .. ".", { race = race, female = false })
			end
		end
	elseif key:match("^overlay") then
		Overlay:Apply()
	elseif key == "questLog" then
		ApplyReadButton()
	end
end

MelloUI:Profile("VoiceOver", "dialog events", eventFrame)
MelloUI:Profile("VoiceOver", "sound pack load", LoadSoundPacks)
MelloUI:Profile("VoiceOver", "line lookup + queue", Enqueue)
