-- Generated by Tools/extract_icons.py from Tools/class_icons.json and
-- docs/class-icons.webp / docs/faction-icons.webp. Do not edit by hand:
-- correct a mapping in Tools/class_icons.json and re-run the script.

MelloUI_ClassIcons = {
	classes = {
		DEATHKNIGHT = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\DEATHKNIGHT",
		DRUID = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\DRUID",
		EVOKER = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\EVOKER",
		HUNTER = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\HUNTER",
		MAGE = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\MAGE",
		MONK = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\MONK",
		PALADIN = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\PALADIN",
		PRIEST = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\PRIEST",
		ROGUE = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\ROGUE",
		SHAMAN = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\SHAMAN",
		WARLOCK = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\WARLOCK",
		WARRIOR = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Class\\WARRIOR",
	},
	factions = {
		Alliance = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Faction\\Alliance",
		Horde = "Interface\\AddOns\\MelloUI\\Media\\Icons\\Faction\\Horde",
	},
}

