-- Generated by Tools/make_kit_shadows.py from the kit's masters. Do not edit by hand.
--
-- The kit's shadow partners (Kit:Shadow, Modules/Kit.lua): a soft copy of each
-- listed piece's shape (its alpha grown by 3 px and blurred, sigma 8 px), white,
-- in one sheet at a quarter of the painted size, the same for every Kit Colours look.
--   file    the sheet (no extension)
--   size    the sheet's width and height in texels
--   pieces  by piece name: uv (left, right, top, bottom in the sheet) and pad (how
--           far the shadow reaches past the piece on its left, top, right and
--           bottom, in the piece's painted px); or the name of a piece whose
--           shadow is the same
--   A strip's parts reach past their outer sides only (a cap_l left, a cap_r right,
--   a mid neither), so the three join without a seam; a mid's shadow is its profile
--   across the rail, stretched along it.
-- sheet sha256 89190152de49005c99f8a7c0153fbbfa55f3436b6a1e91335987cf6300e81c08

-- luacheck: globals MelloUI_KitShadows
MelloUI_KitShadows = {
	file = "Interface\\AddOns\\MelloUI\\Media\\Textures\\KitShadows",
	size = { 128, 256 },
	pieces = {
		["bars/castbar_cap_l"] = { uv = { 0.359375, 0.679688, 0.007812, 0.136719 }, pad = { 30, 28, 0, 30 } },
		["bars/castbar_cap_r"] = { uv = { 0.015625, 0.335938, 0.179688, 0.308594 }, pad = { 0, 28, 29, 30 } },
		["bars/castbar_mid"] = { uv = { 0.390625, 0.421875, 0.179688, 0.308594 }, pad = { 0, 28, 0, 30 } },
		["bars/frame_cap_l"] = { uv = { 0.453125, 0.773438, 0.179688, 0.296875 }, pad = { 29, 28, 0, 28 } },
		["bars/frame_cap_l_red"] = "bars/frame_cap_l",
		["bars/frame_cap_r"] = { uv = { 0.015625, 0.335938, 0.335938, 0.453125 }, pad = { 0, 28, 29, 28 } },
		["bars/frame_cap_r_red"] = "bars/frame_cap_r",
		["bars/frame_mid"] = { uv = { 0.390625, 0.421875, 0.335938, 0.453125 }, pad = { 0, 28, 0, 28 } },
		["bars/rim_cap_l"] = { uv = { 0.453125, 0.570312, 0.335938, 0.445312 }, pad = { 28, 28, 0, 30 } },
		["bars/rim_cap_r"] = { uv = { 0.609375, 0.726562, 0.335938, 0.445312 }, pad = { 0, 28, 28, 30 } },
		["bars/rim_mid"] = { uv = { 0.484375, 0.515625, 0.476562, 0.585938 }, pad = { 0, 28, 0, 30 } },
		["bars/rimgold_cap_l"] = { uv = { 0.765625, 0.882812, 0.335938, 0.445312 }, pad = { 28, 28, 0, 30 } },
		["bars/rimgold_cap_r"] = { uv = { 0.015625, 0.132812, 0.476562, 0.585938 }, pad = { 0, 28, 28, 30 } },
		["bars/rimgold_mid"] = { uv = { 0.546875, 0.578125, 0.476562, 0.585938 }, pad = { 0, 28, 0, 30 } },
		["bars/rimhair_cap_l"] = { uv = { 0.296875, 0.414062, 0.601562, 0.699219 }, pad = { 28, 28, 0, 28 } },
		["bars/rimhair_cap_r"] = { uv = { 0.453125, 0.570312, 0.601562, 0.699219 }, pad = { 0, 28, 28, 28 } },
		["bars/rimhair_mid"] = { uv = { 0.609375, 0.640625, 0.601562, 0.699219 }, pad = { 0, 28, 0, 28 } },
		["bars/rimround_cap_l"] = { uv = { 0.671875, 0.789062, 0.476562, 0.582031 }, pad = { 28, 28, 0, 28 } },
		["bars/rimround_cap_r"] = { uv = { 0.828125, 0.945312, 0.476562, 0.582031 }, pad = { 0, 28, 28, 28 } },
		["bars/rimround_mid"] = { uv = { 0.015625, 0.046875, 0.601562, 0.707031 }, pad = { 0, 28, 0, 28 } },
		["bars/rimsunk_cap_l"] = { uv = { 0.171875, 0.289062, 0.476562, 0.585938 }, pad = { 28, 28, 0, 30 } },
		["bars/rimsunk_cap_r"] = { uv = { 0.328125, 0.445312, 0.476562, 0.585938 }, pad = { 0, 28, 28, 30 } },
		["bars/rimsunk_mid"] = { uv = { 0.609375, 0.640625, 0.476562, 0.585938 }, pad = { 0, 28, 0, 30 } },
		["buttons/orb_normal"] = { uv = { 0.015625, 0.320312, 0.007812, 0.160156 }, pad = { 28, 28, 30, 30 } },
		["deco/gem_large"] = { uv = { 0.078125, 0.265625, 0.601562, 0.699219 }, pad = { 28, 28, 28, 31 } },
	},
}
