-- Generated by Tools/make_kit_shadows.py from the kit's masters. Do not edit by hand.
--
-- The kit's shadow partners (Kit:Shadow, Kit:ShadowNine, Modules/Kit.lua): a soft copy of the
-- shape of each piece on an element's outline (its alpha grown and blurred: sigma 8 px at the
-- kit's scale, less for a family drawn larger: the single rail), white, in one sheet at a
-- quarter of the painted size, the same for every palette and Kit Colours look.
--   version  2
--   file     the sheet (no extension)
--   size     the sheet's width and height in texels
--   pieces   by piece name: uv (left, right, top, bottom in the sheet) and pad (how far the
--            shadow reaches past the piece on its left, top, right and bottom, in the piece's
--            painted px); or the name of a piece whose shadow it uses (the same shape, within
--            8 of 255). A strip's parts reach past their outer sides only (a cap_l left, a
--            cap_r right, a mid neither), so they join without a seam; a mid's shadow is its
--            profile across the rail, stretched along it. A mid's endL / endR: the soft end of
--            a strip drawn without a cap on that side, a partner just past the mid's end,
--            pad[1] (endL) or pad[3] (endR) px wide, its other pads the mid's.
--            window/frame_* and window/single_* lie in their family's nine (below). Outside
--            only: nothing is shaded inward of the middle of a piece's rim round an opening.
--   nines    by family (window/frame, window/single, deco/barframe_red, _iron): the rails'
--            shadow as one picture to cut into nine. uv; pad (its reach past the frame's rect);
--            corner (the rails' corner, painted px); margins (where to cut: px from the
--            picture's left, top, right and bottom); size (the picture in painted px). The
--            edges between the cuts are profiles (stretch them); the middle is empty (outside
--            only: nothing inward of the rails' middle line).
--   shapes   shade/square (a filled box; its middle filled) and shade/capsule (a pill, its
--            middle rows none: scale it by its height) cut as the nines; shade/round (a disc,
--            stretched whole): for frames that have no kit piece. All three are filled (the
--            shadow of a solid shape), unlike the pieces and nines (outside only).
-- sheet sha256 23a91ca27b00c918d6a0e071ec4ab9a8305f90ef4664eced8f3e0396a44c7980

-- luacheck: globals MelloUI_KitShadows
MelloUI_KitShadows = {
	version = 2,
	file = "Interface\\AddOns\\MelloUI\\Media\\Textures\\KitShadows",
	size = { 512, 512 },
	pieces = {
		["bars/castbar_cap_l"] = { uv = { 0.003906, 0.083984, 0.355469, 0.419922 }, pad = { 30, 28, 0, 30 } },
		["bars/castbar_cap_r"] = { uv = { 0.769531, 0.849609, 0.394531, 0.458984 }, pad = { 0, 28, 29, 30 } },
		["bars/castbar_mid"] = { uv = { 0.980469, 0.988281, 0.378906, 0.443359 }, pad = { 0, 28, 0, 30 }, endL = { uv = { 0.332031, 0.345703, 0.347656, 0.412109 }, pad = { 28, 28, 0, 30 } }, endR = { uv = { 0.355469, 0.369141, 0.347656, 0.412109 }, pad = { 0, 28, 28, 30 } } },
		["bars/frame_cap_l"] = { uv = { 0.207031, 0.287109, 0.433594, 0.492188 }, pad = { 29, 28, 0, 28 } },
		["bars/frame_cap_l_red"] = "bars/frame_cap_l",
		["bars/frame_cap_r"] = { uv = { 0.433594, 0.513672, 0.472656, 0.53125 }, pad = { 0, 28, 29, 28 } },
		["bars/frame_cap_r_red"] = "bars/frame_cap_r",
		["bars/frame_mid"] = { uv = { 0.699219, 0.707031, 0.472656, 0.53125 }, pad = { 0, 28, 0, 28 }, endL = { uv = { 0.300781, 0.314453, 0.433594, 0.492188 }, pad = { 28, 28, 0, 28 } }, endR = { uv = { 0.957031, 0.970703, 0.457031, 0.515625 }, pad = { 0, 28, 28, 28 } } },
		["bars/rim_cap_l"] = { uv = { 0.917969, 0.947266, 0.472656, 0.527344 }, pad = { 28, 28, 0, 30 } },
		["bars/rim_cap_r"] = { uv = { 0.378906, 0.408203, 0.496094, 0.550781 }, pad = { 0, 28, 28, 30 } },
		["bars/rim_mid"] = { uv = { 0.417969, 0.425781, 0.496094, 0.550781 }, pad = { 0, 28, 0, 30 }, endL = { uv = { 0.957031, 0.970703, 0.527344, 0.582031 }, pad = { 28, 28, 0, 30 } }, endR = { uv = { 0.980469, 0.994141, 0.527344, 0.582031 }, pad = { 0, 28, 28, 30 } } },
		["bars/rimgold_cap_l"] = { uv = { 0.003906, 0.033203, 0.503906, 0.558594 }, pad = { 28, 28, 0, 30 } },
		["bars/rimgold_cap_r"] = { uv = { 0.042969, 0.072266, 0.503906, 0.558594 }, pad = { 0, 28, 28, 30 } },
		["bars/rimgold_mid"] = { uv = { 0.917969, 0.925781, 0.535156, 0.589844 }, pad = { 0, 28, 0, 30 }, endL = { uv = { 0.730469, 0.744141, 0.535156, 0.589844 }, pad = { 28, 28, 0, 30 } }, endR = { uv = { 0.753906, 0.767578, 0.535156, 0.589844 }, pad = { 0, 28, 28, 30 } } },
		["bars/rimhair_cap_l"] = { uv = { 0.082031, 0.111328, 0.503906, 0.552734 }, pad = { 28, 28, 0, 28 } },
		["bars/rimhair_cap_r"] = { uv = { 0.121094, 0.150391, 0.503906, 0.552734 }, pad = { 0, 28, 28, 28 } },
		["bars/rimhair_mid"] = { uv = { 0.933594, 0.941406, 0.535156, 0.583984 }, pad = { 0, 28, 0, 28 }, endL = { uv = { 0.777344, 0.791016, 0.535156, 0.583984 }, pad = { 28, 28, 0, 28 } }, endR = { uv = { 0.800781, 0.814453, 0.535156, 0.583984 }, pad = { 0, 28, 28, 28 } } },
		["bars/rimround_cap_l"] = { uv = { 0.160156, 0.189453, 0.503906, 0.556641 }, pad = { 28, 28, 0, 28 } },
		["bars/rimround_cap_r"] = { uv = { 0.199219, 0.228516, 0.503906, 0.556641 }, pad = { 0, 28, 28, 28 } },
		["bars/rimround_mid"] = { uv = { 0.433594, 0.441406, 0.542969, 0.595703 }, pad = { 0, 28, 0, 28 }, endL = { uv = { 0.824219, 0.837891, 0.535156, 0.587891 }, pad = { 28, 28, 0, 28 } }, endR = { uv = { 0.847656, 0.861328, 0.535156, 0.587891 }, pad = { 0, 28, 28, 28 } } },
		["bars/rimsunk_cap_l"] = { uv = { 0.238281, 0.267578, 0.503906, 0.558594 }, pad = { 28, 28, 0, 30 } },
		["bars/rimsunk_cap_r"] = { uv = { 0.277344, 0.306641, 0.503906, 0.558594 }, pad = { 0, 28, 28, 30 } },
		["bars/rimsunk_mid"] = { uv = { 0.449219, 0.457031, 0.542969, 0.597656 }, pad = { 0, 28, 0, 30 }, endL = { uv = { 0.871094, 0.884766, 0.535156, 0.589844 }, pad = { 28, 28, 0, 30 } }, endR = { uv = { 0.894531, 0.908203, 0.535156, 0.589844 }, pad = { 0, 28, 28, 30 } } },
		["buttons/cog_hover"] = { uv = { 0.730469, 0.783203, 0.472656, 0.525391 }, pad = { 28, 28, 30, 31 } },
		["buttons/cog_normal"] = { uv = { 0.792969, 0.845703, 0.472656, 0.525391 }, pad = { 28, 28, 30, 31 } },
		["buttons/cog_pressed"] = "buttons/cog_hover",
		["buttons/orb_hover"] = { uv = { 0.316406, 0.392578, 0.261719, 0.337891 }, pad = { 28, 28, 30, 30 } },
		["buttons/orb_normal"] = { uv = { 0.402344, 0.478516, 0.339844, 0.416016 }, pad = { 28, 28, 30, 30 } },
		["buttons/orb_pressed"] = { uv = { 0.097656, 0.173828, 0.347656, 0.423828 }, pad = { 28, 28, 30, 30 } },
		["buttons/rim_checked"] = { uv = { 0.824219, 0.914062, 0.003906, 0.09375 }, pad = { 28, 28, 28, 28 } },
		["buttons/rim_hover"] = "buttons/rim_checked",
		["buttons/rim_normal"] = { uv = { 0.589844, 0.679688, 0.105469, 0.195312 }, pad = { 28, 28, 28, 28 } },
		["buttons/rim_pressed"] = "buttons/rim_checked",
		["buttons/rimgold_checked"] = "buttons/rim_checked",
		["buttons/rimgold_hover"] = "buttons/rim_checked",
		["buttons/rimgold_normal"] = "buttons/rim_normal",
		["buttons/rimgold_pressed"] = "buttons/rim_checked",
		["buttons/rimhair_checked"] = { uv = { 0.691406, 0.78125, 0.105469, 0.195312 }, pad = { 28, 28, 28, 28 } },
		["buttons/rimhair_hover"] = "buttons/rimhair_checked",
		["buttons/rimhair_normal"] = "buttons/rimhair_checked",
		["buttons/rimhair_pressed"] = "buttons/rimhair_checked",
		["buttons/rimround_checked"] = { uv = { 0.792969, 0.882812, 0.105469, 0.195312 }, pad = { 28, 28, 28, 28 } },
		["buttons/rimround_hover"] = "buttons/rimround_checked",
		["buttons/rimround_normal"] = "buttons/rimround_checked",
		["buttons/rimround_pressed"] = "buttons/rimround_checked",
		["buttons/rimsunk_checked"] = "buttons/rim_checked",
		["buttons/rimsunk_hover"] = "buttons/rim_checked",
		["buttons/rimsunk_normal"] = "buttons/rim_normal",
		["buttons/rimsunk_pressed"] = "buttons/rim_checked",
		["buttons/roundrim_checked"] = { uv = { 0.894531, 0.984375, 0.105469, 0.195312 }, pad = { 28, 28, 28, 28 } },
		["buttons/roundrim_hover"] = "buttons/roundrim_checked",
		["buttons/roundrim_normal"] = "buttons/roundrim_checked",
		["buttons/roundrim_pressed"] = "buttons/roundrim_checked",
		["buttons/roundrimgold_checked"] = "buttons/roundrim_checked",
		["buttons/roundrimgold_hover"] = "buttons/roundrim_checked",
		["buttons/roundrimgold_normal"] = "buttons/roundrim_checked",
		["buttons/roundrimgold_pressed"] = "buttons/roundrim_checked",
		["buttons/roundrimhair_checked"] = { uv = { 0.457031, 0.546875, 0.136719, 0.226562 }, pad = { 28, 28, 28, 28 } },
		["buttons/roundrimhair_hover"] = "buttons/roundrimhair_checked",
		["buttons/roundrimhair_normal"] = "buttons/roundrimhair_checked",
		["buttons/roundrimhair_pressed"] = "buttons/roundrimhair_checked",
		["buttons/roundrimsunk_checked"] = "buttons/roundrim_checked",
		["buttons/roundrimsunk_hover"] = "buttons/roundrim_checked",
		["buttons/roundrimsunk_normal"] = "buttons/roundrim_checked",
		["buttons/roundrimsunk_pressed"] = "buttons/roundrim_checked",
		["buttons/roundslot_hover"] = { uv = { 0.003906, 0.095703, 0.160156, 0.251953 }, pad = { 28, 28, 30, 31 } },
		["buttons/roundslot_normal"] = { uv = { 0.105469, 0.197266, 0.160156, 0.251953 }, pad = { 28, 28, 30, 31 } },
		["buttons/roundslot_pressed"] = { uv = { 0.207031, 0.298828, 0.160156, 0.251953 }, pad = { 28, 28, 30, 31 } },
		["buttons/slot_checked"] = { uv = { 0.308594, 0.402344, 0.160156, 0.251953 }, pad = { 28, 28, 29, 30 } },
		["buttons/slot_hover"] = { uv = { 0.558594, 0.652344, 0.207031, 0.298828 }, pad = { 28, 28, 29, 30 } },
		["buttons/slot_normal"] = { uv = { 0.660156, 0.753906, 0.207031, 0.298828 }, pad = { 28, 28, 29, 30 } },
		["buttons/slot_pressed"] = "buttons/slot_checked",
		["deco/barframe_iron"] = { uv = { 0.761719, 0.855469, 0.207031, 0.298828 }, pad = { 28, 28, 29, 30 } },
		["deco/barframe_red"] = "deco/barframe_iron",
		["deco/barjoin"] = { uv = { 0.855469, 0.904297, 0.472656, 0.521484 }, pad = { 28, 28, 28, 28 } },
		["deco/gem_large"] = { uv = { 0.324219, 0.371094, 0.496094, 0.544922 }, pad = { 28, 28, 28, 31 } },
		["deco/rail_cap_l"] = { uv = { 0.003906, 0.21875, 0.003906, 0.150391 }, pad = { 28, 28, 31, 28 } },
		["deco/rail_cap_r"] = { uv = { 0.230469, 0.445312, 0.003906, 0.150391 }, pad = { 28, 28, 31, 28 } },
		["inputs/edit_cap_l_focused"] = { uv = { 0.332031, 0.425781, 0.425781, 0.482422 }, pad = { 28, 28, 0, 31 } },
		["inputs/edit_cap_l_normal"] = "inputs/edit_cap_l_focused",
		["inputs/edit_cap_r_focused"] = { uv = { 0.003906, 0.095703, 0.433594, 0.490234 }, pad = { 0, 28, 28, 31 } },
		["inputs/edit_cap_r_normal"] = "inputs/edit_cap_r_focused",
		["inputs/edit_end_l_focused"] = { uv = { 0.105469, 0.197266, 0.433594, 0.490234 }, pad = { 28, 28, 0, 31 } },
		["inputs/edit_end_l_normal"] = "inputs/edit_end_l_focused",
		["inputs/edit_mid_focused"] = { uv = { 0.714844, 0.722656, 0.472656, 0.529297 }, pad = { 0, 28, 0, 31 }, endL = { uv = { 0.980469, 0.994141, 0.457031, 0.513672 }, pad = { 28, 28, 0, 31 } }, endR = { uv = { 0.675781, 0.689453, 0.472656, 0.529297 }, pad = { 0, 28, 28, 31 } } },
		["inputs/edit_mid_normal"] = "inputs/edit_mid_focused",
		["lists/header_cap_l"] = { uv = { 0.503906, 0.625, 0.394531, 0.462891 }, pad = { 29, 28, 0, 30 } },
		["lists/header_cap_r"] = { uv = { 0.636719, 0.757812, 0.394531, 0.462891 }, pad = { 0, 28, 29, 30 } },
		["lists/header_mid"] = { uv = { 0.941406, 0.949219, 0.394531, 0.462891 }, pad = { 0, 28, 0, 30 }, endL = { uv = { 0.378906, 0.392578, 0.347656, 0.416016 }, pad = { 28, 28, 0, 30 } }, endR = { uv = { 0.957031, 0.970703, 0.378906, 0.447266 }, pad = { 0, 28, 28, 30 } } },
		["tabs/top_cap_l_open"] = { uv = { 0.097656, 0.193359, 0.261719, 0.333984 }, pad = { 29, 28, 0, 31 } },
		["tabs/top_cap_l_plain"] = { uv = { 0.207031, 0.302734, 0.261719, 0.333984 }, pad = { 29, 28, 0, 31 } },
		["tabs/top_cap_l_title"] = { uv = { 0.503906, 0.599609, 0.308594, 0.380859 }, pad = { 29, 28, 0, 31 } },
		["tabs/top_cap_r_open"] = { uv = { 0.613281, 0.708984, 0.308594, 0.380859 }, pad = { 0, 28, 28, 31 } },
		["tabs/top_cap_r_plain"] = { uv = { 0.722656, 0.818359, 0.308594, 0.380859 }, pad = { 0, 28, 28, 31 } },
		["tabs/top_cap_r_title"] = { uv = { 0.832031, 0.927734, 0.308594, 0.380859 }, pad = { 0, 28, 28, 31 } },
		["tabs/top_mid_open"] = { uv = { 0.941406, 0.949219, 0.308594, 0.380859 }, pad = { 0, 28, 0, 31 }, endL = { uv = { 0.957031, 0.970703, 0.207031, 0.279297 }, pad = { 28, 28, 0, 31 } }, endR = { uv = { 0.980469, 0.994141, 0.207031, 0.279297 }, pad = { 0, 28, 28, 31 } } },
		["tabs/top_mid_plain"] = { uv = { 0.488281, 0.496094, 0.339844, 0.412109 }, pad = { 0, 28, 0, 31 }, endL = { uv = { 0.957031, 0.970703, 0.292969, 0.365234 }, pad = { 28, 28, 0, 31 } }, endR = { uv = { 0.980469, 0.994141, 0.292969, 0.365234 }, pad = { 0, 28, 28, 31 } } },
		["tabs/top_mid_title"] = { uv = { 0.316406, 0.324219, 0.347656, 0.419922 }, pad = { 0, 28, 0, 31 }, endL = { uv = { 0.269531, 0.283203, 0.347656, 0.419922 }, pad = { 28, 28, 0, 31 } }, endR = { uv = { 0.292969, 0.306641, 0.347656, 0.419922 }, pad = { 0, 28, 28, 31 } } },
		["window/frame_b"] = { uv = { 0.042969, 0.050781, 0.308594, 0.347656 }, pad = { 0, 0, 0, 30 } },
		["window/frame_bl"] = { uv = { 0.003906, 0.042969, 0.308594, 0.347656 }, pad = { 30, 0, 0, 30 } },
		["window/frame_br"] = { uv = { 0.050781, 0.089844, 0.308594, 0.347656 }, pad = { 0, 0, 30, 30 } },
		["window/frame_gem_bl"] = { uv = { 0.863281, 0.945312, 0.207031, 0.296875 }, pad = { 28, 28, 28, 29 } },
		["window/frame_gem_br"] = { uv = { 0.410156, 0.492188, 0.238281, 0.328125 }, pad = { 28, 28, 29, 30 } },
		["window/frame_gem_tl"] = { uv = { 0.589844, 0.697266, 0.003906, 0.097656 }, pad = { 28, 28, 31, 31 } },
		["window/frame_gem_tr"] = { uv = { 0.707031, 0.8125, 0.003906, 0.091797 }, pad = { 28, 28, 28, 30 } },
		["window/frame_l"] = { uv = { 0.003906, 0.042969, 0.300781, 0.308594 }, pad = { 30, 0, 0, 0 } },
		["window/frame_r"] = { uv = { 0.050781, 0.089844, 0.300781, 0.308594 }, pad = { 0, 0, 30, 0 } },
		["window/frame_t"] = { uv = { 0.042969, 0.050781, 0.261719, 0.300781 }, pad = { 0, 30, 0, 0 } },
		["window/frame_tl"] = { uv = { 0.003906, 0.042969, 0.261719, 0.300781 }, pad = { 30, 30, 0, 0 } },
		["window/frame_tr"] = { uv = { 0.050781, 0.089844, 0.261719, 0.300781 }, pad = { 0, 30, 30, 0 } },
		["window/portrait_ring"] = { uv = { 0.457031, 0.582031, 0.003906, 0.126953 }, pad = { 28, 28, 31, 30 } },
		["window/single_b"] = { uv = { 0.480469, 0.488281, 0.566406, 0.582031 }, pad = { 0, 0, 0, 21 } },
		["window/single_bl"] = { uv = { 0.464844, 0.480469, 0.566406, 0.582031 }, pad = { 21, 0, 0, 21 } },
		["window/single_br"] = { uv = { 0.488281, 0.503906, 0.566406, 0.582031 }, pad = { 0, 0, 21, 21 } },
		["window/single_l"] = { uv = { 0.464844, 0.480469, 0.558594, 0.566406 }, pad = { 21, 0, 0, 0 } },
		["window/single_r"] = { uv = { 0.488281, 0.503906, 0.558594, 0.566406 }, pad = { 0, 0, 21, 0 } },
		["window/single_t"] = { uv = { 0.480469, 0.488281, 0.542969, 0.558594 }, pad = { 0, 21, 0, 0 } },
		["window/single_tl"] = { uv = { 0.464844, 0.480469, 0.542969, 0.558594 }, pad = { 21, 21, 0, 0 } },
		["window/single_tr"] = { uv = { 0.488281, 0.503906, 0.542969, 0.558594 }, pad = { 0, 21, 21, 0 } },
	},
	nines = {
		["deco/barframe_iron"] = { uv = { 0.183594, 0.257812, 0.347656, 0.421875 }, pad = { 28, 28, 28, 28 }, corner = 40, margins = { 68, 68, 68, 68 }, size = { 152, 152 } },
		["deco/barframe_red"] = { uv = { 0.183594, 0.257812, 0.347656, 0.421875 }, pad = { 28, 28, 28, 28 }, corner = 40, margins = { 68, 68, 68, 68 }, size = { 152, 152 } },
		["window/frame"] = { uv = { 0.003906, 0.089844, 0.261719, 0.347656 }, pad = { 30, 30, 30, 30 }, corner = 50, margins = { 80, 80, 80, 80 }, size = { 176, 176 } },
		["window/single"] = { uv = { 0.464844, 0.503906, 0.542969, 0.582031 }, pad = { 21, 21, 21, 21 }, corner = 11, margins = { 32, 32, 32, 32 }, size = { 80, 80 } },
	},
	shapes = {
		["shade/capsule"] = { uv = { 0.527344, 0.59375, 0.472656, 0.53125 }, pad = { 28, 28, 28, 28 }, corner = 32, margins = { 60, 60, 60, 60 }, size = { 136, 120 } },
		["shade/round"] = { uv = { 0.605469, 0.664062, 0.472656, 0.53125 }, pad = { 28, 28, 28, 28 }, size = { 120, 120 } },
		["shade/square"] = { uv = { 0.863281, 0.929688, 0.394531, 0.460938 }, pad = { 28, 28, 28, 28 }, corner = 32, margins = { 60, 60, 60, 60 }, size = { 136, 136 } },
	},
}
