-- Generated by Tools/bake_routes.py from the saved variable MelloUIDB. Do not edit by hand.
-- Settings profiles (serialised like the macro backup) and the one applied on a fresh install.

MelloUI_Profiles = {
	default = "MelloUI",
	profiles = {
		["MelloUI"] = "UIModifications.qol_DarkMode=b0;UIModifications.qol_BarTextures=b0;BarTextures.healthColor=sreaction;BarTextures.texture=sInterface\\\\AddOns\\\\MelloUI\\\\Media\\\\Textures\\\\Minimalist;Tweaks.hideBagBar=b1;Tweaks.hideMicroMenu=b1;Tweaks.worldTextScale=n0.80000001192093;Chat.hideTabs=b1;Chat.savedClassColorCVar=s-1;Nameplates.ccSize=n35;Tooltip.anchor=scursor_right;CooldownText.minDuration=n1;VoiceOver.overlayLock=b1;VoiceOver.overlayPoint=sTOP;VoiceOver.overlayRelativePoint=sTOP;VoiceOver.overlaySubtitles=b1;VoiceOver.overlayX=n-420;VoiceOver.overlayY=n-163;VoiceOver.preferRecordings=b1;VoiceOver.questLogObjectives=b0;QuestList.hideCompleted=b1;QuestList.zoneBadges=b0;Route.arrowX=n6;Route.arrowY=n539;Services.angle=n-130.65832645479",
	},
}
