--------------------------------------------------------------------------------
-- MelloUI - Quest List
--
-- A panel attached to the right of the world map listing the quests that can
-- be picked up in a zone: how many of them you have done, and for each quest
-- its level, the quest giver and where to find it. Quests are grouped under
-- collapsible headers in the style of the quest log: one per quest chain,
-- then the single quests. Titles are coloured by difficulty like the quest
-- log, completed quests are greyed with a tick, and clicking a quest drops a
-- map pin on the giver.
--
-- The module is in four files: this one (data, placement, dungeon summary,
-- lifecycle, /qlmap, the tooltip-line helper), QuestListPanel.lua (the
-- panel), QuestListMap.lua (map pins, entrances, transports and how entrances
-- are learned) and QuestListTips.lua (the quest lines in the game's tooltips).
--
-- Data: Media\QuestListData.lua, generated by Tools\build_quest_list.py from
-- Wowhead's Forever database, the vanilla server database and the map tables.
-- Quest givers that no database places (new Forever NPCs) get their position
-- from the Voice Over collector the first time you talk to them.
--------------------------------------------------------------------------------

-- (0.19.9) an addon of its own, MelloUI_QuestList (docs/plans/split-addons.md):
-- MelloUI is the global the core sets (its own namespace in a world that
-- loads every file as MelloUI's); the list's files share this addon's
-- namespace (ns.QuestList); each file's load timed under the addon's name
local _, ns = ...
local MelloUI = (ns and ns.MelloUI) or _G.MelloUI
local Perf = MelloUI.Perf:Scope("MelloUI_QuestList (QuestList)")
local hooksecurefunc, C_Timer = Perf.hooksecurefunc, Perf.C_Timer

local M = MelloUI:RegisterModule("QuestList", {
	title = "Quest List",
	desc = "A page in the world map's quest log listing the quests of a zone, how many you have completed, and where each one is picked up.",
	icon = "Interface\\Icons\\INV_Misc_Map_01",
	flavour = "Every quest of the zone in the map's quest log: who gives it, where, and what is left to do.",
	group = "Quests and travel", navOrder = 1,
	role = "feature",
	area = { key = "questList", follows = "QuestLogPanel" },   -- the page in the quest log's column: as the quest log
	keep = { "learnedEntrances", "learnedTransports",   -- pins recorded by hand (older versions kept them here): never in a profile
		"savedQuestPOI" },   -- (0.19.5) the game's Quest Objectives setting as the player had it (Hide The Game's Quest Areas)
	enabledByDefault = true,
	defaults = {
		filter = "zone",
		hideCompleted = false,
		showHidden = false,
		startGiver = true,
		startDrop = true,
		startPickup = true,
		startUnknown = true,
		otherFaction = false,
		otherClass = false,
		levelAbove = 0,
		mapPins = true,
		pinCompleted = false,
		zoneBadges = true,
		zoneProgress = true,
		entrancePins = true,
		transportPins = true,
		objectiveMarks = true,
		objectiveTrackedOnly = false,
		objectiveMinimap = true,
		hideGameObjectives = true,
		hideGrey = false,
		dungeonSummary = true,
		tipQuestItems = true,
		tipTurnIn = true,
		tipCharacters = true,
		view = "log",     -- (the map's quest column: "log", the game's quest log, or "list", this list)
	},
	options = {
		{ type = "header", name = "List" },
		{ type = "dropdown", key = "filter", name = "Show Quests For", values = {
			{ value = "all", label = "All" },
			{ value = "continent", label = "Current continent" },
			{ value = "zone", label = "Current zone" },
			{ value = "class", label = "Class quests" },
			{ value = "dungeons", label = "Dungeons" },
			{ value = "raids", label = "Raids" },
			{ value = "attunements", label = "Attunements" },
			{ value = "events", label = "Events" },
		  },
		  desc = "Which quests the list shows. The dropdown at the top of the list switches this as well." },
		{ type = "toggle", key = "hideCompleted", name = "Hide Completed",
		  desc = "Leave out quests you have already completed instead of greying them." },
		{ type = "toggle", key = "showHidden", name = "Show Hidden Quests",
		  desc = "List the quests you hid (Alt-click a quest giver's mark on the map, or a quest in the list), dimmed, so you can Alt-click them back. Hidden quests stay off the map either way. Hiding is kept per character." },
		{ type = "toggle", key = "startGiver", name = "Quests From a Quest Giver",
		  desc = "List quests picked up from a quest giver or an object (the \"!\"). The gear button on the list switches these as well; they apply to the map pins too." },
		{ type = "toggle", key = "startDrop", name = "Quests From a Mob Drop",
		  desc = "List quests that begin with an item dropped by creatures (crossed swords)." },
		{ type = "toggle", key = "startPickup", name = "Quests From an Item Picked Up",
		  desc = "List quests that begin with an item picked up from the ground or a chest (treasure chest)." },
		{ type = "toggle", key = "startUnknown", name = "Quests Starting Somewhere Unknown",
		  desc = "List quests whose giver or starting item is not known yet." },
		{ type = "toggle", key = "otherFaction", name = "Show Other Faction's Quests",
		  desc = "Also list quests only the other faction can take." },
		{ type = "toggle", key = "otherClass", name = "Show Other Classes' Quests",
		  desc = "Also list quests restricted to classes other than yours." },
		{ type = "slider", key = "levelAbove", name = "Hide Quests More Than N Levels Above Me", min = 0, max = 30, step = 1,
		  format = function(v) return v == 0 and "no limit" or ("+" .. v) end,
		  desc = "Leave out quests whose level is more than this many levels above your character. 0 shows everything." },
		{ type = "header", name = "Map" },
		{ type = "toggle", key = "mapPins", name = "Quest Givers On Zone Maps",
		  desc = "Mark every known quest giver on the zone map with a ! or ? coloured by what you can do there. Hover for the quests, click to track the giver. The List tab's choices apply to the pins too: where quests start (for quests not taken yet), the other faction's and other classes' quests, the levels above yours, and Events (a holiday's givers show while the list shows Events or the quest is in your log)." },
		{ type = "toggle", key = "pinCompleted", parent = "mapPins", name = "Include Givers You Are Done With",
		  desc = "Also mark givers whose quests you have all completed, with a grey tick." },
		{ type = "toggle", key = "hideGrey", parent = "mapPins", name = "Hide Grey Quests",
		  desc = "Leave quests that are grey for you (far below your level, as the game colours them) off the zone map until you take them. Quests in your log and the one you track still show." },
		{ type = "toggle", key = "zoneBadges", name = "Zone Progress On Continent Maps",
		  desc = "Show a done/total badge on each zone of the continent map. Hover for the level range, click to open the zone." },
		{ type = "toggle", key = "zoneProgress", name = "Zone Progress On Zone Maps",
		  desc = "Show the zone's progress in the zone map's corner: a ring of the quests you have done, how many are "
			.. "left, and how many of those you can take now." },
		{ type = "toggle", key = "entrancePins", name = "Dungeon And Raid Entrances",
		  desc = "Mark instance entrances on the zone maps. Hover for the level range and your quest progress, click to list its quests. Entrances of new instances are learned the first time you walk in." },
		{ type = "toggle", key = "transportPins", name = "Boats And Zeppelins",
		  desc = "Mark the docks and zeppelin towers on the zone maps with the destination. Click to route there, Shift-click to open the destination's map." },
		{ type = "toggle", key = "objectiveMarks", name = "Objective Marks",
		  desc = "Mark on the zone map where the quests in your log are done: an outline round each objective's area with one mark for it (a sword to kill, a bag to collect, a cog to use, a flag to explore) and its progress, and the single places as small dots when you zoom in. Hover a mark for the quest, the objective and what drops it; click it for a waypoint. A done objective's marks go; a done quest shows only its hand-in ?." },
		{ type = "toggle", key = "objectiveTrackedOnly", parent = "objectiveMarks", name = "Only The Tracked Quests",
		  desc = "Mark only the quests you track, not every quest in your log." },
		{ type = "toggle", key = "hideGameObjectives", parent = "objectiveMarks", name = "Hide The Game's Quest Areas",
		  desc = "While the objective marks are on, the game's own blue quest areas and quest markers on the world map are switched off, through the game's own Quest Objectives setting (the quest buttons in the game's quest tracker go with it). Turning this or the marks off gives the game's setting back as you had it." },
		{ type = "toggle", key = "objectiveMinimap", parent = "objectiveMarks", name = "On The Minimap",
		  desc = "The same marks on the minimap for the objectives near you, and a small mark on its edge with an arrow for the nearest ones just beyond it. Drawn with Route's minimap drawing, so Route has to be on." },
		{ type = "header", name = "Dungeons" },
		{ type = "toggle", key = "dungeonSummary", name = "Quest Check When Entering An Instance",
		  desc = "When you enter a dungeon or raid, list in chat the quests for it you could have picked up but have not." },
		-- the quest tooltips (0.14.0, QuestListTips.lua): read from your quest
		-- log and the list's data, so they live with the list
		{ type = "header", name = "Tooltips" },
		{ type = "toggle", key = "tipQuestItems", name = "Quest Progress On Items",
		  desc = "On the tooltip of an item one of your quests asks for, name the quest and how many you have, for example \"Quest: Red Linen Goods (4/6)\"." },
		{ type = "toggle", key = "tipTurnIn", name = "Turn-In NPCs",
		  desc = "On the tooltip of an NPC that takes back one of your quests: \"Turn in here\" once the quest is ready, a quieter \"Quest ends here\" while it is still in progress." },
		{ type = "toggle", key = "tipCharacters", name = "Your Other Characters On Quests",
		  desc = "On a quest's tooltip in the Quest List and on the map's quest givers, name your other characters who "
			.. "have done the quest or have it in their quest log. A character is noted each time it logs out; "
			.. "/mello alts lists them and forgets a deleted one." },
	},
})

-- Shared with QuestListPanel.lua and QuestListMap.lua: state and helpers the
-- three files use together. Everything else stays local to its file.
local QL = { M = M }
ns.QuestList = QL
-- (0.19.9) the core's handle: the Quest List is an addon of its own
-- (MelloUI_QuestList), and the core's files reach it here (the quest log's
-- skin, /mello alts); nil while it is not loaded
MelloUI.QuestList = QL

--------------------------------------------------------------------------------
-- Data
--------------------------------------------------------------------------------

-- secret-safe reads, one set for the addon (MelloUI.Safe, Core.lua); QL.Plain(v)
-- is v, or nil when v is secret
local IsSecret = MelloUI.Safe.IsSecret
QL.Plain = MelloUI.Safe.Value

-- Row fields in MelloUI_QuestListData.quests
QL.F_ID, QL.F_TITLE, QL.F_LEVEL, QL.F_REQ, QL.F_SIDE, QL.F_CLASS, QL.F_ZONE, QL.F_GIVERZONE, QL.F_GIVER, QL.F_X, QL.F_Y, QL.F_KIND, QL.F_EVENT, QL.F_CHAIN, QL.F_DUNGEON, QL.F_ATTUNE, QL.F_PREV, QL.F_CONT, QL.F_WX, QL.F_WY =
	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
-- giver NPC id; turn-in: name, NPC id, zone (build-time guess), continent, world x, world y
QL.F_NPC, QL.F_ENDER, QL.F_ENDERNPC, QL.F_ENDERZONE, QL.F_ENDERCONT, QL.F_ENDERWX, QL.F_ENDERWY = 21, 22, 23, 24, 25, 26, 27
-- origin: 1 Classic (classic-db has the quest), 2 Forever's own (the data's;
-- no longer shown: the Classic / Forever logos went, the user 2026-10-09)
QL.F_ORIGIN = 28

-- the givers' and turn-ins' map places resolved after login: at most this
-- many ms a frame (ResolveInChunks)
QL.RESOLVE_MS = 2

-- [questID] = row. Made the first time it is asked for, by the index below,
-- and kept: the data does not change.
local rowByID = nil

local function RowByID()
	if not rowByID then
		rowByID = {}
		local data = MelloUI_QuestListData
		for _, row in ipairs(type(data) == "table" and data.quests or {}) do
			rowByID[row[QL.F_ID]] = row
		end
	end
	return rowByID
end
QL.RowByID = RowByID   -- (the quest tooltips read the turn-ins of the log's quests through it)

-- Who takes a quest back, and where (0.14.0, the tracker's turn-in line):
-- name, npcID, cont, wx, wy, zoneName, from the data -- npcID nil when the
-- data has none (an object, or a name only); cont, wx, wy (the world map
-- id: 0, 1, 2991 ... and world yards) nil when it has no position;
-- zoneName the zone the client put the spot in, else the data's. nil when
-- the data names nobody (the caller keeps its own line then). Read through
-- the by-ID lookup, so it answers with the Quest List off too.
function MelloUI:QuestTurnIn(questID)
	if IsSecret(questID) or type(questID) ~= "number" then
		return nil
	end
	local row = RowByID()[questID]
	local name = row and row[QL.F_ENDER]
	if not name or name == "" then
		return nil
	end
	local npc = row[QL.F_ENDERNPC]
	local cont, wx, wy = row[QL.F_ENDERCONT], nil, nil
	if cont and cont >= 0 then
		wx, wy = row[QL.F_ENDERWX], row[QL.F_ENDERWY]
	else
		cont = nil
	end
	return name, (npc and npc ~= 0) and npc or nil, cont, wx, wy, QL.EnderZoneName(row)
end

QL.byZone = nil        -- [areaID] = { rows }   (pick-up zone, falling back to quest zone)
QL.allRows = nil       -- every zone row, sorted by level once
QL.searchText = nil    -- [row] = lower-cased "title giver zone" for the search box; filled on the first search (below)
QL.byDungeon = nil     -- [dungeonID] = { rows }
QL.chainStep = nil     -- [row] = position in its chain (1 = first)
local chainTotal = nil    -- [chainID] = number of steps
local nextInChain = nil   -- [questID] = the row that follows it
QL.eventRows = nil     -- holiday / world event quests, kept out of the zone lists
QL.zoneByName = nil    -- [lower name] = areaID
local classBit = nil      -- player's class bit in the data's mask
local raceBit = nil       -- player's race bit in the data's race masks (nil: a race the data does not know)
local playerSide = nil    -- 1 Alliance, 2 Horde, 0 Neutral (PlayerSide below)
QL.collapsed = {}      -- [group key] = true while a header is collapsed (per session)
QL.doneOpen = {}       -- (0.19.9) [group key] = true while its Done section is open (shut by default; per session)
QL.trackedQuestID = nil -- quest whose giver the map pin currently points at
QL.RefreshPins = nil   -- redraws the map pins; defined in the map pins section
QL.logChanges = 0      -- QUEST_LOG_UPDATEs seen while the module is on (the quest tooltips' index follows it)

-- Pins recorded by hand (entrances, docks) live with the Route module's
-- learned paths, which the baker keeps across sessions, not in the settings
-- (those are mirrored into account macros and must stay small).
function QL.LearnedStore(kind)
	local R = MelloUI.Route
	local store = R and R.Pins and R:Pins()
	if store then
		-- Older versions kept them in the settings: move them over once.
		local old = M.db and (kind == "entrances" and M.db.learnedEntrances or kind == "transports" and M.db.learnedTransports)
		if type(old) == "table" then
			for name, v in pairs(old) do
				if store[kind][name] == nil then
					store[kind][name] = v
				end
			end
			if kind == "entrances" then M.db.learnedEntrances = nil else M.db.learnedTransports = nil end
		end
		return store[kind]
	end
	local key = kind == "entrances" and "learnedEntrances" or "learnedTransports"
	M.db[key] = M.db[key] or {}
	return M.db[key]
end
QL.resolved = nil      -- [row] = the client's placement of a giver's world position (a number for QL.Placement), false when it cannot place it
local zoneOverride = nil  -- [row] = areaID when the client puts the giver in another zone than the build did
QL.rowsByMap = nil     -- [uiMapID] = rows the client placed on that map
QL.resolvedEnd = nil   -- [row] = placement of the turn-in NPC when it is not the giver, as in QL.resolved
QL.endRowsByMap = nil  -- [uiMapID] = rows whose turn-in the client placed on that map

-- The placements themselves, in four flat lists: the map, the position on
-- the continent map and that continent map. A table with six named fields
-- per placed giver and turn-in held 3.2 MB for about 7000 of them (memory
-- audit, 2026-09-24); the position on the map itself is not kept, it comes
-- again from the map's rectangle (cached), the very numbers it was made of.
local placeMap, placeCX, placeCY, placeCont = {}, {}, {}, {}
local placeCount = 0

-- A world point ResolveWorld placed, kept: its number, or false for none.
local function StorePlacement(mapID, cx, cy, contMapID)
	if not mapID then
		return false
	end
	placeCount = placeCount + 1
	placeMap[placeCount], placeCX[placeCount], placeCY[placeCount], placeCont[placeCount] = mapID, cx, cy, contMapID
	return placeCount
end

-- A placement from QL.resolved / QL.resolvedEnd as ResolveWorld gave it:
-- mapID, cx, cy, contMapID.
function QL.Placement(n)
	return placeMap[n], placeCX[n], placeCY[n], placeCont[n]
end

function QL.Data()
	return MelloUI_QuestListData
end

function QL.ZoneOf(row)
	local override = zoneOverride and zoneOverride[row]
	if override then
		return override
	end
	return row[QL.F_GIVERZONE] ~= 0 and row[QL.F_GIVERZONE] or row[QL.F_ZONE]
end

--------------------------------------------------------------------------------
-- World positions
--
-- Vanilla data gives world coordinates. The client turns them into a
-- continent-map position; the continent map's hit test says which zone (and
-- city) is there, and the zone's rectangle on the continent gives the position
-- on the zone map. Build-time zone guesses are wrong at zone edges and on maps
-- Forever changed (Stormwind with its harbour), so this is done here.
--------------------------------------------------------------------------------

function QL.VectorXY(pos)
	if type(pos) ~= "table" then
		return nil, nil
	end
	local x, y = QL.Plain(pos.x), QL.Plain(pos.y)
	if (x == nil or y == nil) and type(pos.GetXY) == "function" then
		local ok, gx, gy = pcall(pos.GetXY, pos)
		if ok then
			x, y = QL.Plain(gx), QL.Plain(gy)
		end
	end
	return x, y
end

-- Is `mapID` the map `uiMapID` or one of its parents (city inside a zone)?
local function IsOnOrUnder(uiMapID, mapID)
	local id = uiMapID
	for _ = 1, 4 do
		if id == mapID then
			return true
		end
		local ok, info = pcall(C_Map.GetMapInfo, id)
		id = ok and type(info) == "table" and QL.Plain(info.parentMapID) or nil
		if not id or id == 0 then
			return false
		end
	end
	return false
end

local rectCache = {}   -- [contMapID][mapID] = { minX, maxX, minY, maxY } or false
local WHOLE_MAP = { 0, 1, 0, 1 }   -- a map's rectangle on itself

-- Rectangle of a map on its continent map, cached. Keyed by the numbers
-- (no string made per look-up: every placed pin asks for it). A map on
-- itself is the whole map, not asked (a zone that is its own top map:
-- Zephras Isle, 0.14.0).
local function RectOn(mapID, contMapID)
	if mapID == contMapID then
		return WHOLE_MAP
	end
	local onCont = rectCache[contMapID]
	if not onCont then
		onCont = {}
		rectCache[contMapID] = onCont
	end
	local r = onCont[mapID]
	if r == nil then
		local ok, minX, maxX, minY, maxY = pcall(C_Map.GetMapRectOnMap, mapID, contMapID)
		minX, maxX, minY, maxY = QL.Plain(minX), QL.Plain(maxX), QL.Plain(minY), QL.Plain(maxY)
		r = (ok and minX and maxX and minY and maxY and maxX > minX and maxY > minY) and { minX, maxX, minY, maxY } or false
		onCont[mapID] = r
	end
	return r or nil
end

local function InRect(r, cx, cy)
	local x, y = (cx - r[1]) / (r[2] - r[1]), (cy - r[3]) / (r[4] - r[3])
	if x >= 0 and x <= 1 and y >= 0 and y <= 1 then
		return x, y
	end
	return nil
end

-- Is the map a zone (not a continent, the world or an instance)? Cached:
-- asked for each quest placed on a map with no continent above it.
local ZONE_TYPE = type(Enum) == "table" and type(Enum.UIMapType) == "table" and Enum.UIMapType.Zone
ZONE_TYPE = type(ZONE_TYPE) == "number" and ZONE_TYPE or 3
local zoneMaps = {}   -- [mapID] = true / false

local function IsZoneMap(mapID)
	local is = zoneMaps[mapID]
	if is == nil then
		local ok, info = pcall(C_Map.GetMapInfo, mapID)
		is = ok and type(info) == "table" and QL.Plain(info.mapType) == ZONE_TYPE or false
		zoneMaps[mapID] = is
	end
	return is
end

-- A world point as mapID, cx, cy, contMapID: the deepest map that holds it
-- (city before zone), its position on the continent map and that map; or
-- nil. QL.ProjectOnMap gives its position on a map (its own or another).
function QL.ResolveWorld(cont, wx, wy)
	if not (C_Map.GetMapPosFromWorldPos and CreateVector2D and C_Map.GetMapInfoAtPosition and C_Map.GetMapRectOnMap) then
		return nil
	end
	local ok, contMapID, pos = pcall(C_Map.GetMapPosFromWorldPos, cont, CreateVector2D(wx, wy))
	contMapID = ok and QL.Plain(contMapID) or nil
	local cx, cy = QL.VectorXY(pos)
	if not (contMapID and cx and cy) then
		return nil
	end
	local okZ, zinfo = pcall(C_Map.GetMapInfoAtPosition, contMapID, cx, cy)
	local zone = okZ and type(zinfo) == "table" and QL.Plain(zinfo.mapID) or nil
	local x, y
	if not zone or zone == contMapID then
		-- the top map itself: on a continent a gap between zones (placed
		-- nowhere); a zone with no continent above it is its own top map
		-- (Zephras Isle, 2521 right under the world map: the Zephras Isle
		-- fix, 0.14.0), placed on itself
		if not IsZoneMap(contMapID) then
			return nil
		end
		zone, x, y = contMapID, cx, cy
	else
		local r = RectOn(zone, contMapID)
		if r then
			x, y = InRect(r, cx, cy)
		end
		if not x then
			return nil
		end
	end
	-- One level deeper: a city inside the zone.
	local okC, cinfo = pcall(C_Map.GetMapInfoAtPosition, zone, x, y)
	local child = okC and type(cinfo) == "table" and QL.Plain(cinfo.mapID) or nil
	if child and child ~= zone then
		local r2 = RectOn(child, contMapID)
		if r2 and InRect(r2, cx, cy) then
			zone = child
		end
	end
	return zone, cx, cy, contMapID
end

-- Position on the map shown (`onMapID`) of a point ResolveWorld placed on
-- `mapID`: on its own map, a parent or a child, or nil when it is elsewhere.
-- On its own map that is the position ResolveWorld found it at: the same
-- rectangle (cached) and the same continent position.
function QL.ProjectOnMap(onMapID, mapID, cx, cy, contMapID)
	if not mapID then
		return nil
	end
	if mapID ~= onMapID and not (IsOnOrUnder(mapID, onMapID) or IsOnOrUnder(onMapID, mapID)) then
		return nil
	end
	local r = RectOn(onMapID, contMapID)
	if not r then
		return nil
	end
	return InRect(r, cx, cy)
end

-- Giver kinds: 1 NPC, 2 object, and an item that begins the quest: 3 dropped
-- by creatures, 4 picked up from an object; items sit at their densest spot.
QL.KIND_DROP, QL.KIND_PICKUP = 3, 4

function QL.IsItemStart(row)
	local kind = row[QL.F_KIND]
	return kind == QL.KIND_DROP or kind == QL.KIND_PICKUP
end

-- The dungeon or raid a quest's item or object is found in, when it is found
-- only inside one (no spot on the world map), or nil.
function QL.InstanceStart(row)
	if (row[QL.F_GIVER] or "") == "" or not (QL.IsItemStart(row) or row[QL.F_KIND] == 2) then
		return nil
	end
	if row[QL.F_X] ~= 0 or row[QL.F_Y] ~= 0 or (row[QL.F_CONT] or -1) >= 0 then
		return nil
	end
	local zone = row[QL.F_GIVERZONE]
	return zone ~= 0 and QL.Data().dungeons[zone] and zone or nil
end

function QL.IsRaid(dungeonID)
	return QL.Data().raids and QL.Data().raids[dungeonID] == true
end

-- How a quest begun by an item or object is marked instead of the "!" (user,
-- 2026-09-23): crossed swords for an item killed for in the world, a chest
-- for one picked up (ground, chest, object), the entrance icon for one found
-- only inside a dungeon or raid; nil for an NPC giver.
function QL.StarterKind(row)
	local instance = QL.InstanceStart(row)
	if instance then
		return QL.IsRaid(instance) and "raid" or "dungeon"
	end
	local kind = row[QL.F_KIND]
	return kind == QL.KIND_DROP and "drop" or kind == QL.KIND_PICKUP and "pickup" or nil
end

-- What a quest starts from, for the panel's filter: "giver" (an NPC or an
-- object, the "!"), "drop", "pickup", or "unknown".
QL.START_KINDS = {
	{ key = "giver", setting = "startGiver", label = "Quest giver" },
	{ key = "drop", setting = "startDrop", label = "Mob drop" },
	{ key = "pickup", setting = "startPickup", label = "Picked up" },
	{ key = "unknown", setting = "startUnknown", label = "Unknown" },
}

function QL.StartCategory(row)
	if (row[QL.F_GIVER] or "") == "" then
		return "unknown"
	end
	local kind = row[QL.F_KIND]
	return kind == QL.KIND_DROP and "drop" or kind == QL.KIND_PICKUP and "pickup" or "giver"
end

function QL.StartShown(row)
	local cat = QL.StartCategory(row)
	for _, k in ipairs(QL.START_KINDS) do
		if k.key == cat then
			return M.db[k.setting] ~= false
		end
	end
	return true
end

-- Atlases in the order tried (not every client has each), then a plain file.
local STARTER_ICON = {
	drop = { atlas = { "ui-hud-unitframe-player-combaticon" }, file = "Interface/CharacterFrame/UI-StateIcon", coords = { 0.5, 1, 0, 0.484375 } },
	pickup = { atlas = { "VignetteLoot", "Mobile-TreasureIcon" }, file = "Interface/Cursor/Pickup" },
	dungeon = { atlas = { "Dungeon", "DungeonSkull" }, file = "Interface/Minimap/Tracking/None" },
	raid = { atlas = { "Raid", "DungeonSkull" }, file = "Interface/Minimap/Tracking/None" },
}

-- The same icons inline in text (menus): atlas markup, else the file's.
function QL.StarterIconMarkup(key, size)
	size = size or 14
	if key == "giver" then
		return string.format("|A:QuestNormal:%d:%d|a", size, size)
	elseif key == "unknown" then
		return string.format("|TInterface/Minimap/Tracking/None:%d:%d|t", size, size)
	end
	local icon = STARTER_ICON[key]
	if not icon then
		return ""
	end
	for _, atlas in ipairs(icon.atlas) do
		if C_Texture and C_Texture.GetAtlasInfo and C_Texture.GetAtlasInfo(atlas) then
			return string.format("|A:%s:%d:%d|a", atlas, size, size)
		end
	end
	local c = icon.coords or { 0, 1, 0, 1 }
	return string.format("|T%s:%d:%d:0:0:64:64:%d:%d:%d:%d|t", icon.file, size, size, c[1] * 64, c[2] * 64, c[3] * 64, c[4] * 64)
end

function QL.SetStarterIcon(tex, key)
	local icon = STARTER_ICON[key]
	if not icon then
		return false
	end
	for _, atlas in ipairs(icon.atlas) do
		if pcall(tex.SetAtlas, tex, atlas) and tex:GetAtlas() then
			return true
		end
	end
	tex:SetTexture(icon.file)
	local c = icon.coords
	if c then
		tex:SetTexCoord(c[1], c[2], c[3], c[4])
	else
		tex:SetTexCoord(0, 1, 0, 1)
	end
	return true
end

-- An instance's door: uiMapID, x, y from the entrance data, else from an
-- entrance learned by walking in.
function QL.EntrancePoint(dungeonID)
	local data = QL.Data()
	for _, e in ipairs(data.entrances or {}) do
		if e[1] == dungeonID then
			local mapID, cx, cy, contMapID = QL.ResolveWorld(e[3], e[4], e[5])
			if mapID then
				return mapID, QL.ProjectOnMap(mapID, mapID, cx, cy, contMapID)
			end
		end
	end
	local name = (data.dungeons[dungeonID] or ""):lower()
	for learnedName, l in pairs(QL.LearnedStore("entrances") or {}) do
		if learnedName:lower() == name and l.mapID and l.x then
			return l.mapID, l.x, l.y
		end
	end
	return nil
end

-- Who gives a quest, as the list shows it: the NPC or object, or the item.
function QL.GiverLabel(row)
	local giver = row[QL.F_GIVER] or ""
	if giver ~= "" and QL.IsItemStart(row) then
		return "Item: " .. giver
	end
	return giver
end

-- Where a quest giver is: uiMapID, x, y (0..1) from the client's placement,
-- else the build-time zone and map percentage.
function QL.GiverPoint(row)
	local n = QL.resolved and QL.resolved[row]
	if n then
		local mapID = placeMap[n]
		return mapID, QL.ProjectOnMap(mapID, QL.Placement(n))
	end
	if row[QL.F_X] ~= 0 or row[QL.F_Y] ~= 0 then
		return nil, row[QL.F_X] / 100, row[QL.F_Y] / 100
	end
	return nil
end

-- Is the quest handed back to the NPC that gave it?
function QL.SameEnder(row)
	local ender, giver = row[QL.F_ENDER] or "", row[QL.F_GIVER] or ""
	if ender == "" then
		return true
	end
	local enpc, gnpc = row[QL.F_ENDERNPC] or 0, row[QL.F_NPC] or 0
	if enpc ~= 0 and gnpc ~= 0 then
		return enpc == gnpc
	end
	return ender == giver
end

-- Where a quest is handed in: uiMapID, x, y from the client's placement, or nil.
function QL.EndPoint(row)
	local n = QL.resolvedEnd and QL.resolvedEnd[row]
	if n then
		local mapID = placeMap[n]
		return mapID, QL.ProjectOnMap(mapID, QL.Placement(n))
	end
	return nil
end

-- Zone name of the turn-in, from its placement or the build-time guess. A
-- turn-in at the giver's own spot is not placed twice (ResolveInChunks):
-- the giver's placement is its placement then.
function QL.EnderZoneName(row)
	local n = QL.resolvedEnd and QL.resolvedEnd[row]
	if n == nil and QL.resolved and row[QL.F_ENDERCONT] == row[QL.F_CONT]
		and row[QL.F_ENDERWX] == row[QL.F_WX] and row[QL.F_ENDERWY] == row[QL.F_WY] then
		n = QL.resolved[row]
	end
	if n then
		local ok, info = pcall(C_Map.GetMapInfo, placeMap[n])
		local name = ok and type(info) == "table" and QL.Plain(info.name) or nil
		if name then
			return name
		end
	end
	return (row[QL.F_ENDERZONE] or 0) ~= 0 and QL.Data().zones[row[QL.F_ENDERZONE]] or nil
end

function QL.ByLevel(a, b)
	if a[QL.F_LEVEL] ~= b[QL.F_LEVEL] then return a[QL.F_LEVEL] < b[QL.F_LEVEL] end
	return a[QL.F_TITLE] < b[QL.F_TITLE]
end

-- The search box's text for every quest, lower-cased "title giver zone":
-- made on the first search rather than with the index, and let go a while
-- after the panel hides with the box empty (memory audit, 2026-09-24: 0.8 MB
-- held from login, whether the box is used or not). QuestListPanel reads
-- QL.searchText[row]; the first read fills the whole table, from the zones
-- as the index has them.
local PanelHidden
local searchTextMeta = {}
function searchTextMeta.__index(t, row)
	setmetatable(t, nil)   -- once: a row it has no text for stays nil
	local data = QL.Data()
	if type(data) ~= "table" then
		return nil
	end
	local zones = data.zones or {}
	for _, r in ipairs(data.quests or {}) do
		t[r] = (r[QL.F_TITLE] .. " " .. r[QL.F_GIVER] .. " " .. (zones[QL.ZoneOf(r)] or "")):lower()
	end
	-- made while the map is closed (the panel lays itself out on a setting
	-- change even then): no OnHide is coming, so the wait starts here
	local frame = QL.Panel and QL.Panel.frame
	if frame and not frame:IsVisible() then
		PanelHidden()
	end
	return rawget(t, row)
end

local function ForgetSearchText()
	QL.searchText = setmetatable({}, searchTextMeta)
end

-- A term in the panel's search box: the box keeps it when the map closes,
-- and the panel searches it again as soon as it shows.
local function Searching(frame)
	local box = frame.search
	local term = box and box.GetText and box:GetText()
	return type(term) == "string" and term:find("%S") ~= nil
end

-- Let the text go once the panel has been hidden a while with the box empty
-- (not at once: the map is opened and closed all the time; and not with a
-- term left in the box, which every opening searches again -- it was made
-- afresh, 1 MB, on each opening that way; review, 2026-09-24).
local SEARCH_TEXT_KEEP = 30   -- seconds
local panelHides = 0
function PanelHidden()
	panelHides = panelHides + 1
	local hide = panelHides
	C_Timer.After(SEARCH_TEXT_KEEP, function()
		local frame = QL.Panel and QL.Panel.frame
		if hide ~= panelHides or (frame and frame:IsVisible()) then
			return
		end
		-- kept for a term in the box, unless the panel itself is off (the
		-- module is): nothing searches until it is on again
		if frame and frame:IsShown() and Searching(frame) then
			return
		end
		ForgetSearchText()
	end)
end

local function BuildIndex()
	QL.byZone, QL.zoneByName, QL.eventRows, QL.allRows = {}, {}, {}, {}
	ForgetSearchText()
	local data = QL.Data()
	if type(data) ~= "table" then
		return
	end
	local zones = data.zones or {}
	for areaID, name in pairs(zones) do
		QL.zoneByName[name:lower()] = areaID
	end
	-- The client's placements (filled in over a few frames after enable by
	-- ResolveInChunks; the index is rebuilt when they are complete). The zone
	-- a giver lands in wins over the build-time guess.
	zoneOverride, QL.rowsByMap, QL.endRowsByMap = {}, {}, {}
	QL.resolved = QL.resolved or {}
	QL.resolvedEnd = QL.resolvedEnd or {}
	local mapArea = {}
	for _, row in ipairs(data.quests or {}) do
		local n = QL.resolved[row]
		if n then
			local mapID = placeMap[n]
			QL.rowsByMap[mapID] = QL.rowsByMap[mapID] or {}
			table.insert(QL.rowsByMap[mapID], row)
			local areaID = mapArea[mapID]
			if areaID == nil then
				local okI, info = pcall(C_Map.GetMapInfo, mapID)
				local name = okI and type(info) == "table" and QL.Plain(info.name) or nil
				areaID = name and QL.zoneByName[name:lower()] or false
				mapArea[mapID] = areaID
			end
			if areaID and areaID ~= QL.ZoneOf(row) then
				zoneOverride[row] = areaID
			end
		end
		local e = QL.resolvedEnd[row]
		if e then
			local mapID = placeMap[e]
			QL.endRowsByMap[mapID] = QL.endRowsByMap[mapID] or {}
			table.insert(QL.endRowsByMap[mapID], row)
		end
	end
	for _, row in ipairs(data.quests or {}) do
		local zone = QL.ZoneOf(row)
		if (row[QL.F_EVENT] or 0) ~= 0 then
			table.insert(QL.eventRows, row)
		elseif zone ~= 0 then
			QL.byZone[zone] = QL.byZone[zone] or {}
			table.insert(QL.byZone[zone], row)
			QL.allRows[#QL.allRows + 1] = row
		end
	end
	table.sort(QL.eventRows, QL.ByLevel)
	table.sort(QL.allRows, QL.ByLevel)
	for _, rows in pairs(QL.byZone) do
		table.sort(rows, QL.ByLevel)
	end
	-- Chain steps: follow the "previous quest" links back to the chain start.
	QL.chainStep, chainTotal, nextInChain, QL.byDungeon = {}, {}, {}, {}
	RowByID()   -- the by-ID lookup the steps below follow
	for _, row in ipairs(data.quests or {}) do
		if row[QL.F_DUNGEON] ~= 0 then
			QL.byDungeon[row[QL.F_DUNGEON]] = QL.byDungeon[row[QL.F_DUNGEON]] or {}
			table.insert(QL.byDungeon[row[QL.F_DUNGEON]], row)
		end
	end
	local function StepOf(row, depth)
		local step = QL.chainStep[row]
		if step then
			return step
		end
		local prevRow = (row[QL.F_PREV] or 0) ~= 0 and rowByID[row[QL.F_PREV]] or nil
		if prevRow and prevRow[QL.F_CHAIN] == row[QL.F_CHAIN] and depth < 60 then
			step = StepOf(prevRow, depth + 1) + 1
		else
			step = 1
		end
		QL.chainStep[row] = step
		return step
	end
	for _, row in ipairs(data.quests or {}) do
		if row[QL.F_CHAIN] ~= 0 then
			local step = StepOf(row, 0)
			if step > (chainTotal[row[QL.F_CHAIN]] or 0) then
				chainTotal[row[QL.F_CHAIN]] = step
			end
			local prev = row[QL.F_PREV] or 0
			if prev ~= 0 and rowByID[prev] and not nextInChain[prev] then
				nextInChain[prev] = row
			end
		end
	end
	local _, classFile = UnitClass("player")
	for mask, name in pairs(data.classes or {}) do
		if name == classFile then
			classBit = mask
		end
	end
	-- (the eight races the masks know; a newer one is never left out by them)
	local okR, _, _, raceID = pcall(UnitRace, "player")
	raceID = okR and QL.Plain(raceID) or nil
	raceBit = (type(raceID) == "number" and raceID >= 1 and raceID <= 8) and 2 ^ (raceID - 1) or nil
	playerSide = QL.PlayerSide()
end

-- The player's side as the data writes it: 1 Alliance, 2 Horde, and 0 while
-- Neutral (a new Skyborne character before the faction choice): the quests
-- open to both factions only (the Zephras Isle fix, 0.14.0; it counted as
-- Alliance). Route's one side helper (Route.PlayerSide, a plain function
-- that answers with Route off too), so the list, Route and Services agree.
-- (Route.lua loads with every MelloUI; a stripped test world without it
-- counts as Alliance, as before. The rows' own test stays Eligible's: a
-- quest row writes "both" as 0 or 3.)
function QL.PlayerSide()
	local R = MelloUI.Route
	return R and R.PlayerSide and R.PlayerSide() or 1
end

-- The faction picked (or a PvP flag, which comes the same way): the list and
-- the pins follow a new side at once, not after a reload
function QL.SideChanged()
	if playerSide == nil then
		return   -- no index yet: it reads the side when it is made
	end
	local side = QL.PlayerSide()
	if side ~= playerSide then
		playerSide = side
		QL.RefreshPins()
	end
end

-- Ask the client where every vanilla giver and turn-in is, a few hundred rows
-- per frame so login does not stall, then rebuild the index once.
local resolving = false
local resolveDone = false

local function ResolveInChunks(onDone)
	if resolving or resolveDone then
		return
	end
	local data = QL.Data()
	local rows = type(data) == "table" and data.quests or nil
	if not rows or not (C_Map.GetMapPosFromWorldPos and CreateVector2D and C_Map.GetMapInfoAtPosition and C_Map.GetMapRectOnMap) then
		resolveDone = true
		return
	end
	resolving = true
	QL.resolved = QL.resolved or {}
	QL.resolvedEnd = QL.resolvedEnd or {}
	local i, n = 1, #rows
	-- (0.19.2: a time budget per frame, not 300 rows: a row's map conversions
	-- cost about 0.1 ms, so 300 rows were up to 55 ms a frame, 18 frames
	-- running, right after login -- the client's budget for an addon is a
	-- 1000 ms burst refilled at 500 ms a second, and once it is spent the
	-- game cannot call MelloUI's hooks: the user's "attempt to call a nil
	-- value" flood, 2026-10-05. QL.RESOLVE_MS a frame stays far under it)
	local function Step()
		local t0 = debugprofilestop()
		while i <= n do
			local row = rows[i]
			if (row[QL.F_CONT] or -1) >= 0 and QL.resolved[row] == nil then
				QL.resolved[row] = StorePlacement(QL.ResolveWorld(row[QL.F_CONT], row[QL.F_WX], row[QL.F_WY]))
			end
			if (row[QL.F_ENDERCONT] or -1) >= 0 and QL.resolvedEnd[row] == nil
				and not (row[QL.F_ENDERCONT] == row[QL.F_CONT] and row[QL.F_ENDERWX] == row[QL.F_WX] and row[QL.F_ENDERWY] == row[QL.F_WY]) then
				QL.resolvedEnd[row] = StorePlacement(QL.ResolveWorld(row[QL.F_ENDERCONT], row[QL.F_ENDERWX], row[QL.F_ENDERWY]))
			end
			i = i + 1
			if debugprofilestop() - t0 >= QL.RESOLVE_MS then
				break
			end
		end
		if i <= n then
			C_Timer.After(0, Step)
		else
			resolving = false
			resolveDone = true
			onDone()
		end
	end
	Step()
end

-- step, total steps, next row (or nil) for a quest in a chain.
function QL.ChainInfo(row)
	if row[QL.F_CHAIN] == 0 or not QL.chainStep then
		return nil
	end
	return QL.chainStep[row] or 1, chainTotal[row[QL.F_CHAIN]] or 1, nextInChain[row[QL.F_ID]]
end

function QL.Eligible(row)
	local db = M.db
	-- (hidden by hand and not taken: off the map, off the list unless asked for)
	if not db.showHidden and QL.IsHidden(row[QL.F_ID]) and not QL.IsOnQuest(row[QL.F_ID]) then
		return false
	end
	if not db.otherFaction and row[QL.F_SIDE] ~= 0 and row[QL.F_SIDE] ~= 3 and row[QL.F_SIDE] ~= playerSide then
		return false
	end
	if not db.otherClass and row[QL.F_CLASS] ~= 0 and classBit and bit.band(row[QL.F_CLASS], classBit) == 0 then
		return false
	end
	local above = tonumber(db.levelAbove) or 0
	if above > 0 then
		local level = QL.Plain(UnitLevel("player")) or 60
		if row[QL.F_LEVEL] > level + above then
			return false
		end
	end
	return not QL.Closed(row)
end

function QL.IsCompleted(questID)
	if C_QuestLog and C_QuestLog.IsQuestFlaggedCompleted then
		local ok, done = pcall(C_QuestLog.IsQuestFlaggedCompleted, questID)
		if ok and not IsSecret(done) then
			return done == true
		end
	end
	return false
end

function QL.IsOnQuest(questID)
	if C_QuestLog and C_QuestLog.IsOnQuest then
		local ok, on = pcall(C_QuestLog.IsOnQuest, questID)
		if ok and not IsSecret(on) then
			return on == true
		end
	end
	return false
end

-- A quest in the log whose objectives are all done.
local readyChecks = nil
function QL.IsReadyForTurnIn(questID)
	if not readyChecks then
		readyChecks = {}
		for _, name in ipairs({ "ReadyForTurnIn", "IsComplete" }) do
			if C_QuestLog and type(C_QuestLog[name]) == "function" then
				readyChecks[#readyChecks + 1] = C_QuestLog[name]
			end
		end
	end
	for _, fn in ipairs(readyChecks) do
		local ok, ready = pcall(fn, questID)
		if ok and not IsSecret(ready) and ready ~= nil then
			return ready == true
		end
	end
	return false
end

-- What the game asks before it offers a quest (0.19.3; user, 2026-10-05: "the
-- quest list is showing me quests on the map that i can pick up, but when i
-- go there there are no quests"). The data's `needs` (build_quest_list.py:
-- the server's own checks from classic-db; a quest of Forever's own: the
-- quest before it in Wowhead's series), read in two ways:
--   QL.Closed  never offered to this character, now or later: a quest for
--              other races, one above its last level, a breadcrumb whose
--              quest is taken or done, one of a group of which only one can
--              be done once another is taken or done, one below a standing
--              the character is past. Out of the lists, the counts and the
--              map, like another class's quest (QL.Eligible)
--   QL.Unmet   not yet: a quest to do first (or to have in the log), a
--              profession's skill, a standing with a faction, or its giver
--              did not offer it when last asked (Offers, below). Listed,
--              never as one to pick up now, and not on the map
-- (A quest taken or done is the player's own: never closed, never unmet.)
local NO_NEEDS = {}
local function Needs()
	local data = QL.Data()
	return type(data) == "table" and data.needs or NO_NEEDS
end

local function TakenOrDone(questID)
	return QL.IsCompleted(questID) or QL.IsOnQuest(questID)
end

-- [questID] = its group of the data's `exclusive`, made on first use
local exclusiveOf = nil
local function ExclusiveOf(questID)
	if not exclusiveOf then
		exclusiveOf = {}
		for _, members in ipairs(Needs().exclusive or NO_NEEDS) do
			for _, id in ipairs(members) do
				exclusiveOf[id] = members
			end
		end
	end
	return exclusiveOf[questID]
end

-- The character's standing with a faction (the reputation bar's value: 0 is
-- Neutral, 3000 Friendly ...); 0 for one not met yet, nil when it cannot be
-- read (never holding a quest back then)
local function Standing(factionID)
	local ok, value
	if C_Reputation and C_Reputation.GetFactionDataByID then
		local info
		ok, info = pcall(C_Reputation.GetFactionDataByID, factionID)
		if ok and info == nil then
			return 0
		end
		value = ok and type(info) == "table" and QL.Plain(info.currentStanding)
	elseif GetFactionInfoByID then
		local name
		ok, name, _, _, _, _, value = pcall(GetFactionInfoByID, factionID)
		if ok and not name then
			return 0
		end
		value = ok and QL.Plain(value)
	end
	return type(value) == "number" and value or nil
end

-- A profession's skill (with its bonuses, as the server counts it); 0 when not
-- learned, nil when it cannot be read
local function Skill(skillLineID)
	if not (C_SkillInfo and C_SkillInfo.GetSkillLineInfoByID) then
		return nil
	end
	local ok, info = pcall(C_SkillInfo.GetSkillLineInfoByID, skillLineID)
	if not ok then
		return nil
	end
	local rank = type(info) == "table" and QL.Plain(info.rank)
	if type(rank) ~= "number" then
		return info == nil and 0 or nil
	end
	return rank + (QL.Plain(info.tempPoints) or 0) + (QL.Plain(info.modifier) or 0)
end

function QL.Closed(row)
	local id = row[QL.F_ID]
	local needs = Needs()
	local mask = needs.races and needs.races[id]
	if mask and raceBit and bit.band(mask, raceBit) == 0 then
		return true
	end
	local maxLevel = needs.maxLevel and needs.maxLevel[id]
	local target = needs.breadcrumbs and needs.breadcrumbs[id]
	local group = needs.exclusive and ExclusiveOf(id)
	local rep = needs.reps and needs.reps[id]
	local below = rep and rep[3] ~= 0
	-- (0.19.5; user, 2026-10-06: "only the ones i can pick up") the next
	-- quest of its chain taken or done (cmangos' Player::SatisfyQuestNextChain)
	local nextChain = needs.nextChain and needs.nextChain[id]
	if not (maxLevel or target or group or below or nextChain) or TakenOrDone(id) then
		return false
	end
	if nextChain and TakenOrDone(nextChain) then
		return true
	end
	if maxLevel and (QL.Plain(UnitLevel("player")) or 0) > maxLevel then
		return true
	end
	if target and TakenOrDone(target) then
		return true
	end
	if group then
		for _, other in ipairs(group) do
			if other ~= id and TakenOrDone(other) then
				return true
			end
		end
	end
	if below then
		local standing = Standing(rep[3])
		if standing and standing >= rep[4] then
			return true
		end
	end
	return false
end

-- One of `after`'s choices met: a quest done (a negative id: in the log), or
-- every quest of a list
local function AfterMet(choice)
	if type(choice) == "table" then
		for _, id in ipairs(choice) do
			if not AfterMet(id) then
				return false
			end
		end
		return true
	end
	if choice < 0 then
		return QL.IsOnQuest(-choice)
	end
	return QL.IsCompleted(choice)
end

-- The quest to name for a choice not met: itself, or a list's first not done
local function AfterName(choice)
	if type(choice) == "table" then
		for _, id in ipairs(choice) do
			if not AfterMet(id) then
				return math.abs(id)
			end
		end
		return math.abs(choice[1])
	end
	return math.abs(choice)
end

-- (0.19.5) a quest's condition: the data's `cond`, the server's own from
-- classic-db's conditions table (build_quest_list.py condition_tree). True,
-- false, or nil when it cannot be told from here (a place, an instance
-- script, the war effort's supplies, an aura that reads secret): nil never
-- holds a quest back. `depth` bounds a condition that asks whether another
-- quest can be picked up (leaf 19), whose own needs may ask again.
-- Leaves: {8, quest, rev} rewarded, {9, quest, rev} taken, {19, quest}
-- available, {23, item, count, rev} items with the bank (rev: fewer than),
-- {1, spell, rev} the player's aura; {0} cannot tell.
local function ItemCount(itemID)
	local f = C_Item and C_Item.GetItemCount or GetItemCount
	if type(f) ~= "function" then
		return nil
	end
	local ok, n = pcall(f, itemID, true)
	n = ok and QL.Plain(n)
	return type(n) == "number" and n or nil
end

function QL.CondMet(t, depth)
	local kind = t[1]
	if kind == "and" or kind == "or" then
		local unknown = false
		for i = 2, #t do
			local v = QL.CondMet(t[i], depth)
			if v == (kind == "or") then
				return v
			elseif v == nil then
				unknown = true
			end
		end
		if unknown then
			return nil
		end
		return kind == "and"
	elseif kind == "not" then
		local v = QL.CondMet(t[2], depth)
		if v == nil then
			return nil
		end
		return not v
	elseif kind == 8 or kind == 9 then
		local v = (kind == 8 and QL.IsCompleted or QL.IsOnQuest)(t[2])
		return (t[3] == 1) ~= v
	elseif kind == 23 then
		local n = ItemCount(t[2])
		if not n then
			return nil
		end
		local have = n >= math.max(t[3] or 1, 1)
		return (t[4] == 1) ~= have
	elseif kind == 1 then
		if not (C_UnitAuras and C_UnitAuras.GetPlayerAuraBySpellID) then
			return nil
		end
		local ok, aura = pcall(C_UnitAuras.GetPlayerAuraBySpellID, t[2])
		if not ok or IsSecret(aura) then
			return nil
		end
		return (t[3] == 1) ~= (aura ~= nil)
	elseif kind == 19 then
		depth = (depth or 0) + 1
		local row = RowByID()[t[2]]
		if not row or depth > 3 then
			return nil
		end
		if TakenOrDone(t[2]) then
			return false
		end
		return QL.Eligible(row) and QL.Unmet(row, depth) == nil
	end
	return nil
end

-- The words for a condition not met: its first leaf that is false
local function CondWhy(t, depth)
	local kind = t[1]
	if kind == "and" or kind == "or" then
		for i = 2, #t do
			if QL.CondMet(t[i], depth) == false then
				return CondWhy(t[i], depth)
			end
		end
		return nil
	elseif kind == "not" then
		return "Not yet offered to you"
	end
	local rev = (kind == 23 and t[4] or t[3]) == 1
	if kind == 8 or kind == 9 or kind == 19 then
		local other = RowByID()[t[2]]
		local title = other and other[QL.F_TITLE] or "another quest"
		if kind == 8 then
			return (rev and "Only before you hand in %s" or "After %s"):format(title)
		elseif kind == 9 then
			return (rev and "Not while you have %s in your log" or "While you have %s in your log"):format(title)
		end
		return ("While %s can still be picked up"):format(title)
	elseif kind == 23 then
		local ok, name = pcall(C_Item.GetItemNameByID, t[2])
		name = ok and QL.Plain(name) or "an item"
		return (rev and "Only without %s in your bags" or "Needs %s"):format(name)
	elseif kind == 1 then
		return "Needs a special effect on you"
	end
	return nil
end

-- For a quest neither taken nor done (the callers have asked already): nil
-- when the game would offer it now (its level aside: the callers compare
-- that), else why not: "after", questID, inLog (the quest to do first, or to
-- have in the log) / "skill", skill line, skill / "rep", faction, standing /
-- "crumb", questID (a breadcrumb leading to it is in the log) / "cond", its
-- words (the server's condition) / "refused", npc id, giver's name (not
-- offered the last time it was asked)
function QL.Unmet(row, depth)
	local id = row[QL.F_ID]
	local needs = Needs()
	local after = needs.after and needs.after[id]
	if after then
		local list = type(after) == "table" and after or { after }
		local met = false
		for _, choice in ipairs(list) do
			if AfterMet(choice) then
				met = true
				break
			end
		end
		if not met then
			local first = list[1]
			return "after", AfterName(first), type(first) == "number" and first < 0
		end
	end
	local skill = needs.skills and needs.skills[id]
	if skill then
		local have = Skill(skill[1])
		if have and have < math.max(skill[2], 1) then
			return "skill", skill[1], skill[2]
		end
	end
	local rep = needs.reps and needs.reps[id]
	if rep and rep[1] ~= 0 then
		local standing = Standing(rep[1])
		if standing and standing < rep[2] then
			return "rep", rep[1], rep[2]
		end
	end
	-- (0.19.5) a breadcrumb leading to it in the log: the server offers the
	-- quest only once that one is handed in
	local crumbs = needs.crumbsTo and needs.crumbsTo[id]
	if crumbs then
		for _, crumb in ipairs(crumbs) do
			if QL.IsOnQuest(crumb) then
				return "crumb", crumb
			end
		end
	end
	-- (0.19.5) the server's condition, where the client can tell
	local cond = needs.cond and needs.cond[id]
	if cond and QL.CondMet(cond, depth) == false then
		return "cond", CondWhy(cond, depth) or "Not yet offered to you"
	end
	-- (and what the data cannot know: its giver did not offer it, Offers below)
	local npc = QL.RefusedBy(id)
	if npc then
		return "refused", npc, row[QL.F_GIVER]
	end
	return nil
end

-- (the professions quests ask for, by the skill line ids classic-db uses:
-- their names when the character has not learned one, so the game has none)
local SKILL_NAMES = {
	[129] = "First Aid", [164] = "Blacksmithing", [165] = "Leatherworking", [171] = "Alchemy", [182] = "Herbalism",
	[185] = "Cooking", [186] = "Mining", [197] = "Tailoring", [202] = "Engineering", [333] = "Enchanting",
	[356] = "Fishing", [393] = "Skinning",
}
-- the standings by the bar's value where each begins (the game's own words:
-- FACTION_STANDING_LABEL1 .. 8)
local STANDING_AT = { -42000, -6000, -3000, 0, 3000, 9000, 21000, 42000 }

-- QL.Unmet's answer in words, for the tooltips: "After: Quest", "Needs
-- Mining 50", "Needs Honored with the Argent Dawn"
function QL.UnmetText(kind, a, b)
	if kind == "after" then
		local prev = RowByID()[a]
		local title = prev and prev[QL.F_TITLE] or "another quest"
		return (b and "While you have %s in your log" or "After %s"):format(title)
	elseif kind == "skill" then
		local okI, info = pcall(C_SkillInfo.GetSkillLineInfoByID, a)
		local name = okI and type(info) == "table" and QL.Plain(info.name) or SKILL_NAMES[a] or "a profession"
		return b > 0 and ("Needs %s %d"):format(name, b) or ("Needs %s"):format(name)
	elseif kind == "rep" then
		local okI, info = pcall(C_Reputation.GetFactionDataByID, a)
		local name = okI and type(info) == "table" and QL.Plain(info.name) or "a faction"
		for i, at in ipairs(STANDING_AT) do
			local label = _G["FACTION_STANDING_LABEL" .. i]
			if at == b and type(label) == "string" then
				return ("Needs %s with %s"):format(label, name)
			end
		end
		return ("Needs more reputation with %s"):format(name)
	elseif kind == "crumb" then
		local crumb = RowByID()[a]
		return ("Hand in %s first"):format(crumb and crumb[QL.F_TITLE] or "the quest that leads here")
	elseif kind == "cond" then
		return a
	elseif kind == "refused" then
		return ("Not offered when you last talked to %s"):format(b or "its giver")
	end
	return nil
end

-- What the giver itself offered (0.19.3; user, 2026-10-05, at Helene
-- Peltskinner in Goldshire: "im here but there is no quest"). Forever's own
-- quests come with no requirements anywhere -- Wowhead lists none, the
-- client holds none -- and her "Rough Wolf Pelts" is a skinner's. The
-- giver's window is the game's own answer: when a quest giver's gossip or
-- greeting lists what it offers, a quest of the data's for that NPC that it
-- leaves out (neither done nor in the log) is remembered as not offered,
-- for this character, and one it lists is offered again. QL.Unmet reads it:
-- no "!" on the map until
--   a level up or a profession learned  every giver is asked again (all of
--                                       it forgotten)
--   a quest turned in                   its turn-in NPC's quests (the next
--                                       step of a chain the data does not know)
--   the giver is talked to again        what it lists then
-- (A window that cannot be read in full teaches nothing.) Kept per character
-- in MelloUIQuestOffers (SavedVariablesPerCharacter): { level, professions
-- (a bit per PROFESSION_IDS), refused = { [questID] = the giver's npc id } }.
-- Nothing at login: read with the first quest asked about.
local PROFESSION_IDS = { 129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393 }
local Offers = { store = nil, seen = {}, byNpc = nil }   -- seen: what the open window lists (one table, wiped)
QL.Offers = Offers

function Offers.Professions()
	local mask, bitValue = 0, 1
	for _, id in ipairs(PROFESSION_IDS) do
		local have = Skill(id)
		if have and have > 0 then
			mask = mask + bitValue
		end
		bitValue = bitValue * 2
	end
	return mask
end

-- Its refusals forgotten when the level or the professions are not those
-- they were learned at; true when it forgot any
function Offers.Recheck(s)
	local level, professions = QL.Plain(UnitLevel("player")), Offers.Professions()
	if level == s.level and professions == s.professions then
		return false
	end
	s.level, s.professions = level, professions
	if next(s.refused) then
		wipe(s.refused)
		return true
	end
	return false
end

function Offers.Store()
	local s = Offers.store
	if s then
		return s
	end
	s = rawget(_G, "MelloUIQuestOffers")
	if type(s) ~= "table" then
		s = {}
		_G.MelloUIQuestOffers = s
	end
	if type(s.refused) ~= "table" then
		s.refused = {}
	end
	Offers.Recheck(s)
	Offers.store = s
	return s
end

-- the giver's npc id when the data's quest was not offered by it the last
-- time it was asked
function QL.RefusedBy(questID)
	return Offers.Store().refused[questID]
end

-- Quests hidden by hand (0.19.5; the user, 2026-10-06: Questie's manual
-- hide): per character, in this same store (hidden = { [questID] = true };
-- a level up or a profession keeps them, unlike the refusals). A hidden quest
-- is left off the map, and off the list unless Show Hidden Quests is on
-- (QL.Eligible); once taken it shows as ever. Alt-click a giver's mark
-- (every quest it marks that is not taken) or a row (QL.ToggleHidden).
function QL.IsHidden(questID)
	local hidden = Offers.Store().hidden
	return (hidden and hidden[questID] == true) and true or false
end

function QL.HiddenCount()
	local n = 0
	for _ in pairs(Offers.Store().hidden or {}) do
		n = n + 1
	end
	return n
end

function QL.SetHidden(questID, on)
	local s = Offers.Store()
	if type(s.hidden) ~= "table" then
		s.hidden = {}
	end
	s.hidden[questID] = on and true or nil
end

-- the list and the map again after a hide, its sound and its line
local function HiddenChanged(text, on)
	MelloUI:PlayUISound(on and "option_off" or "option_on")
	MelloUI:Announce(text, "silent")
	if QL.Panel and QL.Panel.Update then
		QL.Panel:Update()
	end
	if QL.RefreshPins then
		QL.RefreshPins()
	end
end

-- a row's Alt-click: hidden, or shown again
function QL.ToggleHidden(row)
	local id = row[QL.F_ID]
	local on = not QL.IsHidden(id)
	QL.SetHidden(id, on)
	HiddenChanged((on and "Hidden: " or "Shown again: ") .. row[QL.F_TITLE], on)
end

-- a giver mark's Alt-click: its quests not taken yet hidden (the map's mark
-- groups a giver's quests: { row, state } each)
function QL.HideGiver(group)
	local n, first = 0, nil
	for _, q in ipairs(group.quests or {}) do
		if q.state == "available" or q.state == "locked" then
			QL.SetHidden(q.row[QL.F_ID], true)
			n = n + 1
			first = first or q.row[QL.F_TITLE]
		end
	end
	if n > 0 then
		HiddenChanged(n == 1 and ("Hidden: " .. first) or string.format("Hidden: %d quests from %s", n, group.giver or "this giver"), true)
	end
end

--------------------------------------------------------------------------------
-- The account record (0.19.9, the Completed view: docs/plans/completed-quests.md):
-- which of your characters have done a quest or have it in their log, for the
-- quest tooltips (QL.RecordLines: your OTHER characters -- this one's own state
-- is the tooltip's). Account-wide, in MelloUIQuestRecord (SavedVariables):
-- { chars = { ["Name-Realm"] = { name, realm, class, level, seen,
-- done = { [questID] = true }, log = { [questID] = true } } } }. A character is
-- written as it logs out (PLAYER_LOGOUT: the game's own done set and its quest
-- log as they stand then), so nothing runs at login or per event. /mello alts
-- lists the characters; /mello alts forget <name> lets one go (a deleted
-- character stays until then).
--------------------------------------------------------------------------------
local Record = { me = nil, name = nil, realm = nil, order = nil, names = {} }   -- names: one line's (one table, wiped)
QL.Record = Record
local RECORD_NAMES = 6   -- names on one line, then "and N more"

function Record.Store()
	local s = rawget(_G, "MelloUIQuestRecord")
	if type(s) ~= "table" then
		s = {}
		_G.MelloUIQuestRecord = s
	end
	if type(s.chars) ~= "table" then
		s.chars = {}
	end
	return s
end

-- this character's key ("Name-Realm"), or nil while its name cannot be read
function Record.Me()
	if Record.me then
		return Record.me
	end
	local name = QL.Plain(UnitName("player"))
	local ok, realm = pcall(GetRealmName)
	realm = ok and QL.Plain(realm)
	if type(name) ~= "string" or name == "" or type(realm) ~= "string" then
		return nil
	end
	Record.me, Record.name, Record.realm = name .. "-" .. realm, name, realm
	return Record.me
end

-- This character as it logs out: the game's done set (kept as it was when the
-- game cannot hand it), and the quests in its log (the log's walk shows the
-- quests under open headers only: one met before stays while the game still
-- has it in the log)
function Record.Write()
	local key = Record.Me()
	if not key then
		return
	end
	local chars = Record.Store().chars
	local c = chars[key]
	if type(c) ~= "table" then
		c = {}
		chars[key] = c
	end
	local _, class = UnitClass("player")
	c.name, c.realm, c.class = Record.name, Record.realm, QL.Plain(class)
	c.level, c.seen = QL.Plain(UnitLevel("player")), time()
	local ok, ids = pcall(C_QuestLog.GetAllCompletedQuestIDs)
	if ok and type(ids) == "table" then
		local done = {}
		for _, id in ipairs(ids) do
			id = QL.Plain(id)
			if type(id) == "number" then
				done[id] = true
			end
		end
		c.done = done
	elseif type(c.done) ~= "table" then
		c.done = {}
	end
	local log, old = {}, type(c.log) == "table" and c.log or {}
	local okN, n = pcall(C_QuestLog.GetNumQuestLogEntries)
	n = okN and QL.Plain(n)
	for i = 1, type(n) == "number" and n or 0 do
		local okI, id = pcall(C_QuestLog.GetQuestIDForLogIndex, i)
		id = okI and QL.Plain(id)
		if type(id) == "number" and id > 0 then
			log[id] = true
		end
	end
	for id in pairs(old) do
		if not log[id] then
			local okQ, on = pcall(C_QuestLog.IsOnQuest, id)
			if okQ and QL.Plain(on) == true then
				log[id] = true
			end
		end
	end
	c.log = log
end

-- the other characters, by key (made once a session: their record does not
-- change while this one plays; a forget makes it again)
local function RecordOthers()
	local order = Record.order
	if order then
		return order
	end
	local me = Record.Me()
	order = {}
	for key, c in pairs(Record.Store().chars) do
		if key ~= me and type(c) == "table" then
			order[#order + 1] = key
		end
	end
	table.sort(order)
	if me then
		Record.order = order
	end
	return order
end

-- a character's name as a line shows it: its realm only when it is not yours
local function RecordName(key, c)
	local name = type(c.name) == "string" and c.name or key
	if type(c.realm) == "string" and c.realm ~= Record.realm then
		return name .. "-" .. c.realm
	end
	return name
end

-- the other characters with the quest in one of their sets ("done" or "log"),
-- as one line's list, or nil
local function RecordList(questID, set)
	local names, chars = Record.names, Record.Store().chars
	wipe(names)
	for _, key in ipairs(RecordOthers()) do
		local c = chars[key]
		if type(c) == "table" and type(c[set]) == "table" and c[set][questID] then
			names[#names + 1] = RecordName(key, c)
		end
	end
	local n = #names
	if n == 0 then
		return nil
	end
	if n > RECORD_NAMES then
		for i = n, RECORD_NAMES + 1, -1 do
			names[i] = nil
		end
		return table.concat(names, ", ") .. string.format(" and %d more", n - RECORD_NAMES)
	end
	return table.concat(names, ", ")
end

-- A quest's lines for your other characters (Your Other Characters On Quests,
-- the Quest List's Tooltips): who has done it, who has it in their log.
-- Nothing until a character has been written (the record's first logout).
function QL.RecordLines(tip, questID, indent)
	if not M.db.tipCharacters or type(rawget(_G, "MelloUIQuestRecord")) ~= "table" then
		return
	end
	local done = RecordList(questID, "done")
	if done then
		QL.TipLine(tip, (indent or "") .. "Done by " .. done, "text", true)
	end
	local log = RecordList(questID, "log")
	if log then
		QL.TipLine(tip, (indent or "") .. "In the quest log of " .. log, "text", true)
	end
end

-- /mello alts [forget <name>]: the record's characters, or one let go (by its
-- name, or Name-Realm when two share it; the one you play comes back as it
-- logs out, so it stays)
local ALTS = {
	none = "No characters in the quest record yet: each one is noted as it logs out.",
	head = "Your characters in the quest record (the quest tooltips name them):",
	line = "  %s: level %s %s, %d quests done, %d in the log, last seen %s",
	usage = "/mello alts (your characters in the quest record) | /mello alts forget <name> (let a deleted one go)",
	unknown = "No character called %s in the quest record.",
	twice = "Two characters are called %s: name the realm too (Name-Realm).",
	you = "%s is the character you are playing: it is noted again as you log out.",
	forgot = "Forgotten: %s.",
}

local function RecordCount(t)
	local n = 0
	if type(t) == "table" then
		for _ in pairs(t) do
			n = n + 1
		end
	end
	return n
end

function Record.Slash(rest)
	local word, name = (rest or ""):match("^(%S*)%s*(.-)%s*$")
	local chars = Record.Store().chars
	if word == "forget" and name ~= "" then
		local want, hit, hits = name:lower(), nil, 0
		for key, c in pairs(chars) do
			if key:lower() == want then
				hit, hits = key, 1
				break
			elseif type(c) == "table" and type(c.name) == "string" and c.name:lower() == want then
				hit, hits = key, hits + 1
			end
		end
		if hits == 0 then
			MelloUI:Print(ALTS.unknown, name)
		elseif hits > 1 then
			MelloUI:Print(ALTS.twice, name)
		elseif hit == Record.Me() then
			MelloUI:Print(ALTS.you, hit)
		else
			chars[hit] = nil
			Record.order = nil
			MelloUI:Print(ALTS.forgot, hit)
		end
		return
	elseif word ~= "" then
		MelloUI:Print(ALTS.usage)
		return
	end
	local keys = {}
	for key, c in pairs(chars) do
		if type(c) == "table" then
			keys[#keys + 1] = key
		end
	end
	if #keys == 0 then
		MelloUI:Print(ALTS.none)
		return
	end
	table.sort(keys)
	MelloUI:Print(ALTS.head)
	local classNames = rawget(_G, "LOCALIZED_CLASS_NAMES_MALE")
	for _, key in ipairs(keys) do
		local c = chars[key]
		local class = type(classNames) == "table" and classNames[c.class] or c.class or "?"
		local seen = type(c.seen) == "number" and date("%Y-%m-%d", c.seen) or "?"
		MelloUI:Print(ALTS.line, key, tostring(c.level or "?"), class, RecordCount(c.done), RecordCount(c.log), seen)
	end
end

-- the NPC whose window is open: its creature id, or nil
local function WindowNpc()
	local ok, guid = pcall(UnitGUID, "npc")
	guid = ok and QL.Plain(guid)
	if type(guid) ~= "string" then
		return nil
	end
	local kind, id = guid:match("^(%a+)%-[^-]*%-[^-]*%-[^-]*%-[^-]*%-(%d+)")
	return (kind == "Creature" or kind == "Vehicle") and tonumber(id) or nil
end

-- The quests the open window offers, into `into`; false when they cannot
-- all be read
local function Listed(event, into)
	if event == "GOSSIP_SHOW" then
		local ok, list = pcall(C_GossipInfo.GetAvailableQuests)
		if not ok or type(list) ~= "table" then
			return false
		end
		for _, info in ipairs(list) do
			local id = type(info) == "table" and QL.Plain(info.questID)
			if type(id) ~= "number" then
				return false
			end
			into[id] = true
		end
		return true
	end
	local okN, n = pcall(GetNumAvailableQuests)   -- QUEST_GREETING
	n = okN and QL.Plain(n)
	if type(n) ~= "number" then
		return false
	end
	for i = 1, n do
		local ok, _, _, _, _, id = pcall(GetAvailableQuestInfo, i)
		id = ok and QL.Plain(id)
		if type(id) ~= "number" then
			return false
		end
		into[id] = true
	end
	return true
end

-- [npc id] = the data's quests that NPC gives, made with the first window
local function GivenBy(npcID)
	local byNpc = Offers.byNpc
	if not byNpc then
		byNpc = {}
		for _, row in pairs(RowByID()) do
			local npc = row[QL.F_NPC]
			if npc and npc ~= 0 then
				byNpc[npc] = byNpc[npc] or {}
				table.insert(byNpc[npc], row)
			end
		end
		Offers.byNpc = byNpc
	end
	return byNpc[npcID]
end

-- A quest giver's gossip or greeting (GOSSIP_SHOW, QUEST_GREETING): what it
-- offers now. True when that changed what is known
function Offers.Window(event)
	local npc = WindowNpc()
	local rows = npc and GivenBy(npc)
	if not rows then
		return false
	end
	local seen = Offers.seen
	wipe(seen)
	if not Listed(event, seen) then
		return false
	end
	local refused = Offers.Store().refused
	local changed = false
	for _, row in ipairs(rows) do
		local id = row[QL.F_ID]
		local was = refused[id]
		if seen[id] or TakenOrDone(id) then
			refused[id] = nil
		else
			refused[id] = npc
		end
		changed = changed or refused[id] ~= was
	end
	return changed
end

-- A quest's details from its giver (QUEST_DETAIL): offered
function Offers.Detail()
	local ok, id = pcall(GetQuestID)
	id = ok and QL.Plain(id)
	local refused = Offers.Store().refused
	if type(id) == "number" and refused[id] then
		refused[id] = nil
		return true
	end
	return false
end

-- A quest turned in (QUEST_TURNED_IN): its turn-in NPC is asked again
function Offers.TurnedIn(questID)
	local row = type(questID) == "number" and RowByID()[questID]
	local ender = row and row[QL.F_ENDERNPC]
	if not ender or ender == 0 then
		return false
	end
	local refused = Offers.Store().refused
	local changed = false
	for id, npc in pairs(refused) do
		if npc == ender then
			refused[id] = nil
			changed = true
		end
	end
	return changed
end

-- A level up (PLAYER_LEVEL_UP) or a skill changed (SKILL_LINES_CHANGED, a
-- profession learned among them): asked again when either moved
function Offers.Changed()
	return Offers.store ~= nil and Offers.Recheck(Offers.store)
end

-- The quest log walk, one for the Quest List (the panel's sums and the
-- quest tooltips' index; 0.14.0). QL.LogCalls: the log read by C_QuestLog
-- (true), the older calls (false) or not at all (nil).
function QL.LogCalls()
	if C_QuestLog and C_QuestLog.GetNumQuestLogEntries and C_QuestLog.GetQuestIDForLogIndex then
		return true
	elseif _G.GetNumQuestLogEntries and _G.GetQuestLogTitle then
		return false
	end
	return nil
end

-- the log's lines (headers too) and quests, nil when it cannot be read
function QL.LogSize(modern)
	local ok, lines, quests
	if modern then
		ok, lines, quests = pcall(C_QuestLog.GetNumQuestLogEntries)
	elseif modern == false then
		ok, lines, quests = pcall(_G.GetNumQuestLogEntries)
	end
	if not ok then
		return nil
	end
	lines, quests = QL.Plain(lines), QL.Plain(quests)
	if type(lines) ~= "number" or type(quests) ~= "number" then
		return nil
	end
	return lines, quests
end

-- the quest id on a log line, nil for a header
function QL.LogQuestID(modern, i)
	local ok, id
	if modern then
		ok, id = pcall(C_QuestLog.GetQuestIDForLogIndex, i)
	else
		local _, isHeader
		ok, _, _, _, isHeader, _, _, _, id = pcall(_G.GetQuestLogTitle, i)
		if ok and QL.Plain(isHeader) then
			return nil
		end
	end
	id = ok and QL.Plain(id) or nil
	return (type(id) == "number" and id > 0) and id or nil
end

-- The quests in the log: their ids into `into` (emptied first: one table
-- kept and filled again), then true when that is every quest of the log
-- (false when a folded header hides some, or the log cannot be read)
function QL.LogQuestIDs(into)
	wipe(into)
	local modern = QL.LogCalls()
	local lines, quests = QL.LogSize(modern)
	for i = 1, lines or 0 do
		local id = QL.LogQuestID(modern, i)
		if id then
			into[#into + 1] = id
		end
	end
	return lines ~= nil and #into >= quests
end

-- Quest log colouring: grey trivial, green easy, yellow fair, orange hard, red very hard.
-- The level the game colours a quest by: for a quest in the log its own
-- difficulty level (C_QuestLog.GetInfo, which can sit under the level shown
-- -- user, 2026-09-23: a quest green in the quest log was yellow in the
-- list), else the level of the data
function QL.ColourLevel(row)
	local level = row[QL.F_LEVEL]
	if C_QuestLog and C_QuestLog.GetLogIndexForQuestID and C_QuestLog.GetInfo then
		local ok, index = pcall(C_QuestLog.GetLogIndexForQuestID, row[QL.F_ID])
		index = ok and QL.Plain(index) or nil
		if index then
			local okI, info = pcall(C_QuestLog.GetInfo, index)
			local d = okI and type(info) == "table" and (QL.Plain(info.difficultyLevel) or QL.Plain(info.level)) or nil
			if type(d) == "number" and d > 0 then
				level = d
			end
		end
	end
	return level
end

-- A quest grey for you, as the game colours it (DifficultyUtil.
-- GetRelativeDifficultyColor: more than 4 levels under yours and further
-- than your trivial range, UnitQuestTrivialLevelRange); where the client
-- has no range, QL.DifficultyColor's own steps. A quest of no known level
-- is never grey.
function QL.IsGrey(row)
	local level = row[QL.F_LEVEL]
	local mine = type(UnitEffectiveLevel) == "function" and QL.Plain(UnitEffectiveLevel("player")) or nil
	if type(mine) ~= "number" then
		mine = QL.Plain(UnitLevel("player"))
	end
	if type(level) ~= "number" or level <= 0 or type(mine) ~= "number" then
		return false
	end
	local below = mine - level
	if below <= 4 then
		return false
	end
	local range
	if type(UnitQuestTrivialLevelRange) == "function" then
		local ok, r = pcall(UnitQuestTrivialLevelRange, "player")
		range = ok and QL.Plain(r) or nil
	end
	if type(range) == "number" then
		return below > range
	end
	local trivial = mine >= 40 and 12 or mine >= 30 and 9 or mine >= 20 and 7 or mine >= 10 and 6 or 5
	return below >= trivial
end

-- (0.19.5, the user's Hide Grey Quests; Questie hides them by default) a
-- quest not taken yet that the map leaves out for being grey -- never one in
-- the log, never the tracked one
function QL.GreyHidden(row, state)
	return state == "available" and M.db.hideGrey == true and QL.trackedQuestID ~= row[QL.F_ID] and QL.IsGrey(row)
end

function QL.DifficultyColor(level)
	if level <= 0 then
		return 0.75, 0.61, 0
	end
	if GetQuestDifficultyColor then
		local ok, color = pcall(GetQuestDifficultyColor, level)
		if ok and type(color) == "table" and color.r then
			return color.r, color.g, color.b
		end
	end
	local mine = QL.Plain(UnitLevel("player")) or 60
	local diff = level - mine
	if diff >= 5 then return 1, 0.1, 0.1 end
	if diff >= 3 then return 1, 0.5, 0.25 end
	if diff >= -2 then return 1, 0.82, 0 end
	local trivial = 5
	if mine >= 40 then trivial = 12 elseif mine >= 30 then trivial = 9 elseif mine >= 20 then trivial = 7 elseif mine >= 10 then trivial = 6 end
	if diff > -trivial then return 0.25, 0.75, 0.25 end
	return 0.5, 0.5, 0.5
end

--------------------------------------------------------------------------------
-- Tooltip lines (0.14.0, the palettes): the one helper for the lines the
-- Quest List writes -- its rows, the map's pins, the quest lines it adds to
-- the game's own tooltips. A line's colour is named, and read as the line is
-- added (a palette switch shows on the next tooltip):
--   a palette role   selectedTrim a title or a highlight; text the body and
--                    the hints (small text is never mutedText, the palette
--                    rule -- but for the user's own muted "Quest ends here")
--   a meaning colour one of QL.MEANING, the same under every palette
-- The quest's difficulty colour (QL.DifficultyColor) is the game's, as the
-- quest log shows it, and is handed over as it is.
--   QL.TipTitle(tip, text[, name])       the first line (selectedTrim when no name)
--   QL.TipLine(tip, text, name[, wrap])  one more line
--   QL.TipColour(name) -> r, g, b
--------------------------------------------------------------------------------

QL.MEANING = {
	questGold = { 1, 0.82, 0 },   -- a quest to pick up or hand in: the game's own "!" and "?" gold (meaning colour)
	pinHint = { 0.6, 0.8, 1 },    -- the map's quest-giver blue: a map pin's or waypoint's click, the tracked giver's name (meaning colour)
	alliance = { 0.3, 0.6, 1 },   -- a transport of the Alliance (meaning colour)
	horde = { 1, 0.3, 0.3 },      -- a transport of the Horde (meaning colour)
}

-- (the palette as the Quest List's look shows it -- the Quest Log's switch, the
-- user's pick 2026-10-02: the game's colours while that look is off)
function QL.TipColour(name)
	local c = QL.MEANING[name] or MelloUI.Look.Palette("questList")[name]
	return c[1], c[2], c[3]
end

function QL.TipLine(tip, text, name, wrap)
	local c = QL.MEANING[name] or MelloUI.Look.Palette("questList")[name]
	tip:AddLine(text, c[1], c[2], c[3], wrap)
end

function QL.TipTitle(tip, text, name)
	name = name or "selectedTrim"
	local c = QL.MEANING[name] or MelloUI.Look.Palette("questList")[name]
	tip:SetText(text, c[1], c[2], c[3])
end

--------------------------------------------------------------------------------
-- Map helpers
--------------------------------------------------------------------------------

local mapIDByName = nil

local function MapIDForZoneName(name)
	if not mapIDByName then
		mapIDByName = {}
		local ok, root = pcall(C_Map.GetFallbackWorldMapID)
		root = ok and QL.Plain(root) or 947
		local okC, children = pcall(C_Map.GetMapChildrenInfo, root, nil, true)
		if okC and type(children) == "table" then
			for _, info in ipairs(children) do
				local n = QL.Plain(info.name)
				local id = QL.Plain(info.mapID)
				if n and id and not mapIDByName[n:lower()] then
					mapIDByName[n:lower()] = id
				end
			end
		end
	end
	return mapIDByName[name:lower()]
end

function QL.ZoneNameForMap(mapID)
	if not mapID then
		return nil
	end
	local ok, info = pcall(C_Map.GetMapInfo, mapID)
	if ok and info then
		return QL.Plain(info.name)
	end
	return nil
end

local function CurrentMapID()
	local ok, id = pcall(WorldMapFrame.GetMapID, WorldMapFrame)
	local mapID = ok and QL.Plain(id) or nil
	if not mapID then
		local okP, pid = pcall(C_Map.GetBestMapForUnit, "player")
		mapID = okP and QL.Plain(pid) or nil
	end
	return mapID
end

function QL.CurrentAreaID()
	local mapID = CurrentMapID()
	local name = QL.ZoneNameForMap(mapID)
	if not name then
		return nil, nil
	end
	local areaID = QL.zoneByName[name:lower()]
	if not areaID then
		-- A continent or the world is shown: use the zone the player is in.
		local okP, pid = pcall(C_Map.GetBestMapForUnit, "player")
		local pname = QL.ZoneNameForMap(okP and QL.Plain(pid) or nil)
		if pname then
			areaID, name = QL.zoneByName[pname:lower()], pname
		end
	end
	return areaID, name
end

-- The continent a zone of the data is grouped under by the Continent filter:
-- the data's (0 Eastern Kingdoms, 1 Kalimdor, 2991 Zephras Isle), or for a
-- zone the data places on no continent (-1) the zone on its own, as
-- -areaID (the Zephras Isle fix, 0.14.0: such a zone showed "Unknown
-- continent" and an empty list). The data's table is written that way on
-- the first ask (its -1 zones, once), so its other reader -- the panel's
-- Continent filter, `zoneContinent[zone] == c` -- lists such a zone's
-- quests alone. nil for a zone the data does not know.
function QL.ContinentOfZone(areaID)
	local data = QL.Data()
	local map = type(data) == "table" and data.zoneContinent
	if type(map) ~= "table" then
		return nil
	end
	if QL.ownContinents ~= map then
		QL.ownContinents = map
		for id, c in pairs(map) do
			if c == -1 and type(id) == "number" then
				map[id] = -id
			end
		end
	end
	return areaID and map[areaID] or nil
end

-- Continent of the map shown (as QL.ContinentOfZone), walking up the map
-- tree: its id and name.
function QL.CurrentContinent()
	local mapID = CurrentMapID()
	for _ = 1, 6 do
		if not mapID then break end
		local ok, info = pcall(C_Map.GetMapInfo, mapID)
		if not ok or not info then break end
		local name = QL.Plain(info.name)
		if name then
			for c, cname in pairs(QL.Data().continentNames or {}) do
				if cname:lower() == name:lower() then
					return c, cname
				end
			end
		end
		mapID = QL.Plain(info.parentMapID)
		if not mapID or mapID == 0 then break end
	end
	local areaID, zoneName = QL.CurrentAreaID()
	local c = QL.ContinentOfZone(areaID)
	if c then
		-- (a zone on its own is named as the zone)
		local names = QL.Data().continentNames
		return c, names and names[c] or zoneName
	end
	return nil, nil
end

-- The quest's giver (or turn-in) as the waypoint. True when set; the second
-- answer (here and in QL.RouteToPoint) is true when Route took it and its
-- notice says so with a sound, so the caller plays no click sound of its own
function QL.SetWaypoint(row, atEnder)
	local mapID, x, y
	if atEnder then
		mapID, x, y = QL.EndPoint(row)
	end
	if not x then
		mapID, x, y = QL.GiverPoint(row)
	end
	-- An item found only inside a dungeon or raid: to its entrance.
	local instance = not x and not atEnder and QL.InstanceStart(row)
	if instance then
		mapID, x, y = QL.EntrancePoint(instance)
	end
	if not x then
		return false
	end
	if not mapID then
		local zoneName = QL.Data().zones[QL.ZoneOf(row)]
		mapID = zoneName and MapIDForZoneName(zoneName)
	end
	if not mapID or not C_Map.SetUserWaypoint or not UiMapPoint then
		return false
	end
	local okCan, can = pcall(C_Map.CanSetUserWaypointOnMap, mapID)
	if okCan and can == false then
		return false
	end
	-- Through the Route module when it is on: pin, route, label and notice in one.
	local R = MelloUI.Route
	if R and R.isEnabled and R.SetDestinationTo then
		local who = atEnder and (row[QL.F_ENDER] or "") ~= "" and row[QL.F_ENDER] or row[QL.F_GIVER]
		local icon = atEnder and "|A:QuestTurnin:16:16|a " or "|A:QuestNormal:16:16|a "
		local label = icon .. row[QL.F_TITLE] .. (who ~= "" and (" - " .. who) or "")
		local what = atEnder and "turn-in" or QL.IsItemStart(row) and "item" or "quest giver"
		local text = string.format("%sTracking %s %s for %s, {dist} away", icon, what, who ~= "" and who or "", row[QL.F_TITLE])
		if instance then
			local kind = QL.IsRaid(instance) and "raid" or "dungeon"
			icon = QL.IsRaid(instance) and "|A:Raid:16:16|a " or "|A:Dungeon:16:16|a "
			label = icon .. row[QL.F_TITLE] .. " - " .. QL.Data().dungeons[instance]
			text = string.format("%sTracking the %s entrance of %s for %s (%s is found inside), {dist} away", icon, kind,
				QL.Data().dungeons[instance], row[QL.F_TITLE], who)
		end
		if R:SetDestinationTo({ mapID = mapID, x = x, y = y }, label, true, text) then
			QL.trackedQuestID = row[QL.F_ID]
			return true, R.AnnounceSounds ~= nil and R:AnnounceSounds()
		end
	end
	local point = UiMapPoint.CreateFromCoordinates(mapID, x, y)
	local ok = pcall(C_Map.SetUserWaypoint, point)
	if ok and C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then
		pcall(C_SuperTrack.SetSuperTrackedUserWaypoint, true)
	end
	if ok then
		QL.trackedQuestID = row[QL.F_ID]
	end
	return ok
end

-- Route to a point on a map (entrance, dock, flight master): the Route
-- module when it is on, else a plain user waypoint.
function QL.RouteToPoint(mapID, x, y, label, notice)
	if not (mapID and x and y) then
		return false
	end
	local R = MelloUI.Route
	if R and R.isEnabled and R.SetDestinationTo then
		if R:SetDestinationTo({ mapID = mapID, x = x, y = y }, label, true, notice) then
			return true, R.AnnounceSounds ~= nil and R:AnnounceSounds()
		end
		return false
	end
	if not (C_Map.SetUserWaypoint and UiMapPoint) then
		return false
	end
	local okCan, can = pcall(C_Map.CanSetUserWaypointOnMap, mapID)
	if okCan and can == false then
		return false
	end
	local ok = pcall(C_Map.SetUserWaypoint, UiMapPoint.CreateFromCoordinates(mapID, x, y))
	if ok and C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then
		pcall(C_SuperTrack.SetSuperTrackedUserWaypoint, true)
	end
	return ok
end

function QL.ClearWaypoint()
	if C_Map.ClearUserWaypoint then
		pcall(C_Map.ClearUserWaypoint)
	end
	QL.trackedQuestID = nil
end

-- The pin can be removed from the map itself; forget the quest then.
function QL.SyncTracked()
	if QL.trackedQuestID and C_Map.HasUserWaypoint then
		local ok, has = pcall(C_Map.HasUserWaypoint)
		if ok and has == false then
			QL.trackedQuestID = nil
		end
	end
end

--------------------------------------------------------------------------------
-- Dungeon check on entering an instance
--------------------------------------------------------------------------------

local lastInstance = nil

local function DungeonSummary()
	if not (M.isEnabled and M.db.dungeonSummary and QL.byZone) then
		return
	end
	local okI, inInstance, kind = pcall(IsInInstance)
	if not okI or not inInstance or (kind ~= "party" and kind ~= "raid") then
		lastInstance = nil
		return
	end
	local okN, name = pcall(GetInstanceInfo)
	name = okN and QL.Plain(name) or nil
	if not name or name == lastInstance then
		return
	end
	lastInstance = name
	local data = QL.Data()
	local dungeonID
	for id, dname in pairs(data.dungeons or {}) do
		if dname:lower() == name:lower() then
			dungeonID = id
		end
	end
	if not dungeonID then
		return
	end
	local missing, inLog, done, total, later = {}, 0, 0, 0, 0
	for _, row in ipairs(data.quests or {}) do
		if row[QL.F_DUNGEON] == dungeonID and QL.Eligible(row) then
			total = total + 1
			if QL.IsCompleted(row[QL.F_ID]) then
				done = done + 1
			elseif QL.IsOnQuest(row[QL.F_ID]) then
				inLog = inLog + 1
			elseif QL.Unmet(row) then
				later = later + 1   -- (not offered yet: another quest first, a skill, a standing)
			else
				missing[#missing + 1] = row
			end
		end
	end
	if total == 0 then
		return
	end
	MelloUI:Print("%s: %d of %d quests done, %d in your log, %d not picked up%s.", name, done, total, inLog, #missing,
		later > 0 and string.format(", %d not offered yet", later) or "")
	for _, row in ipairs(data.quests or {}) do
		if row[QL.F_DUNGEON] == dungeonID and QL.Eligible(row) and QL.IsOnQuest(row[QL.F_ID]) and QL.IsReadyForTurnIn(row[QL.F_ID]) and (row[QL.F_ENDER] or "") ~= "" then
			local endZone = QL.EnderZoneName(row) or QL.Data().zones[QL.ZoneOf(row)]
			print(string.format("   |cffffd200%s|r is ready: turn in to %s%s", row[QL.F_TITLE], row[QL.F_ENDER], endZone and (" in " .. endZone) or ""))
		end
	end
	table.sort(missing, QL.ByLevel)
	for i, row in ipairs(missing) do
		if i > 12 then
			print(string.format("   ... and %d more; see the Dungeons tab of the quest list.", #missing - 12))
			break
		end
		local r, g, b = QL.DifficultyColor(row[QL.F_LEVEL])
		local zone = data.zones[row[QL.F_GIVERZONE]] or data.zones[row[QL.F_ZONE]]
		local from = row[QL.F_GIVER] ~= "" and row[QL.F_GIVER] or "giver unknown"
		print(string.format("   |cff%02x%02x%02x%s|r (%d)  -  %s%s", r * 255, g * 255, b * 255, row[QL.F_TITLE], row[QL.F_LEVEL],
			from, zone and (", " .. zone) or ""))
	end
end

--------------------------------------------------------------------------------
-- Module lifecycle
--------------------------------------------------------------------------------

local eventFrame = CreateFrame("Frame")
Perf.SetScript(eventFrame, "OnEvent", function(_, event, ...)
	if event == "PLAYER_ENTERING_WORLD" then
		-- Instance info and quest flags settle a moment after the load.
		C_Timer.After(2, function()
			if not QL.LearnEntrance() then
				C_Timer.After(6, QL.LearnEntrance)
			end
			DungeonSummary()
		end)
		if QL.pendingExit then
			C_Timer.After(1, QL.LearnEntranceOnExit)
		end
	elseif event == "UNIT_SPELLCAST_SUCCEEDED" then
		-- Hearthstone or Astral Recall out of the instance: the arrival point
		-- is not the door.
		local _, _, spellID = ...
		spellID = QL.Plain(spellID)
		if spellID == 8690 or spellID == 556 then
			QL.pendingExit = nil
		end
	elseif event == "PLAYER_LEAVING_WORLD" or event == "ZONE_CHANGED" or event == "ZONE_CHANGED_INDOORS" or event == "ZONE_CHANGED_NEW_AREA" then
		QL.RememberOutside()
	elseif event == "QUEST_LOG_UPDATE" then
		-- counted only: the quest tooltips make their index again on the
		-- next tooltip that needs it (QuestListTips.lua)
		QL.logChanges = QL.logChanges + 1
		-- (0.19.5) the objective marks follow the log's progress while the map
		-- shows (once after a burst: QuestListObjectives.lua)
		if QL.Objectives then
			QL.Objectives.LogChanged()
		end
	elseif event == "PLAYER_LOGOUT" then
		-- (0.19.9) this character into the account record (QL.Record)
		QL.Record.Write()
		return
	elseif event == "NEUTRAL_FACTION_SELECT_RESULT" or (event == "UNIT_FACTION" and QL.Plain(...) == "player") then
		QL.SideChanged()
	else
		-- what the givers offer (Offers): the pins follow what was learned
		local changed
		if event == "GOSSIP_SHOW" or event == "QUEST_GREETING" then
			changed = QL.Offers.Window(event)
		elseif event == "QUEST_DETAIL" then
			changed = QL.Offers.Detail()
		elseif event == "QUEST_TURNED_IN" then
			changed = QL.Offers.TurnedIn(QL.Plain(...))
		elseif event == "PLAYER_LEVEL_UP" or event == "SKILL_LINES_CHANGED" then
			changed = QL.Offers.Changed()
		end
		if changed then
			QL.RefreshPins()
		end
	end
	if WorldMapFrame and WorldMapFrame:IsShown() then
		QL.Panel:Schedule()
	end
end)

local hooked = false

-- the side window's settings, gone with it after 0.18.0 (its Panel Width
-- and its fold): a saved value is dropped, so no profile, share string or
-- backup carries a setting that no longer exists
local GONE = { "width", "folded" }

function M:OnInit(db)
	self.db = db
	for _, key in ipairs(GONE) do
		db[key] = nil
	end
end

-- (0.19.8) switched on after the login's PLAYER_ENTERING_WORLD (Core's
-- start-up pass over the login's first frames): that event as it came
function M:OnLoginWorld(...)
	MelloUI:ReplayWorld(eventFrame, ...)
end

function M:OnEnable(db)
	self.db = db
	if type(MelloUI_QuestListData) ~= "table" then
		MelloUI:Print("Quest List: its quest data (Media\\QuestListData.lua) is missing, so the list stays off. Reinstall MelloUI from its download, copying every folder.")
		return
	end
	if not WorldMapFrame then
		return
	end
	-- the quest tooltips (QuestListTips.lua): their two post-calls, once;
	-- the log may have changed while the module was off (QUEST_LOG_UPDATE,
	-- which counts the changes, is registered below with the module's
	-- other events)
	QL.logChanges = QL.logChanges + 1
	if QL.InstallTips then
		QL.InstallTips()
	end
	if not QL.byZone then
		BuildIndex()
	else
		playerSide = QL.PlayerSide()   -- a faction picked while the list was off
	end
	QL.Panel:Create()
	QL.Panel:Apply()
	QL.CreateProvider()
	QL.RefreshPins()
	ResolveInChunks(function()
		BuildIndex()
		if QL.Panel.frame and QL.Panel.frame:IsShown() then
			QL.Panel:Update()
		end
		QL.RefreshPins()
	end)
	if not hooked then
		hooked = true
		if WorldMapFrame.OnMapChanged then
			-- quiet: a map that lists the same quests is not laid out again
			hooksecurefunc(WorldMapFrame, "OnMapChanged", function() QL.Panel:Update(true) end)
		end
		-- the page is the addon's own frame (in the layer over the map): its
		-- search text goes a while after it hides
		if QL.Panel.frame then
			Perf.HookScript(QL.Panel.frame, "OnHide", PanelHidden)
		end
	end
	-- the events go with the module's state (they ran on after a disable;
	-- audit 2026-09-22)
	eventFrame:RegisterEvent("QUEST_LOG_UPDATE")
	eventFrame:RegisterEvent("ZONE_CHANGED_NEW_AREA")
	eventFrame:RegisterEvent("PLAYER_LEVEL_UP")
	eventFrame:RegisterEvent("PLAYER_ENTERING_WORLD")
	eventFrame:RegisterEvent("PLAYER_LEAVING_WORLD")
	eventFrame:RegisterEvent("ZONE_CHANGED")
	eventFrame:RegisterEvent("ZONE_CHANGED_INDOORS")
	eventFrame:RegisterEvent("PLAYER_LOGOUT")   -- (the account record: QL.Record)
	-- (what the quest givers offer: QL.Offers)
	for _, event in ipairs({ "GOSSIP_SHOW", "QUEST_GREETING", "QUEST_DETAIL", "QUEST_TURNED_IN", "SKILL_LINES_CHANGED" }) do
		eventFrame:RegisterEvent(event)
	end
	if eventFrame.RegisterUnitEvent then
		eventFrame:RegisterUnitEvent("UNIT_SPELLCAST_SUCCEEDED", "player")
		eventFrame:RegisterUnitEvent("UNIT_FACTION", "player")
	else
		eventFrame:RegisterEvent("UNIT_SPELLCAST_SUCCEEDED")
		eventFrame:RegisterEvent("UNIT_FACTION")
	end
	-- a Neutral character picking its faction (Zephras Isle, 0.14.0),
	-- registered as Route registers it: only where this client has the
	-- event (a RegisterEvent of an unknown one raises)
	pcall(eventFrame.RegisterEvent, eventFrame, "NEUTRAL_FACTION_SELECT_RESULT")
	QL.StartOutsideTicker()
	if QL.Objectives then
		QL.Objectives.GameMarks()   -- (the game's own quest areas off while the objective marks are on)
	end
end

function M:OnDisable()
	eventFrame:UnregisterAllEvents()
	QL.StopOutsideTicker()
	-- the page and its switch gone, the game's list given back
	if QL.Panel.frame then
		QL.Panel:Sync(true)
	end
	-- off with the map closed, the panel's OnHide never comes: the search
	-- text goes now (the first search after an enable makes it again)
	if QL.searchText then
		ForgetSearchText()
	end
	if QL.Provider and WorldMapFrame then
		QL.Provider:RemoveAllData()
	end
	if QL.Objectives then
		QL.Objectives.MiniSoon()   -- (off: the minimap's marks go)
		QL.Objectives.GameMarks()   -- (and the game's own quest areas come back)
	end
end

function M:OnSettingChanged(key, value, db)
	self.db = db
	if key == "tipQuestItems" or key == "tipTurnIn" or key == "tipCharacters" then
		return   -- read by the next tooltip; the panel and the pins show neither
	end
	QL.Panel:Apply()
	QL.RefreshPins()
	if QL.Objectives then
		QL.Objectives.MiniSoon()   -- (the minimap's marks: their switches, the tracked-only choice)
		QL.Objectives.GameMarks()   -- (the game's own quest areas: off while the marks are on)
	end
end

-- /qlmap: why pins are (not) on the map shown.
SLASH_MELLOQUESTMAP1 = "/qlmap"
SlashCmdList.MELLOQUESTMAP = function(msg)
	local data = QL.Data()
	if type(data) ~= "table" then
		MelloUI:Print("Quest List: its quest data (Media\\QuestListData.lua) is missing. Reinstall MelloUI from its download, copying every folder.")
		return
	end
	msg = (msg or ""):gsub("^%s+", ""):gsub("%s+$", "")
	local cmd, rest = msg:match("^(%S+)%s*(.-)$")
	cmd = cmd and cmd:lower()
	if cmd == "dock" or cmd == "zeppelin" then
		-- /qlmap dock Boat to Auberdine [| Alliance|Horde]   (stand on the dock)
		if rest == "" then
			MelloUI:Print("Stand on the dock and type:  /qlmap dock Boat to Auberdine   (add  | horde  or  | alliance  for a faction-only route; default neutral).")
			return
		end
		local label, side = rest:match("^(.-)%s*|%s*(%a+)$")
		label = label or rest
		local faction = 0
		if side and side:lower() == "alliance" then faction = 1 elseif side and side:lower() == "horde" then faction = 2 end
		local mapID, x, y, dock = QL.PlayerMapPoint()
		if not mapID then
			MelloUI:Print("Cannot read your position here.")
			return
		end
		QL.LearnedStore("transports")[label] = { mapID = mapID, x = x, y = y, dock = dock, kind = cmd == "zeppelin" and 2 or 1, faction = faction }
		MelloUI:Print("Recorded '%s' at %s (%.1f, %.1f). Sail there and type  /qlmap arrive %s  to link the destination map.", label, dock, x * 100, y * 100, label)
		QL.RefreshPins()
	elseif cmd == "arrive" then
		local l = rest ~= "" and QL.LearnedStore("transports")[rest]
		if not l then
			MelloUI:Print("No recorded dock called '%s'.", rest)
			return
		end
		local mapID = QL.PlayerMapPoint()
		if mapID then
			l.destMapID = mapID
			MelloUI:Print("'%s' now opens %s when clicked.", rest, QL.ZoneNameForMap(mapID) or tostring(mapID))
		end
	elseif cmd == "entrance" then
		-- /qlmap entrance Hall of Thanes [| raid]   (stand at the entrance)
		if rest == "" then
			MelloUI:Print("Stand at the entrance and type:  /qlmap entrance Hall of Thanes   (add  | raid  for a raid).")
			return
		end
		local name, kind = rest:match("^(.-)%s*|%s*(%a+)$")
		name = name or rest
		local mapID, x, y = QL.PlayerMapPoint()
		if not mapID then
			MelloUI:Print("Cannot read your position here.")
			return
		end
		QL.LearnedStore("entrances")[name] = { mapID = mapID, x = x, y = y, raid = kind ~= nil and kind:lower() == "raid" }
		MelloUI:Print("Recorded the entrance of %s at %.1f, %.1f.", name, x * 100, y * 100)
		QL.RefreshPins()
	elseif cmd == "remove" then
		local removed = false
		if QL.LearnedStore("transports")[rest] then
			QL.LearnedStore("transports")[rest] = nil
			removed = true
		end
		if QL.LearnedStore("entrances")[rest] then
			QL.LearnedStore("entrances")[rest] = nil
			removed = true
		end
		MelloUI:Print(removed and ("Removed '" .. rest .. "'.") or ("Nothing recorded as '" .. rest .. "'."))
		QL.RefreshPins()
	elseif cmd == "list" then
		MelloUI:Print("Recorded pins:")
		for name, l in pairs(QL.LearnedStore("entrances")) do
			print(string.format("   entrance  %s  (%s %.1f, %.1f)", name, QL.ZoneNameForMap(l.mapID) or "?", l.x * 100, l.y * 100))
		end
		for label, l in pairs(QL.LearnedStore("transports")) do
			print(string.format("   dock  %s  (%s %.1f, %.1f)%s", label, QL.ZoneNameForMap(l.mapID) or "?", l.x * 100, l.y * 100,
				l.destMapID and ("  ->  " .. (QL.ZoneNameForMap(l.destMapID) or "?")) or ""))
		end
		return
	elseif cmd and cmd ~= "" then
		MelloUI:Print("/qlmap  (diagnostics)  |  /qlmap dock <label> [| alliance|horde]  |  /qlmap zeppelin <label>  |  /qlmap arrive <label>  |  /qlmap entrance <name> [| raid]  |  /qlmap remove <name>  |  /qlmap list")
		return
	end
	if cmd then
		return
	end
	MelloUI:Print("Quest List map pins")
	print("   provider: " .. tostring(QL.Provider ~= nil) .. "   marks' layer: " .. tostring(QL.Marks and QL.Marks.layer ~= nil)
		.. "   GetMapPosFromWorldPos: " .. tostring(C_Map.GetMapPosFromWorldPos ~= nil) .. "   CreateVector2D: " .. tostring(CreateVector2D ~= nil))
	print(string.format("   data: %d entrances, %d transports, %d learned", #(data.entrances or {}), #(data.transports or {}),
		(function() local n = 0 for _ in pairs(QL.LearnedStore("entrances")) do n = n + 1 end return n end)()))
	print(string.format("   options: pins %s, entrances %s, transports %s, badges %s",
		tostring(M.db.mapPins), tostring(M.db.entrancePins), tostring(M.db.transportPins), tostring(M.db.zoneBadges)))
	if QL.lastPinInfo then
		print(string.format("   last refresh: map %s (%s), type %s", tostring(QL.lastPinInfo.mapID), tostring(QL.lastPinInfo.name), tostring(QL.lastPinInfo.mapType)))
		local client = QL.ClientEntrances(QL.lastPinInfo.mapID)
		print(string.format("   client entrance list for this map: %s, %d entries", tostring(C_EncounterJournal and C_EncounterJournal.GetDungeonEntrancesForMap ~= nil), #client))
		for i, e in ipairs(client) do
			if i > 8 then break end
			print(string.format("      %s at %.1f, %.1f", e.name, e.x * 100, e.y * 100))
		end
		local pois = QL.ClientPOIs(QL.lastPinInfo.mapID)
		print(string.format("   points of interest the map shows: %d", #pois))
		for i, poi in ipairs(pois) do
			if i > 12 then
				print("      ... " .. (#pois - 12) .. " more")
				break
			end
			print(string.format("      %s%s at %.1f, %.1f  [%s]", poi.name, QL.IsEntrancePOI(poi) and " (instance)" or "", poi.x * 100, poi.y * 100, poi.atlas))
		end
	else
		print("   no refresh yet (open the map).")
	end
	if QL.MarkList then
		local marks, kinds = QL.MarkList(), {}
		for _, m in ipairs(marks) do
			kinds[m.kind] = (kinds[m.kind] or 0) + 1
		end
		local parts = {}
		for k, v in pairs(kinds) do parts[#parts + 1] = k .. " " .. v end
		print("   marks on the map: " .. #marks .. (#marks > 0 and (" (" .. table.concat(parts, ", ") .. ")") or ""))
	end
	-- the layers: the marks and the page over the map's picture (their layer a strata up)
	local function Layer(name, f)
		if f then
			print(string.format("   %s: %s %d%s%s", name, f:GetFrameStrata(), f:GetFrameLevel(),
				f.IsFrameBuffer and f:IsFrameBuffer() and ", frame buffer" or "", f:IsVisible() and "" or ", hidden"))
		end
	end
	Layer("map", WorldMapFrame)
	Layer("layer over the map", MelloUI.mapLayer)
	Layer("page", QL.Panel.frame)
	Layer("marks' layer", QL.Marks and QL.Marks.clip)
	for _, err in ipairs(QL.lastPinErrors) do
		print("   |cffff4040error|r " .. err)
	end
	local trace = QL.lastPointTrace
	for i, line in ipairs(trace) do
		if i > 8 then
			print("   ... " .. (#trace - 8) .. " more")
			break
		end
		print("   " .. line)
	end
	-- Probe the API with the first entrance.
	local e = data.entrances and data.entrances[1]
	if e and C_Map.GetMapPosFromWorldPos and CreateVector2D then
		local ok, uiMapID, pos = pcall(C_Map.GetMapPosFromWorldPos, e[3], CreateVector2D(e[4], e[5]))
		local x, y = QL.VectorXY(pos)
		print(string.format("   probe %s at (%d, %.0f, %.0f): ok %s, map %s, pos %s (%s, %s)", e[2], e[3], e[4], e[5],
			tostring(ok), tostring(uiMapID), type(pos), tostring(x), tostring(y)))
	end
end

MelloUI:Profile("QuestList", "quest log events", eventFrame)
