#!/usr/bin/env python3
"""
Bake the Route module's learned paths into Media/RouteData.lua.

This client keeps addon saved variables only in memory across /reload and
drops them at restart, but it writes the file. The Route module saves its
graph as MelloUIRoutes; this script reads that file after a /reload and
writes it as an ordinary addon data file, into the project and straight into
the game's AddOns folder, so the next /reload starts from everything learned.

Usage:
  python Tools/bake_routes.py            bake once
  python Tools/bake_routes.py --watch    bake whenever the saved file changes
"""

import argparse
import glob
import os
import sys
import time

import lupa

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_OUT = os.path.join(HERE, "..", "Media", "RouteData.lua")
DEFAULT_WTF = "F:/World of Warcraft/_classic_beta_/WTF"
DEFAULT_GAME_OUT = "F:/World of Warcraft/_classic_beta_/Interface/AddOns/MelloUI/Media/RouteData.lua"
PROFILES_OUT = os.path.join(HERE, "..", "Media", "Profiles.lua")


def log(msg):
    print(time.strftime("%H:%M:%S ") + msg, file=sys.stderr, flush=True)


def saved_files(wtf):
    return glob.glob(os.path.join(wtf, "Account", "*", "SavedVariables", "MelloUI.lua"))


def lua_value(v):
    """Lua table -> dict (string keys), scalars unchanged."""
    if lupa.lua_type(v) == "table":
        out = {}
        for k, x in v.items():
            if isinstance(k, float) and k.is_integer():
                k = int(k)
            out[str(k)] = lua_value(x)
        return out
    return v


def load_pins(path):
    """{kind: {name: {field: value}}} recorded map pins from MelloUIRoutes."""
    runtime = lupa.LuaRuntime()
    runtime.execute(open(path, encoding="utf-8", errors="replace").read())
    routes = runtime.globals().MelloUIRoutes
    pins = {"entrances": {}, "transports": {}, "services": {}}
    if routes is None or routes["pins"] is None:
        return pins
    for kind in pins:
        table = routes["pins"][kind]
        if table is not None:
            for name, v in table.items():
                if lupa.lua_type(v) == "table":
                    pins[kind][str(name)] = lua_value(v)
    return pins


def load_profiles(path):
    """({name: serialised settings}, default name or None) from MelloUIDB in a saved file."""
    runtime = lupa.LuaRuntime()
    runtime.execute(open(path, encoding="utf-8", errors="replace").read())
    db = runtime.globals().MelloUIDB
    profiles, default = {}, None
    if db is None:
        return profiles, default
    if db["profiles"] is not None:
        for name, text in db["profiles"].items():
            if isinstance(text, str):
                profiles[str(name)] = text
    if isinstance(db["defaultProfile"], str):
        default = db["defaultProfile"]
    return profiles, default


def write_profiles(profiles, default, path):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("-- Generated by Tools/bake_routes.py from the saved variable MelloUIDB. Do not edit by hand.\n")
        fh.write("-- Settings profiles (serialised like the macro backup) and the one applied on a fresh install.\n\n")
        fh.write("MelloUI_Profiles = {\n")
        fh.write(f"\tdefault = {lua_literal(default) if default else 'nil'},\n")
        fh.write("\tprofiles = {\n")
        for name in sorted(profiles):
            fh.write(f"\t\t{lua_key(name)} = {lua_literal(profiles[name])},\n")
        fh.write("\t},\n}\n")


def load_graphs(path):
    """{continent: {cell: (x, y, {cell: cost})}} from MelloUIRoutes in a saved file."""
    runtime = lupa.LuaRuntime()
    runtime.execute(open(path, encoding="utf-8", errors="replace").read())
    routes = runtime.globals().MelloUIRoutes
    graphs = {}
    if routes is None or routes["graphs"] is None:
        return graphs
    for cont, g in routes["graphs"].items():
        nodes = {}
        for key, node in g.items():
            try:
                x, y = float(node[1]), float(node[2])
            except (TypeError, ValueError, KeyError):
                continue
            edges = {}
            if node[3] is not None:
                for other, cost in node[3].items():
                    edges[str(other)] = float(cost)
            nodes[str(key)] = (x, y, edges)
        graphs[int(cont)] = nodes
    return graphs


def merge_into(target, graphs):
    for cont, nodes in graphs.items():
        mine = target.setdefault(cont, {})
        for key, (x, y, edges) in nodes.items():
            if key not in mine:
                mine[key] = (x, y, dict(edges))
            else:
                mx, my, medges = mine[key]
                for other, cost in edges.items():
                    if other not in medges or medges[other] > cost:
                        medges[other] = cost


def lua_key(s):
    return '["' + s.replace("\\", "\\\\").replace('"', '\\"') + '"]'


def lua_literal(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return f"{v:.4f}".rstrip("0").rstrip(".") if isinstance(v, float) else str(v)
    if isinstance(v, dict):
        return "{" + ",".join(f"{lua_key(str(k))}={lua_literal(x)}" for k, x in sorted(v.items())) + "}"
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_lua(graphs, path, pins=None):
    pins = pins or {"entrances": {}, "transports": {}}
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("-- Generated by Tools/bake_routes.py from the saved variable MelloUIRoutes. Do not edit by hand.\n")
        fh.write("-- Learned paths for the Route module: graphs[continent uiMapID][cell] = { yards east, yards south, { [cell] = seconds } }.\n\n")
        fh.write("MelloUI_RouteData = {\n\tgraphs = {\n")
        for cont in sorted(graphs):
            fh.write(f"\t\t[{cont}] = {{\n")
            for key in sorted(graphs[cont]):
                x, y, edges = graphs[cont][key]
                parts = ",".join(f"{lua_key(o)}={c:.1f}" for o, c in sorted(edges.items()))
                fh.write(f"\t\t\t{lua_key(key)}={{{x:.1f},{y:.1f},{{{parts}}}}},\n")
            fh.write("\t\t},\n")
        fh.write("\t},\n\t-- map pins recorded by hand with /qlmap (Quest List)\n\tpins = {\n")
        for kind in ("entrances", "transports", "services"):
            fh.write(f"\t\t{kind} = {{\n")
            for name in sorted(pins.get(kind, {})):
                fh.write(f"\t\t\t{lua_key(name)}={lua_literal(pins[kind][name])},\n")
            fh.write("\t\t},\n")
        fh.write("\t},\n}\n")


def bake(args):
    files = saved_files(args.wtf)
    if not files:
        log(f"no MelloUI.lua under {args.wtf}")
        return False
    graphs = {}
    pins = {"entrances": {}, "transports": {}, "services": {}}
    profiles, default = {}, None
    for path in files:
        try:
            merge_into(graphs, load_graphs(path))
            for kind, table in load_pins(path).items():
                for name, v in table.items():
                    pins[kind].setdefault(name, v)
            p, d = load_profiles(path)
            profiles.update(p)
            default = default or d
        except Exception as exc:  # noqa: BLE001
            log(f"could not read {path}: {exc}")
    nodes = sum(len(n) for n in graphs.values())
    npins = sum(len(t) for t in pins.values())
    if profiles:
        outs = [os.path.abspath(PROFILES_OUT)]
        if args.game_out:
            outs.append(os.path.join(os.path.dirname(args.game_out), "Profiles.lua"))
        for out in outs:
            write_profiles(profiles, default, out)
        log(f"baked {len(profiles)} profile(s), default {default or 'none'} -> {', '.join(outs)}")
    if nodes == 0 and npins == 0:
        log("no learned paths or recorded pins in the saved variables yet (walk around, then /reload)")
        return bool(profiles)
    outs = [os.path.abspath(PROJECT_OUT)]
    if args.game_out:
        outs.append(args.game_out)
    for out in outs:
        write_lua(graphs, out, pins)
    log(f"baked {nodes} points on {len(graphs)} continent(s), {npins} recorded pins -> {', '.join(outs)}")
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--wtf", default=DEFAULT_WTF)
    ap.add_argument("--game-out", default=DEFAULT_GAME_OUT, help="also write the file here (the game's addon copy); '' to skip")
    ap.add_argument("--watch", action="store_true", help="keep running and bake after every /reload")
    ap.add_argument("--interval", type=float, default=5.0)
    args = ap.parse_args()

    bake(args)
    if not args.watch:
        return
    last = max((os.path.getmtime(p) for p in saved_files(args.wtf)), default=0)
    log("watching the saved variables; /reload in game writes them")
    while True:
        time.sleep(args.interval)
        current = max((os.path.getmtime(p) for p in saved_files(args.wtf)), default=0)
        if current > last:
            time.sleep(2)
            last = max((os.path.getmtime(p) for p in saved_files(args.wtf)), default=0)
            bake(args)


if __name__ == "__main__":
    main()
